### ISSUE TITLE
page length mismatch because of unregular object numbering vs. lengthNextN

### ISSUE THREAD

**Issue by keszegrobert** [qpdf/qpdf#1]
Hi, I am trying to generate linearized PDF, 
and checking with qpdf, if my hint tables are correct.
Qpdf reports 'page length mismatch' errors,
because my object numbers are not ordered.
This is because lengthNextN is used 
when calculating the length of the objects.
In the PDF reference there is no mention, 
in which order the objects must be, 
only that the object numbers must be unique.
I am sure, I calculate the lengths as it is needed,
but qpdf's error messages are suggesting me 
to change the whole object numbering, 
that is not under my control 
(I am working on an old generator 
written by some old PDF gurus)

**Comment by jberkenbilt** [comment]
I'm doing some cleanup and closing old issues that are not reproducible. Please feel free to reopen or provide additional information if this is still relevant.
