### ISSUE TITLE
error: qpdf: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/lib/libgnutls.so.30)

### ISSUE THREAD

**Issue by dakab1** [qpdf/qpdf#1006]
hi @jberkenbilt 

I get the following error: qpdf: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/lib/libgnutls.so.30)

Using your suggestion [here](https://github.com/qpdf/qpdf/issues/352#issuecomment-1343316831) , any suggestions would be welcome :-)

Thanks in advance

**Comment by dakab1** [comment]
Let me try 11.3, il let you know how that goes

**Comment by dakab1** [comment]
@Sparticuz: `Linux Kernel Version: 4.14.255-311-248.529.amzn2.x86_64`
I tried 11.3. Same error. Perhaps you have LD_LIBRARY set?

**Comment by Sparticuz** [comment]
I don't have LD_LIBRARY set.

https://gist.github.com/Sparticuz/adef97c2ed12cb6d83aa6122f629b4e9
I've take out some internal functions and types, but that's pretty much all that's done to encrypt a pdf.

**Comment by dakab1** [comment]
I ended up deploying the lambda as an image. Basically I compiled it on Amazon 2 linux.

Here is the top part of my docker file:

``` 
# Use the official Amazon Linux base image
FROM amazonlinux:2

# Install required packages for qpdf
RUN yum -y install unzip git wget tar openssl11-devel openssl11 gcc-c++ gnutls-devel zlib-devel libjpeg-devel libpng make

# Download and install CMake
WORKDIR /
RUN wget https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3.tar.gz && \
    tar -xzvf cmake-3.21.3.tar.gz && \
    cd cmake-3.21.3 && \
    ./bootstrap && \
    make -j$(nproc) && \
    make install

# Create a symlink for cmake
RUN ln -s /usr/local/bin/cmake /usr/bin/cmake

# Clone qpdf repository and build
WORKDIR /
RUN git clone https://github.com/qpdf/qpdf.git && \
    cd qpdf && \
    cmake -S . -B build && \
    cmake --build build && \
    cd /usr/local/bin && \
    ln -s /qpdf/build/qpdf/qpdf
```

**Comment by deathemperor** [comment]
Getting the same error on using 11.6.3 and struggle to get it running

`qpdf: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/lib/libqpdf.so.29)`
