### ISSUE TITLE
fix-qdf cannot read from a pipe

### ISSUE THREAD

**Issue by acwaters** [qpdf/qpdf#1010]
This used to work, but it looks like it was broken by [011b1d7](https://github.com/qpdf/qpdf/commit/011b1d7e3af803991ee7e4143b01965296af3cce). The `QUtil::read_lines_from_file()` function would read the input in chunks (albeit extremely inefficiently), reallocating as needed; the `QUtil::read_file_into_string()` function that replaces it attempts to preallocate a buffer large enough to hold the entire input and then read the whole thing in one go. This fails when the input stream is unseekable.

A simple solution would be to check the return code from `fseek()` and, if it fails, fall back to an alternative method like `QUtil::read_lines_from_file()` (slow and functional is better than non-functional, though it wouldn't be a bad idea to update that function to read more than a single byte at a time...).

The ideal solution would rewrite the input processing to handle the file line-by-line without needing to read the whole thing in beforehand. In addition to resolving this issue, that would also solve the outstanding problem of high memory usage for large PDFs (which will ultimately result in the allocation failing if the input is too large to hold in memory all at once). This would be more complex than simply patching `QUtil::read_file_into_string()`, but not inordinately so; there is no special reason why `QdfFixer::processLines()` should iterate over a string or list of strings as opposed iterating over the input stream directly with e.g. `fscanf()` or `std::getline()` (at a glance, it looks like this would actually be a substantial simplification compared to the existing code).

**Comment by jberkenbilt** [comment]
@m-holger Do you have time to take a look at this? I have not yet attempted to reproduce it. I guess there must not be a test case for this. That said, my usual mode of operation is to use fix_qdf from a pipe, and I've never had an issue.

**Comment by acwaters** [comment]
Well, to be more precise, fix-qdf fails when `QUtil::tell()` returns -1, indicating an error with getting the cursor position. Several libc implementations, including glibc and musl, internally implement "tell" as "seek +0", so it will fail whenever seek does, e.g. when operating on an unseekable input stream (such as a pipe). It is entirely possible that your implementation behaves differently; I know for instance that "pipes" on Windows behave very differently than they do on Unix systems, and a seek-to-end there will "work" by racing with the input process.

**Comment by m-holger** [comment]
> Do you have time to take a look at this?

Probably not today, but I should be able to look at it next couple of days.
