### ISSUE TITLE
how to specify locally installed openssl and jpeg when compiling qpdf?

### ISSUE THREAD

**Issue by kqe** [qpdf/qpdf#1020]
Hi, I'm trying to install the lastest qpdf (https://github.com/qpdf/qpdf/archive/refs/tags/v11.5.0.tar.gz) on RHEL, with my locally compiled openssl and jpeg at non-standard location.

When compiling qpdf, how to specify the path to openssl and jpeg?

The documentation said
> All available build options are defined in the the top-level CMakeLists.txt file and have help text. 

I looked at its CMakeLists.txt, libqpdf/CMakeLists.txt, and found the only variables related are:
- OPENSSL_H_PATH
- OPENSSL_LIB_PATH
- JPEG_INCLUDE

for example, one line is:
`      find_path(OPENSSL_H_PATH openssl/evp.h)
`

and I do see the file /opt/openssl3/include/openssl/evp.h

so I tried to build with:

```
cmake -DREQUIRE_CRYPTO_OPENSSL=1 \
-DOPENSSL_H_PATH=/opt/openssl3/include \
-DOPENSSL_LIB_PATH=/opt/openssl3/lib64 \
-DJPEG_INCLUDE=/opt/jpeg/include \
-S . -B build

cmake --build build -- -k

```
but then it fails with many lines like
```
../libqpdf/libqpdf.so.29.5.0: undefined reference to `EVP_CIPHER_CTX_set_key_length'

Pl_DCT.cc:(.text+0x555): undefined reference to `jpeg_CreateCompress'
```

So looks like it did not use my compiled openssl and jpeg at all.

So how to specify the path to my locally installed openssl and jpeg when compiling this qpdf?

**Comment by kqe** [comment]
I figured it out.  Need to separately use 

export PKG_CONFIG_PATH=/opt/openssl3/lib/pkgconfig:$PKG_CONFIG_PATH

before running cmake, while that folder should contain the .pc file such as openssl.pc

**Comment by jberkenbilt** [comment]
I'm glad you figured it out. Sorry for the delayed response. As this is a general issue with using cmake that is not specific to qpdf, I'll go ahead and close this, but feel free to reopen if there are additional issues. Thanks for posting your solution. It may help other users.
