### ISSUE TITLE
Bash Completion Quoting Error on Windows with Git Bash

### ISSUE THREAD

**Issue by wileyqhacker** [qpdf/qpdf#1021]
Hi:

I'm running qpdf 11.2.0 on Windows 11. The binary is installed in `C:\Program Files\qpdf 11.5.0`. I also use Git for Windows, and prefer to use the MSYS2 bash shell that comes with it instead of CMD.EXE or PowerShell.

My `.bashrc` has `eval "$(qpdf --completion-bash)"` in it to enable bash completion. Unfortunately the output of that command does not respect whitespaces in paths, which is very common on Windows.
```shell
$ qpdf --completion-bash
complete -o bashdefault -o default -o nospace -C C:\Program Files\qpdf 11.5.0\bin\qpdf qpdf
```
As a result, bash completion fails with the error 
```
bash: C:Program: command not found
```
Since I also share my home directory with my WSL2 Ubuntu install, and I have qpdf installed in `/usr/bin` there, I can use it from WSL with the same `.bashrc`, but not from MSYS2.

**Comment by jberkenbilt** [comment]
Thanks. This should be easy enough to reproduce and fix.
