### ISSUE TITLE
Compile failure when random devices aren't found

### ISSUE THREAD

**Issue by cwh-0** [qpdf/qpdf#1022]
Just filed https://bugs.gentoo.org/912421

I'm upgrading ChromiumOS (using portage) qpdf 10.x to 11.x, and it looks like this CMake build process is brand new. We cross-compile, and the target build sysroot doesn't have files like /dev/urandom there, and that's causing a build failure.

Source of preprocessor error: https://github.com/qpdf/qpdf/blob/11.5/libqpdf/SecureRandomDataProvider.cc#L105
Related CMake initialization: https://github.com/qpdf/qpdf/blob/11.5/libqpdf/CMakeLists.txt#L323

If I initialize this variable explicitly during the cmake invocation with -DRANDOM_DEVICE, the build succeeds. But it seems incorrect to try to detect runtime features at build time like this in the first place, right?

Also this seems at odds with the README:

> By default, qpdf uses the crypto provider for generating random numbers. The rest of this applies only if you are using the native crypto provider.

But we use OpenSSL, and in fact this preprocessor `#if` block seems like it might be totally independent of the chosen crypto provider, unconditionally executing for non-windows platforms. Is this intended? It very well could have been succeeding by chance in most build environments.

**Comment by jberkenbilt** [comment]
Can you send me a specific command to test this with? I haven't used gentoo myself, but I could either reproduce it in a container or VM or else you could provide a formula for reproducing this using a chroot in Ubuntu if that's convenient. It would be good to make this work. Most likely the way it is now is just a remnant of the days before random numbers were provided by the crypto provider, and this may be the first time anyone noticed or took the trouble to report it. I agree that detecting this at build time is not right.

**Comment by jberkenbilt** [comment]
Yeah, good thought. Thanks -- this should do.

**Comment by jberkenbilt** [comment]
I moved detection of the random device to runtime. This will be in 10.6.0 which I hope to get out today.
