### ISSUE TITLE
Remove encryption when the key is known, but the passwords are not

### ISSUE THREAD

**Issue by mpfaff** [qpdf/qpdf#1037]
I have a PDF file that has an owner password set, but not the user password, so I can get the encryption key. I have an edited copy of this PDF that, due to awful behaviour in macOS Preview, is now encrypted with an unknown user password.

Assuming it uses the same encryption key, is it currently possible to decrypt this PDF? Would it be possible to add an option to decrypt a PDF given the hex representation of the key, rather than a password?

**Comment by jberkenbilt** [comment]
The option you are looking for is already there.
https://qpdf.readthedocs.io/en/stable/cli.html#option-password-is-hex-key

**Comment by jberkenbilt** [comment]
If it doesn't use the same encryption key but uses the same owner password, qpdf could still decrypt it. It takes whatever password you provide and tries it as both the user and owner password, taking whichever one works, and not distinguishing between them for functionality.

**Comment by mpfaff** [comment]
> If it doesn't use the same encryption key but uses the same owner password, qpdf could still decrypt it. It takes whatever password you provide and tries it as both the user and owner password, taking whichever one works, and not distinguishing between them for functionality.

In my case, I have no idea what the owner password is. It's a government form.

> The option you are looking for is already there.
> https://qpdf.readthedocs.io/en/stable/cli.html#option-password-is-hex-key

That worked like a charm! Thank you very much.

**Comment by jberkenbilt** [comment]
Great, thanks for following up. It's nice to hear when one of the more obscure and unusual features of qpdf helps someone. :-)
