### ISSUE TITLE
capture the exit codes of qpdf

### ISSUE THREAD

**Issue by maheshchhatbar** [qpdf/qpdf#1038]
I am tryng to check if a pdf is encrypted with commandline --is-encrypted
when run from a batch file as below I can get the exit code
echo off
qpdf --is-encrypted d:\del\NoPass.pdf
echo off
if %errorlevel%==2 (
   echo pdf is not protected
) else if %errorlevel%==1 (
   echo "errorlevel = 1"
) else if errorlevel 0 (
   echo pdf is password protected
) else (
   echo "Success!"
)

but if i try to run qpdf --is-encrypted d:\del\NoPass.pdf from a VBA shell command , i am not able to capture the exit code.

How to get the exit codes of qpdf to excel vba
Objective is to use it with excel and be able to check many pdf files if the same are encryted

**Comment by vf1962** [comment]
Use "Micrososoft Scripting Runtime" in your VBA code
Enable the library in Tools/Reference 
For my sample I declare the Sleep function in a module
`#If VBA7 Then ' Office 2010 or later
    Public Declare PtrSafe Sub Sleep Lib "kernel32.dll" (ByVal Milliseconds As LongPtr)
#Else ' Office 2007 or earlier
    public Declare Sub Sleep Lib "kernel32.dll" (ByVal Milliseconds As Long)
#End If`   

This is the main function
`Public Function ErrorCode() As Integer
    ' Enable in Tools/References "Micrososoft Scripting Runtime"
    Dim oShl As Object                           ' Shell Object
    Dim oExec As Object                          ' Execution Object
    Dim t As Integer                             ' waiting loop number
    ErrorCode = 9999 ' Default return value for execution timeout
    Set oShl = CreateObject("WScript.Shell")
'    Set oExec = oShl.Exec("qpdf --is-encrypted d:\del\NoPass.pdf")
    ' Wait execution termination
    For t = 1 To 50                              ' 50*100 Millisecond wait for a maximum of 5 seconds
        ' Wait 100 Milliseconds
        Sleep 100
        ' Check if execution terminated
        If oExec.Status = 1 Then
            ' ExitCode
            ErrorCode = oExec.ExitCode
            Exit For
        End If
    Next
End Function
`

**Comment by maheshchhatbar** [comment]
Hi vf1962
Thank you for your code snippet.
Another error on my part was that when i passed a foldername and filename without the double quotes , and when qpdf returned exit code 2 i could not figure it out.
After adding double quotes to begin and end the folder and filenames , qpdf --is-encrypted worked perfectly really well.
In the meantime another option i tested to check if the pdf is password protected is check for presence of the word "/Encrypt" in the pdf file , The function i used was Public Function StringExistsInFile(ByVal TheString As String, ByVal TheFile As String) As Boolean
from [https://bytes.com/topic/visual-basic/answers/636879-searching-particualr-word-text-file-using-vba](url)
It was based on the reference of
Detecting encryption should be as little as searching for the string /Encrypt in the file. from
[https://stackoverflow.com/questions/44731359/detect-in-browser-if-pdf-is-locked-or-encrypted](url)
StringExistsInFile did work fast but apparently is just a quickfix / patchwork , not the real test like qpdf 
Hope it helps someone.
Thank you for your valuable support.
