### ISSUE TITLE
Add facility to copy/move annotations from one page to another page

### ISSUE THREAD

**Issue by m-holger** [qpdf/qpdf#1048]
Use cases:

Edit a pdf file in a qpdf based application while simultaneously annotating (a copy of) it using an external tool. Import the newly created annotations.

Copy or split a page. Selectively move some of the annotations to the new page, for example, based on the location of the annotation. 

See for example https://github.com/pdfarranger/pdfarranger/issues/940#issuecomment-1755119962

**Comment by jberkenbilt** [comment]
I think qpdf can already do this. See `QPDFPageObjectHelper::copyAnnotations`. I'm closing for now, but feel free to reopen if you think something beyond this is needed. I don't see this as something that would make sense to add to the CLI. pdfarranger could make use of the annotation copying functionality from libqpdf, assuming it is exposed to pikepdf.

**Comment by elmimmo** [comment]
I, for one, could make use of this feature in the CLI.

InDesign does not provide a way to export [editorial notes](https://helpx.adobe.com/indesign/using/adding-editorial-notes-indesign.html) to PDF as annotations, but InCopy does, albeit without the rich PDF settings that InDesign allows for, so I export with both and then import the annotations from the PDF of the latter into that of the former with Acrobat. That, each time I need them, which ideally is always, so gets tedious fast.

I can currently do this with qpdf’s CLI by overlaying one PDF onto the other, but I must have made sure that the PDF exported with InCopy had all layers hidden (in which case it will still export notes as annotations) or else, chaos, so it's prone to user error and therefore a fragile workflow.
