### ISSUE TITLE
qpdf error "file is damaged" for pdf saved by Excel

### ISSUE THREAD

**Issue by shawn8888** [qpdf/qpdf#1050]
WARNING: C:\pdftemp\018.pdf (xref stream: object 17 1, offset 110340): EOF while reading token
WARNING: C:\pdftemp\018.pdf (xref stream: object 17 1, offset 110830): unexpected EOF
WARNING: C:\pdftemp\018.pdf (xref stream: object 17 1, offset 110830): parse error while reading object
WARNING: C:\pdftemp\018.pdf (xref stream: object 17 1, offset 110830): expected endobj
WARNING: C:\pdftemp\018.pdf: file is damaged
WARNING: C:\pdftemp\018.pdf (offset 110267): xref not found
WARNING: C:\pdftemp\018.pdf: Attempting to reconstruct cross-reference table
qpdf: C:\pdftemp\018.pdf: unable to find trailer dictionary while recovering damaged file

When I use qpdf to merge pdf files, the error above shows the file is damaged. However, this pdf is saved by Excel and works fine. The pdf is attached.
Could you please fix this problem?
Thanks

[018.pdf](https://github.com/qpdf/qpdf/files/12885974/018.pdf)

**Comment by jberkenbilt** [comment]
I acknowledge that there is a bug in qpdf's tokenizer that is affecting this file. I will provide a fix.

**Comment by jberkenbilt** [comment]
@m-holger I believe you introduced this bug when reworking the tokenizer. qpdf 10.6.3 parses this file correctly.

**Comment by jberkenbilt** [comment]
The bug is that this file has the character `\35`, which is valid per the spec, but the current tokenizer requires exactly 3 digits after the `\` rather than _at most 3_ as stated in the spec.

**Comment by jberkenbilt** [comment]
I am working on a fix now.

**Comment by jberkenbilt** [comment]
This was a serious bug. I intend to release 11.6.3 this weekend with a fix. Thanks for the report.

**Comment by jberkenbilt** [comment]
@shawn8888 11.6.3 is out if you'd like to test.

**Comment by shawn8888** [comment]
@jberkenbilt 
I can confirm the bug is fixed!
Thanks a lot for your support!
