### ISSUE TITLE
honor --

### ISSUE THREAD

**Issue by kqe** [qpdf/qpdf#1051]
Hi, '--' is widely expected on linux to specify that there is no more command option, so can safely treat the remaining arguments as filenames etc.

For example, the following command runs perfectly: 
```
$ ls -- -a.pdf
-a.pdf

```

But qpdf appears not honoring it:
```
$ qpdf --stream-data=preserve --encrypt aaa aaa 256 -- -a.pdf -a_enc.pdf

qpdf: unknown option -a.pdf
...
```

Because the filename can be a variable containing any characters, such as ", ', -, etc, so I don't see any other solution unless qpdf can honor -- .

What do you think?  Thanks!

**Comment by jberkenbilt** [comment]
qpdf's command-line arguments are very complex, and `--` is already used to break out of subparsers, like for `--pages` and `--encrypt` as in your example. My suggestion would be to specify the file as `./-a.pdf`.

**Comment by kqe** [comment]
got it, that should work, thanks!
