### ISSUE TITLE
Please consider including the summary of options into the standard linux man page.

### ISSUE THREAD

**Issue by guidomz** [qpdf/qpdf#1064]
Thanks for this wonderful commandline facility. However, I personally see the current multipage help structure as cumbersome making me want to go instead to the online documentation or to stackoverflow, which would be discouraging if I was offline, and that is often.

Perhaps just inserting the contents of https://qpdf.readthedocs.io/en/stable/cli.html into the man page? It would greatly help. Thanks.

**Comment by jberkenbilt** [comment]
That's a good idea. The `--help` output for qpdf is autogenerated from the manual. I don't imagine it would be that hard to do with the manual page.

**Comment by guidomz** [comment]
Much appreciated!

**Comment by jberkenbilt** [comment]
This will be in qpdf 11.7.0. It's not perfect, but it's pretty good, and it looks a lot like a manual page. Making this beautiful will be a low priority, but I'm happy to accept suggestions. I'm using basic nroff man formatting but haven't gone to the trouble of bolding all the options, etc. The manual page is 100% automatically generated and contains the same text as qpdf --help=all but formatted as a manual page.. I'll merge this after it finishes CI. I'm hoping to get 11.7.0 out this weekend.

**Comment by jberkenbilt** [comment]
I hoping to package the HTML and PDF documentation with the debian/Ubuntu packages as well, but there are some barriers. I'm hoping to get that in for 11.7.0, but no guarantees.
