### ISSUE TITLE
qpdf-11.6.3-bin-linux-x86_64.zip doesn't work with AWS Lambda as layer

### ISSUE THREAD

**Issue by deathemperor** [qpdf/qpdf#1068]
I follow [this instruction](https://github.com/qpdf/qpdf/issues/352#issuecomment-1343316831) to create lambda layer with 11.6.3

got this runtime error:

```
qpdf: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/lib/libqpdf.so.29)
```

**Comment by jberkenbilt** [comment]
I guess my CI environment for building the lambda layer uses libraries that are too new now. I'll take a look at this before the next release.

**Comment by deathemperor** [comment]
@jberkenbilt thanks. until that comes do you have any suggestion on how to build it manually? 

Running the last OK version I got this (that's why I upgraded to 11.6.3 trying to fix)

```
WARNING: /tmp/96393646-9ec5-4db6-b0ee-b2025780d483.pdf: file is damaged
WARNING: /tmp/96393646-9ec5-4db6-b0ee-b2025780d483.pdf: can't find startxref
WARNING: /tmp/96393646-9ec5-4db6-b0ee-b2025780d483.pdf: Attempting to reconstruct cross-reference table
qpdf: /tmp/96393646-9ec5-4db6-b0ee-b2025780d483.pdf: unable to find trailer dictionary while recovering damaged file
```

**Comment by jberkenbilt** [comment]
Sorry for the delay -- this finished a long time ago but I got distracted by my day job. :-)
[qpdf-11.6.3-bin-linux-x86_64-ci.zip](https://github.com/qpdf/qpdf/files/13419075/qpdf-11.6.3-bin-linux-x86_64-ci.zip)
If this linux binary works for you, then you can use it as a place-holder until I release 11.6.4 or 11.7.0 or whatever is next. I may still want to release this as 11.6.4, but it might be a few days before I can do it, particularly with the holiday (in the US).

**Comment by deathemperor** [comment]
no problem @jberkenbilt . good thing is I've tested and it works! thanks for the quick help.
