### ISSUE TITLE
crop

### ISSUE THREAD

**Issue by 3052** [qpdf/qpdf#1073]
sorry for the dumb question, but how do you crop with QPDF?

for example, if I want to cut some from the top or bottom of each page. I searched here:

https://qpdf.readthedocs.io/en/stable/search.html?q=crop

**Comment by jberkenbilt** [comment]
qpdf doesn't provide a way to crop. qpdf doesn't have the capability to modify the contents of a page at this time (nor is that its intent). It is a tool for doing structural manipulation of PDF files and operations on whole pages.

**Comment by 3052** [comment]
OK thanks. do you have any recommendation for such a tool?

**Comment by 3052** [comment]
in my case, I was able to just manually remove the text I was concerned about like this:

~~~
qpdf --stream-data=uncompress a.pdf b.pdf
# remove text
qpdf --linearize b.pdf c.pdf
~~~

**Comment by qooxzuub** [comment]
This script uses qpdf and jq to crop. I don't know how robust it is.

```bash
#!/usr/bin/env bash

if (( $# != 3 )); then
    echo Usage: $0 in.pdf out.pdf '"x_bl,y_bl,x_tr,y_tr"'
    exit 1
fi

cmd='(..|objects|select(has("/MediaBox") or has("/CropBox")))'
cmd+='."/CropBox" = ['"$3"']'
tmp="$(tempfile)"
qpdf --json-output "$1" | jq "$cmd" > "$tmp"
qpdf --json-input "$tmp" "$2" && rm "$tmp"
```

**Comment by jberkenbilt** [comment]
@qooxzuub The script looks like it will be pretty good for most PDF files with the caveat that setting CropBox doesn't remove anything outside the region; it just prevents it from being displayed with a conforming reader. But for many use cases, I think this would work. If the goal is to do this on an ad hoc basis from files you are actually looking at, it's probably adequate. If you were going to run in production on lots of files from varied sources and not manually inspect them, it might be better to do something more page-aware. Anyway, thanks for posting this -- I always like seeing ways people have found to use qpdf JSON.
