### ISSUE TITLE
getDictAsMap/ditems behavior difference for null values

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#1087]
getDictAsMap returns keys that are set to null, but ditems omits them.

I'm replacing some usage of getDictAsMap to avoid the extra copying in pikepdf and noticed this. I know nulls aren't that important generally but wanted to bring it to your attention in case this difference wasn't intended. 

It's necessary to use parse to construct a dictionary with a null value since replaceKey deletes it. Or perhaps the issue is that .parse() permits construction of a dictionary with a null value in the first place?

getArrayAsVector and aitems will both output null values.

```c++

#include <qpdf/QPDF.hh>
#include <qpdf/QPDFObjectHandle.hh>

int
main(int argc, char* argv[])
{
    auto d = QPDFObjectHandle::parse("<< /Foo 42 /Bar null >>");

    std::cout << "getDictAsMap iteration:\n";
    for (auto& [k, v]: d.getDictAsMap()) {
        std::cout << k << ": " << v.unparse() << "\n";
    }
    std::cout << "ditems iteration:\n";
    for (auto& [k, v]: d.ditems()) {
        std::cout << k << ": " << v.unparse() << "\n";
    }

    auto a = QPDFObjectHandle::parse("[1 2 null 3]");

    std::cout << "getArrayAsVector iteration:\n";
    for (auto& v: a.getArrayAsVector()) {
        std::cout << v.unparse() << "\n";
    }
    std::cout << "aitems iteration:\n";
    for (auto& v: a.aitems()) {
        std::cout << v.unparse() << "\n";
    }

    return 0;
}

// c++ -I ./include ditems.cpp -lqpdf -Lbuild/libqpdf -o ditems -Wl,-rpath,build/libqpdf
```

Output
```
getDictAsMap iteration:
/Bar: null
/Foo: 42
ditems iteration:
/Foo: 42
getArrayAsVector iteration:
1
2
null
3
aitems iteration:
1
2
null
3
```

**Comment by jberkenbilt** [comment]
I feel like I've noticed this before and think it was just a performance optimization since creating a dictionary using a map can include nulls, and I didn't want to have to prematurely iterate through a dictionary to remove all the nulls. How big of a problem is this? Fixing it would add an extra linear scan of the map in some cases.

**Comment by jbarlow83** [comment]
It's not a problem for me. It's actually a bit more consistent to remove keys for null values. It was just unexpected, and I wanted to check with you if it was an issue.

**Comment by jberkenbilt** [comment]
I agree that the existing behavior is not optimal, but I don't think it's too important relative to other priorities. Since you closed this, I guess you agree. :-)

**Comment by m-holger** [comment]
> I'm replacing some usage of getDictAsMap to avoid the extra copying in pikepdf and noticed this. 

Generally, using getDictAsMap is more efficient than ditems despite the extra copying.

> It's necessary to use parse to construct a dictionary with a null value since replaceKey deletes it. 

This is not necessarily true. Calling replaceKey with an indirect null will insert the indirect null into the dictionary, and a subsequent call to getKey will retrieve the indirect null.

**Comment by jbarlow83** [comment]
@m-holger Why is getDictAsMap faster than ditems? Does it look like it's just the benefit of caching from loading all objects at once?

**Comment by m-holger** [comment]
Basically, the way oh.ditems() works in range based for loop is:
 
Start off by building a set of all keys whose values are not null.

Find the first key in the set and copy it to <string, object handle> pair.

Check it's not an empty string. Retrieve the value (i.e check oh is resolved, try dynamically casting the object pointed to by oh to a QPDF_Dictionary, retrieve the value for the key in the underlying map and copy it to the  <string, object handle> pair. Return a reference to the pair.

As part of the for loop, check the reference doesn't point to  the  <empty string, uninitialized object handle> pair. Process the item and than find the next key in the set and repeat the process.
