### ISSUE TITLE
Can you add "cut pages vertically or herizontally" please ?

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#109]
Hi.

There are certain PDF (especially scanned PDF) prepared so that each faced 2 pages of paper book appeared per single PDF page. For example PDF page 1 contained paper page 1 & 2 (twin pages being side to side).

Can you kindly add option allow user to cut such PDF pages vertically at middle so that the output is single (not multiple) PDF that each of it's page contain single paper page of original book as if it scanned each single paper page individually ? 

If you accept to add this option please make for it a sub-option  to make arrangement "right to left" so that Arabic & Hebrew peoples make benefit from this new option. Let make default arrangement "left to right" & add sub-option if used will make arrangement right to left. For Arabic & Hebrew if we use default left to right arrangement, then resulted PDF will be as if original paper book scanned as follow: page 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, ......... & this will be useless & in this case we need right to left sub-option.

You can look for XChange PDF Editor (a Windows software) which contain such option. Being an immigrant from Windows to Great Linux OS, I miss this functionality.

Best

**Comment by jberkenbilt** [comment]
As with the earlier request, this is not something I would include in qpdf. qpdf is only for structural manipulation of PDF files.
