### ISSUE TITLE
Regression tests fail to identify defective qpdf-11.6.4-msvc64 in Windows

### ISSUE THREAD

**Issue by snovotill** [qpdf/qpdf#1095]
CANCEL CANCEL CANCEL

This i my bad. 
I fell into this festering wound regarding "setlocal".
It is NOT a bug!

CANCEL CANCEL CANCEL

Your regression test suite has failed to identify serious **qpdf --check** errors per the following code:

`C:\Progra~1\QPDF\bin\qpdf --check sample.qdf`
`ECHO Errorlevel: %errorlevel%`

Here is the output, showing that the above command returns **errorlevel 0** for a fully defective qdf file:

WARNING: sample.qdf: file is damaged
WARNING: sample.qdf (offset 35120670): xref not found
WARNING: sample.qdf: Attempting to reconstruct cross-reference table
checking sample.qdf
PDF Version: 1.3
File is not encrypted
File is not linearized
WARNING: sample.qdf (object 151 0, offset 129725): expected endstream
WARNING: sample.qdf (object 151 0, offset 116694): attempting to recover stream length
WARNING: sample.qdf (object 151 0, offset 116694): recovered stream length: 12591
qpdf: operation succeeded with warnings
Errorlevel: 0`

The above violates **C:\Progra~1\QPDF\bin\qpdf --help=exit-status** and therefore breaks Windows scripting.

**Comment by jberkenbilt** [comment]
Thanks for the follow-up. :-)
