### ISSUE TITLE
Syntax for merging entire PDF files

### ISSUE THREAD

**Issue by rbro** [qpdf/qpdf#11]
If I needed to merge the entire a1.pdf and a2.pdf into b.pdf, is the best way to do it with:

qpdf --empty --pages a1.pdf 1-z a2.pdf 1-z -- b.pdf

Is there a way it can be called without specifying 1-z for each page?  It would ideal if I could call it with something like:

qpdf --empty --pages a1.pdf a2.pdf -- b.pdf

which would then allow me to call it with wildcards like:

qpdf --empty --pages a*.pdf -- b.pdf

Thanks for your help.

**Comment by lukeenglish** [comment]
Hi, can you post the syntax to do this so myself and others visiting this issue from google know how to do this as of 4.2.0?

**Comment by jberkenbilt** [comment]
You can now do

qpdf --empty --pages *.pdf -- out.pdf

**Comment by lukeenglish** [comment]
Thanks Jay

**Comment by X1z1** [comment]
In qpdf 6.0.0, if i use
qpdf --empty --pages *.pdf -- out.pdf
i get "open *.pdf: Invalid argument".

So every time I need to specify the name of files (like "qpdf --empty --pages a1.pdf a2.pdf -- out.pdf").
Why "qpdf --empty --pages *.pdf -- out.pdf" don't work?

**Comment by jberkenbilt** [comment]
What operating system or shell are you using? This will only work on a UNIX/Linux like system that does wildcard expansion in the shell. If you are using this on Windows, it will not work.

**Comment by X1z1** [comment]
I use Windows.
There is a command (or batch script) in Windows that automatically merge all pdfs in a folder.

**Comment by Kittukahier** [comment]
Hello X1z1, I also use Windows, and I have Cygwin installed in Windows, somehow it emulates a UNIX/Linux like system, it gives you a shell or terminal to work with. 
So I've installed "qpdf", I've got two documents, doc01.pdf (4 pages) and doc02.pdf (1 page). I needed to merge doc02.pdf as page #4, so I did like this:

`qpdf doc01.pdf --pages doc01.pdf 1-3 doc02.pdf 1 doc01.pdf 4 -- out.pdf`

And it worked perfectly.

**Comment by CMCDragonkai** [comment]
Is there an opposite syntax for splitting? That is split all pages of a pdf into separate files while the filenames are enumerated from a template?

**Comment by jberkenbilt** [comment]
@CMCDragonkai See #30 and #110. I think I'm going to add something soon.

**Comment by alexhunsley** [comment]
Any word on how to do this when there are spaces in the PDF filenames?
if there are spaces, even escaped ones (`'\ '`), qpdf cannot handle them.

**Comment by jberkenbilt** [comment]
qpdf doesn't care what the file names are. If you are having a problem with spaces in file names, it's probably a shell escaping problem. If you are having too much trouble getting your shell to escape things properly, you can put each argument, one argument per line, in a file and use `@file` syntax as explained in `qpdf --help`.

**Comment by devurandom** [comment]
I don't seem to understand the syntax: I try to use `qpdf --pages primary-document.pdf {other,documents}.pdf -- out.pdf` (the `{x,y}` is expanded by my shell) and get this error message: `qpdf: an output file name is required; use - for standard output`. Version is 8.2.1.

**Comment by jberkenbilt** [comment]
@devurandom You need an input file. It's treating out.pdf as the input file. If you don't have an input file, you can use `--empty`. Try `qpdf --empty --pages primary-document.pdf {other,documents}.pdf -- out.pdf`.

**Comment by jberkenbilt** [comment]
Alternatively, you can repeat primary-document.pdf for `qpdf primary-document.pdf --pages primary-document.pdf {other,documents}.pdf -- out.pdf`. The difference here is that document-level structure such as outlines, page numbers, etc., will be copied from the primary document.

**Comment by GreenRaccoon23** [comment]
Windows/PowerShell users also need to put quotes around the `--` argument.

For example, running this:

```powershell
qpdf --empty --pages input.pdf -- output.pdf
```

Results in this error:

```text
qpdf: error at * in numeric range *output.pdf: unexpected character
```
The correct syntax for PowerShell is this:

```powershell
qpdf --empty --pages input.pdf '--' output.pdf
```

**Comment by tarifa10** [comment]
hello dear all  

i just run into terrible issues: see here for more deatails: https://www.linuxquestions.org/questions/showthread.php?p=6151676#post6151676
```

martin@mx:~/Dokumente/kalender/ueberschaar__fixes_urlaub
$ qpdf 98_225.pdf --pages . 1-z:even -- odd.pdf

qpdf: error at * in numeric range 1-z*:even: unexpected character

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help

martin@mx:~/Dokumente/kalender/ueberschaar__fixes_urlaub
$ 
martin@mx:~/Dokumente/kalender/ueberschaar__fixes_urlaub
$ qpdf 98_225.pdf --pages 98_225.pdf 1-z:odd -- even.pdf

qpdf: error at * in numeric range 1-z*:odd: unexpected character

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help
```


now i finally encountered that there something is totally wrong with my system: i cannot copy and paste commands - this does not work here. so i finally do one thing: i will type all the commands character by character...

question: should i type each of the four lines - i guess so. i guess that i need all the four lines.

look forward to hear from you - either here or there https://www.linuxquestions.org/questions/showthread.php?p=6151676#post6151676
