### ISSUE TITLE
Can you kindly add "deskew, descreen, remove background, text sharpening" option for scanned PDF ?

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#111]
Hi.

Adobe acrobat has such abilities & till now no opensource on Linux has such abilities !

What encourage me to ask you for these function is the fact that your great tool output PDF file has same quality of original input scanned PDF without distroying resolution or effect it adversely !

On Adobe acrobat pro these functions have following choices (under "optimize scanned PDF):

a. deskew (either ON or OFF)
b. descreen (either ON or OFF)
c. remove background (either OFF, Low, Medium, or High)
d. text sharpening (either OFF, Low, Medium, High)

The most important point is that if these functionalities added to QPDF, then the resolution of output PDF should not altered adversely.

Best

**Comment by jbarlow83** [comment]
My program [ocrmypdf](https://github.com/jbarlow83/OCRmyPDF) (which uses qpdf for some of its PDF manipulation) can deskew and remove backgrounds without changing the resolution or original compression setting. You can disable OCR if desired, although OCR needs to be redone after deskewing.

**Comment by jberkenbilt** [comment]
qpdf is focused on structural manipulation of files. As @jbarlow83 points out, it would be possible to use qpdf to help with a program that does this, but this is not something I would include in qpdf itself.

**Comment by Nokia808** [comment]
@jbarlow83 

Many thanks for this !!! But unfortunately it is not available on Fedora repositories. 
Just I would like to know:
- does ocrmypdf have option to descreen (remove dots noises without removing dots of characters) ?
- does ocrmypdf have option to increase sharpness of text (make text more clear) ?
- does ocrmypdf have a frontend GUI or not ?

---------------------
In fact we have a great program called gscan2pdf to do all these via unpaper, but result in large sized pdf due to fact it do not support pdf directly, but convert them into image format 1st then reconvert these to pdf. 
It seem that you introduced a program overcome this shortage, which is a very great work !

**Comment by jbarlow83** [comment]
@Nokia808 - this isn't the best place for that Q&A. In short no to the questions. I'm happy to take feature requests and questions on my github issues page.
