### ISSUE TITLE
Proposal for an extension towards --check, as a batch-mode

### ISSUE THREAD

**Issue by rubyFeedback** [qpdf/qpdf#1137]
Hey there folks,

Today I tried to merge tons of .pdf file into a single .pdf file. But it
failed, because one .pdf file was faulty.

Now I wanted to find out which one it was, so I used:

    qpdf --check

This one allows only one .pdf file, though, such as:

    qpdf --check foobar.pdf

It's no issue for me as I can just call qpdf from ruby, so I
get an entry of all files via ruby, then iterate over them
via .each, and call system() on it with qpdf (or rather
`` backticks, and then parse the result).  So for my own
use case I already solved today's problem here.

But I was also thinking ... what if there is a commandline
flag built into qpdf, checking on all .pdf files? Whether they
are all ok or not.

That would be nice on windows in particular.

So here is my suggestion:

    qpdf --check-all
    qpdf --check-extended
    qpdf --check-everything
    qpdf --checking

Just giving ideas for syntax. The idea is that this should take
all .pdf files from the CURRENT working directory, and then
call the functionality of --check on it. So, in other words, all
we would need is to have qpdf work on a list of files; the
rest of the functionality e. g. via --check is probably already
available via some function / method.

(If the functionality already exists please ignore this.)

**Comment by mschilli87** [comment]
If I understand correctly, one could just use `find` with `--maxdepth` and `--exec` or `ls` and `xargs` with `-n` on any POSIX shell to run `qpdf --check` on one file file at a time. IMHO this is easily solvable outside of `qpdf` so modifying the (already complex) interface of `qpdf` is not worth it. But maybe I am missing something.

**Comment by jberkenbilt** [comment]
Yup, what @mschilli87 said. There are plenty of ways to do this from the shell (or ruby), and qpdf's CLI is already big and complicated. There's also (with bash or zsh) `for i in *.pdf; do qpdf --check $i || echo "$i FAILED"; done`
