### ISSUE TITLE
Add support for redacting text

### ISSUE THREAD

**Issue by gredler** [qpdf/qpdf#1139]
It would be nice if qpdf supported redaction of text within PDF files.

The text to be redacted could be specified via regular expression, e.g. to redact social security numbers:

`qpdf input.pdf --redact="\d{3}\-\d{2}\-\d{4}" output.pdf`

For a more advanced use case, it could also support matching surrounding text but redacting only regex groups (if present), e.g. to redact email usernames but not the corresponding email domains:

`qpdf input.pdf --redact="(\S+)@\S+\.\S+" output.pdf`

With the standard PDF fonts, the replacement character could be something like `X` or `*`. With embedded / subset fonts, the replacement character would be limited by the available glyphs.

This functionality would not work with images of text, or with vector shapes that look like text.

When the `--verbose` switch is enabled, qpdf could log the number of text sequences that were redacted (logging the actual text that was redacted might not be advisable, since the information is presumably sensitive).

**Comment by jberkenbilt** [comment]
Thanks for the suggestion. It's unlikely that qpdf will ever be able to do this. It's not a focus of qpdf to modify content streams in a way that requires parsing and understanding the meaning of the content. I think it would be possible to write software that could do this using qpdf, but that software would have to be able to interpret character strings in content against the /ToUnicode map and make judgments based on font metrics about where word boundaries are, etc. Ordinarily I leave enhancements suggestions open, but in this case, as this would be, I just don't see it as a feasible qpdf feature in the foreseeable future. I'm going to close this, but if you have additional questions, feel free to reopen or add additional comments.
