### ISSUE TITLE
 Encryption Options 

### ISSUE THREAD

**Issue by lassegraves** [qpdf/qpdf#114]
I'm trying to add restriction to a pdf file, but don't need a user password. I fail to get this right for some reason.

qpdf.exe --encrypt 40 -modify=y -extract=y -annotate=y -- in.pdf out.pdf

how should I specify the empty password strings?

**Comment by jberkenbilt** [comment]
Hi. Sorry for the long delay in responding. Just use `""` as a password. For example

```
qpdf.exe --encrypt "" owner-password 40 -modify=y -extract=y -annotate=y -- in.pdf out.pdf
```
