### ISSUE TITLE
Test libqdf pdf-npages example by using vs2013, And It reports a memory type error

### ISSUE THREAD

**Issue by napasa** [qpdf/qpdf#116]
I am tring to compile and test qpdf examples, I encounter a error that I dont know how to solve it. Here is a error detail. I compile pdf-npages.cc by using vs2013 with qpdf-6.0.0-bin-msvc32 download from sourceforge. After compile pdf-npages.cc successfully, I try to run demo.  It encounter a Assertion failure which content is  "Debug Assertion Failed！ Expression: _BLOCK_TYPE_IS_VALID(pHead->nBlockUse)" until lines that `QPDFObjectHandle count = pages.getKey("/Count")`

**Comment by jberkenbilt** [comment]
I'm not sure what to tell you. I build with vs2015 and don't see that. master on github has updates to support the newer msvc toolchain. QPDF 7.0.0 will be released sometime this summer, and it will support 2015.

**Comment by napasa** [comment]
I endeavour hardly to compile source code from github, But It seems so difficulty.

**Comment by jberkenbilt** [comment]
It's a bit challenging on Windows. You need a system with autoconf to bootstrap. I will probably release an alpha version at some point. You can subscribe to qpdf-announce (see https://qpdf.sourceforge.net). Alternatively, I can email or attach autofiles.zip for current master, keeping in mind that it will become obsolete before any future release.

**Comment by jberkenbilt** [comment]
I'm closing this issue as it is very old and Windows support has improved considerably since it was created.
