### ISSUE TITLE
qpdf: unknown option --replace-input

### ISSUE THREAD

**Issue by benjibasson83** [qpdf/qpdf#1183]
Hi
I would like to use --replace-input option with qpdf 10.5.0 ( the last for slackware 15)

unfortunaly when I do `qpdf input.pdf --underlay sign.pdf --replace-input`
it is always saying 
`qpdf: unknown option --replace-input`
althought it is printed to help option: 
`The output file can be - to indicate writing to standard output, or it can
be --replace-input to cause qpdf to replace the input file with the output.`

If I do` qpdf input.pdf --underlay sign.pdf -- input.pdf` 
I get 
`qpdf: input file and output file are the same; use --replace-input to intentionally overwrite the input file`

How to use replace-input to replace input please? what is the syntax of --replace-input please?

Cheers

**Comment by m-holger** [comment]
Try
```
qpdf input.pdf --underlay sign.pdf -- --replace-input
```

The `--underlay` option must be terminated with `--`.  The documentation for the underlay option can be found at https://qpdf.readthedocs.io/en/10.5/cli.html#overlay-underlay.
