### ISSUE TITLE
qpdf --json fails with "operation for dictionary attempted on object of type null"

### ISSUE THREAD

**Issue by byF** [qpdf/qpdf#1189]
When I run `qpdf --json thefile` on a certain file, it fails with `operation for dictionary attempted on object of type null` right after it prints out `"pagelabels": []`.

- `qpdf --check thefile` doesn't report anything
- `qpdf thefile test.pdf && qpdf --json test.pdf` fails with the same error, i.e. qpdf doesn't make any correction on the file itself

PDF viewers can display the file.

**Comment by m-holger** [comment]
@byF, do you have an example file that you can share? If not, could you share a copy of the file root object? (i.e. run 
`qpdf --show-object=trailer sample.pdf`. The output will contain something like `... /Root **3** 0 R ...`. Run 
`qpdf --show-object=**3**` (replacing 3 with the id of the root object of the sample file). Thanks.

**Comment by m-holger** [comment]
I have tried to reproduce the problem with input files with /PagesLabels entries of indirect null and empty dictionary as well as indirect null for /Acroform (which is output after ```"pagelabels": []```), all without success. Difficult to diagnose without any information about the file that causes the problem.

**Comment by jberkenbilt** [comment]
This happens if there are Widget annotations on a page that are not mappable to form fields. The code path occurs on a file with Widget annotations but no Acroform dictionary, among possibly other situations. I will push up a simple fix.

As a workaround, if you specify `--json-keys` with the ones you want and omit `acroform`, it will not traverse the code path that is causing the crash.

**Comment by arditmete** [comment]
Hello, am having this issue as well, is it something i can do on my end about it ? 
```
Job is failing and retrying with a potentially unrecoverable error. Failure encountered: \"WARNING: object ***** *: operation for dictionary attempted on object of type null: returning null for attempted key retrieval\
WARNING: object **** * : operation for dictionary attempted on object of type null: returning null for attempted key retrieval\
WARNING: object **** * : operation for dictionary attempted on object of type null: ignoring key replacement request\
qpdf: operation succeeded with warnings; resulting file may have some problems\
```
Thanks!

**Comment by m-holger** [comment]
@arditmete  , there is not a lot to go on to diagnose the issue.  

It looks like qpdf succeeded with warnings, and some job that was running qpdf  treated this as a fatal error. If this is the whole of the problem, have a look at the [exit status](https://qpdf.readthedocs.io/en/stable/cli.html#exit-status) section in the manual for info on how a job running qpdf can distinguish  between qpdf terminating with an error and qpdf producing warnings.
