### ISSUE TITLE
Question : how to burn in form field font and appearances

### ISSUE THREAD

**Issue by CanadianHusky** [qpdf/qpdf#1197]
The supplied sample file is a minimalistic example with a dynamic form field whose font for the text form field is /Garamond
![image](https://github.com/qpdf/qpdf/assets/35332003/116d9cb5-1944-4f3c-99d7-dd6b1df8a1a2)

5 0 obj
<</Rect[0 0 283.46 141.73]/Subtype/Widget/V(0-E150.PDF )/FT/Tx/DR<</Font<</Helv 4 0 R>>>>/P 6 0 R/DA(/Garamond 12 Tf 0 g)/F 4/AP<</N 1 0 R>>/BS<</W 1/S/S>>/Type/Annot/Ff 4194308/T(variable)>>

Opening the PDF in Acrobat displays a Helvetic/Arial style font (wrong)
Clicking into the dynamic annotation (Form Field) causes the correct (Garamond) font to be displayed.
I am guessing the required appearance stream is not created or embedded properly.

![image](https://github.com/qpdf/qpdf/assets/35332003/821cc217-6973-4031-ae5e-ce6f4a24c173)

Using 
`qpdf.exe "input.pdf" "output.pdf" --generate-appearances --flatten-annotations=all`

I was hoping to "burn in" the font appearance and make the PDF open with Garamond font, without the need to click into the field because it will be processed with other software afterwards. It did not work. The output is still Helvetica Style font.

Is this possible with QPDF ?
Thank you

[input.pdf](https://github.com/qpdf/qpdf/files/15321495/input.pdf)

**Comment by jberkenbilt** [comment]
This into the category of things that qpdf doesn't do out of the from the command line but you could probably code it with the library, though it might not be possible depending on how much of the Garamond font was embedded. qpdf doesn't have any capability fonts or font embedding. It just obeys whatever the PDF says should be used for appearance stream generation. Tools like Acrobat, which obviously support everything in the PDF spec and beyond, have more sophisticated capabilities regarding fonts and can deal with form fields that use subsetted fonts, Unicode characters, etc. qpdf just does the naive and minimal substitution of the field value into a template that the PDF file provides as part of the form. So qpdf's ability to generate appearance streams is quite limited in comparison to other tools that have full PDF rendering and editing capabilities.

**Comment by CanadianHusky** [comment]
Understood. Thank you for the detailed response. I would not expect qpdf to have such capability out of the box but someone comfortable with its API may find this post helpful.

In case it helps others I found 3 ways to fix this 'downstream' but I solved my problem 'upstream' by not creating the problem in the first place.
Upstream fix: create the formfield textfield with the final desired font while creating the initial pdf itself via code. Changing the form field font post-creation manually in Acrobat causes unwanted side effects as the first appearance stream does not match the dynamic field property anymore when opened.

downstream fix 1:
Using another library and manipulate the appearance stream via code as shown in the example works
https://github.com/pymupdf/PyMuPDF/issues/1184#issuecomment-1173652342

downstream fix 2:
unpack the pdf with `qpdf --qdf input.pdf output.pdf` (amazing function for people that know the PDF spec)
manipulate appearance stream via code in dictionary /AP /N by injecting/replacing the desired font (which is what the python code above does too) - changes shown below on 2 lines marked with **  This is super convenient for experiementing with the PDF syntax and testing if a particular change worked because the changes can be made manually with a binary/text editor.
fix output with `fix-qdf.exe` (wonderful tool!)

```
%% Original object ID: 1 0
19 0 obj
<<
  /BBox [
    0
    0
    283.46
    141.73
  ]
  /FormType 1
  /Matrix [
    1
    0
    0
    1
    0
    0
  ]
  /Resources <<
    /Font <<
      /Helv 29 0 R
	  **/Garamond 9 0 R**
    >>
    /ProcSet [
      /PDF
      /Text
      /ImageB
      /ImageC
      /ImageI
    ]
  >>
  /Subtype /Form
  /Type /XObject
  /Length 20 0 R
>>
stream
q Q /Tx BMC q 1 1 281.46 139.73 re W n q BT 1 0 0 1 2 66.56 Tm **/Garamond** 12 Tf 0 g (0-E150.PDF)Tj 0 g ET Q Q EMC 
endstream
endobj

```

downstream fix 3:
PDFSharp library can do the dictionary and stream modification done in fix 1 and 2 as well (or any library that can do low-level manipulation on the PDF objects

Obviously all suggested downstream fixes require intimate knowledge of the PDF Spec - but once you do it is easy.

**Comment by jberkenbilt** [comment]
@CanadianHusky What a great summary. Thanks for sharing it here. I agree with your approach -- fix the problem as close to the source as you can. I like how you have made use of a variety of tools here, each for their strengths. Yes, qpdf's strongest suit these days, with so many capable PDF tools out there, is as a power tool that enables PDF experts to work with PDF files in a surgical way. Of course, qpdf has all its other features too, but it's definitely not the only tool that can encrypt, split pages, etc. But it still has an edge when it comes to letting people gain full control over PDF files in the way you described.
