### ISSUE TITLE
Form still not working with pdftk when file decrypted

### ISSUE THREAD

**Issue by Sen** [qpdf/qpdf#12]
PDF file: http://www.immi.gov.au/allforms/pdf/1066.pdf
Part C, question 53. Title(mr/mrs/miss/ms)

Only this kind of Button not working, other parts seems work.

**Comment by jberkenbilt** [comment]
I never did anything with this, and I can't longer reproduce it. Work is being done on form flattening as well. I'm going to close this as "incomplete", but feel free to reopen if this is still an issue.

**Comment by jberkenbilt** [comment]
Actually, I found that I had previously saved the zip file. I am not able to reproduce any issues with the latest qpdf.

**Comment by jberkenbilt** [comment]
For future record, note to self: files saved in `~/source/qpdf/misc/1196s*`
