### ISSUE TITLE
checking error: should they be reported?

### ISSUE THREAD

**Issue by ousia** [qpdf/qpdf#1218]
@jberkenbilt,

many thanks for your excellent tool.

[Faulty PDF document](https://github.com/user-attachments/files/15945529/a.pdf) that `qpdf-1.19.0` (from Fedora 40) validates:

``` bash
$ qpdf --check a.pdf
checking a.pdf
PDF Version: 1.7
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
```

I have found that `pdfcpu` detects the following error:

``` bash
$ pdfcpu validate a.pdf
validating(mode=relaxed) a.pdf ...
validation error (obj#:3): pdfcpu: validateFormFieldKids: non terminal field can not be widget annotation
```

Sorry, just in a hurry, but I don’t know whether you are interested in reports of this kind of errors.

Many thanks for your help.

**Comment by jberkenbilt** [comment]
Thanks for the report. qpdf at this time doesn't do that kind of validation. We've had some discussion about whether it should, but for now, qpdf mainly validates structural things and doesn't look too closely at errors that don't prevent it from doing what it's trying to do.

**Comment by jberkenbilt** [comment]
Yes, qpdf checks the main xref. I think it doesn't report errors in the "deleted" entries, which are supposed to form a closed loop, but otherwise, if there are problems with the xref table (or stream), qpdf will report errors and attempt to recover the file.
