### ISSUE TITLE
Issue with Page object in splitting the PDF after merge

### ISSUE THREAD

**Issue by Thirumaniselvan** [qpdf/qpdf#122]
Hi,

I have two PDFs (first one with 2 pages and the second one with 180 pages). My requirement is to merge these PDFs and then split them at 100 pages each. (i.e in this example first one with 100 pages and the second one with the remaining 82 pages).

Note: The first PDF doesn't have the /Threads elements in the structure and the second PDF has the /Threads element in the structure.

When I try to CopyForeignObject while creating the second split the /Pages & /Page elements from the second PDF is not getting copied to the output PDF. From the CopyForeignObject method definition I could see that /Pages & /Page attributes are explicitly ignored during copy.

Can you please advice on the way to write/copy the /Pages & /Page elements.

Regards, 
Thiru

**Comment by jberkenbilt** [comment]
Take a look at the code in qpdf.cc. Search for `! page_specs.empty()`. The act of copying pages is explicit. You may find that code as a good model to copy off of. If you have any specific questions, I can try to help.

**Comment by jberkenbilt** [comment]
I'm going to go ahead and close this issue, but feel to reopen if you discover a problem in qpdf that prevents you from doing what you're trying to do.
