### ISSUE TITLE
Is it possible to define a page range to the next to last page?

### ISSUE THREAD

**Issue by jsx97** [qpdf/qpdf#1246]
```
qpdf --empty --pages input.pdf 50-z -- output.pdf
```

If I use this command, the output file will contain pages from 50 to the last. But is there a way to tweak this syntax so that the output file will contain pages from 50 to the next to last instead? That is, for example, if the input file is 100 pages, the output is assumed to contain pages 50 to 99.

**Comment by jberkenbilt** [comment]
`50-r2` -- see `qpdf --help=page=ranges` for details.
