### ISSUE TITLE
libqpdf/QPDFTokenizer.cc throws error while compiling

### ISSUE THREAD

**Issue by psmlbhor** [qpdf/qpdf#125]
I recently pulled latest master and tried to compile it. It gave

libqpdf/QPDFTokenizer.cc: In member function 'void QPDFTokenizer::resolveLiteral()':
libqpdf/QPDFTokenizer.cc:71:66: error: 'strtol' was not declared in this scope
                     char ch = static_cast<char>(strtol(num, 0, 16));
                                                                  ^
libqpdf/QPDFTokenizer.cc: In member function 'void QPDFTokenizer::presentCharacter(char)':
libqpdf/QPDFTokenizer.cc:264:59: error: 'strtol' was not declared in this scope
      val += static_cast<char>(strtol(bs_num_register, 0, 8));
                                                           ^
libqpdf/QPDFTokenizer.cc:390:49: error: 'strtol' was not declared in this scope
   char nch = static_cast<char>(strtol(num, 0, 16));

Header file <cstdlib> is not included in libqpdf/QPDFTokenizer.cc

**Comment by jberkenbilt** [comment]
Thanks. I'll take your fix.
