### ISSUE TITLE
Allow --pages to accept the page from the same file more than once

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#127]
Make it so you can do `qpdf a.pdf --pages a.pdf 1 b.pdf 1 a.pdf 1 b.pdf 2 -- out.pdf` instead of having to specify different strings to represent the paths of the same file when duplicating a page.

**Comment by jberkenbilt** [comment]
never mind

**Comment by Nokia808** [comment]
I did not understand ! Is this will fix next release or not ?

**Comment by jberkenbilt** [comment]
It's not a bug. I was mis-remembering the problem. It works in 6.0.0.

**Comment by Nokia808** [comment]
So my question in:
https://github.com/qpdf/qpdf/issues/112

is not needed to be asked & no need to use "./" isn't it ?

**Comment by jberkenbilt** [comment]
Correct, for your question in #112, there is no need to use "./".

**Comment by jberkenbilt** [comment]
In case anyone's interested in this, starting in 8.4.0, it will no longer ever be necessary to use the `./` workaround as it will work to copy the same page multiple times from the same file.
