### ISSUE TITLE
Using wildcards results in file deletion

### ISSUE THREAD

**Issue by gamer191** [qpdf/qpdf#1270]
I don't know if this is fixable, and it probably falls under user error. Regardless I wanted to report it anyway:

Steps to reproduce:
1. Create a directory with 2 PDF files (which you don't mind getting deleted)
2. run `qpdf --linearize *` in the Linux terminal (might also work on Windows)

Expected behaviour:

Both files get linearized

Actual behaviour:

The terminal expands the command to `qpdf --linearize file1.pdf file2.pdf`. This is interpretted by qpdf to mean that file1.pdf is the input and file2.pdf is the output, resulting in file2.pdf being overwritten with a linearized version of file1.pdf

Once again, I doubt this is fixable. If it isn't, feel free to close this issue

**Comment by jberkenbilt** [comment]
It's not fixable. Wildcards are expanded by the shell. qpdf doesn't know whether you used wildcards or not. The only way to fix it would be to require some kind of confirmation if the output file existed, and that would be a significant behavior change. Sorry you got hit by this sharp edge. I suspect many of us have done that kind of thing at one time or another.

**Comment by mschilli87** [comment]
workaround:
```sh
echo * | xargs -n1 qpdf --linearize
```

**Comment by jberkenbilt** [comment]
> ```shell
> echo * | xargs -n1 qpdf --linearize
> ```

Except that qpdf --linearize actually requires an output. You could do
```
echo * | xargs -n1 qpdf --linearize --replace-input
```
or something with a shell for loop.

**Comment by mschilli87** [comment]
> Except that qpdf --linearize actually requires an output.

```sh
echo *.pdf | xargs -n1 -I{} sh -c 'pdf="{}";qpdf --linearize "$pdf" "${pdf/%.pdf/_linearized.pdf}"'
```
