### ISSUE TITLE
insufficient arguments to --pages

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#129]
Sometimes `qpdf --empty out.pdf --pages *.pdf --` says `insufficient arguments to --pages`. This is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825246.

**Comment by jberkenbilt** [comment]
Note to self: I see this if I run in my pdf examples directory.

**Comment by abliss** [comment]
For anyone else who lands here from a web search: this still seems to affect version 8.0.2 which is the latest release in Ubuntu Bionic.
There's a workaround in the link above: just put out.pdf at the end, so run
```
qpdf --empty --pages *.pdf -- out.pdf
```
instead of
```
qpdf --empty out.pdf --pages *.pdf --
```
