### ISSUE TITLE
Compile error with qpdf-11.9.1 and GCC gcc version: 15.0.0 20240919 (experimental)

### ISSUE THREAD

**Issue by rubyFeedback** [qpdf/qpdf#1290]
[ 54%] Linking CXX executable test_xref
    [ 54%] Built target test_xref
    [ 54%] Building C object qpdf/CMakeFiles/qpdf-ctest.dir/qpdf-ctest.c.o
    [ 55%] Linking CXX executable qpdf-ctest
    [ 55%] Built target qpdf-ctest
    [ 55%] Building C object qpdf/CMakeFiles/qpdfjob-ctest.dir/qpdfjob-ctest.c.o
    [ 56%] Linking CXX executable qpdfjob-ctest
    [ 56%] Built target qpdfjob-ctest
    [ 57%] Building CXX object libtests/CMakeFiles/cxx11.dir/cxx11.cc.o
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc: In function ‘void do_inttypes()’:
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:75:16: error: ‘uint8_t’ was not declared in this scope
     75 | check_size<uint8_t>(1, false);
     | ^~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:10:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
     9 | #include <regex>
     +++ |+#include <cstdint>
     10 | #include <type_traits>
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:75:24: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     75 | check_size<uint8_t>(1, false);
     | ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:75:24: error: template argument 1 is invalid
     75 | check_size<uint8_t>(1, false);
     | ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:77:16: error: ‘uint16_t’ was not declared in this scope
     77 | check_size<uint16_t>(2, false);
     | ^~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:77:16: note: ‘uint16_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:77:25: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     77 | check_size<uint16_t>(2, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:77:25: error: template argument 1 is invalid
     77 | check_size<uint16_t>(2, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:79:16: error: ‘uint32_t’ was not declared in this scope
     79 | check_size<uint32_t>(4, false);
     | ^~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:79:16: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:79:25: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     79 | check_size<uint32_t>(4, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:79:25: error: template argument 1 is invalid
     79 | check_size<uint32_t>(4, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:81:16: error: ‘uint64_t’ was not declared in this scope
     81 | check_size<uint64_t>(8, false);
     | ^~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:81:16: note: ‘uint64_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:81:25: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     81 | check_size<uint64_t>(8, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /depot/j/qpdf-11.9.1/libtests/cxx11.cc:81:25: error: template argument 1 is invalid
     81 | check_size<uint64_t>(8, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    make[2]: *** [libtests/CMakeFiles/cxx11.dir/build.make:76: libtests/CMakeFiles/cxx11.dir/cxx11.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:990: libtests/CMakeFiles/cxx11.dir/all] Error 2
    make: *** [Makefile:166: all] Error 2

I was able to compile 11.9.1 with older GCC releases though, so I think this is some error
related to the more recent gcc I guess. I have not yet tried to git clone the latest qpdf
source, so I don't know if this issue still remains or not.

**Comment by rubyFeedback** [comment]
I just checked with the latest git checkout from the sources here,
and the error could not be reproduced; qpdf compiled fine, thus
I close this issue here, so this is just information.

**Comment by trofi** [comment]
Was fixed in https://github.com/qpdf/qpdf/pull/1259. Worth cutting a new `qpdf` release?

**Comment by jberkenbilt** [comment]
@trofi Yes, we are working on cutting a new release.
