### ISSUE TITLE
Question: Remove openaction from PDF

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#1312]
Hi,

Sometimes we get PDF's that have open actions in it like this `/OpenAction [325 0 R /XYZ null null null]` .. in this case it makes the PDF viewer show page 9 instead of the first page.

Is there an option in QPDF to remove this action?

**Comment by Sicos1977** [comment]
```ps
<< /Type /Pages /Kids [
4 0 R
141 0 R
224 0 R
297 0 R
303 0 R
309 0 R
316 0 R
325 0 R
342 0 R
] /Count 9
>>
endobj
295 0 obj
<< /Type /Outlines /Count 4 /First 296 0 R /Last 348 0 R >>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Outlines 295 0 R
/OpenAction [325 0 R /XYZ null null null]
/PageLabels<<
```

Above is the pages dictionary the line that begins with 325 is page 9

I also have other PDF's that have this kind of behavior so I'm looking for something that just remove the openaction

**Comment by jberkenbilt** [comment]
There's no specific option for this, but it's not hard to do by just getting the dictionary and calling `removeKey("/OpenAction")`. You could also do this by using qpdf JSON to update the dictionary and write it back. I'm not sure if you're looking for something more specific. Based on our previous discussions, I'm assuming you probably know how to proceed based on this, but feel free to ask for additional clarification if required.

**Comment by Sicos1977** [comment]
Thanks
