### ISSUE TITLE
Json job with unicode filenames failes

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#1314]
Hi,

Im trying to execute a JSON job (from C#) with this as input.

```json
{
  "inputFile": "TestFiles\\test - ąbć.pdf",
  "outputFile": "D:\\output.pdf"
}
```

It failes on the diacritics ... I think this used to work in the past.

It fails with this error message --> "qpdfjob json: open TestFiles\\test - ?b?.pdf: Invalid argument"

**Comment by jberkenbilt** [comment]
There are tests in CI for this, so it's probably something on the user end. Perhaps the JSON is not being saved in the correct encoding, or a locale is set wrong, or something. It's highly unlikely to be a qpdf issue.
