### ISSUE TITLE
Question: QPDFJob JSON give file as stream

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#1315]
As far as I now can see it is only possible to input a file and not a stream.

Is it somehow possible to feed the file as a stream into QPDF in combination with a JSON job?

Reason for asking is that my files are coming from a webservice or a database and now I first have to save them to disk before I can do something with it.

**Comment by jberkenbilt** [comment]
The regular qpdf C API supports this, but not the qpdf JOB API.
