### ISSUE TITLE
PDF/A endstream issues

### ISSUE THREAD

**Issue by kilburn** [qpdf/qpdf#133]
This is a follow-up of bug #103. I'm using the current master version (with the `--newline-before-endstream` switch), but qpdf still breaks PDF/A compliance, apparently for the same or a very similar reason.

First, we start with a PDF/A compliant file, that I want to linearize after adding some metadata using `exiftool` (I've tried with acrobat pro dc and it also reports the file is valid PDF/A-2b):

```
# verapdf 0005d.pdf 
...
      <validationReport profileName="PDF/A-2B validation profile" statement="PDF file is compliant with Validation Profile requirements." isCompliant="true">
...
```
Now I linearize the file using qpdf. Here I try to tell qpdf to make as few modifications as possible, but I've tried with other stream options (compress, generate object streams) with the same results.
```
# qpdf --stream-data=preserve --object-streams=preserve --normalize-content=n --linearize --newline-before-endstream 0005d.pdf 0005d.tmp.pdf
# verapdf 0005d.tmp.pdf 
...
<validationReport profileName="PDF/A-2B validation profile" statement="PDF file is not compliant with Validation Profile requirements." isCompliant="false">
        <details passedRules="120" failedRules="1" passedChecks="74066" failedChecks="5">
          <rule specification="ISO 19005-2:2011" clause="6.1.7" testNumber="1" status="failed" passedChecks="0" failedChecks="5">
            <description>The value of the Length key specified in the stream dictionary shall match the number of bytes in the file following the LINE FEED (0Ah) character
			after the stream keyword and preceding the EOL marker before the endstream keyword.</description>
            <object>CosStream</object>
            <test>isLengthCorrect</test>
            <check status="failed">
              <context>root/indirectObjects[98](105 0)/directObject[0]</context>
            </check>
            <check status="failed">
              <context>root/indirectObjects[205](161 0)/directObject[0]</context>
            </check>
            <check status="failed">
              <context>root/indirectObjects[230](113 0)/directObject[0]</context>
            </check>
            <check status="failed">
              <context>root/indirectObjects[249](15 0)/directObject[0]</context>
            </check>
            <check status="failed">
              <context>root/indirectObjects[264](49 0)/directObject[0]</context>
            </check>
          </rule>
        </details>
      </validationReport>
...
```

Acrobat Pro DC also reports the violation:
![imatge](https://user-images.githubusercontent.com/116100/29004314-d0ce0488-7ac5-11e7-9769-8b74af351170.png)

Is it possible that you are adding the newline to the stream's content length (which you shouldn't do as per the specification)? I am lost as to what else could be wrong here.

You can download my test file from [here](https://la3.org/~kilburn/0005d.pdf)

**Comment by kilburn** [comment]
Ok, I have opened the linearized file using a hex editor, and manually subtracted 1 from the length of the streams of the problematic objects (as highlighted by the validators above). 

The resulting file is compliant again!
![imatge](https://user-images.githubusercontent.com/116100/29004445-5a1380be-7ac7-11e7-9411-2086ef4d049a.png)

**Comment by jberkenbilt** [comment]
I am about to push a fix to this along with several tests cases that exercise this feature in combination with qdf and validate that qdf is not broken. I hand-created a PDF file with three streams: one that has a newline in the stream that is part of the length, one that has a newline before endstream that is not part of the length, and one that has newline before endstream. With `--newline-before-endstream`, the first stream has two newlines before endstream and the other two streams have one. When writing with this and qdf together, all three streams end up with two newlines before endstream, though the second and third also have the `%QDF: ignore_newline` indicator. I think this is the right behavior as it enables fix-qdf to properly calculate the length if the stream is modified. The tests verify that fix-qdf is a no-op on the qdf files with and without this option. It would be great if you can retest. You'll know the changes are in master when this issue is closed automatically by github in a few minutes.

**Comment by kilburn** [comment]
Everything looks fine from my tests, thank you very much for your hard work and the nice piece of software that you made `qpdf` to be!

What I've tried:

1. I've converted your handcrafted test pdf to pdf/a-2b using Acrobat Pro. Then I've passed it through qpdf and checked that compliance wasn't broken. No issues found.

2. I've linearized my test file that was breaking previously, and checked that the file gets linearized correctly and without breaking pdf/a-2b compliance. This went just fine.

PS: If you are ever insterested, [veraPDF](http://verapdf.org/software/) is a free, open-source pdf/a compliance testing tool. You could use that if you want to verify that qpdf doesn't break compliance some other time.

**Comment by jberkenbilt** [comment]
Great, thanks for additional testing. I'll make a note about veraPDF.
