### ISSUE TITLE
floating point exception with malformed input

### ISSUE THREAD

**Issue by hannob** [qpdf/qpdf#141]
The attached file(s) will cause a floating point exception in qpdf. The zip contains two samples, because it seems this bug manifests differently in the release (6.0.0) and the git version of qpdf.

Found with afl.
[fpe-qpdf.zip](https://github.com/qpdf/qpdf/files/1214519/fpe-qpdf.zip)

**Comment by jberkenbilt** [comment]
Thanks. It was a division by zero error. I checked all divisions in the code and only one case where I think division by zero is possible as a result of input and one other case where it could happen from a logic error. Both cases now result in errors instead of crashes.
