### ISSUE TITLE
Such Ultra Great Program need GUI front-end

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#142]
Hi. 
Such great program like qpdf indeed need front-end GUI ! This will be a great push for Linux ....

**Comment by jberkenbilt** [comment]
Thank you for all your suggestions and kind words. While I agree that a GUI for qpdf might be nice, I am not going to write one. If someone else wants to write one, I'm happy to consult and/or provide API or options to qpdf to facilitate having the GUI discover available options, etc. However, as I am basically never going to do this myself (you don't want me designing guis), I'm going to go ahead and close this ticket. Thanks!
