### ISSUE TITLE
Files with a blank PDF version

### ISSUE THREAD

**Issue by rbro** [qpdf/qpdf#15]
Jay - thank you for your help with the few issues I have reported.  I really appreciate it.  I'm running into another issue that I was hoping you could help with.  Again, I'm not able to share these PDF's, but I can provide any much info as you need to diagnose it:

I have some PDF's where the PDF version is showing up as 0.0 in pdfinfo such as:

Creator:        Toolkit http://www.activepdf.com
Producer:       Toolkit http://www.activepdf.com
CreationDate:   Tue Aug 16 07:52:12 2011
ModDate:        Tue Aug 16 07:52:12 2011
Tagged:         no
Pages:          1
Encrypted:      no
Page size:      799.347 x 609.882 pts
File size:      25588 bytes
Optimized:      no
PDF version:    0.0

When I try to process these files with qpdf, I receive an error:

input.pdf: not a PDF file

When I look at the files in a text editor, the first line of the file either is:

%PDF-

or 

%PDF-0

or 

%PDF-0.0

I am able to view the files in Acrobat, Foxit, and SumatraPDF.  I imagine that they are just falling back to a certain PDF version and trying to display the file with that, but not absolutely sure.

Is there a way that qpdf can support these files too?  Please let me know if I can provide more info.

Thanks.

Ryan

**Comment by jberkenbilt** [comment]
This is fixed on the current master and will be in the next release.
