### ISSUE TITLE
jpeg_mem_dest was not declared in this scope

### ISSUE THREAD

**Issue by egberts** [qpdf/qpdf#153]
OS: CentOS 6.9
JPEG: libjpeg-turbo 1.2.1-3.elo6_5
g++: GCC v5.3.1 20160406 (Red Hat 5.3.1-6)

A compile error happened.  I'm sure it's something simple...  Do we know what the minimum version of libjpeg-turbo it has to be for QPDF?

```
libqpdf/Pl_DCT.cc: In member function 'void Pl_DCT::compress(void*, Buffer*)':
libqpdf/Pl_DCT.cc:152:46: error: 'jpeg_mem_dest' was not declared in this scope
     jpeg_mem_dest(cinfo, &outbuffer, &outsize);
```

**Comment by jberkenbilt** [comment]
Hmm. Looking at /usr/include/jpeglib.h, I see

```
#if JPEG_LIB_VERSION >= 80 || defined(MEM_SRCDST_SUPPORTED)
/* Data source and destination managers: memory buffers. */
EXTERN(void) jpeg_mem_dest (j_compress_ptr cinfo, unsigned char **outbuffer,
                            unsigned long *outsize);
EXTERN(void) jpeg_mem_src (j_decompress_ptr cinfo,
                           const unsigned char *inbuffer,
                           unsigned long insize);
#endif
```

Debian unstable has libjpeg-turbo 1.5.2, which emulates libjpeg6, it seems, but must have MEM_SRCDST_SUPPORTED defined.

I wonder how much of a problem this is. It would be possible to implement my own source and destination managers to avoid having to call these. This would be more complex, but it would make this work with older versions of the jpeg library.

In any case, if I'm going to call these methods, I should update the autoconf test to make sure they are present. I'll try to resolve this one way or another before releasing 7.0.0.

**Comment by jberkenbilt** [comment]
@egberts Do you have a way to either test from github master or to apply 40ecba4172722533916c359fcfe5a43dcd0801ea as a patch to 7.0.b1? I modified that code to avoid using the jpeg_mem_src and jpeg_mem_dest methods to be compatible with older versions of libjpeg, This builds and tests clean on CentOS 6 now.

**Comment by egberts** [comment]
Will try it Monday
