### ISSUE TITLE
Pdftk's `r` prefix is missing in QPDF

### ISSUE THREAD

**Issue by dbitouze** [qpdf/qpdf#155]
Pdftk provides a [`r` prefix](https://www.pdflabs.com/docs/pdftk-man-page/#dest-op-cat):

>You can reference page numbers in reverse order by prefixing them with the letter r. For example, page r1 is the last page of the document, r2 is the next-to-last page of the document, and rend is the first page of the document. You can use this prefix in ranges, too, for example r3-r1 is the last three pages of a PDF.

AFAICS,  such a feature is missing in QPDF.

**Comment by jberkenbilt** [comment]
qpdf doesn't have this, but it does let you reverse the order of pages. When you specify a page range, if the first number is higher than the second, it will do the pages in reverse. You could reverse all the pages with `--pages file.pdf z-1` -- But there's no way to get something like the last three pages without knowing how many pages there are, at least in one pass. You could do it in two commands: first z-1, then 1-3.

I could consider an r prefix as an enhancement request.

**Comment by dbitouze** [comment]
>But there's no way to get something like the last three pages without knowing how many pages there are, at least in one pass. You could do it in two commands: first z-1, then 1-3.

Do you mean, for the last 3 pages:
`qpdf --empty --pages issue.pdf z-1 -- temp.pdf && qpdf --empty --pages temp.pdf 3-1 -- outfile.pdf`

>I could consider an r prefix as an enhancement request.

Would be soooo nice! :)

**Comment by jberkenbilt** [comment]
This missed the train for 8.0.0, but it will be in 8.0.1, which I may be able to get out today.

**Comment by dbitouze** [comment]
Works like a charm: thanks!
