### ISSUE TITLE
i could not able to see the text stream for tagged pdf

### ISSUE THREAD

**Issue by dilip1234567** [qpdf/qpdf#156]
My tagged PDF has simple text as attached 
'This is testing pdf for the tagged pdf with courier new font without entering enter key.
This is new paragraph
This is third paragraph.'

when i tried with differnt optionts 
qpdf.exe  "c:\taggedpdf.pdf" "C:\taggedpdf-qpdf.pdf"  --stream-data=uncompress

also tried with 

qpdf.exe  "c:\taggedpdf.pdf" "C:\taggedpdf-qpdf.pdf"  --object-streams=disable

non of them worked to view the text stream.

could you please let me know the issue from the attached file. i took the attached file and executed above command and not working.

if i try to do manually save pdf as tagged pdf and execute above command stream just works fine.

only issue is this tagged pdf document is created from ABBYY and could not able to stream it.
[taggedpdf-with paragraphs-t_ABBYY.pdf](https://github.com/qpdf/qpdf/files/1314558/taggedpdf-with.paragraphs-t_ABBYY.pdf)

**Comment by jberkenbilt** [comment]
I apologize for waiting over six years to acknowledge this issue. I'm going through old issues. I don't understand what is being asked here. I'm closing this issue because of its age, but if this is still an issue for you, feel free to reopen or create a new issue.
