### ISSUE TITLE
How to check if PDF file has user/owner password?

### ISSUE THREAD

**Issue by t246246** [qpdf/qpdf#159]
In Acrobat, if the file is protected by password, one can see the property of the file which has user/owner password (from File -> Properties -> Security Tab -> Show Details.)
I'm looking for the library which can show that information.  So far as I could find, PDFLib have the ability to check the value via pCos interface. See section 4.3 Universal Pseudo Objects at [pCOS Path Reference](http://www.pdflib.com/fileadmin/pdflib/pdf/manuals/pCOS-path-reference-8.pdf) . Note that they say that are available regardless of encryption and password availability.

I'd like to do it with libqpdf and find `check_owner_password()` and `check_user_password()` is useful, however, they are private function in QPDF_encryption.cc. So I tried to add some public function hasUserPassword() and hasOwnerPassword().

So far as I understand (and if it is right), there are limitations **when V < 5**:
1)  When the file has only user password, it is impossible to check if the file has owner password, without giving the correct user password.
2) When the file has the user password and it is given, there is no way to distinguish the states: 'the file has no owner password' and 'the file has the same owner password as the user password'.

First question is whether the limitations above is correct or not.

Anyway, I tried to modify qpdf source, and now I can see these values via `qpdf --show-encryption` command. (As I modified its output, I also modified test scripts and all tests succeeded in my Mac.)
```
$ qpdf/build/qpdf --show-encryption file.pdf 
V = 5
R = 6
P = -4
Has user password: no
Has owner password: yes
User password = 
extract for accessibility: allowed
extract for any purpose: allowed
print low resolution: allowed
print high resolution: allowed
modify document assembly: allowed
modify forms: allowed
modify annotations: allowed
modify other: allowed
modify anything: allowed
stream encryption method: AESv3
string encryption method: AESv3
file encryption method: AESv3
```
(Note that I also add to show V value.)
Thus we can see encryption info and can also check if PDF has password **without** giving password, except for the limited case described above. If the case of limitation 1), owner password is shown as **unknown**, and limitation 2), **no (maybe same)** is shown.

I just pushed it to [my folk](https://github.com/t246246/qpdf/tree/add-check-if-password-exists) repository, so if you have an interest, I'd appreciate if you could check it.

**Comment by jberkenbilt** [comment]
Thanks for doing this. I haven't had time to study it in depth, but it looks like a good addition. At first glance, it seems like there is a lot more code than I would expect for this. When I get a chance, I will study your changes and see if either I want to take them more or less as they are or whether I can find a simpler way to do it. I'm going to put a "next" tag on this so that I remember to study it next time I have a chunk of time to do some qpdf work. This is probably the most complete patch I've received in that it includes updates to the tests as well. Much appreciated.

**Comment by jberkenbilt** [comment]
I don't think this is implemented in a way that I can really include it in the library, but I'll leave the bug open in case I have time to work on it. Thanks again for the patch.

**Comment by fmitha** [comment]
I just happened across this, and I must say that this would be a good feature. It's helpful to know whether the user/owner passwords have been set.

**Comment by jberkenbilt** [comment]
@fmitha Okay, good to know. I've tagged "enhancement". I had descoped this for now, but next time I flip through tickets, I'll take a fresh look. I want to get 9.0.0 out soon. This may or may may not make the cut, but we'll see. Thanks for expressing your interest.

**Comment by jberkenbilt** [comment]
qpdf 9.0.0 will have methods to check whether the supplied password matches the user password and whether it matches the owner password so you can tell if it matches one or both. Also --show-encryption will disclose this information. When I push to master, this issue will close. I'll include a link to the commit so you can see how I implemented it. It's a pretty small code change.

**Comment by jberkenbilt** [comment]
I hope to get qpdf 9.0.0 out this weekend, but if not, then next weekend.

**Comment by jberkenbilt** [comment]
The way you would use this as I implemented it would be just to create the QPDF object in the normal way, possibly supplying a password. If you passed no password or an empty string as the password and you saw isEncrypted() was true, then userPasswordMatched() would be true of there is no user password, and ownerPasswordMatched() would be true if there is no owner password.

**Comment by jberkenbilt** [comment]
This is the commit that encapsulates the changes: https://github.com/qpdf/qpdf/commit/5da146c8b53bb5a12c514f83fb52265e4922b5e1

**Comment by lunaticmonk** [comment]
@jberkenbilt Is there any way I can detect that a pdf is password protected or not? I just want a flag whether a pdf is password protected. I checked out the `--show-encryption`, it gives me the following output:

```sh
$ qpdf/build/qpdf --show-encryption encrypted.pdf
$ ./encrypted.pdf: invalid password
```

Is there a way to do it?

**Comment by jberkenbilt** [comment]
@lunaticmonk Please see #390. I will be adding a feature for this in qpdf 9.1.1, which I hope to get out any day.
