### ISSUE TITLE
Read Arguments from STDIN

### ISSUE THREAD

**Issue by tmclean** [qpdf/qpdf#16]
When calling QPDF from an external process it would be useful to push arguments via standard input. This would help with automated merges that are called on a set of files with unpredictable length and unpredictable file names.

**Comment by thomasbachem** [comment]
I'd like to second this feature request. I'm using `qpdf` in PHP via the CLI and would love to be able to use STDIN instead of creating a temporary file.

Similar to many other command line utilities, I'd like to propose the ability to simply supply a dash (`-`) to tell `qpdf` to read the input from STDIN, e.g. to read from STDIN and write to STDOUT:

```
cat foo.pdf | qpdf --linearize - -
```

**Comment by jberkenbilt** [comment]
qpdf can already take - as an output file to write to stdout, but the PDF file format fundamentally can't work with a non-seekable input, so reading from stdin is not possible. Any program that is able to read PDF files from stdin is doing something internally like writing it to a temporary file or loading it into memory.

However, reading arguments from stdin is certainly doable.

**Comment by thomasbachem** [comment]
I see, thanks for the explanation!

**Comment by jberkenbilt** [comment]
I think adding the ability to read arguments from a file or from stdin would be a good enhancement. I'm thinking about the more-or-less standard convention of `@file` or perhaps `@-` to read from STDIN.

**Comment by jberkenbilt** [comment]
Version 7.0.0, to be released later this summer, will allow `@filename` and `@-` as arguments to mean reading args from a file and stdin respectively. We don't look for `@` recursively. In these files, each line is taken to be a separate option. This allows an arbitrary number of arbitrarily long lines, and the lines can contain spaces, etc. No interpolation is done on the lines. I think it should satisfy this requirement. I will be pushing the change to master momentarily.

**Comment by jberkenbilt** [comment]
Sorry it took soooo long.

**Comment by rl1m** [comment]
I have been trying to use the `@filename` as a command line argument.
However I could not use it for `--encrypt`. Could you give me a guidance, please?

Here what I tried:
```
bash-3.2$ cat encrypt_params.txt 
--encrypt helloworld12345 helloworld12345 40 --
qpdf @encrypt_params.txt test_input.pdf test_passwd.pdf
qpdf: unknown option --encrypt helloworld12345 helloworld12345 40 --

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help
```

Thanks in advance. Look forward to hearing from you.

**Comment by jberkenbilt** [comment]
You need to put each command line argument on a separate line. This is in the docs. Sorry if it's unclear. So your file should contain

```
--encrypt
helloworld12345
helloworld12345
40
--
```

This makes it possible to specify arguments that contain spaces.

**Comment by rl1m** [comment]
Aha..Thanks for the example 🤓
