### ISSUE TITLE
Feature request: support for filling forms

### ISSUE THREAD

**Issue by chneukirchen** [qpdf/qpdf#162]
I realize this is probably a complicated feature, but necessary to replace some uses of pdftk.

Naively, I tried to diff a PDF->QDF of an empty and a filled PDF, but it actually adds new objects to the stream, I don't think I can do this programatically.

It would be nice if qpdf could list all form element names, and then export a PDF where certain elements are set to certain values.

**Comment by sahilarora535** [comment]
This is closely related to #178 if I am correct.

**Comment by jberkenbilt** [comment]
@sahilarora535 Yes, I think you're right. I plan on putting some time into that next week. Thanks for linking the two tickets so I can keep this in mind. While being able to actually fill in forms is not directly on the roadmap, if we get the high level interfaces right, it should be pretty natural to extend qpdf to support this, at least in some limited fashion.

**Comment by sahilarora535** [comment]
@jberkenbilt I think we can safely close this as well since #213 is already merged now.

**Comment by jberkenbilt** [comment]
Thanks @sahilarora535. @chneukirchen -- I'm going to be releasing qpdf 8.1.0 today. It includes some new API for working with forms. I can't currently update appearance streams or embed fonts, but it can enumerate form fields and set values. There's a new example `pdf-set-form-values.cc` that illustrates this. I'm going to close this issue, but if there is a problem, please feel free to reopen or create a new one.

**Comment by rajeshstarlite** [comment]
Hello Jay,


I've searched for this form fill feature in document of qPDF and different related resources but still I don't know how to use this feature. 

Do you have any example / CLI code how we can use this feature?

We've source PDF file where we use Forms Data Format (FDF) placeholders and we want to get them replaced with real values and need final output PDF file.

Thank you

**Comment by jberkenbilt** [comment]
The form filling capbilities are only available through the C++ API. They are not available from the command-line tool. I'm not familiar with FDF, so I can't say for sure whether qpdf has everything that you would need to do this, but even if it does, you would have to write C++ code to do it. Probably not the answer you were hoping for, but I hope this helps.

**Comment by rajeshstarlite** [comment]
Thanks @jberkenbilt 

I understand.
