### ISSUE TITLE
How to use the qpdf in vb.net

### ISSUE THREAD

**Issue by rmellnick** [qpdf/qpdf#169]
would love to put a little wrapper around this program. I use it often to convert large volumes of pdf's when our other 3rd party pdf makers mess them up.

Is there a way to use the qpdf18.dll in vb.net ? Do you happen to have any examples ?

Thanks again for a great program

Russ

**Comment by jberkenbilt** [comment]
There is a "C" API in QPDF that I wrote specifically to enable someone to do a Delphi integration. You can find details about it in `include/qpdf/qpdf-c.h`. Assuming vb.net can call arbitrary functions in DLLs, you can probably be fairly successful using those methods as you won't have to deal with C++ name-mangling and other complications. The C API is not as complete as the C++ API, but you can do a lot of things with it. Take a look and let me know if you have questions. Note that I have never touched vb.net, and I use Windows environments only when absolutely necessary, so I don't have much in the way of tips and tricks.

**Comment by rmellnick** [comment]
I will look at this. Since I live in the windows environment I had to smile at your comment " I use Windows environments only when absolutely necessary" I once heard a Unix admin say Windows was just a boot virus. 

Thanks

Have a great Holiday
Russ

**Comment by jberkenbilt** [comment]
@rmellnick There are an increasing number of people who are trying to use qpdf from languages like vb, PHP, node, and others where there is no easy way to directly call qpdf. I'm working on some enhancements that will increase the utility of qpdf from the command line. Maybe those will be of some use.

**Comment by jberkenbilt** [comment]
I'm going to close this issue though since there's nothing specifically to do here. Thanks for the report.
