### ISSUE TITLE
When a password includes a '$' in it, QPDF fails to encrypt the file so that other readers can open it

### ISSUE THREAD

**Issue by jeffrobins** [qpdf/qpdf#170]
When a password includes a '$' in it, QPDF fails to encrypt the file so that other reads can open it.  

For example, the password "hop$e" is used to encrypt: 
qpdf --encrypt "hop$e" "hop$e"  256 --print=full  -- input.pdf output.pdf 
Niether Adobe Reader (Windows) or Okular (Linux) can open it with the correct password.

Oddly, if "hope$" is used as the password, then Okular can open the pdf.  I have not tried Adobe with the '$' at the end.

**Comment by jberkenbilt** [comment]
What is your environment? If you are using Linux or a UNIX-like environment and typing the command exactly as above, then the shell is expanding $e as a variable, which is probably empty. Using single quotes instead should resolve the issue, or putting the command line arguments in a file and using the `@file` syntax described in the --help output could also work. Try

```
qpdf --encrypt 'hpe$e' 'hope$e' 256 --print=full -- input.pdf output.pdf
```

If I am right, you will find the password "hop" will work to open your file above.

**Comment by jeffrobins** [comment]
I was using Linux and that was definitely the problem.  Just tried it again and "hop" worked for the password.  I got "hop$e" to work with the single quotes.  
I tried about 20 different things, but never single quotes.  I'll make sure to try them the next time I'm having odd command-line issues.

Thanks
