### ISSUE TITLE
Build picks preinstalled libqpdf.so over the locally built one

### ISSUE THREAD

**Issue by yurivict** [qpdf/qpdf#176]
I had qpdf-6.0.0 installed, and the build of 7.1.0 was failing:
```
/bin/sh ./libtool --mode=link c++ -O2 -pipe -fno-omit-frame-pointer  -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -std=gnu++98 -Wold-style-cast -Wall libtests/build/concatenate.o -o libtests/build/concatenate -ljpeg -lz -L/usr/local/lib -lqpdf -Llibqpdf/build -fstack-protector
libtests/build/bits.o: In function `main':
libtests/bits.cc:(.text+0x5aa): undefined reference to `BitStream::getBitsSigned(int)'
libtests/bits.cc:(.text+0x617): undefined reference to `BitStream::getBitsSigned(int)'
libtests/bits.cc:(.text+0x684): undefined reference to `BitStream::getBitsSigned(int)'
libtests/bits.cc:(.text+0x6f1): undefined reference to `BitStream::getBitsSigned(int)'
libtests/bits.cc:(.text+0x75e): undefined reference to `BitStream::getBitsSigned(int)'
libtests/bits.cc:(.text+0x9fc): undefined reference to `BitWriter::writeBitsSigned(long long, unsigned int)'
libtests/bits.cc:(.text+0xa11): undefined reference to `BitWriter::writeBitsSigned(long long, unsigned int)'
libtests/bits.cc:(.text+0xa24): undefined reference to `BitWriter::writeBitsSigned(long long, unsigned int)'
libtests/bits.cc:(.text+0xa39): undefined reference to `BitWriter::writeBitsSigned(long long, unsigned int)'
```

Newly-built files should be preferred over pre-installed ones.

**Comment by jberkenbilt** [comment]
I'll have to look into this. qpdf 7.1.0 was supposed to have included a fix for this problem.

**Comment by yurivict** [comment]
@jberkenbilt  Please apply this patch and make a release.
https://bz-attachments.freebsd.org/attachment.cgi?id=190221

**Comment by jberkenbilt** [comment]
Can you tell me the exact ./configure line that your system is using? I wonder whether something is being specified with LIBS that should be specified with LDFLAGS. Is there a way to reproduce this easily so I can test various fixes? For example, is there a docker image or AWS AMI or something I could use to get myself a freebsd system quickly? I'd like to make sure that I fix this properly without breaking the previous fix for the same issue on osx, which I know is also BSD-based. For reference, 6299c64cf3351fb1935319378aed421e26ed2f90 is the commit with the other fix to this problem. Clearly it is necessary to specify `-Llocal-build-dir` `-lqpdf` `-Lother-link-directories` `-lother-libs` in that order, but it's hard to get the build code right without knowing the exact way people are initializing things. The right fix may be a little more involved...I may have to parse some of the options and reorder stuff.

**Comment by yurivict** [comment]
```$ ./configure --disable-static --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/ --build=amd64-portbld-freebsd11.1```

**Comment by jberkenbilt** [comment]
Thanks. Looking over the build logic, I think your reversal of $3 $4 is correct and that the reversal of the order in which things were passed to the macros in the other patch was wrong. I will just look it over and make sure the code does what I think it should, and then I'll see if I can test in various environments. I have a mac at work I can use, and I can either find a way to run bsd somewhere or maybe you'll suggest some other way I can test. I would very much like qpdf 8 to not have this problem.

**Comment by yurivict** [comment]
Docker doesn't work on FreeBSD.
OSX is only BSD-based in kernel, not in the user-level software.

**Comment by yurivict** [comment]
Are you able to make a release with the patch, or should I instead just patch the port?

**Comment by jberkenbilt** [comment]
I'm working on a 7.2 release that fixes a just-reported issue with linearization, but I'm not sure when I'll do it. Definitely no sooner than the weekend, possibly later. If you need something sooner, go with the patch, but stay tuned for a 7.1.1 or 7.2.0 release announcement. Whatever I release next will have the fix. I might ask you to test it before I release.

**Comment by jberkenbilt** [comment]
@yurivict I've pushed fixes to master for the three bugs you recently reported. Can you recheck?

**Comment by yurivict** [comment]
I am sorry, I won't be able to recheck. Just make a release, and we will take it from there.

**Comment by jberkenbilt** [comment]
7.1.1 is released.
