### ISSUE TITLE
pdf-bookmarks: Incorrectly encoding (UTF-8) Latin characters 'š' and 'ž'

### ISSUE THREAD

**Issue by hokomo** [qpdf/qpdf#179]
For some reason the `pdf-bookmarks` tool has trouble processing bookmarks that contain the Latin characters 'š' (U+0161) and 'ž' (U+017E).  'š' is wrongly encoded as `C2 9E` (U+009D), while 'ž' is encoded as `C2 9D` (U+009E) (UTF-8 is used from what I've seen in the source code).

Another interesting thing is that the characters are correctly encoded if the bookmark also contains one of the characters 'č' (U+010D), 'ć' (U+0107) or 'đ' (U+0111).

For example, a file with the following bookmarks:

```
ž
žč
žđ
žć
žš
ž ajklyghvbnmxcseqwuioprtzdf
š
šč
šđ
šć
šž
š ajklyghvbnmxcseqwuioprtzdf
```

looks like this when the output of `pdf-bookmarks` is piped into `less`:

```
<U+009E>
žč
žđ
žć
<U+009E><U+009D>
<U+009E> ajklyghvbnmxcseqwuioprtzdf
<U+009D>
šč
šđ
šć
<U+009D><U+009E>
<U+009D> ajklyghvbnmxcseqwuioprtzdf
```

I've prepared 2 test files which you can use to try and reproduce the bug. I've tested two PDF editors: Master PDF Editor 4.3.61 and Foxit Reader 2.4.1.0609. Both files were actually created with Master PDF Editor, but the bookmarks were then added using the two tools separately.

[foxit.pdf](https://github.com/qpdf/qpdf/files/1690734/foxit.pdf)
[masterpdfeditor.pdf](https://github.com/qpdf/qpdf/files/1690735/masterpdfeditor.pdf)

I'm not completely sure that this is due to QPDF but I thought I would check here first.

**Comment by jberkenbilt** [comment]
Thanks for reporting this. I'm going to be preparing a qpdf 8 release soon. I'll try to study this before the release and see if I can figure out what's going on.

**Comment by jberkenbilt** [comment]
I have fixed this on my work branch. The fix will definitely be in qpdf 8. I've used your file in the test suite. Thanks!

**Comment by hokomo** [comment]
@jberkenbilt Tested and works, nice work! Glad I was able to help. :-)
