### ISSUE TITLE
Tagged PDFs

### ISSUE THREAD

**Issue by bigweld86** [qpdf/qpdf#182]
Hi.
I need to create PDFs that are 508 compliant. My current PDF generator supports everything but Tagged PDFs, does qpdf support Tagged PDFs? I didn't see it in the reference documentation.
Thanks

**Comment by jberkenbilt** [comment]
qpdf isn't really a PDF generator primarily. As far as I know, qpdf won't break 508-compliant files if they are processed with qpdf, but I can't guarantee that. qpdf doesn't have any specific support for 508 compliance.

I'm going to close this, but if you have any further questions about this, please feel free to reopen.
