### ISSUE TITLE
Releases of "8.0.rc2", "8.0.rc3" and "8.0.0" erranously include linuxdeployqt-*.AppImage

### ISSUE THREAD

**Issue by KurtPfeifle** [qpdf/qpdf#187]
See

* https://github.com/qpdf/qpdf/releases/

I think these additional artefacts can be removed again manually by the project owner by clicking on the right links in the GitHub web interface...

**Comment by jberkenbilt** [comment]
Oops, thankfully this was just an upload error and not a problem in any code. Thanks. I've fixed 8.0.0 and will fix the others.

**Comment by jberkenbilt** [comment]
All fixed.
