### ISSUE TITLE
qpdf 8.0.1: PDF with no content stream triggers "page operation called on non-Page object"

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#194]
The /Contents key of PDF page is optional and can be omitted to create a blank page. PDF spec 1.7, section 7.7.3.3 has this in a table.

For page objects that omit /Contents, `qpdf --check` says "page operation called on non-Page object" and treats this an error.

Test file attached. 
[no_contents.pdf](https://github.com/qpdf/qpdf/files/1784405/no_contents.pdf)

**Comment by jberkenbilt** [comment]
Thanks. Yes, this is a mistake. All the assertion functions in QPDFObjectHandle get me in trouble. I should finish removing the rest of the assertions. I'll have to update the code to make sure a null content stream is treated appropriately. Should be an easy fix. Thanks for reporting.

**Comment by jberkenbilt** [comment]
As far as I can tell, 100% of the places in the code that call assertPageObject work fine even in cases where it would have thrown an exception. I'm removing all calls to assertPageObject(). I had to make a one-line change to make piping contents work on pages with no contents.
