### ISSUE TITLE
QPDF Doesn't Replace or even Remove Jpx

### ISSUE THREAD

**Issue by MarjaE2** [qpdf/qpdf#196]
Unfortunately many pdf files rely on jpeg2000 and other jpx images. These freeze my computer. These don't even display on my Kindle. Early pdf standards didn't support jpx.

Going by the manual, I think qpdf --force-version=1.4 input.pdf outpu.pdf is supposed to force the pdf into version 1.4, either converting or just cutting incompatible elements such as jpx. It doesn't. The files still contain jpxdecode, and still give error messages on my Kindle.

Going by the manual, I think --object-streams=disable is also supposed to do something about jpx, either decompressing or just cutting them. It doesn't either.

**Comment by jberkenbilt** [comment]
I'm afraid qpdf doesn't do anything with jpx. There are a lot of things --force-version doesn't do. It also never modifies page contents. It would be possible to write a C++ program that uses the qpdf library to replace jpx images with jpeg images, but there is nothing built into qpdf that does it. The example `pdf-invert-images.cc` has a lot of the basic code that would be required in terms of iterating through the pages and getting all the images.

As this isn't something qpdf can do or will be able to do in the foreseeable future, I'll close this issue, but if you have any questions, feel free to comment further or reopen. Thanks.
