### ISSUE TITLE
files VCRUNTIME140.dll and MSVCP140.dll causes error messages

### ISSUE THREAD

**Issue by uwe16321** [qpdf/qpdf#197]
Hello,
using qpdf causes error messages on my Windows10pro-32bit.
command is like:
	.\qpdf-8.0.2\bin\qpdf.exe --decrypt "indatei.pdf" "outdatei.pdf"

using 'vcruntime140.dll' and 'msvcp140.dll' from 'qpdf-8.0.2-bin-msvc32.zip' results errormessages:
	'VCRUNTIME140.dll is either not intended for running on Windows or contains an error. Reinstall the program with the original installation media, or contact the system administrator or software vendor for assistance. Error status 0xc000035a.'
	'MSVCP140.dll is either not intended for running on Windows or contains an error. Reinstall the program with the original installation media, or contact the system administrator or software vendor for assistance. Error status 0xc000035a.'

if i'm alternatively using 'vcruntime140.dll' and 'msvcp140.dll' from 'qpdf-7.0.0-bin-msvc32.zip' it works fine. 
what am I doing wrong?

thanks for your work and your answer.
regards uwe (uwe16321@gmx.de)
i come from Germany. so please excuse me for my bad english.

**Comment by jberkenbilt** [comment]
I apologize for not responding to this issue. Since qpdf's build was replaced with cmake, I doubt this will still be an issue with current qpdf versions. If you have continued issues with this, please feel free to reopen or create a new issue.
