### ISSUE TITLE
doc update: Read password via external file/descriptor

### ISSUE THREAD

**Issue by wavexx** [qpdf/qpdf#198]
I don't see any way currently to pass the encryption/decryption password of qpdf except command-line arguments.

In a multi-user environment, this is a bad idea.

I'd like to provide a file containing the password and/or specify a file description where the password can be read.

**Comment by jberkenbilt** [comment]
Any argument that starts with @ is interpreted as as a file that arguments are read from. If you put the password in a file called /tmp/pass, you can run `qpdf .... @/tmp/pass ...` to pull in the password from the file. I'll close this ticket, but if you are not able to get it from this information, please feel free to reopen.

**Comment by jberkenbilt** [comment]
I guess it would have to be putting `--password=password` in the file. Basically whatever command-line args you want to read, put each arg on a line by itself in a file, and then use `@file` to reference the file. Details are in `qpdf --help` and the manual.

**Comment by wavexx** [comment]
On Wed, Mar 21 2018, Jay Berkenbilt wrote:
> Any argument that starts with @ is interpreted as as a file that
> arguments are read from. If you put the password in a file called
> /tmp/pass, you can run `qpdf .... @/tmp/pass ...` to pull in the
> password from the file. I'll close this ticket, but if you are not
> able to get it from this information, please feel free to reopen.

Ok, I've seen the option now (right at the beginning of the manual!,
sorry about that).

But it would be helpful to point this out in the description of
the --password argument with a simple example as you pointed out.

**Comment by jberkenbilt** [comment]
Good idea. I'll update the documentation to call attention to this for the next release.
