### ISSUE TITLE
the not so useful 'overflow reading bit stream' message

### ISSUE THREAD

**Issue by keszegrobert** [qpdf/qpdf#2]
Hi! I went to a trap that is not very good implemented in qpdf.
When I have written my hint tables 
into the hint stream with my own PDF generator,
I tried to write the bit stream in little endian 
instead of big endian as is written in the reference.
When I checked my generated PDF with qpdf --check-linearization , 
I got an error message saying 'overflow reading bit stream' 
that was not so useful for me, because 
the error was in the first hint table's header not on the end of the stream.
When I am looking for other possibilities, when this can happen
this error can come out when the hint stream contains 
only a little 1bit error somewhere in the hint table.
So what I am suggesting is a more detailed solution 
for checking the hint table fields through processing the hint stream.
Anyway, qpdf is a nice project, well done, guys!

**Comment by jberkenbilt** [comment]
I've added a comment to the to-do list in connection with a different issue. I'm going to go ahead and close this because it's very old and I don't anticipate actually getting to it in the foreseeable future.
