### ISSUE TITLE
How to calculate the hint stream data in linearized PDF files?

### ISSUE THREAD

**Issue by manid2** [qpdf/qpdf#204]
Hi,

Can anyone point me to a proper blog or tutorial where I can study about how to calculate the hint stream data for linearizing [aka web optimizing] the PDF file. It is too complicated for me to do it all alone. So kindly point me to right direction.

Please let me know if you need any information.

Thank you,
Mani

**Comment by jberkenbilt** [comment]
This isn't really a qpdf issue, so I'm going to close this. The hint streams are quite complex to calculate. You can certainly look at qpdf's source code as a guide, but I don't know of any tutorials. I worked it out by reading the spec and testing with a wide range of PDF writers and readers.
