### ISSUE TITLE
Unreachable condition in Token constructor

### ISSUE THREAD

**Issue by mcsjosh** [qpdf/qpdf#206]
In QPDFTokenizer.cc, there's a Token constructor with an `if`/`else if` that both have the same condition, making the second unreachable:

```
QPDFTokenizer::Token::Token(token_type_e type, std::string const& value) :
    type(type),
    value(value),
    raw_value(value)
{
    if (type == tt_string)
    {
        raw_value = QPDFObjectHandle::newString(value).unparse();
    }
    else if (type == tt_string)
    {
        raw_value = QPDFObjectHandle::newName(value).unparse();
    }
}
```
I'd guess the second condition was meant to be `type == tt_name`.

**Comment by jberkenbilt** [comment]
If true, then I think you're probably right. Otherwise, most likely it has to do with potatoes in some way. Thanks for report. I'll fix.
