### ISSUE TITLE
qpdf --check causes assertion failure on a certain file

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#209]
[This PDF](http://aris.empr.gov.bc.ca/ArisReports/27764.PDF) causes an assertion failure with qpdf 8.0.2 on macOS:

```
$ qpdf --check 27764.PDF
PDF Version: 1.4
File is not encrypted
File is linearized
Assertion failed: (this->m->obj_cache.count(og) > 0), function lengthNextN, file libqpdf/QPDF_linearization.cc, line 748.
```

`qpdf 27764.PDF fixed.pdf && qpdf --check fixed.pdf ` produces no errors.

(The file is copyrighted, but may be downloaded freely.)

**Comment by jberkenbilt** [comment]
Thanks for the report and the file. The linearization code is the last place in qpdf's source where I still have to go through and clean up the assertions, replacing them with proper warnings and error handling. This stuff hearkens back to qpdf's earliest use as a PDF validator before I made it open source and added any of its write capabilities. I will leave this open as a reminder. I don't think this is going to be hard to fix. I just have to find a few hours to go through all that code and handle all assertions and exceptions using the library's current error-handling techniques.

**Comment by jberkenbilt** [comment]
(Note to self: saved as issue-209.pdf)
