### ISSUE TITLE
Make page-range optional in rotate option

### ISSUE THREAD

**Issue by dalboris** [qpdf/qpdf#211]
I have a quite common use case where I scan a document and all pages end up upside down. To turn them back up I currently do:

    qpdf --rotate=180:1-z input.pdf output.pdf

Could the page range be optional and default to all pages of the document? This way, users could more simply do:

    qpdf --rotate=180 input.pdf output.pdf

It seems to me that applying the rotation to all pages as default makes sense: what else would users expect with the above command? And it would make the command so readable and easy to remember for those using qpdf only occasionally, especially users not familiar with the command line! :)

By the way, thank you so much for qpdf! I just started using it and so far the syntax is already way more intuitive and readable than pdftk (compare to `pdftk input.pdf cat 1south output output.pdf`), which I was using so far for these types of operations.

Oh, and I suppose that making page-range optional would also be useful for options other than "rotate", but I've only investigated this use case for now so maybe it is already optional for other options.

Also, in the meantime, how would you feel about adding the example `qpdf --rotate=180:1-z input.pdf output.pdf` in the documentation? Since it was my first time using qpdf, I had to do the extra step to look for the page-range syntax (thanks for having a link to it already! :) ). It didn't take long but users not used to reading technical documentation may appreciate an example to copy-paste for what I assume is the most common use of this option, and save them a few minutes of their time. The given example `qpdf in.pdf out.pdf --rotate=+90:2,4,6 --rotate=180:7-9` seems not so common ;)

**Comment by jberkenbilt** [comment]
I like all your suggestions: both the optional page range and doc update suggestions. I'll work these in for the next update. Page ranges are already optional for merging, so this is consistent with other qpdf usage. Thanks for taking the time to make these great suggestions!

**Comment by dalboris** [comment]
Great, looking forward for these changes! Thanks again for your work on qpdf :)

**Comment by jberkenbilt** [comment]
This will be in 8.1, which I hope to get out this week. It took me all of 12 minutes to code and document this one. Thanks for the great suggestion. :-)

**Comment by dalboris** [comment]
Great, thanks for the quick implementation! :)
