### ISSUE TITLE
QUtil::throw_system_error - include errno

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#221]
Could you include the `errno` in the exception message sent by `std::runtime_error`? I'd like to remap  C++ exceptions to their appropriate Python exception for the more common cases (e.g. `FileNotFoundError`). `strerror` localizes the error message, so it's not ideal for checking which error occurred.

Perhaps it would be best to subclass and `std::runtime_error` to include the `errno` as data, as that would avoid breaking any applications that do depend on an exact error message.

**Comment by jberkenbilt** [comment]
Yes, actually QPDFExc is based on an exception hierarchy I designed in a previous life (before std::exception) which included a SystemError exception type that made errno available. I don't think it would be very hard to make this work and then find the places where qpdf throws exceptions in response to various system error conditions.
