### ISSUE TITLE
Image replacement in PDF

### ISSUE THREAD

**Issue by shailenderjain** [qpdf/qpdf#223]
Is there any option to replace images in PDF using this utility with our in build image processing application i.e. we need an option to extract the image on a flat file system which will be processed by our image processing application. The output from the image processing application should replace the image in PDF. The output image will be of same dimension. However, DPI may decrease or increase

**Comment by jberkenbilt** [comment]
One of the examples: [pdf-invert-images.cc](https://github.com/qpdf/qpdf/blob/master/examples/pdf-invert-images.cc) in the examples directory of the source distribution, contains most of the code you would need. It wouldn't be too hard to create a C++ program that uses the qpdf library to do what you want, using that example as a starting point. The idea would be to replace the stream data of each image to contain the new image, updating any of the other image fields as needed. If the image will be the same dimensions, you won't need to modify any of the references to the image, so it should be pretty self-contained to the image objects themselves.

I'll go ahead and close this, but if this doesn't answer your question, please feel free to reopen the issue. Thanks!
