### ISSUE TITLE
Escaped end-of-line markers mishandled

### ISSUE THREAD

**Issue by gtbarnabas** [qpdf/qpdf#226]
When a backslash ("reverse solidus") precedes an end-of-line marker in a literal string, any number of literal carriage returns and/or line feeds that follow the end-of-line marker will be swallowed by QPDF despite the lack of additional backslashes to escape them.
```
(Example: this is a string with an escaped end-of-line, followed by 3 embedded newlines\



but QPDF removes all of them!)
```
Relevant standards text from PDF32000 spec:

7.3.4.2 "The REVERSE SOLIDUS (5Ch) (backslash character) at the end of a line shall be used to indicate that the string continues on the following line. A conforming reader shall disregard the REVERSE SOLIDUS and the end-of-line marker following it when reading the string; the resulting string value shall be identical to that which would be read if the string were not split."

End-of-line marker, 7.2.2 "The CARRIAGE RETURN (0Dh) and LINE FEED (0Ah) characters, also called newline characters, shall be treated as end-of-line (EOL) markers. The combination of a CARRIAGE RETURN followed immediately by a LINE FEED shall be treated as one EOL marker."

Literal newlines in a literal string, 7.3.4.2 "An end-of-line marker appearing within a literal string without a preceding REVERSE SOLIDUS shall be treated as a byte value of (0Ah), irrespective of whether the end-of-line marker was a CARRIAGE RETURN (0Dh), a LINE FEED (0Ah), or both."

EXPECTED BEHAVIOR:

Based on the prescription from the specification, only a single CR, a single LF, or a single CR followed by a LF, should be escaped by a backslash at the end of a line and therefore disregarded when reading the string.

**Comment by jberkenbilt** [comment]
When you say qpdf is discarding these, can you give a specific command? The only time when qpdf does other than preserve exactly what's in streams is in qdf mode (or, more specifically, content normalization mode), and in that mode, it explicitly normalizes whitespace, so discarding unnecessary whitespace is part of the intended behavior. If you can tell me what command you're running and, ideally, provide either a file or just a fragment of content stream, I'll see if I can reproduce what you're describing and explain whether it's a bug or intended behavior. Thanks.

**Comment by gtbarnabas** [comment]
The bug is related to strings, not streams per se. I'm just using the QPDF API to dump PDF objects, and saw that escaped EOL absorbs any number of CR's or LF's afterward. The example string I gave in the original description demonstrates the problem.

Keep in mind this is inside a string, so the only whitespace normalization allowed would be end-of-line marker normalization (CR, LF, or CRLF could all be reduced e.g. to 0Ah as indicated in the spec: "An end-of-line marker appearing within a literal string without a preceding REVERSE SOLIDUS shall be treated as a byte value of (0Ah), irrespective of whether the end-of-line marker was a CARRIAGE RETURN (0Dh), a LINE FEED (0Ah), or both."). Any other whitespace embedded inside a string should be preserved, e.g. if a string contains embedded newlines, they should not be removed.

This patch to QPDF v8.1.0's QPDFTokenizer.cc gives me the expected behavior (i.e. after a backslash, only set string_ignoring_newline for a CR, not for LF's, and then only consume a single LF after that):
@@ -336,5 +336,5 @@
     {
 	if (this->m->string_ignoring_newline &&
-            (! ((ch == '\r') || (ch == '\n'))))
+            (ch != '\n'))
 	{
 	    this->m->string_ignoring_newline = false;
@@ -354,7 +354,8 @@
 	}
 
-	if (this->m->string_ignoring_newline && ((ch == '\r') || (ch == '\n')))
+	if (this->m->string_ignoring_newline)
 	{
 	    // ignore
+            this->m->string_ignoring_newline = false;
 	}
 	else if (ch_is_octal &&
@@ -388,6 +389,6 @@
 
 	      case '\r':
-	      case '\n':
 		this->m->string_ignoring_newline = true;
+	      case '\n':
 		break;

**Comment by jberkenbilt** [comment]
Thanks for the clarification. Yes, this looks like a bug. I'll take a look at the patch and and the behavior and make sure it's handled correctly. I appreciate the report and the additional information.

**Comment by jberkenbilt** [comment]
I have confirmed this bug. Wow, good catch. Extremely few bugs have been found in qpdf's lexer. I'l definitely ensure that this is fixed properly. There are at least two bugs here because qpdf was also not treating CF LF as just LF.
