### ISSUE TITLE
QPDF::isEncrypted() returns incorrect string_method

### ISSUE THREAD

**Issue by gtbarnabas** [qpdf/qpdf#227]
Apparent typo causes cf_stream member to be returned for both stream_method AND string_method.

This patch to QPDF v8.1.0's QPDF_encryption.cc gives me the expected behavior:
```
@@ -1397,5 +1397,5 @@
         V = Vkey.getIntValue();
         stream_method = this->m->cf_stream;
-        string_method = this->m->cf_stream;
+        string_method = this->m->cf_string;
         file_method = this->m->cf_file;
 	return true;
```

**Comment by jberkenbilt** [comment]
Thanks. I'm going to try to get 8.1.1 out in the next few weeks, and I will definitely include this fix.

**Comment by jberkenbilt** [comment]
@gtbarnabas It looks like you're looking through qpdf's code and reporting things as you find them. If this is the case, I really appreciate it. Could I ask you to let me know your status? I'm going to release 8.2.0 (I've had to make a API addition, so it won't be 8.1.1 after all), and if you're "almost done", I might wait to see what else you find. It will probably be a couple of weeks before I can make the release.

**Comment by jberkenbilt** [comment]
Do you have a simple file suitable from a license perspective to include with qpdf's test suite you can share that triggers this bug? If not, I will attempt to generate one for the test suite. Thanks.

**Comment by jberkenbilt** [comment]
I'm just going to include this fix without a test. There are no files in qpdf's test suite that use a different encryption method for strings and streams. I suspect such files are very rare, and it's probably not worth the effort to try to generate a file that uses different methods. If you have one that can be included, that would be great, but if not, this fix is oviously a correct fix.

**Comment by gtbarnabas** [comment]
I actually came across this bug (and the fallback-decryption bug #229) because my co-worker reported some PDF files where my dumping tool said that string encryption was none, but strings for keys like "/Author", "/Title" and "/CreationDate" appeared garbled. So I thought perhaps the qpdf library was returning the wrong encryption information, and after finding those 2 issues by inspection, I assumed there might be some relationship. I'm not at all sure that's what was causing this discrepancy though; my co-worker is looking for the files he reported to me last week, to investigate further.

**Comment by jberkenbilt** [comment]
Great, thanks. Note that if you find files that I can look at but not keep, redistribute, include in the test suite, etc., just let me know. I have good methods of handling files and have even occasionally received files under NDA. If needed, you can email me directly at ejb@ql.org. I sometimes take files people send me, figuring out what's special about them, and then hand-craft files with similar behavior for the test suite, discarding the originals if I am not allowed to keep them.
