### ISSUE TITLE
Fallback string decryptions looks inconsistent

### ISSUE THREAD

**Issue by gtbarnabas** [qpdf/qpdf#229]
By inspection, the damaged-PDF fallback decryption for strings looks like it would be inconsistent: the first string would be treated as RC4, and only subsequent strings would be decrypted with AES.

Proposed patch:
```
@@ -1125,4 +1125,5 @@
 	    // we'd want to use AES if V == 4.
 	    this->m->cf_string = e_aes;
+            use_aes = true;
 	    break;
 	}
```

**Comment by jberkenbilt** [comment]
I agree.
