### ISSUE TITLE
'configure' step fails on OSX because pcre.h isn't found

### ISSUE THREAD

**Issue by pdfkungfoo** [qpdf/qpdf#23]
I'm trying to build QPDF from Git on OSX (Mavericks).

After completing _'./autogen.sh'_ successfully, _'./configure'_ ends with this error:

```
configure: WARNING: unable to find required header pcre.h

configure: error: some required prerequisites were not found
```

I've MacPorts installed:

```
$>  port installed pcre
   The following ports are currently installed:
   pcre @8.33_0 (active)

$>  ls -lh /opt/local/include/pcre.h
  -rw-r--r--  1 root  admin  30K Oct 28 08:02 /opt/local/include/pcre.h
```

I don't understand what the problem is...

**Comment by ademars94** [comment]
I am getting this error and the above fix did not work for me.  Have there been any changes that may have affected this since the issue was raised?
