### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [qpdf/qpdf#234]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ClosedFileInputSource::Members](https://github.com/qpdf/qpdf/blob/651b51f0564d7726df09faf6ac0a0dd36e4fa65a/libqpdf/ClosedFileInputSource.cc#L12 "Destructor for ClosedFileInputSource::Members")
- [Pl_Flate](https://github.com/qpdf/qpdf/blob/7b9f23a99a1ea3e97eaecf80ef29e2805e351b8f/libqpdf/Pl_Flate.cc#L32 "Destructor for Pl_Flate")
- [Pl_RC4::finish](https://github.com/qpdf/qpdf/blob/e8b845dd0344c797b58bfa31b810af53595d2599/libqpdf/Pl_RC4.cc#L47 "Pl_RC4::finish function")

**Comment by jberkenbilt** [comment]
Thanks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/qpdf/qpdf/commit/b6e414b10b3ae7b28ad16da2027106ec59a99a0a "Removal of extraneous null pointer checks").
