### ISSUE TITLE
slowness merging files in 8.1.0 on cifs share

### ISSUE THREAD

**Issue by rbro** [qpdf/qpdf#237]
I am running qpdf on CentOS 7 to merge files that are located on a cifs share (mounted in linux with mount.cifs).

Starting in version 8.1.0, I am seeing slowness merging files on the cifs share, while versions 8.0.0 and earlier are fine.  Merging the file on the native linux partition runs fine.  It's only slow when merging on the cifs share.

I'm just merging a simple pdf file like the attached with:

```time qpdf --empty --pages input.pdf 1-z -- output.pdf```

input.pdf is [input.pdf](https://github.com/qpdf/qpdf/files/2299054/input.pdf).

Could something have changed in 8.1.0 to cause this?  I printed my results below.  Please let me know if I can give more information to help narrow this down.

Thanks for your help.

```
qpdf 8.0.0 with input.pdf on linux partition:
real    0m0.052s
user    0m0.020s
sys     0m0.033s

qpdf 8.0.0 with input.pdf on cifs share:
real    0m0.057s
user    0m0.017s
sys     0m0.035s

qpdf 8.1.0 with input.pdf on linux partition:
real    0m0.082s
user    0m0.037s
sys     0m0.049s

qpdf 8.1.0 with input.pdf on cifs share:
real    0m1.094s
user    0m0.024s
sys     0m0.393s
```

**Comment by rbro** [comment]
Funny timing - I see you just released 8.2.0 and it seems much better there.  It's still slower than 8.0.0 though:

```
qpdf 8.2.0 with input.pdf on linux partition:
real    0m0.053s
user    0m0.026s
sys     0m0.032s

qpdf 8.2.0 with input.pdf on cifs share:
real    0m0.290s
user    0m0.029s
sys     0m0.080s
```

**Comment by jberkenbilt** [comment]
If you use the `--preserve-unreferenced-resources` flag, 8.2.0 will come extremely close to 8.0.2's performance. The slow-down from 8.0.2 in 8.2.0 is the process of finding unreferenced images and excluding them, a performance hit that is often worth the cost. The performance bug in 8.1.0, which you found and which I had already fixed, was because of the change in not keeping all merged files open at the same time. I improved the implementation of this for 8.2.0. There is still some overhead, but it is much smaller.

Please reopen if you find anything major. Thanks.

**Comment by rbro** [comment]
Thanks, when I call it with --preserve-unreferenced-resources, I'm still seeing the same slowness on cifs.  Should it be comparable to 8.0.0?

```time qpdf --preserve-unreferenced-resources --empty --pages input.pdf 1-z -- output.pdf```

Results are:

```
qpdf 8.2.0 with input.pdf on linux partition:
real    0m0.050s
user    0m0.022s
sys     0m0.038s

qpdf 8.2.0 with input.pdf on cifs share:
real    0m0.289s
user    0m0.021s
sys     0m0.096s
```

**Comment by rbro** [comment]
I'm not able to reopen the issue, but I'm not able to get back to the 8.0.0 speeds even with --preserve-unreferenced-resources for the pdf file at https://www.iso.org/iso/annual_report_2009.pdf.

Seeing similar results for the file http://www.peoplelikeus.org/piccies/codpaste/codpaste-teachingpack.pdf when stored on a cifs share.  8.2.0 is better than 8.1.0, but still much slower than 8.0.0.

```
8.0.0 runs in 0.6 seconds
8.1.0 runs in 25.3 seconds
8.1.0 runs in 24.4 seconds with --preserve-unreferenced-resources
8.2.0 runs in 16.8 seconds
8.2.0 runs in 16.3 seconds with --preserve-unreferenced-resources
```

Please let me know if I can supply more information to help narrow it down.  Thanks again for your help.

**Comment by rbro** [comment]
I appreciate your quick response.  I'm happy to run some tests before you release if it helps.

**Comment by jberkenbilt** [comment]
I'm really torn as to what the default should be. My philosophy has been to favor functionality over performance by default. 8.2.0 is pretty good for local file systems, but it will perform badly over network file systems, especially CIFS, which has a high overhead for opening and closing files. It will probaby be very bad over NFS too. I guess =preserving unreferenced items is not too bad of a hit, and that's really what people expect as the default behavior.

I think I'll maybe just add a flag to keep files open and have the default be based on the number of files.

**Comment by rbro** [comment]
From my tests, using --preserve-unreferenced-resources in 8.2.0 is still slower than 8.0.2.  Should those be comparable at least?  From my test above, it was 16 seconds in 8.2.0 vs 0.6 seconds in 8.0.2.  Or is there something else that changed that is affecting it too?

**Comment by jberkenbilt** [comment]
No, there are two separate issues. `--preserve-unreferenced-files` turns off the behavior of analyzing the file to eliminate unreferenced resources. The thing that's killing the performance for remote file systems is the new behavior of keeping files closed and only opening them when reading from them. There is no switch to turn this off in 8.2.0, but in my working version right now, it can be turned off. Can you test from my work branch? If so, I'll push a change where it's off by default and you can see how it does.

**Comment by jberkenbilt** [comment]
If possible, test from https://github.com/jberkenbilt/qpdf off the `work` branch, or grab ed143276358b82cfd5faa4b7a2e7948befe685f0 and apply as a patch. I haven't added the command-line flags, but I have keep_files_open true by default in this commit. With this change plus `--preserve-unreferenced-resources`, performance should match 8.0.0. Then you can see the individual impact of preserve unreferenced-resources.

**Comment by jberkenbilt** [comment]
(There's no `--preserve-unreferenced-files`. I just typed it wrong.)

**Comment by rbro** [comment]
Yes, that seemed to do it.  Using your work branch, I'm getting similar performance compared to 8.0.2 when merging files on a CIFS share.

**Comment by rbro** [comment]
Also, I'm not really seeing any noticeable difference using ```--preserve-unreferenced-resources``` in your work branch - roughly same speeds.

**Comment by jberkenbilt** [comment]
I've done a bunch of measurements. The overhead is low for local file systems on Linux even with hundreds of files in 8.2.0, so I'm going to have the behavior of keeping files open switched off by default at the threshold of 200 files. For people who are merging larger number of files than that but less than their OS's max open files over remote file systems, they can specifiy `--keep-files-open=y` to get back to 8.0.0's performance.

**Comment by rbro** [comment]
Thanks, I confirmed the change works.  Not passing the flag is fast, ```--keep-files-open=y``` is fast, and ```---keep-files-open=n``` is slow.  Just curious, and I'm fine with passing the flag, but for me on linux, ```ulimit -n``` is 1024 and I don't recall ever hitting the file limit in the past.  Is there a way the limit could be dynamically looked up?  If not, that's fine - I'll just always pass the flag in my scripts going forward.

**Comment by jberkenbilt** [comment]
I think it will be hard to look up the limit portably across all the platforms that qpdf is built for. The overhead is low for local file systems. This is not ideal, but it's good enough. The original feature was motivated by someone who was working on a system with max open files = 256, and I also had someone sponsor the feature implementation who was working with many thousands of files on a routine basis and was going to implement so multi-pass divide and conquer thing.

**Comment by rbro** [comment]
I see, yes.  Thinking about it more, and I'm fine with always passing ```--keep-files-open=y``` going forward for my use case, but I believe most linux utilities don't have a separate internal file open limit.  The operating system will just stop the script if you reach its limit.  Using that thinking, should the default be ```--keep-files-open=y``` and instead the user would have to pass a option if you need to get around that because your operating system's limit is low?  Again, I'm fine with passing it - just trying to think about general use cases.

**Comment by rbro** [comment]
And looking back, it looks like I did run into this a few years ago, and I just changed my script to process the files in groups of 500 at a time, which maybe was a little slower, but still worked fine.  I didn't try, but I'm thinking that doing that in groups of 500 will still be faster than open/closing the files with the new behavior as all of my files are on CIFS shares.

**Comment by jberkenbilt** [comment]
When I think about general use cases, I think about non-Linux users. I have tons of mac and Windows users and some users who build on obscure platforms. I'm quite certain that you are correct that doing it in groups of 500 will be faster if you are using CIFS.

**Comment by jberkenbilt** [comment]
Also, there are lots of modern cases where open file limits may be more restrictive, such as when running in containers with specified resource limits, running on embedded devices (though use of CLI would be unusual in that case), etc.

**Comment by jberkenbilt** [comment]
Besides, I don't have time to code a smarter heuristic and still get this out in time for Ubuntu 18.10's code freeze. :-)

**Comment by jberkenbilt** [comment]
Thanks for your report and testing. The timing worked out well.

**Comment by rbro** [comment]
Thanks so much for your help and quick response - really appreciate it.
