### ISSUE TITLE
Qpdf view text in text editor

### ISSUE THREAD

**Issue by geenino** [qpdf/qpdf#238]
i have used qpdf  with 

> qpdf --qdf orig.pdf expanded.pdf

I can see all objects in text editor. But i cannot view the text in the pdf.

I have test with "Hello world" text in pdf. But i can't see this text after decompress. can someone help, how to view the text with objects

Thank you.

File tried with
[Pdf file](https://drive.google.com/file/d/1KalBFyRma8dCKxLjbIy--G0XaYfRyKHF/view?usp=sharing)

**Comment by jberkenbilt** [comment]
This isn't something qpdf can do directly. Text in PDF content streams is often encoded using subsetted fonts where you have to look up each byte in a table to map it into the character, and even when the text appears directly, it is often placed on the page character by character to achieve specific text positioning, so you might not be able to discern individual words. If you were trying to really understand text encoding in PDF, qpdf in qdf mode would help, but if you're just trying to extract text, it will only work for a small class of PDF files.

There are some tools, like ghostscript, that come with pdf extractors. This is somewhat outside my area of expertise though -- probably a good google search would yield better results. I'm just confirming here that just looking at the uncompressed PDF content stream data is not sufficient in the general case to see the text.

I'll close this issue, but feel free to reopen if you have any qpdf-specific concerns.
