### ISSUE TITLE
Handling of invalid indirect references

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#240]
I came across a certain PDF program that generates the following:

```
9 0 obj
<< /Type /Outlines
/First 10 0 R  # <--- indirect reference to null
/Last 9 0 R
/Count 0
>>
endobj

xref
0 10
0000000000 65535 f 
0000003808 00000 n   # <--- 1 0 R
0000003900 00000 n 
0000003964 00000 n 
0000000009 00000 n 
0000000161 00000 n 
0000000243 00000 n 
0000000261 00000 n 
0000003788 00000 n 
0000004022 00000 n   # <--- 9 0 R
trailer
```

There are 9 numbered objects in the xref table. `10 0 R` appears to be an intentionally invalid reference, which the PDF spec says should be treated as an indirect reference to `null`. (reference manual s. 7.3.10). (So this is an awkward construct, questionable PDF spec decision, and the PDF generator in question would be better off deleting /Outlines entirely, but so it is....)

Now the problem: if libqpdf is asked to make a new object with `QPDF::makeIndirectObject`, it will generate an object with the next available number... which happens to be 10. Consequently the null reference `10 0 R` becomes a live reference - quite likely it's pointing at data that doesn't belong in /Outlines at all.

A workaround is to trigger the resolution of all indirect objects before modifying anything. (As such, command line qpdf avoids the problem and deletes the /First key.) 

[kcs.pdf](https://github.com/qpdf/qpdf/files/2376131/kcs.pdf)

**Comment by jberkenbilt** [comment]
Wow, this is icky. There is already code in QPDFWriter that traverses the PDF file making certain objects direct. I could probably move that code and have makeIndirectObject trigger it (or something similar to it) the first time it's called. I'll have to think through whether that has any unwanted side effects. A lighter weight fix that would probably work around this specific problem would be to just detect all indirect references and add explicit nulls to the xref table for these cases. I'll think it through a little. Thanks for the report. This is a weird one.
