### ISSUE TITLE
Compile error on Windows with cygwin

### ISSUE THREAD

**Issue by jbnivoit** [qpdf/qpdf#242]
Hi,

I am building on Windows with the mingw compiler, configured as:

./configure CC=x86_64-w64-mingw32-gcc.exe CFLAGS=-Ic:/github/qpdf/jpeg-6b CXXFLAGS="-Ic:/github/qpdf/jpeg-6b -fpermissive" LDFLAGS=-L./jpeg-6b CXX=x86_64-w64-mingw32-g++.exe

and am seeing the following error:

/bin/bash ./libtool --quiet --mode=compile x86_64-w64-mingw32-g++.exe -Ic:/github/qpdf/jpeg-6b -fpermissive -Wold-style-cast -Wall-MD -MF libqpdf/build/QUtil.tdep -MP -Iinclude -Ilibqpdf  -c libqpdf/QUtil.cc -o libqpdf/build/QUtil.o; sed -e 's/\.o:/.lo:/' < libqpdf/build/QUtil.tdep > libqpdf/build/QUtil.dep
libqpdf/QUtil.cc:713:49: error: ‘int QUtil::_stricmp(const char*, const char*)’ should have been declared inside ‘QUtil’
 QUtil::strcasecmp(char const *s1, char const *s2)
                                                 ^
libqpdf/QUtil.cc: In function ‘int QUtil::_stricmp(const char*, const char*)’:
libqpdf/QUtil.cc:713:49: error: ‘int QUtil::_stricmp(const char*, const char*)’ conflicts with a previous declaration
In file included from include/qpdf/RandomDataProvider.hh:25:0,
                 from libqpdf/qpdf/SecureRandomDataProvider.hh:4,
                 from libqpdf/QUtil.cc:9:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/string.h:69:23: note: previous declaration ‘int _stricmp(const char*, const char*)’
   _CRTIMP int __cdecl _stricmp(const char *_Str1,const char *_Str2);
                       ^~~~~~~~
The issue seems to be that "strcasecmp" is redefined to be "_stricmp" on this platform.
My fix was to add an "#undef strcasecmp" in QUtil.hh and to move the #include <qpdf/QUtil.hh> to be the last inclusion in QUtil.cc (so as to be necessarily after the #include that redefines "strcasecmp" as a macro).

**Comment by jberkenbilt** [comment]
I will undefine strcasecmp if defined in both QUtil.hh and QUtil.cc. Thanks for the report. In retrospect, I should have called it something else, but it's in the public API, so we're stuck with it.

**Comment by jberkenbilt** [comment]
Sorry I didn't get to this for 8.3.0. I need to decide how I actually want to handle it. I have a strict policy that every source file includes its own header file first. This ensures that every header file is included first in at least one place. I think the best bet here is probably actually to just change the name of the function next time I have to break binary compatibility and just put something really loud in the release notes about having to migrate. It's not like QUtil::strcasecmp is a meaningful part of the QPDF API, and it's actually not used anywhere in the library. Any change I make to the definition of strcasecmp in QUtil.hh has the potential to break code that includes QUtil.hh and also uses strcasecmp, so doing that is actually also potentially breaking compatibility. Sorry to make you have to patch in the interim.

**Comment by jbnivoit** [comment]
no worries, I will keep a local patch until I get a proper fix by pulling from master when it's available.
Do what you must, no need to rush this change. Thanks for the good work!

**Comment by jberkenbilt** [comment]
Thanks. I'm going to remove the "next" label from this. I have it on my "Next ABI" change list in the TODO file, so it will not be forgotten.

**Comment by jberkenbilt** [comment]
This is coming soon. Current master is radically different from 8.4.2 -- almost every file has been touched.
