### ISSUE TITLE
Syntax to collate odd and even pages?

### ISSUE THREAD

**Issue by sbraz** [qpdf/qpdf#259]
Hi,
My scanner can only do one side at once so I need to collate odd and even pages. I know that [pdftk can do this](https://www.pdflabs.com/blog/how-to-collate-even-odd-scanned-pages/), is there any way to achieve the same thing with qpdf?

**Comment by jberkenbilt** [comment]
qpdf can definitely do this, but you'd have to construct the page ranges manually. Having a shortcut for even and odd pages is a good idea. I'll give this some thought and see if I can come up with a good command-line syntax for it.

**Comment by sbraz** [comment]
Maybe the title is misleading, I don't need to extract odd and even pages from a document but I need to merge two documents, one which contains odd pages and one which contains even pages.
From pdftk's man page:
>  shuffle [ < page ranges > ]
Collates pages from input PDFs to create a new PDF. Works like the cat operation except that it takes one page at a time from each page range to assemble the output PDF. If one range runs out of pages, it continues with the remaining ranges. Ranges can use all of the features described above for cat, like reverse page ranges, multiple ranges from a single PDF, and page rotation. This feature was designed to help collate PDF pages after scanning paper documents.

**Comment by jberkenbilt** [comment]
No, I understood. You can do something like `qpdf a.pdf --pages a.pdf 1 b.pdf 1 a.pdf 2 b.pdf 2 a.pdf 3 b.pdf 3 ... -- out.pdf`, which would do the shuffle, but you'd have to script generating the command. Adding something to interleve would be a useful enhancement to the CLI but would not requirement a change to the underlying library code. I think it's a good idea and a useful enhancement.

**Comment by jberkenbilt** [comment]
Maybe something like `qpdf --shuffle file1.pdf file2.pdf file3.pdf -- out.pdf` would be useful. I'll have to think about what the syntax should be to reverse pages...it could be to interleve pagespecs for something like `qpdf --shuffle file1.pdf file2.pdf z-1 -- out.pdf`. This would let you do things like shuffle sets of pages, as in `qpdf --shuffle file1.pdf 5-15 file2.pdf 15-5 -- out.pdf` to shuffle only pages 5-15 of the to files to create a single 22-page document.

**Comment by Elektropepi** [comment]
I too would love this feature. My scanner currently scans the odd pages 1-z and the even pages z-1. I used `pdftk A="$1" B="$2" shuffle A Bend-1 output "$3"` for that and for qpdf I wrote a small function to achieve the same:

```bash
function pdfscanmerge() {
	if [ $# -ne 3 ]; then 
		echo "Usage: pdfscanmerge <odd> <even> <output>";
		return;
	fi
	let odd_pages=$(qpdf --show-npages $1)
	let even_page=$(qpdf --show-npages $2)
	argument=
	for (( odd_page=1; odd_page<=$odd_pages; odd_page++ ))
	do 
		argument+="$1 $odd_page "
		if [ even_page > 0 ]; then
			argument+="$2 $even_page "
		fi
		let even_page--
	done
	qpdf --empty --pages $argument -- $3
}
```

**Comment by Elektropepi** [comment]
The hard task of this would be to think of a useful shuffle-use case besides collating scanned pages. The number of pages to collate will always match during scanning. Maybe finding different uses would show what behavior would be the best. 

My personal preference would be to simply ignore missing pages. This also seems to be the case for shuffle with pdftk after some tests. I can't think of a case where adding blank pages would be useful.

**Comment by jberkenbilt** [comment]
What I've decided to do is to add a `--collate` option, which will just change the semantics of `--pages` to collate rather than concatenate. So you'll be able to run `qpdf odd.pdf --collate --pages odd.pdf even.pdf -- all.pdf` or `qpdf --empty --collate --pages odd.pdf even.pdf z-1 -- all.pdf` or any other thing. Interallly, qpdf will just treat this as if you had actually spelled out the pages the way the script does. This way we will get all the merging and splitting enhancements I've been working on such as page number preservation. I'm going to try to finish this today so I can get it into 8.3.0. We'll see.

**Comment by yigitsever** [comment]
> The hard task of this would be to think of a useful shuffle-use case besides collating scanned pages. The number of pages to collate will always match during scanning. Maybe finding different uses would show what behavior would be the best.

I've stumbled upon this thread while I was trying to port the Möbius double-sided printing method described [here](https://byorgey.wordpress.com/how-to-print-things/) from pdftk to qpdf;

```
PDF=$1
OUTPUT="${PDF:r}_spliff.pdf"
N=`qpdf --show-npages $1`
qpdf --collate --empty --pages $1 1-$(((N+1)/2)) $1 $(((N+1)/2 + 1))-$N -- $OUTPUT

```

this discussion comes up on the search results so I'll leave this here, sorry for creating noise on an old thread.
