### ISSUE TITLE
Wrong MSVC 32bit libraries

### ISSUE THREAD

**Issue by JtheWall** [qpdf/qpdf#260]
In the msvc32 packages are included libraries msvcp140.dll and vcruntime140.dll in 64 bit version (x64) instead of 32 bit (x86).

**Comment by JtheWall** [comment]
versions 8.1.0 and 8.2.1.

**Comment by jberkenbilt** [comment]
Thanks for the report. I will look into it and ensure that this is fixed before whatever I released next. This is timely as I am in the process of automating the whole release process and taking a top-to-bottom look at all this stuff.

**Comment by jberkenbilt** [comment]
The msvc32 package for qpdf 8.3.0, released last night, contains the correct libraries, and I believe I have addressed this issue in the installer creation process. Thanks for the report. Please feel free to re-open if the problem does not seem to be resolved.
