### ISSUE TITLE
QPDF from VBA

### ISSUE THREAD

**Issue by fermark2** [qpdf/qpdf#264]
Hi everyone. I would like to make a button inside a Form in Microsoft Access 2016 x64, with some code similar to this, so whenever it's clicked, the restrictions of a PDF file will be removed.
```
Public Sub Button1_Click()
Dim CommandName as String, SourceFileName as String, DestinationFileName as String
    'Now call a sub or function defined accordingly to the QPDF library...
    QPDF_Sub CommandName, SourceFileName, DestinationFileName
End Sub
```
If we had to do this by the Command Prompt, we should type: **`QPDF --decrypt File1.pdf File2.pdf`**

But I need to execute the same function with the 3 variables (the command name <decrypt>, the name of the source file and the name of the destination file) from VBA when I click a button.
Since I'm not a programmer, I would really appreciate if anybody could tell me how to do it.
1) I downloaded the file `qpdf-8.2.1-bin-msvc64.zip`, but I am not sure if it is the appropriate one.
2) I tried to find a way to declare a Sub or Function, but 2 main doubts araised:
  2.a) I don't know the name of the library I should invoque (the file name that should be written when declaring a Sub or Function calling a Dll)
  2.b) I don't know the name an data type of the variables (string, integer, double, etc)

As you can see I know nothing about this, so if anyone could give me a hand I would be really grateful.

**Comment by fermark2** [comment]
Hi everyone, I finally find the way to achieve my goal. I couldn't do this by invoquing the dll from VBA, but at least it could be done with the Shell Command. I paste some example code now and then comment about a few things that should be considered too.
```
Private Sub Command0_Click()
Dim QPDF_Path As String, file1 As String, file2 As String
  QPDF_Path = "C:\QPDFTEST\qpdf.exe"
  file1 = "C:\QPDFTEST\01.pdf"
  file2 = "C:\QPDFTEST\02.pdf"

  Shell (QPDF_Path & " --decrypt " & file1 & " " & file2)
End Sub
```

In the above code, consider that:
1) At least for this example in which we want to decrypt a file, the folder named in this example as "QPDFTEST" only needs two files inside. These files are `qpdf.exe` and `qpdf21.dll`
2) I guess that there is a string length restriction for the file1 / file2 strings, so I advise you to make the path to file1 and file2 as short as possible.
3) Files (file1 and file2) don't need to be in the same folder where the .exe and .dll files are located. So you could have a folder for the .exe and .dll files and another folder for the pdf files pre and/or post decrypted.

If you are executing this code anytime you press a button, this will work just like I wrote above. But if you use this code, for example, to decrypt a certain number of files in one step, you may need to insert a certain sleep time between two consecutive calls to the Shell Function. I tried it and in my case with 150 milliseconds it worked fine. To insert this sleep time, you could invoque `kernel32.dll` as follows:

`Public Declare PtrSafe Sub Sleep Lib "kernel32" (ByVal dwMilliseconds As Long)`

PtrSafe word in the line above is a way to make the library usable by 64bits programs. If you don't have 64bits program, just exclude the word "PtrSafe"
After invoquing the `kernel32.dll`, you just need to call for a sleep time whenever you want, for example like this:
`Sleep(150) ' This will make a pause of 150 milliseconds`

I know this solution is not the most appropriate because it would be better calling the qpdf dll than executing the `qpdf.exe` file through SHELL command, but I didn't find out how to do it. So if anyone reading this issue knows how to do it, I invite them to explain us in a new comment.
I hope this helps you.
Greetings.

**Comment by jberkenbilt** [comment]
@fermark2 Thanks for creating the issue. I know you settled on accessing qpdf from the CLI, which is similar to what others I've talked to do with PHP and nodejs. I'm working on some enhancements that will greatly increase what you can do with the PDF file from the CLI. However I think for your current needs, accessing qpdf through the CLI is probably fine.

**Comment by jberkenbilt** [comment]
I'm going to go ahead and close this based on our offline discussions. qpdf 8.3.0 has a json mode which could be helfpul to others trying to work with qpdf through the CLI.
