### ISSUE TITLE
Decryption of PDF filename prefix "@" crashes `qpdf`

### ISSUE THREAD

**Issue by evandrix** [qpdf/qpdf#265]
e.g.
```
$ qpdf --decrypt --password="password" @document.pdf
libc++abi.dylib: terminating with uncaught exception of type QPDFSystemError: open document.pdf: No such file or directory
[1]    16337 abort qpdf --decrypt --password="password" @document.pdf
```

- i did try to escape it, e.g. `qpdf --decrypt --password="password" \@document.pdf` or `qpdf --decrypt --password="password" "\@document.pdf"`, but both still fail with the same error
- decryption works fine without errors after renaming "@document.pdf" to "document.pdf"

i'm on Mac OSX 10.12.6, using Homebrew's `qpdf` @ /usr/local/Cellar/qpdf/8.2.1/bin/qpdf

**Comment by jberkenbilt** [comment]
qpdf treats `@` at the beginning of a file name to indicate that that file should be read for a list of command-line arguments. It is incorrect for it to crash in this way, so I will fix that. If you want to access a file whose name actually starts with `@`, I suggest using `./@document.pdf`. I could potentially add a feature where if you say `@file` and `file` does not exist but `@file` does, qpdf does not treat it as a command-line argument file and just treats it as a normal parameter, but that might be a little hacky.

**Comment by evandrix** [comment]
yay, ok! will do

**Comment by jberkenbilt** [comment]
@evandrix Thanks! I'm going to go ahead and reopen this as a reminder that I should fix the error message at least. :-)

**Comment by jberkenbilt** [comment]
I have fixed this so it won't crash. The fix will be in the next version, which I expect to release soon.
