### ISSUE TITLE
How to rotate all page(s)?

### ISSUE THREAD

**Issue by colourful-land** [qpdf/qpdf#274]
I've got a file downloaded from https://docs.wixstatic.com/ugd/768d53_5e42ed90dbe3477aa35c0241210d348f.pdf

I wish to rotate the 2-page document:

    $ qpdf 768d53_5e42ed90dbe3477aa35c0241210d348f.pdf --rotate=-90 output.pdf
    qpdf: invalid parameter to rotate: -90

So I check the number of pages:

    $ pdfinfo 768d53_5e42ed90dbe3477aa35c0241210d348f.pdf  | grep Pages
    Pages:          2

Then I do the rotate:

    $ qpdf 768d53_5e42ed90dbe3477aa35c0241210d348f.pdf --rotate=-90:1,2 output.pdf

My wish is qpdf be forgiving and allow me to success the first time.

Thank you!

**Comment by jberkenbilt** [comment]
There is nothing wrong with your command. When I run the commands you provided on the file you provided, it works. Is it possible that you might not have the most up-to-date version? I tested with 8.3.0 and 8.2.1. I think prior to 8.1.0, the page range was required, but starting with 8.1.0, it was optional. Maybe you have an older qpdf in your path.

**Comment by jberkenbilt** [comment]
If you're stuck with an old version, you can always use --rotate=90:1-z to explicitly mean all pages.

**Comment by jberkenbilt** [comment]
I'm going to close this, but please re-open if you continue to have a problem with it. Thanks!

**Comment by colourful-land** [comment]
Okay, you are right. Me bad. I am using 8.0.2. Too bad Ubuntu only ship up to 8.0.2...

Thank you very much!

**Comment by jberkenbilt** [comment]
I've toyed with the idea of making a PPA for qpdf. Maybe sometime.
