### ISSUE TITLE
Output from --split-pages content not as the original file content

### ISSUE THREAD

**Issue by mcuguy** [qpdf/qpdf#279]
Hi @jberkenbilt 
I'm trying to use qpdf to split pdf files into single pages.
It seems to work, in the sense that the original file is splitted in one file per page, but the content of single pages is not like the original one.
If you e.g. take this example file https://bitcoin.org/bitcoin.pdf and run the following

`qpdf --split-pages bitcoin.pdf output.pdf`

you will notice that the texts inside the drawings are completely missed.
Also in the last page there are missed texts (the ones in italic)
I've noticed this behavior also in other example files (e.g. it removes completely the text in bold), so seems a more generalized bug and not only for this specific file.

Same issue if I use the --pages option:

`qpdf bitcoin.pdf --pages bitcoin.pdf z -- output_z.pdf`

or even doing a full copy of the document:

`qpdf bitcoin.pdf --pages bitcoin.pdf 1-z -- output_1-z.pdf`

But, if I simply do a rotation of the page

`qpdf --rotate=+180 bitcoin.pdf output_rotated_180.pdf`

it works fine, but if I split this file again

`qpdf --split-pages output_rotated_180.pdf output_rotated_180_split.pdf`

I have the same text-removal problems.
Using also intermediate steps like --linearize or -qdf to try to "rearrange" a little bit the original file leads to the same error.
I've tried the output file in both Linux and Windows with the same results.
This bug unfortunately prevents me to use your program because I constantly miss parts of the original text without any warnings, so just a manual check can let me see the problem.
As I said, this bug affects also other files. So probably fixing it for this example file, it will fix for the others too (If you want, I can give you feedback on bug resolution on that later using my personal files that unfortunately I cannot share).

Thank You for any help!

**Comment by mcuguy** [comment]
Seems that by adding the option `--preserve-unreferenced-resources` gives a correct result.
Do you have any explanation that can be useful to understand why QPDF cannot detect the issue and fix it automatically?
Should I use this option everytime by default or there is any possible side effect for specially crafted documents?
Thanks again!

**Comment by jberkenbilt** [comment]
Yes, it's a known bug that is already fixed on master and will be in 8.4.0, which I hope to get out in the next week or two at most. I have already uploaded a patched version of 8.3.0 to debian, but other distributions that have 8.1 or 8.2 are stuck with this bug, unfortunately. There was a logic error (really more of a typo) in handling one particular way in which resources are shared. Details in #276 if you're interested.

**Comment by mcuguy** [comment]
OK perfect!
Thank a lot for the fast answer. I will upgrade as soon as 8.4.0 is available.

**Comment by jberkenbilt** [comment]
@mcuguy Thanks for the report! If you'd like to test the next version to see whether it works for your cases, you can download the latest CI build [here](https://dev.azure.com/qpdf/f24ef40e-3b5d-43d6-ac5d-40e46e203e50/_apis/build/builds/144/artifacts?artifactName=distribution&api-version=5.1-preview.5&%24format=zip). This zip file contains all the binary distributions that would be uploaded if I were doing an official release. It is basically 8.4.0 minus a few minor enhancements I'm still working on. If you decide to test with this, please let me know how it goes. It would be nice to get confirmation that you are in fact experiencing this known issue.

**Comment by mcuguy** [comment]
@jberkenbilt 
Just downloaded and compiled from the source on Ubuntu and it works perfectly fine with both the bitcoin.pdf file and with one of my files. So the bug seems to be fixed! :-)

Just a note on the docs, seems that there is a copy-paste error.
`--preserve-unreferenced-resources    Starting with qpdf 8.1 [...]`
`See also --preserve-unreferenced-resources, which does something completely different. `

I guess that the last line should be `See also --preserve-unreferenced, which does...`

**Comment by jberkenbilt** [comment]
Yes, you're right. I just now fixed it. Thanks! Nice to know that someone is reading the docs. :-)

**Comment by jberkenbilt** [comment]
And thanks for following up.
