### ISSUE TITLE
Not able to optimize images

### ISSUE THREAD

**Issue by msmani** [qpdf/qpdf#280]
When I try to linearize pdf with optimize images option then almost always I am getting the following two messages.

not optimizing because image dictionary is missing required keys
not optimizing because unable to decode data or data already uses DCT

**Comment by jberkenbilt** [comment]
The second message is normal -- it basically means that the image is already optimized. The first option would be normal under some conditions as well, but it's also possible that I made some mistake. If you have a file you could share that produces the first message, I'll take a look at and make sure. I'm going to be releasing 8.4.0 soon, so if there's a bug, now would be a great time to get it fixed.

**Comment by jberkenbilt** [comment]
This is very helpful. I think I see the problem. It should be fixable.

**Comment by jberkenbilt** [comment]
I think the fix is just going to be to improve the error message. The issue here is that the images are using ICC-based color spaces. It's out of scope for qpdf to be able to convert these JPEG. I can fix the message to say that the image contains a colorspace qpdf doesn't know how to convert.
