### ISSUE TITLE
Cannot decrypt password protected document

### ISSUE THREAD

**Issue by atanasj** [qpdf/qpdf#282]
Hi, 

I'm not sure if this is within the functional scope of `qpdf`, however when I try to decrypt a password protected `.pdf` I get the following error: 

```
| => qpdf --decrypt --password=xxxx enr_enc.pdf enr_enc2.pdf
enr_enc.pdf: invalid password
```

I have tested this with the correct password, and it works as expected. 

My assumption is that `qpdf` could crack the password protection on a `.pdf` where the password was unknown If this is not the case, apologies and please feel free to close the issue. 

Other relevant details: 

```
qpdf version 8.3.0

ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54 
``` 

If it is an issue, please let me know if you require more info. 

Cheers,
Atanas.

**Comment by jberkenbilt** [comment]
Hello. qpdf does require you to provide the correct password when you open a file. It does not crack passwords. You could potentially use qpdf to do a brute force attack on a password or on the file's underlying encryption key, but it will not do this automatically. Closing the issue per your request, but let me know if you have additional questions.

**Comment by atanasj** [comment]
Thanks for that. Is there documentation about How I could use `qpdf` for a brute force attack somewhere?

**Comment by jberkenbilt** [comment]
@atanasj Someone blogged about it here: https://blog.didierstevens.com/2017/12/28/cracking-encrypted-pdfs-part-3/

**Comment by jberkenbilt** [comment]
@atanasj Also note that the blog requires patching qpdf, but current qpdf has the `--password-is-hex-key` option that you can use his technique with without rebuilding qpdf.
