### ISSUE TITLE
Question: parse hyperlinks from pdf

### ISSUE THREAD

**Issue by jeroen** [qpdf/qpdf#284]
I need to write a small application that checks pdf files for dead hyperlinks. Is it possible to use qpdf to extract hyperlinks from a pdf file? 

I was able to compile the [parse-content.cc](https://github.com/qpdf/qpdf/blob/master/examples/pdf-parse-content.cc) example but it is not clear to me if it is possible to check for hyperlinks in the `QPDFObjectHandle` types.

**Comment by jberkenbilt** [comment]
I apologize for overlooking this for the past almost 5 years. Hyperlinks are stored in annotations, so the way you would do this would be to start at the page object and iterate through the annotations to find annotations of type /Link. Parsing those would enable you to extract the URI. Given the age of this issue, I am going to close it, but if still have a problem here, feel free to reopen or create a new issue.
