### ISSUE TITLE
AppImage `qpdf --completion-bash` outputs a temporary path

### ISSUE THREAD

**Issue by krrk** [qpdf/qpdf#285]
I'm not sure if this is fixable, but the output from `--completion-bash` is not directly useful for the appimage. Each time it is called it outputs a different temporary path like:

`complete -o bashdefault -o default -o nospace -C /tmp/.mount_qpdf.avVGEsK/usr/bin/qpdf qpdf`

I used `sed` to change the command in my bashrc, but perhaps if possible I think the appimage could detect the name under which the command was called and use that for the command. Here is the sed fix:

`eval "$(qpdf.ai --completion-bash | sed -e 's%/.*/usr/bin/qpdf qpdf%qpdf.ai qpdf.ai%')"`

**Comment by jberkenbilt** [comment]
Next time I work on qpdf, I will investigate. Since I have control over the entrypoint within the appimage, I can almost certainly make this work one way or another. Thanks for raising this issue.
