### ISSUE TITLE
Windows unable to acquire crypt context with new keyset

### ISSUE THREAD

**Issue by zdenop** [qpdf/qpdf#286]
I am not sure if this is variant of bug reported in #163, but when I tried to remove password on Windows with user log in domain I got error:
```
qpdf.exe --decrypt --password=TOP_SECRET --progress 09868_01.12.2018.pdf out.pdf
unable to acquire crypt context with new keyset
```
When I run the same comand on the same computer under local user it works.

I use the latest [qpdf (8.40)](https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.4.0/qpdf-8.4.0-bin-msvc64.zip).

**Comment by zdenop** [comment]
qpdf-8.4.0-bin-mingw64.zip produces same error message under domain user.

**Comment by jberkenbilt** [comment]
I don't have any way to diagnose or test this as I don't have access to any Windows systems that are part of a domain. Maybe someone who is familiar with how this code works can provide some assistance.

**Comment by zdenop** [comment]
Can you please implement better error message/exception handling e.g. something like this:

```diff
diff --git a/libqpdf/SecureRandomDataProvider.cc b/libqpdf/SecureRandomDataProvider.cc
index fe9f1d4..ba99d64 100644
--- a/libqpdf/SecureRandomDataProvider.cc
+++ b/libqpdf/SecureRandomDataProvider.cc
@@ -66,6 +66,17 @@ class WindowsCryptProvider
                                          PROV_RSA_FULL,
                                          CRYPT_NEWKEYSET))
                 {
+                    DWORD errorMessageID = ::GetLastError();
+                    LPSTR messageBuffer = nullptr;
+                    size_t size = FormatMessageA(
+                                  FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM |
+                                  FORMAT_MESSAGE_IGNORE_INSERTS, NULL, errorMessageID,
+                                  MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
+                                  (LPSTR)&messageBuffer, 0, NULL);
+                    std::string message(messageBuffer, size);
+                    LocalFree(messageBuffer);
+                    fprintf(stderr, "Error number %lx: %s", errorMessageID,  message.c_str());
+
                     throw std::runtime_error(
                         "unable to acquire crypt context with new keyset");
                 }
```

which now provided useful explanation of problem:

```
>qpdf.exe --decrypt --password=TOP_SECRET --progress 09868_01.12.2018.pdf out.pdf
Error number 80090345: The requested operation cannot be completed. The computer must be trusted for delegation and the current user account must be configured to allow delegation.
unable to acquire crypt context with new keyset
```
This will help also with #163 .

**Comment by zdenop** [comment]
And based on error message I [found solution](https://dba.stackexchange.com/questions/178325/the-computer-must-be-trusted-for-delegation-and-the-current-user-account-must):

> I added the following value under:
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Protect\Providers\df9d8cd0-1501-11d1-8c7a-00c04fc297eb
> 
> ProtectionPolicy = 1 (DWORD)
> ```

**Comment by jberkenbilt** [comment]
@zdenop Thanks -- yes, I will take this. This is a helpful change. Can you also suggest some text I might add to README-windows.md?

**Comment by jberkenbilt** [comment]
I will incorporate the error into qpdf's regular error reporting mechanism, but your code snippet shows me how to get the details.

**Comment by zdenop** [comment]
I am not sure if to put something to README-windows.md:  when I get error text (error code does not help me - it was too general for searching on internet) - I found fix (windows policy) quickly.

**Comment by jberkenbilt** [comment]
By the way, I think it's really funny that a Windows-specific issue has number 286.

**Comment by jberkenbilt** [comment]
qpdf 9 will include this change, though I have no way of testing it. When this issue is closed, you will know the change is in master. Feel free to test if you'd like. If you're subscribed to [the qpdf announce list](https://sourceforge.net/projects/qpdf/lists/qpdf-announce), watch for an announcement of an alpha or other prerelease of qpdf 9. There are lots of changes, so I want to give people a chance to test before I do a full 9.0.0 release. Thanks again for the patch.

**Comment by msdousti** [comment]
I ran into this problem when running `qpdf` from a normal command prompt in Windows 10. Using `Run as administrator` to elevate the command prompt solved the issue.
