### ISSUE TITLE
Decrypt to same file produces empty file

### ISSUE THREAD

**Issue by thany** [qpdf/qpdf#29]
When I decrypt a PDF file like so:
`qpdf -decrypt test.pdf test.pdf`
I get this error in the console:
`test.pdf (object 291 0, file position 239): EOF while reading token`
In my case at least. The numbers may differ from document to document. More importantly, the test.pdf is now 0 bytes.

I would expect qpdf to just write the decrypted pdf to the original file. This is preferrable especially when creating a registry-entry for a simple "right-click -> decrypt" command in Windows (or any other OS really).

The workaround is to "invent" a temporary file and optionally overwrite the original file with that, after qpdf has finished. Which is fiddly.

**Comment by SebastianHD** [comment]
It still has the behavior of creating an empty file.

**Comment by vanshg** [comment]
Any way to do pdf decryption in place yet?

**Comment by jberkenbilt** [comment]
This check will finally be included in qpdf 7.0.0.

@vanshg Adding decryption in place is not planned. It can't actually be done without some kind of temporary file tricks because qpdf needs to be able to read the original file throughout the creation of the final file.

**Comment by jberkenbilt** [comment]
Specifically, qpdf 7.0.0 will exit without overwriting the file if you attempt to make the output file the same as the input file. I'm not planning on adding the temporary file stuff to qpdf, but this should be much safer than what is there now.

**Comment by evandrix** [comment]
`qpdf --decrypt --password="password" document.pdf - | sponge document.pdf`
