### ISSUE TITLE
Some completion tests for quoting don't work on Windows using GIT-shell.

### ISSUE THREAD

**Issue by ams-tschoening** [qpdf/qpdf#291]
I'm not using MSYS2 stand-alone, but the one distributed with the GIT-installer for Windows. That might or might not make a difference regarding this problem, but I would like at least ask others if they see the same behaviour and if not, document my problem to maybe find a solution at some point.

The following tests are failing for me:

    ['qpdf --encrypt \'user " password\' ', undef, 'quoting'],
    ['qpdf --encrypt "user password" ', undef, 'quoting'],
    ['qpdf --encrypt "user pass\'word" ', undef, 'quoting'],

I have no clue yet what the expected results are and how things should work, but the command line built in the end is simply wrong for those tests in my environment:

> "C:/Program Files/Git/usr/bin/sh" C:/Users/TSCHOE~1/AppData/Local/Temp/testtemp.7228/tmpscript env COMP_LINE=qpdf --encrypt 'user " password'  COMP_POINT=33 qpdf qpdf "" password'

vs.

> "C:/Program Files/Git/usr/bin/sh" C:/Users/TSCHOE~1/AppData/Local/Temp/testtemp.13160/tmpscript env "COMP_LINE=qpdf --encrypt 'user password' " COMP_POINT=31 qpdf

The difference in all cases is that `COMP_LINE` is not properly quoted if double quotes (`"`) are already present in the string. Not sure who is responsible for the correct quoting, though. The `tmpscript` seem to only contain redirect-setup and afterwards forward the arguments, like in the following example:

    exec >C:/Users/TSCHOE~1/AppData/Local/Temp/testtemp.13160/winrun.tmp
    exec 2>&1
    # diff
    # -a
    # -u
    # C:/Users/TSCHOE~1/AppData/Local/Temp/testtemp.13160/expected
    # C:/Users/TSCHOE~1/AppData/Local/Temp/testtemp.13160/actual
    "$@"

`$@` handles the quotes in theory and I guess that breaks for some of the test commands.

Not sure if it's related, but the used function `bash_completion` seems to not properly handle the commands to test as well. If you look at my failing command line above, there's the following part at the end:

> password'

Including the last character doesn't make sense to me, that can't become a valid command line or argument part anywhere. So I added some debugging statements and how the given command line is splitted doesn't look OK:

	before_point: qpdf --encrypt 'user " password'  at qpdf.test line 3911, <GEN3> line 1.
	before_point: qpdf --encrypt 'user " password'  at qpdf.test line 3913, <GEN3> line 1.
	first: qpdf --encrypt 'user " password'; sep:  ; cur:  at qpdf.test line 3915, <GEN3> line 1.
	prev: qpdf --encrypt 'user " password' at qpdf.test line 3917, <GEN3> line 1.
	prev: password' at qpdf.test line 3919, <GEN3> line 1.
	this: qpdf --encrypt 'user " password' at qpdf.test line 3921, <GEN3> line 1.
	$VAR1 = 'env';
	$VAR2 = 'COMP_LINE=qpdf --encrypt \'user " password\' ';
	$VAR3 = 'COMP_POINT=33';
	$VAR4 = 'qpdf';
	$VAR5 = 'qpdf';
	$VAR6 = '';
	$VAR7 = 'password\'';

The problem is with `$prev`:

    my $prev = ($sep eq '=' ? $sep : $first);
    $prev =~ s/.* (\S+)$/$1/;

`$sep` is a  space, so `$prev` gets the whole command line, which includes spaces again, so that `$prev` gets everything at the end which doesn't contain anymore spaces. This includes the single quote character, which was originally used to quote arguments in the command line. So the function breaks a single argument into multiple ones etc.

But my problem happens with `zsh_completion` as well, which doesn't do such things. So I guess it's two separate issues.

So, do all those completion tests pass for others under Windows? If so, under which environment exactly please? Thanks!

**Comment by jberkenbilt** [comment]
Sorry for not replying for ages. The tests listed above are gone now since qpdf 11.7.0 added some additional syntax for encrypted files. I'm not planning on prioritizing any fixes related to completion with Windows shells.
