### ISSUE TITLE
Usage of qpdf in windows task scheduler causes problems

### ISSUE THREAD

**Issue by benni-dev** [qpdf/qpdf#303]
Hello,
I decided to use qpdf in order to merge several .pdf files on a windows server directory to one single file (that will be later send via e-mail from the server).
The command is executed out of a vbscript using wshshell.run command. The pages command works fine when I start it from the console. However, when I run the script in a scheduled task the same qpdf command does not seem to work any longer. 
Is there a recommendation how to execute qpdf.exe using a script language for Windows. Would powershell handle it better 'in the background'. 

Thanks in advance, appreciate this great program!
Benni

**Comment by bitraid** [comment]
What do you mean by "does not seem to work"? What is the output of the command (you can redirect it to a file and check it  - you should start the `vbs` with a `cmd`) ? Is the task running as the correct user with the right privileges?

**Comment by benni-dev** [comment]
As I wrote, the script works fine and does the job from the console. File operations like copy from a source folder work fine in the script. So I believe it should not be privileges. I am not quite sure how to redirect the output to a file.
So in general qpdf command should work together with Windows task scheduler?

**Comment by bitraid** [comment]
Try starting the script with a `cmd` containing: `cscript.exe "path_to_vbscript" > "path_to_log_file"`  and then check the generated file.

**Comment by benni-dev** [comment]
Ok, thanks for the hint - I will come back once I am logged onto my windows server.

**Comment by benni-dev** [comment]
I could finally schedule a task using powershell.
Attached, I document how I created the task using command 'start-process'.
The .ps1 script contains this test command. 
start-process -filepath "D:\PDF_email\qpdf.exe" -ArgumentList "D:\PDF_email\1.pdf --pages D:\PDF_email\1.pdf D:\PDF_email\2.pdf -- D:\PDF_email\zieldatei1.pdf"

So I recommend to not use cmd.exe but rather statt powershell.

**Comment by benni-dev** [comment]
<img width="352" alt="task_scheduler1" src="https://user-images.githubusercontent.com/44068221/53962104-82a6b880-40ea-11e9-9ede-7849d09c4973.PNG">
<img width="486" alt="task_scheduler2" src="https://user-images.githubusercontent.com/44068221/53962115-876b6c80-40ea-11e9-9294-4cfdaaebb61c.PNG">
