### ISSUE TITLE
qpdf hangs handling a specific PDF file

### ISSUE THREAD

**Issue by eesheesh** [qpdf/qpdf#305]
To reproduce:
1. Download https://nca2018.globalchange.gov/downloads/NCA4_2018_FullReport.pdf
2. Run `qpdf  --check NCA4_2018_FullReport.pdf` (I'm using qpdf 8.4.0 AppImage).
3. qpdf appears to be stuck after `File is not linearized`. Running under strace shows that something is happening, but there's no output from qpdf itself.

Thanks!

**Comment by jberkenbilt** [comment]
Thanks for reporting, and sorry to take so long to respond.

I will have to study this in more depth. I wonder whether this is similar to #311. The file appears valid, so I'm not sure what's making qpdf have so much trouble with it. The file has 1524 pages and 109,357 objects, but qpdf shouldn't care about that. Something's definitely weird.

**Comment by jberkenbilt** [comment]
Great news -- I've found a fix to the memory problem with this file. The fix will be in 9.0.0. Statistics were similar to the file in #305.
