### ISSUE TITLE
Can qpdf extract raw image data?

### ISSUE THREAD

**Issue by jsxcool** [qpdf/qpdf#306]
I tried "pdf-parse-content.cc". In general, it works well for text data. But when I tried to get data of image, it only gives the coordinate displacement matrix without the raw bits of image. Is there some function to extract them ?

**Comment by jberkenbilt** [comment]
From the library, you can use QPDFObjectHandle::getRawStreamData. From the CLI, you can use `--show-object` with the `--raw-stream-data` or `--filtered-stream-data` flags. You may need `--decode-level=all` if you want to uncompress JPEG image data. The `--help` flag and manual should provide additional information, but feel free to reopen this issue if you have further questions.

**Comment by jsxcool** [comment]
I tested two simple pdf files made by Latex, either containing a png or jpeg picture. (6.pdf is png, pic2.pdf is jpeg)

I tried the command  "qpdf --qdf --compress-streams=n --decode-level=all in.pdf out.pdf".
It did decode the image stream, but gave me unreadable bits. Like 
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ

For "pdf-parse-content.cc", in function "handleObject(QPDFObjectHandle obj)", 
 if (obj.isInlineImage())  {
        std::cout << QUtil::hex_encode(obj.getInlineImageValue()) << std::endl;
  }
else    std::cout << obj.unparse() << std::endl;
This if statement was always false when I debug. So it se
[pdfTestFiles.zip](https://github.com/qpdf/qpdf/files/2954239/pdfTestFiles.zip)
[pdfTestFiles.zip](https://github.com/qpdf/qpdf/files/2954240/pdfTestFiles.zip)

emed skipping all image values.

For my purpose, I want to extract text and image contents from pdf file. So I can encode and compress them as my way. In the example folder, "pdf-invert-images.cc" seems should be into QPDFObjectHandle::getRawStreamData, but it still can't handle the two pdf files. So is there a easy-use API to extract image ? Or For different PDF producers, there exists decoding problem ?
