### ISSUE TITLE
`qpdf --pages .` errors out

### ISSUE THREAD

**Issue by mxxk** [qpdf/qpdf#307]
When using the `--pages .` syntax "as a shortcut for the primary input file" <sup>[1]</sup>, QPDF exits with status code 2:

```
$ qpdf input.pdf --pages . 1 -- output.pdf
.: read 1024 bytes
$ echo $?
2
```

This is odd, since in the above example `--pages .` is expected to be the same as `--pages input.pdf`, which works as intended:

```
$ qpdf input.pdf --pages . 1 -- output.pdf
```

This issue affects QPDF 8.3.0 on Alpine Linux in Docker.

# Steps to Reproduce

1. Pull Alpine Linux image (the image digest below corresponds to `alpine:latest` at the time of this writing):

    ```
    $ docker pull alpine@sha256:644fcb1a676b5165371437feaa922943aaf7afcfa8bfee4472f6860aad1ef2a0
    ```

2. Download provided PDF file [input.pdf](https://github.com/qpdf/qpdf/files/2945328/input.pdf) to current directory.

3. Run image with volume mount (to make PDF file available to container).

    ```
    $ docker run -v "$PWD:/mnt" alpine@sha256:644fcb1a676b5165371437feaa922943aaf7afcfa8bfee4472f6860aad1ef2a0 sh
    ```

4. Install QPDF via `apk` (latest version is 8.3.0-r0 at the time of this writing):

    ```
    # cd /mnt
    # apk add --no-cache qpdf=8.3.0-r0
    ```

5. Attempt to extract page 1:

    ```
    # qpdf input.pdf --pages . 1 -- output.pdf
    .: read 1024 bytes
    ```

# References

1. > In the `--pages` option, allow use of “.” as a shortcut for the primary input file. That way, you can do **`qpdf in.pdf --pages . 1-2 -- out.pdf`** instead of having to repeat in.pdf in the command. 
    >
    > See: http://qpdf.sourceforge.net/files/qpdf-manual.html

**Comment by jberkenbilt** [comment]
Looks like you have an older version of qpdf. The `.` enhancement was very recent, just having been introduced in 8.4. Run `qpdf --version` in your environment and see if you have an older version.

**Comment by jberkenbilt** [comment]
Actually, your very through and well-written bug report explicitly shows that you are using 8.3.0. The `.` feature wasn't there in 8.3.0. I'll close this, but thanks for taking the time to report this.

**Comment by mxxk** [comment]
Oh whoops! 🤦‍♂️ Thanks for the prompt reply @jberkenbilt. 😅
