### ISSUE TITLE
Small decimal values are exported to JSON (via --json) as ".841742" instead of "0.841742"

### ISSUE THREAD

**Issue by bastibense** [qpdf/qpdf#308]
This happens in some files when I try to convert them into JSON by running qpdf with --json.

Here's a snippet from JSON output. Even the syntax highlighting on GitHub shows it as an error.

``` json
"1028 0 R": {
      "/BitsPerComponent": 8,
      "/ColorSpace": [
        "/CalRGB",
        {
          "/Gamma": [
            2.2,
            2.2,
            2.2
          ],
          "/Matrix": [
            .41239,
            .21264,
            .01933,
            .35758,
            .71517,
            .11919,
            .18048,
            .07219,
            .95053
          ],
          "/WhitePoint": [
            .95046,
            1,
            1.08906
          ]
        }
      ],
      "/Filter": "/FlateDecode",
      "/Height": 282,
      "/Intent": "/Perceptual",
      "/Length": 42829,
```

The JSON parsers I tried failed at the point where it finds a "." but no prefixing "0". At least that's my theory as parsers complain about an unexpected token (char ".").

Thanks for looking into this issue! Let me now if you need anything.

**Comment by jberkenbilt** [comment]
Oops, thanks for catching this. This is the downside of using an old language like C++ and writing my own json serializer to keep external dependencies at a minimal! This will be an easy fix. I'll fix it for the next version. I'm hoping to do an 8.4.1 release soon with various minor fixes.

**Comment by bastibense** [comment]
Thanks! Great work, by the way! I'll let you know if everything works as soon as I get an update notification.

**Comment by jberkenbilt** [comment]
Turns out what's happening here is that qpdf is preserving the representation of the decimal value that appeared in the input file. QPDF internally stores reals that it parsed from a file as strings to avoid accumulating floating point error. The double to string conversion is actually right. So basically this is a very small special case in the JSON serialization of QPDFObjectHandles that are reals to just stick a leading 0 in front of the decimal place if the string starts with `.` or `-.`. A trivial fix that doesn't break backward compatibility.

**Comment by jberkenbilt** [comment]
I'll merge this to master once CI is green. Not sure when I'll get the release out. Probably a few weeks. I have to find a chunk of several hours.

**Comment by bastibense** [comment]
Just tested it. Works great now!

``` json
    "/Filter": "/FlateDecode",
      "/Length": 103,
      "/Matrix": [
        0.9838666,
        0.1789039,
        0.1685381,
        -0.9856952,
        0,
        0
      ]
```

Thanks again for the quick fix!
