### ISSUE TITLE
fix-qdf: stdin: not a qdf file

### ISSUE THREAD

**Issue by 2011** [qpdf/qpdf#312]
Hi,

This is all pretty new to me, so I hope I am not missing something obvious (apologies in advance if I am).

Basically, I have:

```
$ /usr/bin/qpdf qpdf --deterministic-id --empty --linearize --pages file.pdf  -- --qdf file.qdf
$ time nice -n 20 /usr/bin/fix-qdf < file.qdf > file_new.qdf
fix-qdf: stdin: not a qdf file
```

So it appears that none of the text objects are being decompressed (file.qdf is full of "/Filter /FlateDecode /Length nnnn" lines).

Played around this this some more, and it seems that the "--linearize" parameter is causing the problem.

```
$ /usr/bin/qpdf qpdf --deterministic-id --empty --pages file.pdf  -- --qdf file.qdf
$ time nice -n 20 /usr/bin/fix-qdf < file.qdf > file_new.qdf
$
```

I guess that leaves me with two questions:

1. Is it supposed to work that way?
2. Should there some warning (assuming I haven't missed it) in the documentation that --linearize is basically incompatible with --qdf?

**Comment by jberkenbilt** [comment]
`--linearize` and `--qdf` are definitely not compatible. They actually have conflicting requirements. I will mark this as a bug to ensure that the documentation is clear. If you specify both qdf mode and linearization, linearization wins. It's probably reasonable to have the qpdf CLI output a warning if both arguments are given. In QPDFWriter.hh, above the declaration of setLinearization, there is a comment that says:
```
    // Create linearized output.  Disables qdf mode, content
    // normalization, and stream prefiltering.
```
but I'll grant you that this is not an obvious place for an end user to find this information!

Thanks for taking the time to report this.
