### ISSUE TITLE
qpdf CLI: incompatible behavior regarding page labels between 8.2.1 and 8.4.0

### ISSUE THREAD

**Issue by femifrak** [qpdf/qpdf#317]
The other day I wanted to install ver. 8.4.0 on my ubuntu 18.04 which has per default an older version of qpdf. I did this as usually by downloading the sources, "configure", "make", "make install" without errors (as far as I remember). Initiating qpdf gave an error (which I don't remember), but the error disappeared after reboot. 
`whereis qpdf` results in /usr/bin/qpdf and /usr/local/bin/qpdf. 

Both,
`/usr/local/bin/qpdf --version`
and
`/usr/bin/qpdf --version`
result in 8.4.0

This wouldn't be serious, however 
`qpdf --empty --pages file1.pdf file2.pdf file3.pdf -- out.pdf `
results in non-continuous page labels. (qpdf is /usr/local/bin/qpdf).
The same command but with /usr/bin/qpdf correctlty results in continuous page labels.

/usr/local/bin/qpdf is from installation date,
/usr/bin/qpdf is one year old.

Is this a bug or did I do something wrong during installation? How can I correct this?

Thanks a lot!

**Comment by jberkenbilt** [comment]
Most likely it's intended behavior. Starting in qpdf 8.3 or 8.4 (Ubuntu 18.04 has 8.2.1), qpdf started preserving page labels from the original files. I guess there may be cases in which this is undesirable. Maybe there should be an option to not do this. Off the top of my head, I can't remember what the behavior is if the labels are not explicit in the files. I'd have to check the code. Please let me know if you'd like further investigation or if you are seeing inconsistent behavior within a single version. I can look at files if you are able to share, or I can send you some commands to generate metadata that you can send (using the new `--json` mode).

**Comment by femifrak** [comment]
Thanks for the offer. I am fine with using the version of /usr/bin.
However, I find it unusual that two versions that are identical in name (8.4.0) behave differently.
Isn't the parameter "--empty" meant (among others) to reassign continuous page labels and not to use the original page numbers of the individual files?

**Comment by jberkenbilt** [comment]
You're raising an important issue. I have been extremely strict about never breaking compatibility for the library, but I have been less strict about the CLI. I have considered qpdf's behavior up to now of losing page numbering information to be a bug and this to be a fix, but you are pointing out that people may be dependent on the old behavior. What this tells me very strongly is that I need to be quite conservative about changing the behavior, and if I do change the behavior, I need to provide a compatibility flag.

I will mark this as a bug and ensure that the next release includes some way to revert to the behavior of not preserving page labels. When Ubuntu 19.04 comes out in a few days, more users will start getting qpdf 8.4.0 by default, and there won't be an old version in /usr/bin, so this may start affecting more people.

**Comment by femifrak** [comment]
I see what you mean. You think that /usr/bin is the old version. But why does `/usr/bin/qpdf --version` result in 8.4.0?

**Comment by jberkenbilt** [comment]
Most likely it's picking up the wrong shared library. If you run ldd /usr/bin/qpdf, it will probably show you that it's finding libqpdf.so.whatever in /usr/local/lib. The value of --version comes from the library, but the behavior of preserving page numbers is implemented in the CLI tool itself. Definitely not intuitive, but that's how it works. I didn't realize you were seeing 8.4.0 with /usr/bin/qpdf --version. I should probably do something about that too.

**Comment by femifrak** [comment]
ah, okay, I see.
Thanks a lot for you help and especially for developing qpdf! This is really helpful. 

Here, if interesting, the output of ldd:
`ldd /usr/bin/qpdf` gives (among other lines)
libqpdf.so.21 => /usr/local/lib/libqpdf.so.21 (0x00007f206eaf6000)
`ldd /usr/local/bin/qpdf` gives (among other lines)
libqpdf.so.21 => /usr/local/lib/libqpdf.so.21 (0x00007ff5d2c76000)

**Comment by jberkenbilt** [comment]
@femifrak Rather than reverting the new behavior of preserving page labels when merging and splitting, I have added a new flag for 8.4.1 called `--remove-page-labels` which you can use to get the old behavior. I have also updated `qpdf --version` to notice if the CLI is using a different library version than expected.
