### ISSUE TITLE
Extracting Bookmarks Discussion

### ISSUE THREAD

**Issue by emcmakin** [qpdf/qpdf#318]
Placeholder for @wmbutler and @emcmakin to discuss extracting bookmarks from split pdfs.

Jay please leave this issue for us while we fine tune.

**Comment by jberkenbilt** [comment]
Will do. Thanks for using an issue for this. Looking forward to it.

**Comment by jberkenbilt** [comment]
Hmm. I know you guys. I'm going to close this now. :-) (Just trying to catch up on old qpdf issues -- this is in scope for my pages work.)
