### ISSUE TITLE
Finally GUI for QPDF but unfortunately not advanced !

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#320]
Hi. Just for your knowledgement, I call GUI PDF software developers to use your QDPF as a backend.

Till now, only one respond positively & replace his backend by QPDF but unfortunately he said that he has no time to build advanced PDF editor ...... Please look to this:
https://github.com/junrrein/pdfslicer/issues/59

I do not know how can you help from your side. But from my side I'm ready to help you by money.

Regarding money support, I was planned to use private e-mail. But when I see that someone respond to me & include your great application in his GUI, I decided to post this publicly because I'm sure that there are many peoples who use Linux are very hunger for advanced PDF editor on Linux.   

Frankly speaking, why you do not introduce GUI for your great application? I'm ready to support you. Just inform us how many you need & how many it will cost you?

Building strong GUI need time, & you have a family & need to eat as any other human. So, I'm - & I think many other peoples - ready to support you .....

**Comment by mschilli87** [comment]
From my point of view there is not really a need for a GUI for QPDF.
I like to render my PDFs with a simple viewer (e.g. `mupdf`) and do all the editing from command line.
This enables me to script my editing so instead of repeatedly performing the same clicks, I can 'tell' QPDF when and where to perform which operation (or my shell when and how to call `qpdf`).

So I'd rather see more developer time invested in further improving this great library and its CLI instead of in creating (and maintaining!) a TUI or GUI for it.

This is just my two cents but I'd be curious to learn about a use case a GUI could satisfy but the CLI could not.

**Comment by Nokia808** [comment]
@mschilli87 
Dear I'm respecting your opinion. But this is NOT CONVENTIONAL. I'm also can use command line. But using command line is not convenient for many wanted operations ...... For example, creation or editing outlines (or bookmarks) for/of PDF.  Also, delete pages are also possible via command line but it associated with somewhat long commands.

To be more clear: we on Fedora Linux we have a sandbox tool called SELinux. It is of huge number of command line. But with GUI of SELinux, user can avoid many headache causes by avoiding entrance of such command directly ......

**Comment by jberkenbilt** [comment]
I think a GUI for qpdf is a good idea, and it is something that gets requested with increasing frequency. I can *support* its creation, but I have no intention of creating one myself. GUI code is not my primary skill area, and I would rather use my very limited time on qpdf for library and CLI functionality enhancements, of which I already have quite a backlog.

What I could do is to work with someone who is writing a GUI to add features that make it easier to support a GUI. The approach I would recommend would be to have the GUI be a wrapper around the CLI and have it expose what the CLI offers. In this case, it would be useful for the CLI to have some options that would be there specifically for communicating with a GUI. For example, as of qpdf 8.3.0, qpdf supports TAB completion with bash and zsh, and this is done by having the exact code that sets up qpdf's command-line parsing also support completion. As such, any time I add any option to qpdf, it is automatically supported by completion. If someone were dynamically constructing a GUI based on available options, it would be possible to add some way for qpdf to provide the information along with additional metadata (categories, layout, etc.) that would make it easier for the GUI to automatically reflect new options to qpdf as it was added. For example, I could imagine some something like `qpdf --gui-data` that would output something like a json stream that would describe a group of options by category with a mapping to the CLI options to support them. A GUI could run this and dynamically construct a GUI based on the output.

It would also be possible for someone to write a GUI that would provide functionality directly by calling the library. This might be a bit more flexible, but it would require a lot more on-going maintenance and would create a tighter coupling between qpdf and its GUI. For these reasons, I prefer the first option. But if someone wanted to do this, I could help out by moving some of the functionality that's purely implemented in the CLI, such as page splitting and merging, into the library and expose it with helper functions.

There is precedent for my doing stuff like this. In particular, qpdf has a C ABI in addition to the C++ ABI to support interoperability with other languages that can call C functions through a DLL or shared library. The C API is much more limited, but it supports lots of basic functionality, and I know it is used by people from languages such as Pascal (Delphi) and Visual Basic. I added this specifically to help out someone who was creating a Delphi wrapper. This was also the motiviation behind the initial Windows port, and I think the Delphi wrapper and Windows support were a big part of what put qpdf on the map. Additionally, qpdf 8.3.0 added support for dumping data about the PDF file to json. I added this feature to assist a user who was interfacing with qpdf on the CLI from nodejs, and that work was sponsored (they paid me for it). I have also made a few changes to support pikepdf, an excellent Python module for qpdf written by someone else that I use myself.

Regarding payment, I am willing to do sponsored qpdf work, and I have done so on two prior occasions, but there are some constraints: 1) All sponsored work must go into the open source version. I am happy for people to use qpdf in their closed-source systems and use the commercial-friendly Apache license, but if I add something to qpdf to support a commercial user, whatever I change in qpdf has to be part of the core qpdf open source product; and 2) I work according to my own priorities and schedule and won't generally be willing to commit to a particular schedule. However, I will do an estimate of the work. Basically sponsorship may enable me to alter priorities and, in some cases, I have taken a few days of leave from work to do qpdf work, which would be much harder to manage without sponsorship. All that said, what I enjoy most is to do enhance qpdf in ways that directly support other open source efforts, such as all the recent work I've done to add features used by the Linux Printing project to support printing files that contain interactive forms, or the many features I've added in response to suggestions from the community.

**Comment by Nokia808** [comment]
@jberkenbilt 

1) regarding your replay "What I could do is to work with someone who is writing a GUI"
Who this one ?? I asked for that but only one accept but just for simple editor not for advanced one.
I asked this:
https://gitlab.com/scarpetta/pdfmixtool/issues/9
& this:
https://github.com/muriloventuroso/pdftricks/issues/28
& this:
https://github.com/linuxmint/xreader/issues/246
& as you see no one interested !

2) regarding your replay "All sponsored work must go into the open source version"
This is exactly what I was to insist on you after you accept this issue. 
From this regard I'm with you 100%. I asked for GUI to be available for all Linux users not just for me.

3) regarding your replay "I work according to my own priorities and schedule and won't generally be willing to commit to a particular schedule"
Certainly I'm with you ! I did not ask any one to be slave for donation !

4) from my side the only conditions that I ask before donations are just 2:
- sponsored work will be available as a free open source project available for every one,
- project aim & road map must in direction to include ALL command line features & powers of QPDF to ensure that it will be real advanced PDF editor,
- be available as AppImage/flatpak (one of them or both of them) so as to ensure that every one can utilize the new GUI project.

5) regarding money: it is available to me the following options:
- pre-paid master cards,
- master card (bank account),
- I'm able to buy Bitcoin then send them to you for your wallet address,
- or (I do not recommend it) real money transfer from Iraq to your Bank account or an exchanger account to receive it.

PayPal not allowed to be used for residents in Iraq, so it is useless ......

6) no one better than you can make GUI. However, if you recommend someone this is different story. You must, in later case, recommend exactly WHO will make GUI so as to be able to trust him.

7) can you inform me in approximate way about how it will cost to see how much can I cover ?

**Comment by jberkenbilt** [comment]
I just don't have time or inclination to do it, so there's really no point in discussing the "how" at this point. I appreciate your willingness and enthusiasm. If circumstances change and this becomes something I would consider, I will let you know. But right now, I get just a week or two in a year to work on qpdf, and there many things I want to do more than writing a GUI.

**Comment by SumatraPeter** [comment]
@Nokia808: Was just browsing through open Qpdf issues and came across this. If you're really willing to put money behind this I wonder if it might be worth your while to take a look at sites such as Toptal, UpWork, DonationCoder, Rent-a-Coder etc.?

**Comment by jberkenbilt** [comment]
I'm going to close this issue for inactivity. I have no intention of ever working on a gui for qpdf, but I think that the QPDFJob work (added since this was created) could be of help to anyone who did want to write a qpdf gui.
