### ISSUE TITLE
Detect jpeg build flags

### ISSUE THREAD

**Issue by paulmenzel** [qpdf/qpdf#324]
Currently, `-ljpeg` is hard coded in the configure script.

https://github.com/qpdf/qpdf/blob/7db5bc289bdb80a33af0468e5b37147d0ff9b0c1/configure.ac#L600

The flags should be detected from [libjpeg’s pkg-config file](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/release/libjpeg.pc.in).

**Comment by jberkenbilt** [comment]
Good point. However, pkg-config is not always available on all the platforms on which qpdf builds. I will update configure.ac to use pkg-config when available and to fall back to -ljpeg when not. Thanks for bringing this to my attention.
