### ISSUE TITLE
Ignore build user umask

### ISSUE THREAD

**Issue by paulmenzel** [qpdf/qpdf#326]
The pkg-config file `/usr/local/lib/pkgconfig/libqpdf.pc` seems to be installed with the umask of the build user.

    $ umask
    0007
    $ wget --quiet https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.4.0/qpdf-8.4.0.tar.gz
    $ tar xf qpdf-8.4.0.tar.gz
    $ cd qpdf-8.4.0/
    $ ./configure --disable-check-autofiles --disable-static
    $ make
    $ sudo make install
    $ ls -l /usr/local/lib/pkgconfig/libqpdf.pc
    -rw-r----- 1 root root 246 Apr 25 16:49 /usr/local/lib/pkgconfig/libqpdf.pc

I have to check if there is a standard for that, but wanted to report it.

**Comment by paulmenzel** [comment]
Hmm, the [issue for GNU Automake](https://lists.gnu.org/archive/html/automake/2019-01/msg00000.html) says that files are supposed to be installed with `install -m 755` and that the problem only exists for directories. So this issue seems different.

For the record:

```
$ automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

**Comment by jberkenbilt** [comment]
This is probably because my make install target just uses cp instead of, say, install. I don't use automake at all in qpdf. I can probably fix the installation to use install if available.
