### ISSUE TITLE
Page selection for multiple input files is ignored

### ISSUE THREAD

**Issue by Nutznieser** [qpdf/qpdf#327]
I execute the following command:

```
qpdf --empty --pages *.pdf 2-z -- out.pdf
```
And I expected to get an output file that contained the pages 2-z from each input file.

But what I got is ALL pages from all input files. Only from the last input file the first page is omitted but not for all. 

Is this the right behavior? What am I doing wrong?

**Comment by jberkenbilt** [comment]
Hi. The shell expands wildcards, not qpdf, so basically 2-z is only applying to the last file. Suppose you have 1.pdf through 4.pdf in your directory. When you type this, what qpdf actually sees is
```
qpdf --empty --pages 1.pdf 2.pdf 3.pdf 4.pdf 2-z -- out.pdf
```
which will include all pages of 1.pdf through 3.pdf and all but the first of 4.pdf. In bash, you could do something like this
```
qpdf --empty --pages $(for i in *.pdf; do echo $i 2-z; done) -- out.pdf
```
to get the effect you're looking for. If you're in Windows, you'll probably have to script it.

I'm going to close this issue, but feel free to ask additional questions if any. Thanks!

**Comment by Nutznieser** [comment]
Ok, I understand. Thanks for your information!
