### ISSUE TITLE
QPDF produces wrong PDF

### ISSUE THREAD

**Issue by sz5000** [qpdf/qpdf#329]
Hello, I've got a special PDF file that QPDF 8.4.1 can not process. The produced PDF is empty. The PDF can be opened with the Adbe reader or with the PDF24 Reader or with Ghostscript, but  QPDF fails here. The PDF is attached.

[qpdf_error.pdf](https://github.com/qpdf/qpdf/files/3179119/qpdf_error.pdf)

I use the following simple command:
`qpdf.exe qpdf_error.pdf xxxxx.pdf`

QPDF output is the following:

```
WARNING: qpdf_error.pdf (object 8 0, offset 121): stream keyword not followed by proper line terminator
WARNING: qpdf_error.pdf (object 8 0, offset 1759): expected endstream
WARNING: qpdf_error.pdf (object 8 0, offset 121): attempting to recover stream length
WARNING: qpdf_error.pdf (object 8 0, offset 121): recovered stream length: 1642
qpdf: operation succeeded with warnings; resulting file may have some problems
```

Can QPDF be optimized so that the output is not an empty PDF file?

**Comment by jberkenbilt** [comment]
Thanks for sharing your file. I will study it and see if I can make qpdf able to recover it. I'm planning some qpdf time in mid to late June, so it will like be then before I can look at it. The file has errors, but I see other readers can handle it, and I always want qpdf to be able to recover from as many kinds of errors as possible.

**Comment by jberkenbilt** [comment]
This is definitely a broken file, but I think I can make qpdf able to handle this particular type of damage.
