### ISSUE TITLE
qpdf linearization of PDF file with pages merged using iText's PDFStamper results in missing pages

### ISSUE THREAD

**Issue by justforwork** [qpdf/qpdf#33]
I use iText's PDFStamper to add contents of B.pdf to A.pdf**. I pass the merged file, say C.pdf, to qpdf* for linearization. When the number of pages in A.pdf < 10, linearization succeeds and the number of pages in the linearized file is same as that of C.
If number of pages in A.pdf > 10, I can see that number of pages in C.pdf is the sum of number of pages in A.pdf + B.pdf, but upon linearization only pages from A.pdf are retained in the output file, and the pages added from B.pdf are missing. 

* qpdf version we use right now 4.0.1. 
** A.pdf is generated as a PDF file from A.docx

**Comment by jberkenbilt** [comment]
I'm going to close this for now, but feel free to reopen if you are able to provide additional information. Thanks.
