### ISSUE TITLE
qpdf silently produces broken uncompressed file

### ISSUE THREAD

**Issue by rbrito** [qpdf/qpdf#332]
Dear Jay,

As we talked earlier this year, I found a file that is giving qpdf some troubles... When I decompress it with

```
qpdf --stream-data=uncompress --compress-streams=n --decode-level=specialized 1966-06.pdf 1966-06.unc.pdf
```

the generated file is not readable by both gv (that is, Ghostscript) or poppler-based viewers (actually, viewers based on poppler just show blank pages).

I'm using version your uploaded version 8.4.2, from Debian's sid.

I'm attaching both the original and the generated files here, to see if you can reproduce the problem.

[1966-06.pdf](https://github.com/qpdf/qpdf/files/3228525/1966-06.pdf)
[1966-06.unc.pdf](https://github.com/qpdf/qpdf/files/3228526/1966-06.unc.pdf)

If you need any extra information, please let me know.

Thanks,

Rogério Brito.

**Comment by jberkenbilt** [comment]
Thanks for this report. I am going to look at this very soon and see if I can figure out what's going on before I release qpdf 9.0.0.

**Comment by jberkenbilt** [comment]
There's some special case code in qpdf that treats the `#` differently in name objects for PDF 1.0 and PDF 1.1. This file claims to be PDF 1.0 and uses the `#` character in the names of the XObjects containing the page images. If you hand-edit the PDF file and change the header to say %PDF-1.2, the file works. I will reread this section of the spec and see if I am interpreting it incorrectly. I've never seen an actual file in the wild that uses `#` in name objects and has PDF version 1.0 or 1.1. Either way, this will probably be a simple fix.

**Comment by jberkenbilt** [comment]
Wow, this logic has been wrong in qpdf since before the first public release. I don't think this would have ever worked in any released qpdf version. Well, it will work in 9.0.

**Comment by jberkenbilt** [comment]
Content normalization was also completely broken for PDF 1.0 and 1.1 files with `#` in names. Luckily these are very rare. Hopefully qpdf 9.0.0 will get it a lot closer. One thing is certain though: if a PDF 1.0 file has names that contain `#` and are not valid in newer PDF versions and the file is converted to use something that forces QPDFWriter to write a newer format, the new file will be broken. For what it's worth, files like this are also not readable with xpdf or atril, so I'm not worried about it. This particular file has names that are valid in both PDF < 1.2 and PDF >= 1.2, so qpdf 9.0.0 will work completely fine on this file for all those odd cases.

**Comment by jberkenbilt** [comment]
I'm not sure whether I like the fix on my work branch. Please don't consider it final. I'm going to sleep on it.

**Comment by jberkenbilt** [comment]
I have coded a proper fix. The file you provided, which is a valid file, will work perfectly with qpdf 9.0.0. Also, files whose name tokens are invalid should still work properly with qpdf 9. Any PDF 1.0 or 1.1 file that had any token with a `#` in its name, whether valid or not, would have broken with all previous versions of qpdfl.
