### ISSUE TITLE
qpdf fails if /Length is not provided in encryption dictionary

### ISSUE THREAD

**Issue by gettalong** [qpdf/qpdf#333]
According to section 7.6.1 of the PDF 1.7 specification (unchanged in the PDF 2.0 spec):

> Length - Integer - (Optional; PDF 1.4; only if V is 2 or 3) The length of the encryption key, in bits. The value shall be a multiple of 8, in the range 40 to 128. Default value: 40.

This means that for V 4 or 5 there is no need to produce the Length key in the encryption dictionary. Additionally, the extended description of the V key in the PDF 2.0 spec describes that V=4 always has a 128bit key and V=5 always has a 256bit key.

However, qpdf set the default length to 40 in https://github.com/qpdf/qpdf/blob/master/libqpdf/QPDF_encryption.cc#L935 and only changes it if there is a Length key. 

Possible resolution: If V = 4, set the default value of Length to 128, if V = 5, set it to 256.

Here is a [sample PDF](https://github.com/qpdf/qpdf/files/3275470/outn.pdf) that doesn't work with qpdf but works fine with Adobe Acrobat and every other viewer I tried.

**Comment by jberkenbilt** [comment]
Thanks. I'll make sure this is fixed for the next qpdf release. qpdf was historically very strict. Over time, as issues like this have come up, I've just made it more lax about things that it can infer. I'll have to look at the code, but most likely qpdf can just infer the length. Anyway, I'll have to reread this section of the spec, look at your files, and look at the code, but I'm quite sure I can easily resolve this issue. I have set aside some time to work on qpdf next week. I will try to work this in.

**Comment by gettalong** [comment]
@jberkenbilt Thank you!

And thank you for making qpdf - I use it to test the results of my PDF library and also for performance comparisons.

**Comment by jberkenbilt** [comment]
Does this file have a password? I am getting an invalid password error on this file with all readers that I have tried including Adobe reader. However, I have been able to fabricate files that exercise this bug, and I'm pretty sure I will have it fixed properly for qpdf 9. But if you supply the password for this file, I can also test with it. Thanks for reporting.

**Comment by gettalong** [comment]
@jberkenbilt Sorry, the password is 'test'.

**Comment by jberkenbilt** [comment]
Great, thanks. Yes, it works now with qpdf in master.
