### ISSUE TITLE
Segfault if set QPDFWriter::setR*EncryptionParameters called before setOutput*

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#336]
This is fairly minor.

In QPDFWriter, if `setEncryptionParameters` is called before calling some version of `setOutput[Filename,Pipeline,etc]`, and we are *not* using a deterministic ID, then a segfault occurs here:

https://github.com/qpdf/qpdf/blob/e3129ef4323a8a0b6ecc0a711d5f5d1ca5fd0c56/libqpdf/QPDFWriter.cc#L2199

This happens because `this->m->filename` is null, and appending null to `std::string` is a segfault.

Since the filename is used to seed the output, perhaps it would make sense for the encryption functions to throw an exception if filename is not initialized.

**Comment by jberkenbilt** [comment]
Thanks. That would be an easy fix, and I'm working on qpdf this week. Hopefully I can get to this and the other easy fixes.
