### ISSUE TITLE
Preserve original xref table order

### ISSUE THREAD

**Issue by viduranga** [qpdf/qpdf#338]
I'm trying some hacky thing where I compress few image streams inside the PDF file. 
I get the image streams with getPageImages and iteratively compress them and write them back in the same place with replaceStreamData. The compressed data is just un viewable binary data so after writing the resulting pdf file, it is un viewable and that's fine.
Then I do the decompression of the pdf file using the same procedure.
The problem is that After the first compression, compressed pdf file has a different object order than the original file.
For example, the original object was on 2/0 location and the compressed one's location is 6/0.
Because of this, after the final decompression, background images come forward and texts in pdf are not visible.
Is there a way to preserve the original xref table ordering when writing the modified pdf file?
Hope there was a mailing list to post this.
BTW, loving QPDF.

**Comment by jberkenbilt** [comment]
Thanks for your report. There's no way that the order in which qpdf puts objects in the xref table or the way it numbers objects can possibly have anything to do with the way the file renders. If background images are coming forward and text is not visible, it must be for some other reason. Perhaps you have code that is using the original object IDs, which no longer point to the same things? If you work with qpdf by mutating the objects through QPDF and QPDFObjectHandle, and then you write with QPDFWriter, everything will be renumbered together.

However, there is another issue that is requesting preservation of Object IDs. I may see if I can do something with that request. There are several issues right now that might cause me to go back into that part of the code. Thanks!

**Comment by viduranga** [comment]
The objects coming to foreground is one of my dumb mistakes but I'd like to mention here if someone else came across the same.
I'm reading the pdf file using processMemoryFile with an std::vector<uint8_t>. I call the function as follow.
qpdf.processMemoryFile("decoder", reinterpret_cast<char*>(const_cast<uint8_t*>(data.data())), data.size());
But what I didn't realize is that processMemoryFile does not make a copy of the char* buf; and when I write the data, the std::vector is out of scope and so is the pdf file data. Only the data written by replaceStreamData remains not corrupt.
What would be ideal is that QPDF library to have smart pointers, but this is a major change and not worth the effort right now I think. Any way, a std::memcpy of the vector.data and pass to the processMemoryFile, did the trick and works seamless now.

However I would still like the option to preserve the original ordering as you mentioned because that would help to compare the two pdfs easily.

**Comment by jberkenbilt** [comment]
Thanks for the follow-up. Regarding smart pointers, qpdf has PointerHolder, which I wrote probably over 20 years ago before smart pointers were part of the standard or even a proposed part of the standard. They are all over qpdf's interface, and as much as I'd like to replace them with C++11 smart pointers, there are lots of pragmatic reasons why this is unlikely. However, you can certainly use a smart pointer in this place. qpdf 9.0.0 will include a method called QUtil::read_file_into_memory (see https://github.com/qpdf/qpdf/blob/4db1de97cea9dfab3f3abe43766053ba0d594610/include/qpdf/QUtil.hh#L309) that you can use. In current master, there are a few examples of using it. But really all you have to do is make sure the memory exists for the life of the QPDF object. It can be backed by a smart pointer if you want. Note that QPDF does not modify the buffer, so you can create multiple QPDF objects from the same memory buffer.
