### ISSUE TITLE
Handle "xref" more tolerant on broken PDF files.

### ISSUE THREAD

**Issue by ams-tschoening** [qpdf/qpdf#341]
One of my customers provided me some PDF file which QPDF is unable to parse properly and I'm somewhat sure that the problem is with the PDF itself, but in theory QPDF could handle that specific problem more tolerant. As it's doing so for other cases with non-standard `xref` already, I would like to document my problem here and discuss possible solutions. While I'm not able to share the whole PDF for privacy reasons, I'm going to share the most relevant parts according to my tests.

The following is the error:

    C:\Users\tschoening\Desktop>qpdf --check "Test.pdf"
    WARNING: Test.pdf: file is damaged
    WARNING: Test.pdf (offset 31352): xref not found
    WARNING: Test.pdf: Attempting to reconstruct cross-reference table
    Test.pdf: unable to find trailer dictionary while recovering damaged file

The following is the relevant part around `xref`:

	/Creator(Neevia docuPrinter TSE v6.8)
	/Author(s0330765)>>endobj
	xref
	0 28
	0000000000 65535 f 
	[...]
	0000029431 00000 n 
	trailer
	<< /Size 28 /Root 1 0 R /Info 2 0 R
	/ID [<FF3A5C433DA07654221870C2893843C3><FF3A5C433DA07654221870C2893843C3>]
	>>
	startxref
	31352
	%%EOF

According to my tests, `startxref` simply is off by one: 31352 is the newline BEFORE `xref`, like can be seen in the following screenshot. Increasing that value to 31353 using some HEX editor makes the problem go away and allows QPDF to successfully parse the PDF.

![Clipboard01](https://user-images.githubusercontent.com/6223655/60530467-15520f80-9cf9-11e9-96fa-76ac102c5bc4.png)

Looking at [QPDF::read_xref](https://github.com/qpdf/qpdf/blob/master/libqpdf/QPDF.cc#L580) I saw that you are already dealing with `xref`s violating the official spec and hoped you would provide a workaround for my problem as well:

> // The PDF spec says xref must be followed by a line
> // terminator, but files exist in the wild where it is
>  // terminated by arbitrary whitespace.

I'm of course willing to provide a PR, but can think of multiple possible solutions and would like to first check with you for the best approach: One approach could be changing `read_xref` to additionally check for the problem I have. Might get clumsy and the caller doesn't get a correct offset this way.

Another option might be changing [QPDF::parse](https://github.com/qpdf/qpdf/blob/master/libqpdf/QPDF.cc#L403), where `read_xref` gets actually called and add another call to that function with an increased offset by one in the exception handler. Or one could add some additional `read_xref` optionally with an additional signature or such doing exactly that by catching the exception, recalling with an increased offset and in case of success return the correct offset to the caller.

In [QPDF::parse](https://github.com/qpdf/qpdf/blob/master/libqpdf/QPDF.cc#L391) again, where the actual offset is read, one could add some logic to check that the offset really belongs to some `x` of `xref` and else might increase it or such.

I would prefer the option internally wrapping `read_xref` to handle additional strategies of fault-tolerance, maybe giving it some other name: `read_xref_tolerant` or such. In that wrapper one could try again using my +1, maybe a +2 is needed at some point, maybe the space-handling after `xref` could be externalized as well etc.

What do you think?

**Comment by jberkenbilt** [comment]
Most likely I would just modify the code to locate the xref if it's near the suggested location, perhaps skipping over whitespace. I've learned over the years that this kind of auto-recover techinque is almost always worth it. I could have it give a warning. qpdf, like all good tools, should be tolerant about what it reads and strict about what it writes, but I originally wrote qpdf as a PDF checker, and there are still parts of the code that are needlessly strict. Mostly I have relaxed stuff and generated warnings. In any case, I think having qpdf be looser about finding the xref before it goes into a full-fledged recovery is worth doing and not very much code. I appreciate the offer of a PR, but my guess is that it will take me less time to look at the code and fix it myself than to analyze a PR and decide whether it's a complete and correct fix.

**Comment by ams-tschoening** [comment]
> I appreciate the offer of a PR, but my guess is that it will take me less time to look at the code and fix it myself than to analyze a PR and decide whether it's a complete and correct fix.

Do you have any time schedule? While I don't want to apply any pressure of course, I have the problem that my customer might run into this problem at any time again and at least next time is simply going to ask me for when this will be fixed. :-) I would like to avoid applying a custom patch then unlikely to get merged as PR, just to need to remove that patch when you are fixing it differently.

Additionally I wrote to the company creating that PDF writer and asked for a fix on their site as well, just to be sure.

**Comment by jberkenbilt** [comment]
I don't have a specific time frame. However, I am hoping to get qpdf 9 out in the next few weeks. I had taken time off to work on qpdf but didn't quite get through, so I will probably steal a little more time to push it over the finish line.

**Comment by jberkenbilt** [comment]
I finally pushed a fix for this. I'm very close to the end of the changes for 9.0.0. I'm going to try to get that version out soon though realistically it could be a week or more.
