### ISSUE TITLE
split block of pages with given pages no as starting pdf page

### ISSUE THREAD

**Issue by HemanthJabalpuri** [qpdf/qpdf#344]
I have a problem that, if I have a book of 200 pages then I want to split it into chapter wise
i.e., 1-10 for introduction, 11-100 for chapter 1 and 101 to 200 for chapter 2.
I am a android user using qpdf in Termux Linux environment.
I saw an app called PDF Tools. With that we can split pages into multiple files by specifying 1,11,101 and this will give the perfect solution for above case.
How can I do the same thing with qpdf?
My thought is that if I specify 1,11,101 then the pdf will split into three files starting with the corresponding page.

**Comment by mschilli87** [comment]
@HemanthJabalpuri:
What I do when I have to do something lime this, is running `qpdf` in  `--split-pages` mode to get each page separately into it's own PDF file and then merge them back in the chunks I need.
As I rarely do this, I never automated this but writing a shell script that parses your page rages, creates a temporary directory, splits the input into that directory, merges accroding to your specification, and deletes the temporary directory shouldn't be hard to do.
Using qpdf as a library, you could probably even implement the same as a standalone binary with little more effort.

**Comment by HemanthJabalpuri** [comment]
@mshchilli87

Thanks for you suggestion.
I managed to write a shell script for this purpose.
```bash
splitblock_temp() {
  count=1
  while [ "$1" ]; do
    initpage=$1; lastpage=$(($2-1)); range=0
    case "$1" in
      *-*) range=1
        initpage="$(echo "$1" | cut -d\- -f1)"
        lastpage="$(echo "$1" | cut -d\- -f2)"
    esac
    if [ "$range" != "1" ]; then
      if [ "$2" ]; then case "$2" in *-*) echo "in 2nd case"; lastpage="$((`echo "$2" | cut -d\- -f1`-1))"; esac
      else lastpage=z
      fi
    fi
    #echo "$initpage -- $lastpage"
    qpdf --pages infile.pdf ${initpage}-${lastpage} -- outfile-${count}.pdf
    shift
    count=$((count+1))
  done
}

splitblock_temp 1-15 23 50 72-80
```

-Closing this issue.
