### ISSUE TITLE
Linearize multiple input files at once

### ISSUE THREAD

**Issue by Voralberg** [qpdf/qpdf#346]
Good morning,
Is there a way to add the possibility to linearize multiple input files, in one directory, in output with the same name with a simple command?
Something like:
`qpdf --linearize *.pdf (something?)`
Maybe there is a way, in that case I apology for this issues, that is simple and does not involve strange bash script that I am not aware of.

Thanks

**Comment by jberkenbilt** [comment]
You can do something like
```
mkdir out
for i in *.pdf; do qpdf --linearize $i out/$i; done
```
For each PDF file in your directory, a file of the same name in the `out` subdirectory will be linearized. This is not something qpdf supports directly or will support.

Please comment or reopen if you have any questions. Thanks.
