### ISSUE TITLE
alter page labels

### ISSUE THREAD

**Issue by femifrak** [qpdf/qpdf#348]
Hi,
I have a pdf from a scan where the page number of the file start with one. As the scanned (graphical) page number do not start with one, I would like to make an offset to the file page numbers as well.
Is this possible with qpdf?
Or is there any other possibility?

Thanks,
Femi

**Comment by femifrak** [comment]
Solution can be found here:
[]()https://superuser.com/questions/232553/how-to-change-internal-page-numbers-in-the-meta-data-of-a-pdf

in detail:
add


```
    /PageLabels <<
      /Nums [
        0 << /S /D /St 77 >>
      ]
    >>

behind   /Type /Catalog in the pdf file

```
to add an offset of 77 (e.g.)

**Comment by jberkenbilt** [comment]
I think it would be useful to have library or cli options to do this directly with qpdf. This type of question comes up from time to time. I'm glad you've found a solution to your specific case.

**Comment by jberkenbilt** [comment]
This can be done now with qpdf JSON, but I plan to implement the proposal in #939. I'm going to close this in favor of that issue. Please feel free to subscribe to that issue if you want to follow progress. Thanks!

**Comment by jberkenbilt** [comment]
A solution to this issue will be in qpdf 11.8.0. See #939 for details.
