### ISSUE TITLE
Split Pages fails with "operation for name attempted on object of type null"

### ISSUE THREAD

**Issue by yashodhan19** [qpdf/qpdf#349]
$ qpdf --split-pages "test.pdf" %d-out

WARNING: test.pdf, object 5 0 at offset 138160 -> dictionary key /Type: operation for name attempted on object of type null: returning dummy name

test.pdf (object 22 0, offset 133774): invalid Type /QPDFFakeName in page tree

**Comment by jberkenbilt** [comment]
This condition would happen if the page structure in qpdf were invalid and qpdf had attempted a recovery. If you could share the PDF file, I can see what was wrong with the file and improve qpdf's ability to recover. If you can't share the file, the next best thing would be the share the output of `qpdf --json test.pdf`. If you can't share either, then I won't be able to do anything with this. Thanks!

**Comment by yashodhan19** [comment]
Unfortunately I'm unable to provide the source doc
$ qpdf --json test.pdf
WARNING: test.pdf, object 5 0 at offset 138160 -> dictionary key /Type: operation for name attempted on object of type null: returning dummy name
test.pdf (object 27 0, offset 138750): invalid Type /QPDFFakeName in page tree

$ qpdf --show-xref test.pdf | grep offset
1/0: uncompressed; offset = 138961
2/0: uncompressed; offset = 138882
3/0: uncompressed; offset = 138750
4/0: uncompressed; offset = 137945
5/0: uncompressed; offset = 138149
6/0: uncompressed; offset = 10
7/0: uncompressed; offset = 4286
8/0: uncompressed; offset = 4309
9/0: uncompressed; offset = 4401
10/0: uncompressed; offset = 7457
11/0: uncompressed; offset = 115771
12/0: uncompressed; offset = 123470
13/0: uncompressed; offset = 123494
14/0: uncompressed; offset = 123588
15/0: uncompressed; offset = 125331
16/0: uncompressed; offset = 129426
17/0: uncompressed; offset = 129450
18/0: uncompressed; offset = 129544
19/0: uncompressed; offset = 133614
20/0: uncompressed; offset = 133638
21/0: uncompressed; offset = 133732
22/0: uncompressed; offset = 137827
23/0: uncompressed; offset = 137851
24/0: uncompressed; offset = 138271
25/0: uncompressed; offset = 138386
26/0: uncompressed; offset = 138508
27/0: uncompressed; offset = 138625

**Comment by jberkenbilt** [comment]
Can you add `--json-key=objects` to the command? Maybe this will prevent qpdf from trying to resolve pages.

**Comment by yashodhan19** [comment]
Same warning
$qpdf --split-pages --json-key=objects test.pdf %d-out
WARNING: test.pdf, object 5 0 at offset 138160 -> dictionary key /Type: operation for name attempted on object of type null: returning dummy name
test.pdf (object 22 0, offset 133774): invalid Type /QPDFFakeName in page tree

**Comment by jberkenbilt** [comment]
Actually, the full command should be `qpdf --json --json-key=objects test.pdf`. No `--split-pages`, and no output file. Just `--json` and `--json-key`. Sorry for being unclear. I was typing from my phone before.

If that still doesn't work, try `qpdf --show-object=5` and `qpdf --show-object=22`? Failing that, I may ask you to send specific byte ranges of the file, which you can extract with `dd`. Since you were kind enough to provide the xref table, I will be able to give you specifics. You can inspect them to ensure that there is no sensitive information. I'll do that only if the above doesn't work.

**Comment by yashodhan19** [comment]
Thanks Jay,

$qpdf --json --json-key=objects test.pdf
{
  "objects": {
    "1 0 R": {
      "/Pages": "5 0 R",
      "/Type": "/Catalog"
    },
    "10 0 R": {
      "/BitsPerComponent": 8,
      "/ColorSpace": "/DeviceRGB",
      "/Filter": [
        "/ASCII85Decode",
        "/FlateDecode"
      ],
      "/Height": 341,
      "/Length": 108095,
      "/Name": "/Im2",
      "/Subtype": "/Image",
      "/Type": "/XObject",
      "/Width": 975
    },
    "11 0 R": {
      "/Length": "12 0 R"
    },
    "12 0 R": 7638,
    "13 0 R": {
      "/Contents": "11 0 R",
      "/Parent": "5 0 R",
      "/Resources": "4 0 R",
      "/Rotate": 90,
      "/Type": "/Page"
    },
    "14 0 R": {
      "/BitsPerComponent": 8,
      "/ColorSpace": "/DeviceRGB",
      "/Filter": [
        "/ASCII85Decode",
        "/FlateDecode"
      ],
      "/Height": 44,
      "/Length": 1525,
      "/Name": "/Im3",
      "/Subtype": "/Image",
      "/Type": "/XObject",
      "/Width": 151
    },
    "15 0 R": {
      "/Length": "16 0 R"
    },
    "16 0 R": 4034,
    "17 0 R": {
      "/Contents": "15 0 R",
      "/Parent": "5 0 R",
      "/Resources": "4 0 R",
      "/Rotate": 90,
      "/Type": "/Page"
    },
    "18 0 R": {
      "/Length": "19 0 R"
    },
    "19 0 R": 4009,
    "2 0 R": {
      "/HT": "/Default",
      "/OP": false,
      "/SA": false,
      "/Type": "/ExtGState"
    },
    "20 0 R": {
      "/Contents": "18 0 R",
      "/Parent": "5 0 R",
      "/Resources": "4 0 R",
      "/Rotate": 90,
      "/Type": "/Page"
    },
    "21 0 R": {
      "/Length": "22 0 R"
    },
    "22 0 R": 4034,
    "23 0 R": {
      "/Contents": "21 0 R",
      "/Parent": "5 0 R",
      "/Resources": "4 0 R",
      "/Rotate": 90,
      "/Type": "/Page"
    },
    "24 0 R": {
      "/BaseFont": "/Courier",
      "/Encoding": "/WinAnsiEncoding",
      "/Name": "/F1",
      "/Subtype": "/Type1",
      "/Type": "/Font"
    },
    "25 0 R": {
      "/BaseFont": "/Helvetica-Bold",
      "/Encoding": "/WinAnsiEncoding",
      "/Name": "/F2",
      "/Subtype": "/Type1",
      "/Type": "/Font"
    },
    "26 0 R": {
      "/BaseFont": "/Helvetica",
      "/Encoding": "/WinAnsiEncoding",
      "/Name": "/F3",
      "/Subtype": "/Type1",
      "/Type": "/Font"
    },
    "27 0 R": {
      "/BaseFont": "/Helvetica-Oblique",
      "/Encoding": "/WinAnsiEncoding",
      "/Name": "/F4",
      "/Subtype": "/Type1",
      "/Type": "/Font"
    },
    "3 0 R": {
      "/Angle": 45,
      "/Frequency": 60,
      "/HalftoneName": "Default",
      "/HalftoneType": 1,
      "/SpotFunction": "/Round",
      "/Type": "/Halftone"
    },
    "4 0 R": {
      "/ExtGState": {
        "/GS1": "2 0 R"
      },
      "/Font": {
        "/F1": "24 0 R",
        "/F2": "25 0 R",
        "/F3": "26 0 R",
        "/F4": "27 0 R"
      },
      "/ProcSet": [
        "/PDF",
        "/Text",
        "/ImageC"
      ],
      "/XObject": {
        "/Im1": "9 0 R",
        "/Im2": "10 0 R",
        "/Im3": "14 0 R"
      }
    },
    "5 0 R": {
      "/Count": 5,
      "/Kids": [
        "8 0 R",
        "13 0 R",
        "17 0 R",
        "20 0 R",
        "23 0 R"
      ],
      "/MediaBox": [
        0,
        0,
        612,
        792
      ],
      "/Types": "/Pages"
    },
    "6 0 R": {
      "/Length": "7 0 R"
    },
    "7 0 R": 4217,
    "8 0 R": {
      "/Contents": "6 0 R",
      "/Parent": "5 0 R",
      "/Resources": "4 0 R",
      "/Rotate": 90,
      "/Type": "/Page"
    },
    "9 0 R": {
      "/BitsPerComponent": 8,
      "/ColorSpace": "/DeviceRGB",
      "/Filter": [
        "/ASCII85Decode",
        "/FlateDecode"
      ],
      "/Height": 44,
      "/Length": 2838,
      "/Name": "/Im1",
      "/Subtype": "/Image",
      "/Type": "/XObject",
      "/Width": 1054
    },
    "trailer": {
      "/Root": "1 0 R",
      "/Size": 28
    }
  },
  "parameters": {
    "decodelevel": "generalized"
  },
  "version": 1
}

**Comment by jberkenbilt** [comment]
Thanks, this gives me what I need. Should be an easy fix. I'm not sure when I'll have time to do it. I really wanted to get 9.0.0 out this summer, but we'll see if I can find the time.

I think the solution here will be to have qpdf fix the /Type keys in all nodes of the pages tree. That will solve this problem and many similar problems that have been reported over the years.

**Comment by jberkenbilt** [comment]
I'm pushing up a change that I think will most likely fix this. If you would like to test, you can grab the changes to QPDF_pages.cc from the commit that contains the fix, or you can build qpdf from github or you can use the automated build from Azure Pipelines. This issue will close when I push to master, and 20 minutes or so later, the automated build will finish, and I can post the URL. Or you can wait for 9.0.0 and hope for the best.

**Comment by jberkenbilt** [comment]
Wow, this logic has been wrong in qpdf since before the first public release. I don't think this would have ever worked in any released qpdf version. Well, it will work in 9.0.

**Comment by jberkenbilt** [comment]
Oops, commented on wrong issue.

**Comment by yashodhan19** [comment]
Thank you. It works great with all files I had issues when splitting pages.

**Comment by jberkenbilt** [comment]
@yashodhan19 Excellent. Thanks for testing and following up.
