### ISSUE TITLE
problems with encoding

### ISSUE THREAD

**Issue by olivroy** [qpdf/qpdf#353]
I use the function pdf_length 
and there is a é inside the address of the pdf file
Error in cpp_pdf_length(input,password) No such file or directory
and then my é becomes  Ã©

**Comment by jberkenbilt** [comment]
I'm not familiar with pdf_length or cpp_pdf_length, but It appears that your input contains é encoded as UTF-8, and whatever is printing the error message is outputting it in something else, possible ISO-8859-1 or Windows ANSI 1252 or PDF doc encoding, which are single-byte character sets.
