### ISSUE TITLE
Linearization fails with "unknown token while reading object (PDF)"

### ISSUE THREAD

**Issue by CRCulver** [qpdf/qpdf#36]
Attempting to linearize the PDF file [here](http://www.christopherculver.com/temp/dixon.pdf) by means of `qpdf --linearize dixon.pdf output.pdf` fails with the error `(file position 3844619): unknown token while reading object (PDF)`. My qpdf version is 5.1.2.

I’ve encounted this same error with a number of PDFs (all ebooks) recently.

**Comment by jberkenbilt** [comment]
saved as qpdf/misc/bugs/36.pdf

**Comment by jberkenbilt** [comment]
I believe latest fixes on master will allow qpdf to recover this file. qpdf now recovers from invalid tokens and malformed dictionaries much more often than before. These fixes will be in 7.0.0.
