### ISSUE TITLE
Character conversion test fails on architectures where char defaults to unsigned

### ISSUE THREAD

**Issue by mgorse** [qpdf/qpdf#361]
I get the following test failure on ppc64le, s390x, and aarch64:

@@ -10,4 +10,4 @@
 QIntC::to_ulonglong<int32_t>(i1): integer out of range converting -1153374643 from a 4-byte signed type to a 8-byte unsigned type PASSED
 QIntC::to_char<int32_t>(i2): 81 Q PASSED
 QIntC::to_uchar<int32_t>(i2): 81 Q PASSED
-QIntC::to_uchar<char>(c1): integer out of range converting M-w from a 1-byte signed type to a 1-byte unsigned type PASSED
+QIntC::to_uchar<char>(c1): M-w M-w FAILED

On these architectures, chars are signed by default, so the char is not
range checked the way the test expects.
If I add --signed-char to CXXFLAGS, then the tests pass.
I'm not sure what should be done here, if anything. If the code generally
assumes the chars are signed, then maybe configure should set --signed-char
if the compiler supports it.

**Comment by jberkenbilt** [comment]
Thanks for this helpful report. I think the details of your report might be a little confused...you might have said the opposite of what you meant in a few cases. Did you mean to say that chars are *unsigned* by default on these architectures? chars are signed by default on the architectures I test with. Also, x86_64 and ix86 are little-endian, so it is probably not related to endian-ness.

Either way, it seems clear that there is code in qpdf that assumes `char` is signed, which is probably because I didn't realize that there were any platforms where `char` was unsigned by default. I think your idea of adding `--signed-char` is a good one. My most likely fix will be to see if I can add an autoconf test for whether chars are signed or unsigned and, if unsigned, refuse to build. This test can include trying to find a flag to make chars signed. Alternatively, I can try to figure out a way of testing locally with char unsigned by default and fix the code to work either way.

Thanks for taking the time to report this. I'm sure this issue would stump a lot of people trying to build on these architectures, and I'd definitely like to make it work more easily.

**Comment by mgorse** [comment]
Sorry about that. I meant that chars are unsigned by default on some architectures. We noticed this after updating qpdf for the upcoming SLES/SLED service pack, and the build failed on several architectures. I'm updating the SLE and openSUSE specs to pass --signed-char (although, on second thought, -fsigned-char might be more correct, since it is what is documented in the gcc manpage). There is also a -funsigned-char that makes chars unsigned.

**Comment by zdohnal** [comment]
I got the same test failures when trying to build qpdf-9.0.0 for Fedora.

**Comment by jberkenbilt** [comment]
I guess I'll have to find a durable fix and make a 9.0.1. Does anyone know how I can reliably reproduce this on a platform I have access to? I have a regular x86_64 PC. I don't have runtime environments for other platforms unless I get logins on other people's systems or something in a public cloud. Or maybe I can pass a flag to gcc or clang that will cause me to have a test failure on my platform so I can fix it.

I will want to look into this enough to see whether the test failure is revealing a problem that has always been there and previously went undetected or whether it's a new problem. I did a lot of work between 8.4.2 and 9.0.0 making qpdf much safer regarding integer conversions. Lots of things that would cause silent data loss in the past cause runtime errors now. These are mostly either extreme boundary conditions or problems handling already invalid data, but still.

**Comment by jberkenbilt** [comment]
Actually, I see that `-fsigned-char` and `-funsigned-char` work. I should be able to get to the bottom of this either by making the code work either way, by adding autoconf that forces char to be signed by default, or by explicitly using `signed char` where needed.

**Comment by zdohnal** [comment]
@jberkenbilt You can see the whole build results here https://koji.fedoraproject.org/koji/taskinfo?taskID=37699322 if it helps.

Then I tried to find out you could get e.g. aarch64 machine and found this manual https://fedoraproject.org/wiki/Architectures/AArch64/Install_with_QEMU - it is for running aarch64 Fedora guest in qemu on Fedora x86. The current link you can use for creating the VM is https://dl.fedoraproject.org/pub/fedora-secondary/releases/30/Workstation/aarch64/os/ . Though I have not tried the manual yet :( .

**Comment by jberkenbilt** [comment]
Okay, I've looked at this, and it's a test-only issue. It's only the test code that is assuming char is signed. I will push a fix, which you can include as a patch in the fedora package. I'll give 9.0.0 a little more time to bake before releasing 9.0.1, which will include this fix.

**Comment by jberkenbilt** [comment]
I'll push this to master when CI is green. At that time, you can use the latest commit on master as the patch.

**Comment by jberkenbilt** [comment]
Hmm. I maintain qpdf for debian and had failed to notice lots of build failures in debian as well for this and other reasons on some architectures all related to integer warnings. I will definitely have to clean this up and release 9.0.1.

**Comment by jberkenbilt** [comment]
The commit https://github.com/qpdf/qpdf/commit/6d81f014764e3bb9452d3697b84093bed0668f02 can be used as a patch against 9.0.0. Hopefully the 8-bit character that is not valid UTF-8 won't break the patch. If it causes a significant problem, I can push out 9.0.1. There are integer warnings on some of the debian architectures which I'd like to clean up before releasing 9.0.1.

**Comment by jberkenbilt** [comment]
@mgorse @zdohnal Please see https://raw.githubusercontent.com/jberkenbilt/debian-qpdf/master/debian/patches/int-conversion for a patch I'm applying to the debian package. This cleans up integer conversion warnings for big endian systems as well as the failed QIntC test for systems with unsigned char. If this is clean on all debian architectures (I should know in a day or two), then I will release as 9.0.1.

**Comment by zdohnal** [comment]
Thank you for quickly fixing the issue! I'll test it right away.

**Comment by jberkenbilt** [comment]
The build is clean now on all debian architectures. I will see if there are any other very easy fixes and will release 9.0.1. Also in master as an integer overflow fix caught by oss-fuzz.

**Comment by jberkenbilt** [comment]
This fix is in 9.0.1, so feel free to just skip 9.0.0 and package that instead. Debian packages are already uploaded.
