### ISSUE TITLE
--flatten-annotations vertically flips some fields

### ISSUE THREAD

**Issue by mhufsky** [qpdf/qpdf#363]
running `qpdf.exe --flatten-annotations=print .\Example.pdf .\Example_flat.pdf` will produce this result:
<img width="373" alt="result" src="https://user-images.githubusercontent.com/42769330/65121844-2bb26200-d9f0-11e9-82c3-3d1e26e06295.png">

[Example.pdf](https://github.com/qpdf/qpdf/files/3624797/Example.pdf)

Version from download qpdf-9.0.0-bin-mingw64.zip
Operating System: Windows Server 2012 R2

**Comment by jberkenbilt** [comment]
Thanks for the report. I am able to reproduce this. It's not obvious to me what's going on, but I should be able to figure it out and fix it. I have to release 9.0.1 to fix a build problem on some platforms. No guarantees, but I'll see if I can get this in.

**Comment by jberkenbilt** [comment]
There's a strange error in the file with the rectangles for those form fields appearing with the coordinates out of order, but it's an easy fix. The fix will be in 9.0.1 which I plan to release in the next couple of days. Thanks for the report and the sample file.

**Comment by mhufsky** [comment]
In the meantime we have run many files thru qpdf 9.0.1 with no flipped form fields.
Thanks for the fast solution.
