### ISSUE TITLE
Syntax for selection of even or odd pages in page range

### ISSUE THREAD

**Issue by equaeghe** [qpdf/qpdf#364]
I sometimes get scans where the even pages are rotated 180 degrees. I can then use the rotate option to rotate those, but I have to specify all the page numbers individually AFAIK. Would it be possible to add a modifier that subselects all even or odd pages from a range? For example, syntax as

```
qpdf in.pdf out.pdf --rotate=180:1-z:even
qpdf in.pdf out.pdf --rotate=180:1-z:odd
```

**Comment by jberkenbilt** [comment]
Yes -- this is a great suggestion.

Funny you should suggest this. Just yesterday on my way home from work, I was deciding to implement this feature. This weekend, I needed to prepare some materials for double-sided printing and wanted to use odd/even page selection. What I will probably do is to extend the numeric range syntax to allow a skip value and have odd and even as special cases, or else I will just implement odd and even, which is probably the main thing people will want. In any case, this should be a pretty easy feature to add, so I will get it in for the next non-patch release, which will most likely be 9.1. Or maybe I can sneak it into 9.0.1 if I have time. I need to get that out in a few days.

**Comment by jberkenbilt** [comment]
This is in for 9.1.0, implemented as suggested; i.e. you can append `:even` or `:odd` to any numeric range.
