### ISSUE TITLE
Using --replace-input on file with / in name

### ISSUE THREAD

**Issue by rEes9P** [qpdf/qpdf#365]
Hi. Thanks for the excellent utility. Scripting newbie here so apologies at the start if this is a very obvious question!

I have been using qpdf on my Mac to decrypt bills and statements sent to me in pdfs and it works well except in cases where I want to replace the file that I decrypt. I have tried using the `--replace-input` option but to no avail. Here are the things I tried with the results I got:

```
$ qpdf --decrypt --password=password /Users/me/Desktop/folder/remove\ encryption/abc.pdf /Users/me/Desktop/folder/remove\ encryption/abc.pdf

qpdf: input file and output file are the same; use --replace-input to intentionally overwrite the input file

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help
```

```
$ qpdf --decrypt --password=password --replace-input /Users/me/Desktop/folder/remove\ encryption/abc.pdf 
open .~qpdf-temp./Users/me/Desktop/folder/remove encryption/abc.pdf#: No such file or directory
```

```
$ qpdf --decrypt --password=password /Users/me/Desktop/folder/remove\ encryption/abc.pdf --replace-input
open .~qpdf-temp./Users/me/Desktop/folder/remove encryption/abc.pdf#: No such file or directory
```

I am at a loose end and would be glad to know what it is that I am missing. Many thanks!

**Comment by jberkenbilt** [comment]
You found a silly bug that resulted from a last minute change in my naming conventions for replace-input. Apparently I coded it in a way that will only work if the file is in the current directory. I will get a fix out for this soon. In the mean time, try this instead:
`(cd /Users/me/Desktop/folder/remove\ encryption; qpdf --decrypt --password=password --replace-input abc.pdf)`

**Comment by jberkenbilt** [comment]
Thanks for reporting this!

**Comment by rEes9P** [comment]
Thank _you_ for this wonderful utility and for all your work!

**Comment by rEes9P** [comment]
> You found a silly bug that resulted from a last minute change in my naming conventions for replace-input. Apparently I coded it in a way that will only work if the file is in the current directory. I will get a fix out for this soon. In the mean time, try this instead:
> `(cd /Users/me/Desktop/folder/remove\ encryption; qpdf --decrypt --password=password --replace-input abc.pdf)`

I did try this but it doesn't work!

**Comment by jberkenbilt** [comment]
Hmm. Are you sure? If you cd to a directory and run it on a file in that directory without a full path or any slashes in the file name at all, you still get this message? I don't understand how that could be the case because the automated tests for this feature pass on the mac, and they do what I described. There is definitely a bug if you have any slashes in the path.

Anyway, I will find some time code a fix for this either by changing the temporary file to only ever append something (so absolute vs. relative path makes no difference at all) or by parsing the path name and mutating it correctly.

**Comment by rEes9P** [comment]
Ah! I get it now. It does work. I made the mistake of including the full path after cding into the directory. Using the just the file name did the trick. Thanks.

**Comment by rEes9P** [comment]
Hi @jberkenbilt. Don't mean to be pushy but was wondering when this fix is likely to see the light of day as I have a bunch of pdfs that I need to decrypt and the Hazel rule that I mean to use for it needs this fix. Many thanks!

**Comment by jberkenbilt** [comment]
I can probably go ahead and push out 9.0.2 with just this fix. There are some pull requests open that I need to work with for a 9.1 release, but this is currently the only open "bug" ticket. Let's see if I can find some time this weekend for 9.0.2. No promises, but I'll try.

**Comment by rEes9P** [comment]
That would be great if possible but no worries at all if not. Looking forward to it whenever it comes about :-) Have a great week ahead!

**Comment by jberkenbilt** [comment]
This is in 9.0.2, which I am releasing momentarily.
