### ISSUE TITLE
Getting an error with qpdf-9.0.1-bin-mingw32

### ISSUE THREAD

**Issue by andres99** [qpdf/qpdf#366]
On Windows XP SP3, trying to use QPDF mingw version, I am getting no result but an error message The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll.

The command line was "qpdf.exe --linearize --force-version=1.4 --object-streams=disable"

The same problem does not appear in qpdf-9.0.1-bin-msvc32, which works with the same command line as expected.

**Comment by mschilli87** [comment]
Windows XP in 2019? Microsoft stopped supporting this OS five years ago! Why would assume anyone else still supported it? Sorry for the noise, I'm just shocked people actually still use this OS. :wink:

**Comment by andres99** [comment]
In reply to your question. First of all, XP actually still works. I have a very nice and stable, extremely quiet computer with no speed problems. Windows 7 or 10 would be slower on the same machine. Buying a new computer would mean a good deal of configuring (I like my computer tailored to my needs), possibly a noisier machine.

I am a system admin and I have used a lot of Windows 7 (usable) and Windows 10 (very difficult to control because of some compulsory elements and actions introduced by Microsoft). I have found XP to be cleaner, faster and smoother in a number of ways than Windows 7.

In Windows 7, quite many updates contain(ed) Microsoft spyware or adware, some trying to lure the user into installing Windows 10 at any cost, even downloading the upgrade without the user’s consent and then trying to make the user just to press a button to start the upgrade process. In addition, Microsoft used to "punish" the users who still stayed with Windows 7 by making their updates extremely slow (sometimes it can take days, not minutes or hours). Windows 7 is manageable though when I skip the useless updates and install only useful ones. Windows 10 is worse in that sense, since there are processes which have been deliberately moved out of the user’s control and updates that just cannot be avoided. But hey, it’s my computer, isn’t it?

The importance of Microsoft’s security updates is kinda overrated in my opinion. Yes, the security problems exist but probably the biggest security problem is Microsoft’s and the hardware manufacturers’ back doors anyway. I have not used a background-running antivirus for 15 years. Instead of it I apply reasonable caution, use a good 3rd party firewall and a relatively safe LAN. I check suspicious files occasionally with VirusTotal and I also make occasional manual checks with some antivirus. During those 15 years I just had 1 incident and even then I got it under control. Otherwise my computer has been clean. And now, XP has become so obscure that it may be safer in the sense of no one being too serious about targeting it.

I will stop using Windows XP when I cannot do what I want with it. So far I can.

As for qpdf, I did not assume support. I just notified, in case. And it was only about the mingw version. The msvc version still actually works in XP and I am using it as we speak.

Regards
Andres

**Comment by mschilli87** [comment]
Apologies for side tracking this. It was in the morning and I must have been half asleep. I'm just replying once more to make sure I didn't step on anyones toes. Personally, I stopped using Windows as my main system in 2003 and uninstalled my last copy (an XP install btw) in early 2007. Once you cannot do with Windows XP what you want with it, I recommend you to give a lighweight but modern  Linux distribution a try. I would be surprised if you won't be amazed by the performance especially on aged hardware. That said, keep running with what works for you, I did not mean to be patronizing. And apologies to everyone else having to read this unrelated comments of mine. I'm goingsorry  to mark them off-topic to lower the nise. @andres99: Feel free to drop me an email if you want to continue this conversion.

**Comment by jberkenbilt** [comment]
I'm glad the msvc32 version works for you. If you needed a mingw version for xp, you might be able to build one. I don't have access to a development environment on/for Windows XP, and I doubt I will prioritize making it work on that platform. Thanks for taking the time to report. This report may help someone else with the same problem.
