### ISSUE TITLE
fix-qdf assumes fixed size for /W fields in object stream

### ISSUE THREAD

**Issue by aluebcke** [qpdf/qpdf#37]
I've used qpdf extensively and encountered finally encountered a problem.
The perl script fix-qdf that rewrites offsets after edits/insertion assumes that object numbers in an object_stream will only occupy a single byte.
Excerpt from qpdf 5.1.2 contains             print "  /W [ 1 $xref_f1_nbytes 1 ]\n";
Unfortunately the environment I work in doesn't let me provide a full file however I'm working with PDF files generated by MS word. Here's an excerpt of file showing content where this is not true:
1431 0 obj
<<
  /Type /XRef
  /Length 8592
  /W [ 1 3 2 ]
  /Info 2 0 R
  /Root 1 0 R
  /Size 1432

There were 257 items in this particular object stream. I'm not fluent in PERL and haven't been able to generate a fix for the script.

**Comment by jberkenbilt** [comment]
Sorry this took so long to fix. I just hardly have any time to look at qpdf these days. Anyway, I coded a fix and will be pushing to github today. Hopefully I will have time to get a new release out.

**Comment by jberkenbilt** [comment]
5.1.3 is released
