### ISSUE TITLE
Overlay only stamps first page in range

### ISSUE THREAD

**Issue by chrisvwn** [qpdf/qpdf#378]
In Windows 10 with qpdf version 9.0.2

Running `qpdf --overlay` only stamps the first page "in range". If you specify the `--to=` option it will stamp the first page in range e.g. `--to=2-10` will stamp page 2. Without specifying `--to` it will stamp page 1 only.

The behavior is also the same whether using `--replace-input` or not.

**Comment by mschilli87** [comment]
I have to guess but it sounds like your 'stamp file' has only one page.
Try

```sh
qpdf --overlay stamp.pdf --repeat=1 unstamped.pdf stamped.pdf 
```

**Comment by chrisvwn** [comment]
Correct. The stamp file has only one page.

And your solution works. Is this how it is intended to work? The docs say omitting `--to` means the stamp file will be applied to all pages.

**Comment by mschilli87** [comment]
Yes, but it also says that `--from` indicates the pages to use from the ~stamp~overlay file and `--repeat` which ones to repeat once those are depleted. If you have a suggestion how to improve the documentation to make the behaviour more clear, I'm sure a pull request would be welcome. :wink:

**Comment by chrisvwn** [comment]
Thanks @mschilli87 Got it! I am grateful for qpdf which makes PDF manipulation so much easier.
