### ISSUE TITLE
After upgrading from qpdf 8 to qpdf 9: extracting pages is much slower

### ISSUE THREAD

**Issue by janjan** [qpdf/qpdf#380]
First of all: Thanks a lot for your wonderful tool!

From time to time I use qpdf to extract single pages from large pdfs. I am very happy with the results but after upgrading from qpdf 8 to qpdf 9 I noticed that for some pdfs the extraction of one page takes much longer than before. Is this a known issue?

I managed to create a test pdf using Inkscape: [stars-25-pages.pdf](https://github.com/qpdf/qpdf/files/3790161/stars-25-pages.pdf) As you can see it contains tons of small vector objects

For qpdf 8 I get these results:

    > qpdf --version
    qpdf version 8.0.2
    Run qpdf --copyright to see copyright and license information.
    
    > time qpdf stars-25-pages.pdf --pages stars-25-pages.pdf '10-10' -- 'output.pdf'
    real    0m0,013s
    user    0m0,010s
    sys     0m0,000s

For qpdf 9 I get these results:

    > qpdf --version
    qpdf version 9.0.0
    Run qpdf --copyright to see copyright and license information.
    
    > time qpdf stars-25-pages.pdf --pages stars-25-pages.pdf '10-10' -- 'output.pdf'
    real    0m3,300s
    user    0m3,220s
    sys     0m0,034s

(Unfortunately, I can't upgrade to 9.0.2 at the moment but I did not see anything the changelog  which might be related to this problem)

I use an up-to-date OpenSuse 15 for the tests above. My machine is a standard Intel i7 with 32 gb of ram and an SSD.

If I have to extract a single page the new behavior is totally fine for me but sometimes I have to extract dozens of random single pages from a pdf and then the longer runtime becomes noticeable.

is there any command-line option I can use to make the extraction faster? Or is this some sort of new bug?

If you need any more info or tests: Just let me know, I will try to help as much as I can!

**Comment by jberkenbilt** [comment]
Try the `--preserve-unreferenced-resources` flag and see if that solves your problem. Starting in version 8.1, qpdf attempts to scan through a page's contents and remove unreferenced objects. This solves a problem a lot of users were having where some PDF files listed all images on all pages in the metadata even though most pages didn't include most images. The result was that each extracted page was almost as large as the whole file. The new behavior however is slower, especially for files with lots and lots of objects. The `--preserve-unreferenced-resources` flag causes the old faster behavior with the caveat that some unnecessary objects may be included.

Thanks for your detailed report and for providing all the information I needed, including a sample file.

**Comment by janjan** [comment]
Thanks for the fast answer!

I tried the `--preserve-unreferenced-resources` on a bunch of complex pdfs and I can confirm that it indeed brings back the old speed.

Could you perhaps make an update to the description of that flag in the manual? When I encountered the slowness issue, I searched the manual for words like 'fast', 'slow', ... and did not find any relevant results. 

If you would add a sentence like this one

> The new behavior however is slower, especially for files with lots and lots of objects. The `--preserve-unreferenced-resources` flag causes the old faster behavior with the caveat that some unnecessary objects may be included.

to the manual I would have been able to solve my issue without bothering you with an unnecessary Github issue ;)

Since my issue is solved you can close this issue as "successfully soved"!

Thanks again for your help and your wonderful tool :)

**Comment by jberkenbilt** [comment]
I have updated the wording in both the release notes for 8.1 and the description of the `--preserve-unreferenced-resources` flag to include the word "slow". You can see the changed language in the commit that closes this issue. The updates to the manual will be in version 9.1.0, which I will release soon. Thanks again!

**Comment by jberkenbilt** [comment]
@janjan In qpdf 10, qpdf will analyze files when run with `--split-pages` to determine whether there are any shared resources, and only do the expensive detection and removal of unreferenced resources if shared resources are found. This herustic should be right most of the time and will generally make it so people don't have to care about `--preserve-unreferenced-resources`. It is still possible to force explicit behavior. For details, see the release notes for qpdf 10 (to be released soon).

**Comment by janjan** [comment]
Thanks for the update, I will keep an eye out for qpdf 10 and give some feedback if I find any issue!

**Comment by jberkenbilt** [comment]
@janjan I released 10.0.1 a few days ago: https://github.com/qpdf/qpdf/releases/tag/release-qpdf-10.0.1. Read through the release notes for details, but hopefully you should get much better performance with default options. I'll save the details for the release notes, but let me know if you have any further problems.
