### ISSUE TITLE
fix-qdf integrated in the main executable

### ISSUE THREAD

**Issue by ceztko** [qpdf/qpdf#381]
fix-qdf is a really valuable tool but it suffer for the fact of being a Perl script which is inconvenient for platforms where Perl is not default installed. Could it be ported to C++ and integrated in the main executable or there are other reasons it's shipped as a separate script?

**Comment by jberkenbilt** [comment]
Adding it to the main executable is on my roadmap. I just haven't gotten to it yet.

**Comment by jberkenbilt** [comment]
I have rewritten fix-qdf in C++. It's still a separate program, but it's now no longer a perl script. This was made much easier now that I'm requiring a C++-11 compiler and have std::regex, which made it possible to do a direct translation from perl to C++. The C++ version will be in the 9.1.1 release, and qpdf will no longer have a runtime dependency on perl.

**Comment by ceztko** [comment]
I tested it and it works good. Thank you.
