### ISSUE TITLE
create new pdf with GBK or Unicode contents

### ISSUE THREAD

**Issue by lugeluge** [qpdf/qpdf#389]
I ran pdf-create.cc in the example, and then I wanted to write Chinese text in the pdf, but I tried to modify the font and it did not display Chinese correctly, so how do I insert Chinese or other unicode encoded text in the pdf,should I need Change the encoding method of text or just string type text, and then the font can use trueType type font？
![image](https://user-images.githubusercontent.com/16603407/70106391-79994680-167e-11ea-8af9-ae9271a9e617.png)

**Comment by jberkenbilt** [comment]
Hello. Sorry for the delay. Answering this out of scope for a github issue on qpdf. Unfortunately, the PDF spec doesn't just allow you to put an encoded string here. Instead, you have to use character maps. qpdf doesn't have any methods to help you do this, but you can certainly use qpdf to do it if you manage all your character maps by hand. There may be higher level libraries that make this easier. Unfortunately, Unicode support is one of those areas where the PDF specification shows its age.
