### ISSUE TITLE
Getting blank pages or greyscale page in the result pdf

### ISSUE THREAD

**Issue by gulabbisht** [qpdf/qpdf#393]
Hey,

Using this library for adding dynamic watermark to pdfs but in some cases getting greyscaled pdf or some blank pages in the output pdf.

This only happens on load testing scenario.

Watermark pdf id generated through `tcpdf`.

`qpdf source.pdf output.pdf --overlay watermark.pdf --from= --repeat=1 --`

**Comment by jberkenbilt** [comment]
Hi. What do you mean that it only happens on load testing scenario? What kind of load testing are you doing? Are you saying that the command above always produces correct results when run on a single file, but under some other situations it does not? Is there any reliable way to reproduce the results with a single command?

Is your load testing environment possibly creating a situation where two instances of qpdf are writing the same file at the same time?

'll need a little more information before I can help. Thanks for the report.

**Comment by gulabbisht** [comment]
I have a REST endpoint that got this command to generate the pdf file. On hitting the endpoint one at a time or even multiple times within the short time frame everything is okay.

But in the load testing scenario, I'm hitting the endpoint 50 times within 5 seconds. And this causes the above-mentioned scenario. In my case, I need to generate the pdf dynamically.

And I'm not able to reproduce this on single command run.

**Comment by jberkenbilt** [comment]
Thanks for the update. I don't think there's much chance that this could be a qpdf issue. This is probably  a problem with your system that you have exposed by wisely doing load testing. You could probably troubleshoot this by eliminating qpdf entirely and just having your service temporarily not do the watermark at all to make sure your underlying system isn't generating bad files, or you could use qpdf is some kind of passthrough mode where it just rewrites the file without adding watermarks. But qpdf is stateless between runs and wouldn't have any kind of bug that would cause it to behave differently when invoked multiple times in a short period. Any qpdf's test suite runs qpdf much more than 10 times a second on multiple platforms with every build.

I'd take a hard look at your file management to make sure there aren't clashes. If you had two instances of qpdf simultaneously processing input files with the same name and some external process was modifying the input file while qpdf was reading it, it's likely that you could see corruption of this type. Especially if both qpdf instances were writing to separate locations, the output files would be valid PDF but would reflect the damaged input. My best guess is that something like this is going on. Maybe under load you have a situation where your system is invoking qpdf before a previous invocation is finished, and they are using the same files. qpdf doesn't write any temporary files except when run in the `--replace-input` option, so there's nothing about qpdf that prevents you from running it in parallel as long as you don't try to write to the same file in multiple places or read a file that is changing while you read it.

I'm going to go ahead and close this, but feel free to ask additional questions or reopen if you somehow discover a bug you can reliably reproduce by running qpdf on a stable input file. Thanks!
