### ISSUE TITLE
qpdf in WebAssembly

### ISSUE THREAD

**Issue by iamtekeste** [qpdf/qpdf#394]
Hi there, first of all, I would like to say thank you for this amazing tool!
I am thinking of creating a PDF optimizer that works on the browser by compiling qpdf into a [wasm](https://webassembly.org/) file.

In order to reduce the file size of the generated file, I would only like to compile the optimization(linearization) and page splitting features only.

How do I go about extracting the c plus plus files related to those features and ignore/remove the other features?

Thank you again! Sorry if it is a dumb question I am a web developer with barely any CPP experience :)

**Comment by jberkenbilt** [comment]
Hello. I don't provide any way to compile qpdf with some features enabled and some features not enabled, nor do I have any intention of doing that. qpdf is not architected to support that kind of usage. Thanks for the kind words and the question. Sorry I can't help with this one.
