### ISSUE TITLE
No output produced with `qpdf input.pdf --pages . 17-30 -- ./output.pdf`

### ISSUE THREAD

**Issue by pibion** [qpdf/qpdf#396]
I'm trying to split a pdf with the command `qpdf input.pdf --pages . 17-30 -- output.pdf` but no output file is produced.

Is it possible I'm using the wrong command, or that the user guide is incorrect?

I have qpdf version 8.0.2 installed.

**Comment by jberkenbilt** [comment]
The `.` syntax to mean the current input file wasn't added until 8.4.0. For 8.0.2, you'll need to say `qpdf input.pdf --pages input.pdf 17-13 -- output.pdf`.

**Comment by jberkenbilt** [comment]
I'll go ahead and close this, but feel free to reopen if you need further assistance. Thanks!
