### ISSUE TITLE
How to hard copy a pdf page onto the same file?

### ISSUE THREAD

**Issue by RuthgerD** [qpdf/qpdf#399]
Example command:
`qpdf some_pdf.pdf --replace-input  --pages . 1-z,z --`
Does what it advertises, it appends/copies the last page onto itself.
I have a very particular use case where I need qpdf to "hard copy" the page instead of what now happens where it just adds a page entry pointing to the same obj:
`32 0 obj
<< /Contents 76 0 R /MediaBox [ 0 0 595 842 ] /Parent 2 0 R /Resources << /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ] /XObject << /Xf22 77 0 R >> >> /Type /Page >>
endobj
33 0 obj
<< /Contents 76 0 R /MediaBox [ 0 0 595 842 ] /Parent 2 0 R /Resources << /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ] /XObject << /Xf22 77 0 R >> >> /Type /Page >>
endobj`
As you can see `<< /Xf22 77 0 R >>` is duplicated.
While I get that it's done for performance reasons I'd like an option to disable this behavior so that it copies / clones a page uniquely. 
Im not well versed in pdf terms so forgive me for using the wrong naming.

**Comment by jberkenbilt** [comment]
You can do a little trick and refer to the same file by a different name, like this:

```
qpdf some_pdf.pdf --replace-input --pages . 1-z ./some_file.pdf z --
```

qpdf explicitly doesn't consider it the same file if the name is specified in a different way. That feature exists to handle this type of case. I'll make sure the docs are clear and the test suite includes a case to ensure this never breaks For a long time, this was the only way to add a page from a given file more than once.

**Comment by RuthgerD** [comment]
I see that works!
Thanks for the swift reply.
