### ISSUE TITLE
Acquire Cryptographic Context fails on fresh windows install

### ISSUE THREAD

**Issue by michalrames** [qpdf/qpdf#40]
Call to ```CryptAcquireContext``` in SecureRandomDataProvider fails when using qpdf 5.1.2 with ```--encrypt``` option in a fresh windows install. This probably doesn't present itself once some user keys have been created in `C:\Users\<user>\AppData\Roaming\Microsoft\Crypto\RSA`.

This fixed it for me:

```C++
if (!CryptAcquireContext(&crypt_prov, 
                         "Container", 
                         NULL, 
                         PROV_RSA_FULL, 
                         0))
{
    if (GetLastError() == NTE_BAD_KEYSET)
    {
        if (!CryptAcquireContext(&crypt_prov, 
                                 "Container", 
                                 NULL, 
                                 PROV_RSA_FULL, 
                                 CRYPT_NEWKEYSET))
        {
            throw std::runtime_error("unable to acquire crypt context with new keyset");
        }
    } else {
		throw std::runtime_error("unable to acquire crypt context");
	}
}
```

**Comment by jberkenbilt** [comment]
Sorry I never replied to this. Thanks for reporting. I'm hoping to get a 5.1.3 release out one of these days with a handful of bug fixes. I'll be sure to include this when I do.

**Comment by jberkenbilt** [comment]
This will be in 5.1.3 which I will release momentarily.

**Comment by jberkenbilt** [comment]
5.1.3 is released.

**Comment by spsoofbaf** [comment]
Hi, this error exists in version 5.1.3 when i try use qpdf with an Asp.Net application in windows server 2008 r2. Also when i try qpdf in a windows application or in command prompt in windows server, it works fine.
