### ISSUE TITLE
qpdf fails with "getStreamData called on unfilterable stream" when opening metadata of this PDF

### ISSUE THREAD

**Issue by allan-simon** [qpdf/qpdf#402]
When trying to open the metadata of this file https://github.com/allan-simon/example-of-failing-pdf/raw/master/AC0.pdf

I get the following error 

```
offset 168017): getStreamData called on unfilterable stream
```

Is there something I can do to help fixing the issue ?

(by the way thanks a lot for this library, it's really helping us a lot )

**Comment by jberkenbilt** [comment]
I'm glad qpdf is helping you. Thanks for providing that feedback -- it's always good to hear.

I'm afraid there's nothing qpdf or likely any other PDF software will be able to do for this file. All the data in the file is badly damaged. It looks to me like someone opened this file in a text editor without binary file support and then saved it, causing the editor to basically obliterate the data. The compressed data consists of lots of of repetitions of the hex codes EF, BF, BD which happens to be the UTF-8 encoding for the Unicode codepoint U+FFFD, which is the "invalid character" replacement code, often rendered as � or similar. Many repetitions of the same code like that would never appear in compressed data, and the fact that it's U+FFFD is a smoking gun. Basically someone loaded the file into a text editor in an attempt to edit some value, and saved. The text editor was unable to decode the original binary data as Unicode text, and so replaced all the characters that it couldn't recognize with U+FFFD, and saved the file with UTF-8 encoding, thus obliterating all the original data.

I'm going to close this issue, but feel free to follow up if you have any additional questions.

**Comment by allan-simon** [comment]
oh sorry to have made you lost time on this bug report, yes indeed, after further investigation that exactly what happened and I was like "hmmm maybe it's one of those pdf that can only be opened with adobe"

**Comment by jberkenbilt** [comment]
No worries. I only spent about 10 minutes on it, and I like a good puzzle. :-)
