### ISSUE TITLE
Error code 3 after trying to linearize a PDF

### ISSUE THREAD

**Issue by j75** [qpdf/qpdf#407]
Hello,

I found the following issue when trying to linearise the PDF I have downloaded from https://cs.brown.edu/courses/cs227/archives/2012/papers/newsql/hstore-endofera.pdf
```
% qpdf-9.1.1-x86_64.AppImage --linearize /tmp/hstore-endofera.pdf /tmp/pula.pdf

WARNING: /tmp/hstore-endofera.pdf (object 12 0): object has offset 0
qpdf: operation succeeded with warnings; resulting file may have some problems
```
Is this a known problem, are there any solutions to it?

**Comment by jberkenbilt** [comment]
I'll take a look. Can I assume this is the thing you sent me email through sourceforge about? If so, I will disregard that email and use this instead. This is the correct place to create issues. Thanks!

Most likely, there is no problem here. qpdf detects and warns about a number of conditions that a number of other packages silently ignore. There's probably a slight problem with the file but most likely qpdf can work around it safely. However, I will take a look at this particular file and see if I can shed some more light. Thanks for the report.

**Comment by j75** [comment]
> Can I assume this is the thing you sent me email through sourceforge about

Yes, that was me (I found later the github reference on that site).

>Most likely, there is no problem here. qpdf detects and warns about a number of conditions that a >number of other packages silently ignore.

Anyhow, an older **qpdf** version (such as **8.0.2**) is silent at that point... should I presume that the newer one has an improvement and that file is somehow corrupted and older **qpdf** versions did not detect that?

**Comment by jberkenbilt** [comment]
Yes, no problem here. I have confirmed that 8.0.2 is silent about this but produces identical output to 9.1.1 and current master. I'm not exactly sure why 8.0.2 didn't issue the warning, but I can confirm that you are seeing normal behavior of qpdf reporting a warning that it encounters during processing of the file. Thanks for taking the time to report the issue. It's always best to be sure!
