### ISSUE TITLE
object 84/0: error reading object: overflow/underflow converting 177668849846246633066255978 to 64-bit integer

### ISSUE THREAD

**Issue by juergen852** [qpdf/qpdf#408]
Using qpdf version 8.0.2 on Ubuntu 18.04 i get the following error message:

qpdf --empty --pages input.pdf 1,2,3,4,5 -- output.pdf
WARNING: input.pdf: object 84/0: error reading object: overflow/underflow converting 177668849846246633066255978 to 64-bit integer
WARNING: object 84 0: operation for dictionary attempted on object of type null: returning null for attempted key retrieval
WARNING: object 84 0: operation for dictionary attempted on object of type null: returning false for a key containment request
WARNING: object 84 0: operation for dictionary attempted on object of type null: returning null for attempted key retrieval
WARNING: object 84 0 -> null returned from getting key /Type from non-Dictionary: operation for name attempted on object of type null: returning dummy name
input.pdf (object 18 0, offset 639747): invalid Type /QPDFFakeName in page tree

Using Evince I can open the document without problems.
PDF was created with PDF Architect 4 in Format PDF-1.7, non optimized, no security.

**Comment by juergen852** [comment]
Just compiled and tired with qpdf version 9.1.1
Seems to result in same error.

qpdf --empty --pages in.pdf 1,3,4,5 -- out.pdf
WARNING: in.pdf: object 84/0: error reading object: overflow/underflow converting 177668849846246633066255978 to 64-bit integer
WARNING: object 84 0: operation for dictionary attempted on object of type null: returning false for a key containment request
WARNING: object 84 0: operation for dictionary attempted on object of type null: returning null for attempted key retrieval
WARNING: in.pdf (page tree node, offset 639747): /Type key should be /Page but is not; overriding
WARNING: object 84 0: operation for dictionary attempted on object of type null: ignoring key replacement request
qpdf: parsing numeric range for in.pdf: error in numeric range 1,3,4,5: number 3 out of range

**Comment by jakemauer** [comment]
Just wanted to chime in that I'm getting this error when attempting to ingest PDFs created/downloaded via AirMail.app on a Mac into paperless-ngx which utilizes qpdf.

**Comment by jberkenbilt** [comment]
I would need a sample file to be able to do anything with this.

**Comment by jakemauer** [comment]
@jberkenbilt Absolutely. Is there a way I can send you the failing PDF through another channel? It contains private info that I don't want to post to Github.

**Comment by jakemauer** [comment]
[failing-pdf.pdf](https://github.com/qpdf/qpdf/files/13430126/failing-pdf.pdf)
I take that back I was able to reproduce it with a dummy pdf.

The process to reproduce for me is view an email in AirMail, open the print dialog, click PDF and save as a PDF.

**Comment by jberkenbilt** [comment]
Thanks -- tagging with `next` so I remember to study this next time I work on qpdf.

**Comment by jberkenbilt** [comment]
The attached file doesn't have this error. I think I'm not going to do anything about this. As far as I can tell, qpdf is correctly handling an error in a broken PDF. I'm going to close this, but if someone can find a reliable way to reproduce it, e.g., a specific file and a specific command run with the latest version of qpdf, then please feel free to reopen or create a separate issue. Thanks.
