### ISSUE TITLE
boringssl crypto provider

### ISSUE THREAD

**Issue by deanscarff** [qpdf/qpdf#417]
BoringSSL is Google's fork of openssl, see: https://boringssl.googlesource.com/boringssl/

I've implemented a QPDFCryptoProvider_openssl based on boringssl, I expect it will also be compatible with openssl.  I can send a PR if you're interested in merging it in.

**Comment by jberkenbilt** [comment]
No promises, but I'd be interested in taking a look.

**Comment by jberkenbilt** [comment]
...and merging it in if it looks good. :-) I'm working on 10.0.0 now, but it's probably too late to make it in for that release.
