### ISSUE TITLE
QPDF() is not deterministic

### ISSUE THREAD

**Issue by deanscarff** [qpdf/qpdf#419]
In b8bdef0a, support was added to QPDFWriter for deterministic IDs.  However, 7588cac2 added code into the QPDF ctor that initializes m->unique_id using the time mixed with RNG data.  Admittedly, the non-determinism isn't exposed in the output except in the (unlikely) case of a collision.

Some solutions, none of them great:

- static counter of some sort (caller would need to guarantee thread-safety)
- callback of some sort (again, caller needs to guarantee thread-safety, but better for qpdf not having mutable static state.  Callbacks also add a lot of complexity to the API)
- content hash like QPDFWriter?  (I don't think this works, but just throwing it out there in case I'm wrong)

If this isn't a use case you're concerned about, I won't be offended if you close this issue.  However, if you are interested in a solution, I'm happy to take a stab at the implementation.

**Comment by jberkenbilt** [comment]
Thanks for bringing this up. My inclination is to not care because, as you point out, this is not exposed in the output. Other than noticing the fact that QPDF has non-deterministic internal state, are you aware of a case where this matters in some way? If so, please let know since I don't want to dismiss this concern prematurely. Otherwise, I will probably just close this because I don't think it actually matters. I would point out that the code that the unique ID code replaced was using pointers, which are worse in all possible ways and which are recycled throughout the life of the system. Thanks!

**Comment by deanscarff** [comment]
I haven't observed a case where this matters in any (concerning) way, I just happened to notice the extra syscalls when comparing versions (which are a small inconvenience when auditing, and also a small performance overhead).

Theoretically though, with the current implementation, you will start seeing collisions if you're generating IDs many times a second: the 32 high order bits from `time()` are identical, and the 32 low order bits have =~ 1 - exp(-k(k-1)/(2^33)) probability of collision.  This starts being plausible generating around 1000/s (about 0.012% probability of collision each second you're running).  Admittedly this is unrealistic for most users, CPUs and PDFs.
Maths: https://en.wikipedia.org/wiki/Birthday_problem#Approximations

However, a simple fix that reduces collision chances is ditching the low-entropy time() call and getting a full 64 bits from `QUtil::random()`.  Conveniently for me, this would also make the syscall go away ;)

**Comment by deanscarff** [comment]
A good solution (IMO): use C++11's `std::atomic<unsigned long long>::fetch_add()`.  This is thread safe, doesn't add API complexity, but it may add portability issues depending on the platform.

**Comment by deanscarff** [comment]
I think the above PR is a good solution - it is deterministic (doesn't rely on time or random) and doesn't complicate the API (by putting thread safety constraints on the caller).  The main concern might be the portability, though std::atomic<unsigned long long> is part of C++11.

**Comment by jberkenbilt** [comment]
Since 9.1.0, qpdf requires a c++-11 compiler, and the use of thread-safe static initialization was the thing that forced me to finally take the leap. I agree that your solution is the best one and is an improvement over the previous code. :-)
