### ISSUE TITLE
'--show-xref' under specific circumstances returns wrong info

### ISSUE THREAD

**Issue by KurtPfeifle** [qpdf/qpdf#42]
I've stumbled across a small glitch when checking PDF files with `qpdf --show-xref`.

Here is a handwritten PDF file to demonstrate the problem:

```
%PDF-1.1

1 0 obj
<</Kids[2 0 R]/Count 1/Type/Pages>>
endobj

2 0 obj
<</Parent 1 0 R/Resources 3 0 R/MediaBox[0 0 595 842]/Contents[4 0 R]/Type/Page>>
endobj

3 0 obj
<</Font<</F1<</Type/Font/Subtype/Type1/BaseFont/Times-Italic>> >> >>
endobj

4 0 obj
<</Length  80>>
stream
   1    0    0    1    60    780    cm
BT
  /F1 48 Tf
  (Hello, TROOPERS!)Tj
ET
endstream
endobj


% here is a comment


5 0 obj
<</Pages 1 0 R/Type/Catalog>>
endobj

xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000062 00000 n 
0000000169 00000 n 
0000000245 00000 n 
0000000374 00000 n 
trailer

<</Root 5 0 R/Size 6>>
startxref
4530
%%EOF
```

<sub>(Be careful if you copy'n'paste this example from this page to use the correct EOL convention, and to have the trailing blanks in the `xref`-table included, otherwise it will become invalid for other reasons than the ones I constructed into it!)</sub>

This file has two wrong entries:
1. the `startxref` value should be `453` (not `4530`).
2. the fifth object's offset should be `407` (not `374`).
## Running `qpdf --show-xref` against the above file

When running `qpdf --show-xref` against this file, this is the (expected) result:

```
WARNING: qpdf--show-xref-is-wrong.pdf: file is damaged
WARNING: qpdf--show-xref-is-wrong.pdf (file position 4430): xref not found
WARNING: qpdf--show-xref-is-wrong.pdf: Attempting to reconstruct cross-reference table
1/0: uncompressed; offset = 10
2/0: uncompressed; offset = 62
3/0: uncompressed; offset = 160
4/0: uncompressed; offset = 245
5/0: uncompressed; offset = 407
qpdf: operation succeeded with warnings; resulting file may have some problems
```

So `qpdf`... 
1. ...discovers and reports the wrong `startxref` value;
2. ...determines and reports the correct byte offset (`407`) for object no. 5.

Now change the `startxref` value to the correct `453` one:

```
xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000062 00000 n 
0000000169 00000 n 
0000000245 00000 n 
0000000374 00000 n 
trailer

<</Root 5 0 R/Size 6>>
startxref
453
%%EOF
```
## Running `qpdf --show-xref` against the modified file (with correct `startxref`)

When running `qpdf --show-xref` against the modified file (correct `startxref`, incorrect fifth object's byte offset entry) this is the (unexpected) result:

```
1/0: uncompressed; offset = 10
2/0: uncompressed; offset = 62
3/0: uncompressed; offset = 169
4/0: uncompressed; offset = 245
5/0: uncompressed; offset = 374
```

So `qpdf`...
- ...no longer discovers the incorrect fifth object's byte offset entry and reports just what's in the existing `xref` table.

You can also put `373`, `375`, `404`, `404` or `406` into the `xref` for object no. 5 and `qpdf` will not discover the wrong entry.

This is probably caused by added empty and comment lines in between objects no. 4 and 5.

If you put any value that is in the range of `376..404` into the `xref` for object no. 5 then `qpdf` will report the wrong entry:

```
WARNING: qpdf--show-xref-is-wrong.pdf: file is damaged
WARNING: qpdf--show-xref-is-wrong.pdf (object 5 0, file position 390): expected n n obj
WARNING: qpdf--show-xref-is-wrong.pdf: Attempting to reconstruct cross-reference table
1/0: uncompressed; offset = 10
2/0: uncompressed; offset = 62
3/0: uncompressed; offset = 160
4/0: uncompressed; offset = 245
5/0: uncompressed; offset = 407
qpdf: operation succeeded with warnings; resulting file may have some problems
```

or

```
WARNING: qpdf--show-xref-is-wrong.pdf (object 5 0, file position 409): expected endobj
operation for Dictionary object attempted on object of wrong type
```

<sub>(Note the two different types of error messages depending on the actual wrong value you insert into the `xref` table)</sub>

This is probably caused by the fact that when it checks the byte offsets `376..404` it's inside the commented line an the next byte doesn't look at all like the start of an object.

_Also, I noticed that in many cases an *off-by-one_ deviation from the correct value is not reported: whenever the offset byte is identical with an EOL character. It may be "tolerable" and it may be what all PDF readers out there may be tolerant of -- but strictly speaking: is it correct?\* 

---

For now I work around this glitch like this:

Whenever I want to let `QPDF` check, compute and report the complete `xref` table, I make sure to insert a wrong `startxref` entry into the file first (or comment out the line with the correct value).

**Comment by wmbutler** [comment]
Is there a way to suppress this behavior, or just ignore the error? We are experiencing the same error, but the files appear to open just fine in a typical PDF viewer. We are using qpdf to check for (blank) password protected documents for further processing.

**Comment by jberkenbilt** [comment]
@KurtPfeifle Sorry for the long delay in acknowledging this. I've been really short on time to look at qpdf issues. qpdf's recovery logic doesn't try to recover stuff until it needs to. --show-xref just dumps whatever is in the xref table. If it has mistakes, it won't find them. If it can't find the xref table, it will try to reconstruct it, which is what you're seeing. If you ran some operation like `qpdf --check`, it would try to access every object and may eventually need to recompute the whole xref table even if the initial offset was correct. I don't think there's anyway to force qpdf to dump the xref table from the command-line after reading the file, but it wouldn't be hard to code in C++ using the API. You could check the source to qpdf.cc to see how `--show-xref` works. Your workaround will achieve the desired effect. For what it's worth, I don't consider this to be a glitch. It's intended behavior -- qpdf tries very hard not to do anything it doesn't have to do. This makes it fast and also makes it better able to be used as a manual tool for repairing broken PDFs. Though your use case seems like a valid one, so it might be useful to add the ability to force qpdf to dump the computed xref table after checking a file. That would be a relatively straightforward feature to add if I ever have a good block of time to implement it.

@wmbutler Regarding suppressing this behavior, you can give a flag to qpdf to suppress warning messages, or you can note that qpdf exits with status 3 if there are warnings but no fatal errors.

**Comment by jberkenbilt** [comment]
I have coded a simple fix to this. In 7.0.0, you can run `qpdf --check --show-xref file.pdf`. qpdf will first run `--check`, which result in the xref table being recomputed. Then the show-xref will be applied to the corrected xref table.
