### ISSUE TITLE
Method for disabling rpath when building RPM?

### ISSUE THREAD

**Issue by edrozenberg** [qpdf/qpdf#422]
When trying to build an RPM, I'm seeing the following errors related to `rpath`:

```
ERROR   0001: file '/usr/bin/qpdf' contains a standard rpath '/usr/lib64' in [/usr/lib64]
ERROR   0001: file '/usr/bin/zlib-flate' contains a standard rpath '/usr/lib64' in [/usr/lib64]
ERROR   0001: file '/usr/bin/fix-qdf' contains a standard rpath '/usr/lib64' in [/usr/lib64]
```

One suggestion is to pass `--disable-rpath` to `configure`, but this option is not available for the qpdf `configure` script:
```
configure: WARNING: unrecognized options: --disable-rpath
```

My fallback option is to tell the RPM build to proceed anyway via something like:
```
$ QA_RPATHS=$[ 0x0001|0x0010 ] rpmbuild my-package.src.rpm
```

but would prefer if there is some way to disable the use of `rpath` since that seems like the most "correct" solution.

**Comment by jberkenbilt** [comment]
I'm not doing anything explicitly to get rpath in there, so I don't know how to prevent it from getting in there. I would have to do some research and digging. If this is a known, standard problem, maybe someone can shed some light. Can you provide a little more information as to what you're doing? Does the standard qpdf rpm have this problem? Are you doing this officially for a RedHat-like release, or are you just building it on your own? Thanks.

**Comment by edrozenberg** [comment]
@jberkenbilt I'm building my own RPM under CentOS 7.7 using a standard approach documented in articles such as:

https://tecadmin.net/create-rpm-of-your-own-script-in-centosredhat/
https://www.techrepublic.com/article/making-rpms-part-4-finishing-the-spec-file
https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_syntax

RedHat's documentation on rpath:
https://fedoraproject.org/wiki/RPath_Packaging_Draft

In this article they say:

> **Beware of Rpath**
> Sometimes, code will hardcode specific library paths when linking binaries (using the -rpath or -R flag). This is commonly referred to as an rpath. Normally, the dynamic linker and loader (ld.so) resolve the executable's dependencies on shared libraries and load what is required. However, when -rpath or -R is used, the location information is then hardcoded into the binary and is examined by ld.so in the beginning of the execution. Since the Linux dynamic linker is usually smarter than a hardcoded path, we usually do not permit the use of rpath in Fedora.
> 

The RPM .spec file I'm using to build the RPM is attached.

Thanks.

[qpdf.spec.gz](https://github.com/qpdf/qpdf/files/4434975/qpdf.spec.gz)

**Comment by edrozenberg** [comment]
I was able to build the RPM successfully using the workaround:
```
$ QA_RPATHS=$[ 0x0001|0x0010 ] rpmbuild my-package.src.rpm```

which tells rpmbuild to ignore/allow the use of `rpath` and proceed anyway.

**Comment by jberkenbilt** [comment]
I just realized that there is an -rpath being passed in not when linking executables but when linking the shared library. Maybe that's causing the problem. I'll look at this more closely before the next qpdf release.

**Comment by edrozenberg** [comment]
@jberkenbilt Thanks for looking into that. I ran into the same issue with another package and the same workaround QA_RPATHS worked there as well, so I'll be sure to bookmark this workaround.

**Comment by jberkenbilt** [comment]
@edrozenberg I added `--disable-rpath` on master. If you feel like testing it out, that would be great; feel free to comment here. This will be in 10.0.2 or 10.1.0 or whatever is next.
