### ISSUE TITLE
error: undefined symbol: vtable for QPDFObject

### ISSUE THREAD

**Issue by wenheping** [qpdf/qpdf#424]
I failed build qpdf-10 on FreeBSD-current with clang++8, the last lines of build log is :

/bin/sh ./libtool --mode=link c++  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -fvisibility=hidden    -Wold-style-cast -Wall -Wconversion -Wsign-conversion  libtests/build/main_from_wmain.o -o libtests/build/main_from_wmain -Llibqpdf/build -fstack-protector-strong  -L/usr/local/lib -L/usr/local/lib -lqpdf -lz -ljpeg -L/usr/local/lib -lgnutls
/bin/sh ./libtool --mode=link c++  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -fvisibility=hidden    -Wold-style-cast -Wall -Wconversion -Wsign-conversion  libtests/build/matrix.o -o libtests/build/matrix -Llibqpdf/build -fstack-protector-strong  -L/usr/local/lib -L/usr/local/lib -lqpdf -lz -ljpeg -L/usr/local/lib -lgnutls
libtool: link: c++ -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -fvisibility=hidden -Wold-style-cast -Wall -Wconversion -Wsign-conversion libtests/build/json.o -o libtests/build/.libs/json -fstack-protector-strong  -Llibqpdf/build -L/usr/local/lib /usr/ports/print/qpdf/work/qpdf-10.0.0/libqpdf/build/.libs/libqpdf.so -lz -ljpeg -lgnutls -Wl,-rpath -Wl,/usr/local/lib
ld: error: undefined symbol: vtable for QPDFObject
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(main)
>>> referenced by json.cc
>>>               libtests/build/json.o:(test_main())
>>> referenced by json.cc
>>>               libtests/build/json.o:(test_main())
>>> referenced 6 more times
the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [libtests/build.mk:52: libtests/build/json] Error 1
gmake[2]: *** Waiting for unfinished jobs....
libtool: link: c++ -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -fvisibility=hidden -Wold-style-cast -Wall -Wconversion -Wsign-conversion libtests/build/lzw.o -o libtests/build/.libs/lzw -fstack-protector-strong  -Llibqpdf/build -L/usr/local/lib /usr/ports/print/qpdf/work/qpdf-10.0.0/libqpdf/build/.libs/libqpdf.so -lz -ljpeg -lgnutls -Wl,-rpath -Wl,/usr/local/lib
libtool: link: c++ -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -fvisibility=hidden -Wold-style-cast -Wall -Wconversion -Wsign-conversion libtests/build/main_from_wmain.o -o libtests/build/.libs/main_from_wmain -fstack-protector-strong  -Llibqpdf/build -L/usr/local/lib /usr/ports/print/qpdf/work/qpdf-10.0.0/libqpdf/build/.libs/libqpdf.so -lz -ljpeg -lgnutls -Wl,-rpath -Wl,/usr/local/lib
libtool: link: c++ -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -fvisibility=hidden -Wold-style-cast -Wall -Wconversion -Wsign-conversion libtests/build/matrix.o -o libtests/build/.libs/matrix -fstack-protector-strong  -Llibqpdf/build -L/usr/local/lib /usr/ports/print/qpdf/work/qpdf-10.0.0/libqpdf/build/.libs/libqpdf.so -lz -ljpeg -lgnutls -Wl,-rpath -Wl,/usr/local/lib
ld: error: undefined symbol: vtable for QPDFObject
>>> referenced by matrix.cc
>>>               libtests/build/matrix.o:(main)
>>> referenced by matrix.cc
>>>               libtests/build/matrix.o:(main)
the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)
c++: error: linker command failed with exit code 1 (use -v to see invocation)

Any suggestion ?

**Comment by jberkenbilt** [comment]
Hmm. Somehow I missed this in my local testing. There's a missing QPDF_DLL_CLASS in QPDFObject.hh. I'll close this PR with a commit that fixes it. Let me give this a few days to shake out, and then I'll release 10.0.1 with the fix. Thanks for bringing this to my attention.

Annoyingly, building with clang is on my local checklist for release, but I had just built with clang a few days earlier, and CI builds with clang for MacOS, so I skipped it. :-( Never skip your own checklist items.
