### ISSUE TITLE
Issue migrating from QPDF 8.3 to 10.0.0/.1

### ISSUE THREAD

**Issue by drcdr** [qpdf/qpdf#427]
I'm upgrading from QPDF 8.3 to 10.0.0, and I'm having some problems (Windows10, MSVC).  I have a project that worked fine before, but when I compile and run with QPDF 10.0.1, it doesn't run.  I've also tried the simple example pdf-npages.cc, and I'm getting the same error in the same place.

The problem starts at
`std::vector<QPDFPageObjectHelper> pages = QPDFPageDocumentHelper(pdf).getAllPages();`

In the debugger, stepping into this immediately goes to PointerHolder.hh, to 
`virtual ~QPDFPageDocumentHelper()`, and then to 
`~PointerHolder()`, and then to line 176,
 `if (gone) { delete this->data; }` 

When running from the command line, I get a debug assertion that failed in `minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp, Expression: _CrtlsValidHeapPointer(block).`

Any idea what's going on?  I've tried many different MSVC settings (SDK version, platform toolset, language standards), but can't get any different behavior.  I've read through the release notes, and don't see any breaking changes.

-> I just now tried 10.0.1; same problem.

**Comment by drcdr** [comment]
I should have mentioned, I'm using binaries in `qpdf-10.0.1-bin-msvc64.zip`, I'm not building from source.

**Comment by drcdr** [comment]
OK, I've made progress.  I had to clean up some DLL's and paths.  Once I did that I noticed that my Release build now works, but my Debug build does not -- for both 8.3 and 10.0.1.  Looking at my Release build settings (e.g. no optimization), I must have had that problem before as well.  Maybe this is because the Debug DLLs are not in the bin directory?

**Comment by jberkenbilt** [comment]
You seem to be on this trail, but I think your most likely issue here is a mixture of headers and/or DLLs from the two different versions. Different major versions of qpdf are not binary compatible, so if you were compiling with headers from one version and linking against DLLs from another version, you would get this kind of problem. You should make sure you've got all your old versions of qpdf out of the way and see if you have better success.

**Comment by drcdr** [comment]
Thanks for your input.   I've cleaned all other versions now, but still can't get Debug working (again, I don't think it was working before, either).  Maybe when I get some time, I'll track that down, but I'll just work with Release for now.

**Comment by drcdr** [comment]
I tried again to get things to work in Debug mode and found out that my problem is essentially the same as #199.  I was able to get Debug mode to work OK by changing the Runtime Library option, from the Debug default [Multi-threaded Debug DLL (/MDd)] to the Release default [Multi-threaded DLL (/MD)].
