### ISSUE TITLE
[Feature request] Report correct `startxref` value when doing `-show-xref`

### ISSUE THREAD

**Issue by KurtPfeifle** [qpdf/qpdf#43]
I'd like to see a small feature added to QPDF:

When running `show-xref`, please let it report the (correct) value for the `startxref` entry.

Currently, if the `startxref` value is wrong, `qpdf` reports this:

```
(file position 155987): xref not found
WARNING: demo.pdf: Attempting to reconstruct cross-reference table
1/0: uncompressed; offset = 10
2/0: uncompressed; offset = 62
[....]
403/0: uncompressed; offset = 152245
404/0: uncompressed; offset = 155407
```

Couldn't `qpdf`, when it is computing all the objects' byte offsets also report/suggest a reasonable value for the/an `startxref` entry?  _(Yes, I'm aware of the fact that a damaged/buggy PDF may not contain any `xref` at all...)_

**Comment by jberkenbilt** [comment]
This is a good idea.

**Comment by jberkenbilt** [comment]
Actually, qpdf never attempts to find an xref. If it fails to find the xref in the usual way, it just reads through the file and attempts to reconstruct the xref. Even if there is an xref, qpdf doesn't know where it is. I thought it was a good idea, but it's not really possible the way qpdf is implemented.
