### ISSUE TITLE
Improve code security and check warnings raised by LGTM

### ISSUE THREAD

**Issue by digitalethics** [qpdf/qpdf#431]
Could you work towards resolving the warnings ([10 alerts](https://lgtm.com/projects/g/qpdf/qpdf/?mode=list)) raised by LGTM and improve the overall code security to reach A+?

**Comment by jberkenbilt** [comment]
Definitely -- these all look easy to fix and are good things to fix.

**Comment by jberkenbilt** [comment]
Is there any way I can retest this myself? Or will it just rerun against master?

**Comment by jberkenbilt** [comment]
I'm going to see if I can more tightly integrate qpdf with lgtm.com. I think I found out what I need to know.

**Comment by jberkenbilt** [comment]
@digitalethics Thank you for making me aware of this.

**Comment by digitalethics** [comment]
@jberkenbilt Thank you for responding and resolving this so quickly. Much appreciated!
