### ISSUE TITLE
missing extended graphic!: start dictionary gs0

### ISSUE THREAD

**Issue by dviklown** [qpdf/qpdf#435]
I get this error when trying to open a pdf

**Comment by jberkenbilt** [comment]
I need a lot more to go on if I am going to be able to provide any help, like what PDF you are using, what you have done using qpdf on the PDF to get to this state, and what version of qpdf you are using.

**Comment by dviklown** [comment]
I'm using qpdf notes v4.0. I have done nothing to the document but open it
from an attachment from an email. what other information do you need from
me? and how would I go about doing that? I'm using my phone for this, might
be part of the problem.

**Comment by jberkenbilt** [comment]
I have a feeling you are reporting an issue about the wrong software. There are other things called qpdf, but this one is a C++ library and command-line tool for manipulating PDF files. I think you want https://www.qoppa.com/android/pdfnotes/ instead.
