### ISSUE TITLE
[Feature request] Don't just warn about wrong stream length -- report the correct value too

### ISSUE THREAD

**Issue by KurtPfeifle** [qpdf/qpdf#44]
When checking a PDF with `qpdf --check a.pdf` QPDF rather reliably reports and warns about cases where the stream length is not correctly contained in the PDF code. Example:

```
qpdf --check 4pix.pdf
 checking 4pix.pdf
 PDF Version: 1.3
 File is not encrypted
 File is not linearized
 WARNING: 4pix.pdf (object 6 0, file position 1376): attempting to recover stream length
```

It even says _"attempting to recover stream length"_.  However, it does not tell the user which stream length it deems to be the correct one.

It would be nice if QPDF reported the correct stream length here.

**Comment by jberkenbilt** [comment]
Yes, agreed.
