### ISSUE TITLE
Concatenated objects from a content stream with a streamarray of length 4

### ISSUE THREAD

**Issue by drcdr** [qpdf/qpdf#444]
On a page of a certain file, the first object presented to handleObject() via parsePageContents() is a "q403", instead of two separate tokens "q" and "403".

The content stream tokens on the first part of the page are:
```
q403 0 0 691 0 0 cm
/Im Do
BT
/F1 4 Tf
1 0 0 1 50 5 Tm
0.70588 0.70588 0.70588 rg
(View publication stats) Tj
ET
BT
/F1 4 Tf
1 0 0 1 50 5 Tm
0.70588 0.70588 0.70588 rg
(View publication stats) Tj
ET
Q
```
Digging a little deeper, it appears that the content stream is a streamarray of length 4.  
[NOTE: Edited from initial post]
```
    "85 0 R": ["86 0 R","79 0 R","80 0 R","87 0 R"],
       "86 0 R": {"/Filter": "/FlateDecode","/Length": 9},
       "79 0 R": {"/Filter": "/FlateDecode","/Length": 29},
       "80 0 R": {"/Filter": "/FlateDecode","/Length": 82},
       "87 0 R": {"/Filter": "/FlateDecode","/Length": 9},
```
Decoded individually using `pipeContentStreams` on `streamarray.getArrayItem(n)`, the first stream decodes to "q", and the second decodes to "403 0 0 ...".  It appears they are concatenated without a space, and then the tokenizer presents "q403" as the first token to handleObject().

Unfortunately, I can't post the file.  If I find another example, I'll post that if I can.  (Is there a way I can use the qpdf CLI tool to dump the raw portion of 86, 79, 80, and 87?)

**Comment by jberkenbilt** [comment]
No need to post a sample -- your description is clear, and your analysis sounds correct. I think the file is incorrect, but I will double check the spec and see if qpdf is making a mistake. I'm pretty sure the PDF spec allows content streams to be split mid token as some writers may split content streams at byte boundaries, but I will double check and see if qpdf should be adding a space. Regarding why this works with other viewers, my guess is that the must have some special case code around this. Certainly if you were tokenizing as you went and had knowledge of the semantics of the content stream, you could do this more intelligently. qpdf, at least for now, in this part of the code, is just looking at the content streams as streams of bytes. I'll give some thought as to how to handle this in either the case of qpdf being correct or not. For example, maybe qpdf could have an option to add spaces when concatenating content streams that would be useful for manually repairing broken files. No promises -- I'll check the spec and see.

To answer your question, you can use `qpdf --show-object=86 --filtered-stream-data` or `qpdf --show-object=86 --raw-stream-data` to see the stream data, and `qpdf --show-object=86` to see the stream dictionary. I'm happy to see that you used json mode.

**Comment by drcdr** [comment]
OK, thanks Jay.  For completeness, the object dumps are:
```
> qpdf --show-object=86 --filtered-stream-data x.pdf
q
> qpdf --show-object=79 --filtered-stream-data x.pdf
403 0 0 691 0 0 cm
/Im Do

> qpdf --show-object=80 --filtered-stream-data x.pdf
BT
/F1 4 Tf
1 0 0 1 50 5 Tm
0.70588 0.70588 0.70588 rg
(View publication stats) Tj
ET
BT
/F1 4 Tf
1 0 0 1 50 5 Tm
0.70588 0.70588 0.70588 rg
(View publication stats) Tj
ET

> qpdf --show-object=87 --filtered-stream-data x.pdf
Q
```
I absolutely love `qpdf --json`, I couldn't live without it right now!

**Comment by drcdr** [comment]
Well, this is getting a little stranger.  I thought I'd found a file where the streams are split mid-token, like you suggested above.  But...I think it's only one content stream.  The file is [here](https://www.genetics.org/content/genetics/156/3/1403.full.pdf).

Page 1 contents from the JSON dump are:
```
Pages: 
"10 0 R":  {"/Count": 8,  "/Kids": ["1 0 R", "11 0 R", "16 0 R", "20 0 R", "24 0 R", "27 0 R", "30 0 R", "33 0 R"], "/MediaBox": [ 0,  0,  612,  792 ],  "/Type": "/Pages"},
Page 1:
"1 0 R":  {"/Contents": "2 0 R", "/CropBox": [ 0,  9,  603,  792 ],  "/Parent": "10 0 R", "/Resources": "3 0 R", "/Type": "/Page" },
Page 1 Contents: 
"2 0 R":  {"/Filter": "/LZWDecode", "/Length": 5365 },
```
and the dump of the Contents object is
```
qpdf --show-object=2 --filtered-stream-data genetics_file.pdf
BT
/F4 1 Tf
6.964 0 0 6.976 55.709 756.842 Tm
0 0 0 1 k
BX /GS1 gs EX
0 Tc
(Copyright)Tj
/F11 1 Tf
4.6885 0 TD
...
```
All that is fine.  But, when I use `pipeContentStreams` to look at the data, it breaks the content into many 'streamlets'(?)  With a pipeline.write that looks like
```
void MyPipeline::write(unsigned char* data, size_t len) {
    m_data.append(data, data + len);
    m_icall++;
    //m_data.append(" ");  // for handling "q403", e.g..
    std::string s_data(data, data + len);
    printf("%03d) %s\n", m_icall, s_data.c_str());
}
```
I get
```
001) B
002) T
003)  
      
004) /
005) F
006) 4
007)  
008) 1
009)  
010) T
011) f
012)  
...
```

I'm confused as to why this happens, Can you shed any insight into what might be going on?

**Comment by jberkenbilt** [comment]
@drcdr I'm not sure what aspect of this concerns you. Is it the blank line after `003)`? If so, it's probably just that that token is a newline. Or is there something else you're concerned about?

**Comment by jberkenbilt** [comment]
According to the PDF spec (section 7.7.3.3, Page Objects), Content streams may be split only at boundaries between lexical tokens. This means that the way qpdf is handling content stream concatenation is incorrect. I will try to fix this in a minimally disruptive way, most likely by inserting a newline between streams only if there is not a delimiter character at the border of the streams. I will make sure this is fixed for the next qpdf release.

**Comment by drcdr** [comment]
> @drcdr I'm not sure what aspect of this concerns you. Is it the blank line after `003)`? If so, it's probably just that that token is a newline. Or is there something else you're concerned about?

Yeah, I wasn't too clear here.  Based on the original post, I thought about testing the idea that inserting a " " after each stream would solve the problem.  I tested this using pipeContentStreams and a MyPipeline::write, as shown above.  Since "85 0 R" was a streamarray of 4 streams, I thought I'd be adding 3 additional spaces.  This is indeed the case, and seems to be true...maybe 99% of the time.  And, it clears up the "q403" example shown above.

But for the file that I referenced yesterday, this approach fails in a catastrophic way.  Debugging it, I would have thought it would have worked; only one stream ("2 0 R"), so only one call to the MyPipeline::write, which would produce one extra " " at the end.

But that's not what happened.  This one PDF stream created 3808 calls to pipeline::write, often with just one character (as most of the cases shown above).  With m_data.append(" ") uncommented, the output now looks like:
```
B T
 / F 4   1   T f
 6 . 9 6 4  0   0  6. 9 7 6   5 5 . 7 0 9   7 5 6. 8 4 2  T m
 0  0 0  1   k
 B X   / G S 1  g s   E X
0  T c
 ( C o p y r i g h t ) T j ...
```
> According to the PDF spec (section 7.7.3.3, Page Objects), Content streams may be split only at boundaries between lexical tokens. This means that the way qpdf is handling content stream concatenation is incorrect. I will try to fix this in a minimally disruptive way, most likely by inserting a newline between streams only if there is not a delimiter character at the border of the streams. I will make sure this is fixed for the next qpdf release.

OK, thanks for looking into this.  I don't know if this would work or not, for the file I linked to yesterday.

**Comment by jberkenbilt** [comment]
@drcdr Thanks for the clarification. I will study the file you linked when I get a chance to put some time into this.

**Comment by jberkenbilt** [comment]
@drcdr The file you linked doesn't have multiple content streams. I'm betting you are unintentionally iterating through a string rather than a list because of using `auto` or something along those lines. Just double check your code and make sure you're getting what you think you're getting.

**Comment by drcdr** [comment]
Right, that's what makes this strange, maybe I'm doing something wrong with the Pipeline.  Here is a short program that recreates the issue.  I've tested my main program and this short program with other files also, both with a stream and a streamarray for /Contents, without a problem.
```
#include <iostream>
#include <qpdf/QPDF.hh>
#include <qpdf/QPDFPageDocumentHelper.hh>
#include <qpdf/QUtil.hh>
#include <qpdf/QPDFObjectHandle.hh>
#include <qpdf/Pl_StdioFile.hh>

class MyPipeline : public Pipeline
{
public:
	std::string m_data;
	int m_icall = 0;
	MyPipeline(char const* identifier, Pipeline* next) : Pipeline(identifier, next) {}
	~MyPipeline() {}
	void write(unsigned char* data, size_t len)
	{
		m_data.append(data, data + len);
		m_icall++;
		//m_data.append(" ");  // fix the "q403" error.
		std::string s_data(data, data + len);
		printf("%03d) %s\n", m_icall, s_data.c_str());
	}
	void finish() { }
};

// For pages.
void fastParseContentStreamArray(QPDFObjectHandle& streamarray)
{
	std::string desc = "test", all_desc = "test";
	MyPipeline* pipeline = new MyPipeline("id", 0);
	int tc = streamarray.getTypeCode();
	const char *tn = streamarray.getTypeName();
	streamarray.pipeContentStreams(pipeline, desc, all_desc);
	printf("Typecode = %d, typename=%s\n", tc, tn);
	
	pipeline->finish();
	delete pipeline;
}
int main()
{
	std::string filename = "IBD.pdf";
	QPDF pdf;
	pdf.processFile(filename.c_str());
	std::vector<QPDFPageObjectHelper> qpdfpages = QPDFPageDocumentHelper(pdf).getAllPages();

    QPDFObjectHandle streamorstreamarray = qpdfpages[0].getObjectHandle().getKey("/Contents");
	fastParseContentStreamArray(streamorstreamarray);
}
```
This program ends with
```
3803) 200                      
3804) 0                        
3805) \))                      
3806) ]TJ                      
                               
3807) E                        
3808) T                        
                               
Typecode = 10, typename=stream 
```

**Comment by jberkenbilt** [comment]
I'll have to take a closer look when I am more awake, but if you're just calling pipeContentStreams, there is no expectation that you will get strings passed to write that correspond in any way to tokens. The tokenizer is not invoked here. It is just sending a stream of bytes. More likely than not, the chunks of text you're getting are being flushed out by the deflate filter. If you want to see actual tokens, you will have to use one of the methods that invokes the tokenizer, and this is going to be slower even in the best case. I have a strong hunch that the tokenizer is performing poorly, and it is on my near-term list to improve its efficiency.

I feel like I recently posted a discussion about my intentions here. Let me see if I can find the issue. I'll tag you on it. I'm not in a place where I can easily look at the code, but there are methods that allow you to create a token filter, rather than a pipeline, which will have qpdf sending you a token at a time. Unfortunately the tokenizer spends a lot of time dealing with std::string. I haven't studied it yet, but I have a hunch that I can significantly improve the performance of that part of the code, and that's an important part of the code to improve. The tokenizer code is pretty old, and when I originally wrote qpdf, there was no support for running it over content streams. For parsing content streams, the performance is more important. I like the quote "premature optimization is the root of all evil," but I can say with confidence that this would not be premature optimization. Anyway, I have yet to really analyze it. I'm just going with my instincts here.

**Comment by jberkenbilt** [comment]
@drcdr Oh, I see the discussion about performance is on #442, which is also your issue. :-)

**Comment by drcdr** [comment]
Here, I'm expecting that ::write() would be called with all of the bytes from the stream at one time, not with any tokens.  So, e.g.: 
1) single stream in /Contents, one call to write; 
2) streamarray of length 4 in /Contents, 4 calls to ::write().  
I'm expecting that the tokenizer would not come into play for the pipeline and ::write() - as you mention above - but let me know if I'm missing something.

99% of the time, I see that (1) and (2) are true.  For this file (and some others), ::write() is being called with....short characters strings, not even tokens.  It's quite strange. Maybe there is something going on with the deflate filter, but I'm not in a good position to look into this path, I'm running with binaries.

OK, thanks for looking at this and for the explanation.

**Comment by jberkenbilt** [comment]
There are no guarantees about how many calls to write there are. It's completely a function of which filters are used and how the pipelines for those filters behave. This file appears to be using `/LZWDecode` on its streams. I guess the `LZWDecode` pipeline in qpdf writes downstream in small chunks, or maybe it's a function of the data itself -- it's been a long time since I wrote that code. All the pipelines I've written, which includes all the ones in qpdf, write data downstream as soon as they have it available. I don't want the amount of memory to grow with the number of pipelines. If you need the whole thing at once, you pass an instance of `Pl_Buffer` to `filterPageContents` and then retrieve the memory from the buffer, or you could call `QPDFObjectHandle::getStreamData` on each stream to get a buffer that way.

Is all this an effort to work around poor lexer performance in some way, or is there some other goal?

**Comment by drcdr** [comment]
Thanks, this helped a lot.  I didn't quite understand the difference between the pipeline and `getStreamData`, but now I do.

> According to the PDF spec (section 7.7.3.3, Page Objects), Content streams may be split only at boundaries between lexical tokens. This means that the way qpdf is handling content stream concatenation is incorrect. I will try to fix this in a minimally disruptive way, most likely by inserting a newline between streams only if there is not a delimiter character at the border of the streams. I will make sure this is fixed for the next qpdf release.

I think this will work fine, from what I'm now seeing. 

> Is all this an effort to work around poor lexer performance in some way, or is there some other goal?

That's a thought but seems like it would be a big effort; here I was focused on trying to validate the fix (like you proposed, but I was adding " "), looking for potential problems.

**Comment by jberkenbilt** [comment]
I'm going to try to carve out some time soon to push up a release with a fix to the space problem and any other actual bugs that have been found. I'm unsure whether it will be 10.1 or 10.0.2. Then, next time I get a chunk of time, I'm going to look at lexer performance. Thanks for your help in identifying the problem and for the clarity of your report.

**Comment by jberkenbilt** [comment]
@drcdr I've finally fixed this. I will push to master after CI has passed. Feel free to retest. I hope to get this out into 10.0.2 really soon.

**Comment by jberkenbilt** [comment]
@drcdr You'll know when it's in master when this ticket closes. :-)

**Comment by drcdr** [comment]
OK, thanks Jay, I plan to test/move to 10.0.2 soon!
