### ISSUE TITLE
QPDF should recognize edited QDF files

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#446]
If you create a qdf, edit it in a way that `fix-qdf` can still fix it, and run `qpdf --check` on it, qpdf will declare it corrupt. This is of course, correct, but I think it's worth remarking that the file is a %QDF-1.0 and and `fix-qdf` may be able to convert it to a normal PDF.

**Comment by jbarlow83** [comment]
Example file
[2.19.pdf](https://github.com/qpdf/qpdf/files/4788861/2.19.pdf)

**Comment by jberkenbilt** [comment]
Yeah, I'm well aware of this. Most likely, qpdf's recovery will succeed on any file that fix-qdf can fix, but I'm not absolutely 100% certain about this. But fix-qdf is completely lexical and does not use any of qpdf's internal lexical or parsing code. It's unlikely that I will ever fix this for the sake of fixing it, but I am planning on reworking some of the lexical stuff for performance, and maybe this will fall out of it. At one time, I actually had fixing this on qpdf's TODO, but I took it out.

**Comment by jberkenbilt** [comment]
I meant to say fix-qdf is completely *line-based* and does not use any of qpdf's internal lexical code.

**Comment by jbarlow83** [comment]
What I'm proposing is I think a fair bit simpler - just alerted the user if qpdf sees `%QDF-1.0` and suggest using `fix-qdf` first, as a hint to users that they should use fix-qdf and their file is not full of errors. Could be as simple as scanning for that literal in the first few lines of input.

Trying to fully repair a qdf, I agree, sounds like overkill.

**Comment by jberkenbilt** [comment]
Got it. I think that's a good suggestion.

**Comment by jberkenbilt** [comment]
I've given this some consideration and decided not to implement it. There are so many reasons why a qdf file might have errors that don't have anything to do with fix-qdf that I think this might be more of a distraction than anything else. I use qdf all the time to intentionally create files with errors for testing purposes. The only thing fix-qdf does is fix xref and stream lengths, and the parts of qpdf that know the details of the types of errors doesn't have any way to know it's a qdf file. In any case, thanks for the suggestion.
