### ISSUE TITLE
qpdf could allow strings to be treated as names

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#45]
Some broken pdf files have things like /Type (Page) instead of /Type /Page. It would be a small enhancement to allow qpdf to work with this. Perhaps qpdf could have a general mode in which it's more relaxed about "casting" from one type to another. See also https://bugs.launchpad.net/ubuntu/+source/qpdf/+bug/1397413

**Comment by KurtPfeifle** [comment]
Jay, if you "fix" that: please add a very, very clear and stark warning about the fact that the original PDF file is b0rken to the message output, will you?

**Comment by jberkenbilt** [comment]
Definitely. I already have some notes about having an aggressive recovery mode for qpdf that would be willing to do things like preserve streams that can't be decoded, skip over objects with lexical errors, etc. At the very least, this would generate warnings, and at most it would only be available in some kind of aggressive recovery mode.

**Comment by jberkenbilt** [comment]
This turns out to be pretty hard to fix. There are many places throughout the code that call getName() on name objects in a context from which it is not possible to issue a warning. I think I'm not going to fix this.

**Comment by jberkenbilt** [comment]
I'm going to make another change that should make qpdf not crash when it wants something to be a name that isn't a name, so probably the underlying issue will be resolved in a different way.
