### ISSUE TITLE
Extract outline (bookmarks) from PDF

### ISSUE THREAD

**Issue by mb720** [qpdf/qpdf#452]
Hi and thanks a lot for qpdf!

I'd like to extract the outline of a PDF with qpdf.

This¹ is what I've come up with:

    qpdf --json my.pdf | jq '.objects' | grep -Po 'Title": \K.*'

This works for my case, but includes the title of the PDF. Also, it's unstructured, meaning the hierarchy of the outline is lost.

Is there a better way to extract the outline from a PDF?

---

<sub>I've published this on [Stack Exchange](https://unix.stackexchange.com/questions/143886/how-to-extract-bookmarks-from-a-pdf-file/595722#595722)</sub>

**Comment by jberkenbilt** [comment]
Sorry for not replying. Take a look at pdf-bookmarks.cc from qpdf examples. There's also an `outlines` top-level key in qpdf --json, as noted in the Stack Exchange answer. I'll go ahead and close this. Thanks for answering it on Stack Exchange.

**Comment by mb720** [comment]
No problem.

I went through [pdf-bookmarks.cc](https://github.com/qpdf/qpdf/blob/main/examples/pdf-bookmarks.cc) but couldn't find hints on how to extract the outline using `qpdf` (the command line tool, not the library).

I assume the best way is to run `qpdf --json --json-key=outlines my.pdf`?

**Comment by jberkenbilt** [comment]
Yes, the `qpdf --json` command you gave is a good way to do it.
