### ISSUE TITLE
Add more information to json output pages array

### ISSUE THREAD

**Issue by su-ex** [qpdf/qpdf#456]
It would be very useful to add each page's height and width from `/MediaBox` and the current angle from `/Rotate` to the pages array from the `--json` output.
This information can already be extracted but it's a multi stage process (which I did as per your suggestion in #132).

With this information it's possible to calculate if a page is in landscape or portrait format regardless of what the angle is (Pseudo-Code):
```
$isPortrait = $width < $height
if (absolute($angle / 90) % 2 == 1) {
    $isPortrait = !$isPortrait
}
```
This might also be included in json page information for further convenience.

**Comment by jberkenbilt** [comment]
Thanks for the suggestion. Sorry for not replying. I don't intend to do this -- I agree that it would be convenient, but I'd like to not clutter the json output more than necessary.
