### ISSUE TITLE
typo, doc: at least with qpdf-manual.html, s/--encrypt-file-password/--encryption-file-password/ 

### ISSUE THREAD

**Issue by 74teTItm** [qpdf/qpdf#468]
version: 10.0.1

At least with qpdf-manual.html, it looks to me as if --encrypt-file-password is constantly used. According to --help, it should be --encrypt**ion**-file-password.

**Comment by jberkenbilt** [comment]
Thanks for noticing and reporting. I will check and make sure they are correct and consistent.
