### ISSUE TITLE
When I switch from 40-bit to 128-bit, no .PDF gets created (and same problem when I switch from 9.1.1 to 10.0.1)

### ISSUE THREAD

**Issue by abergquist** [qpdf/qpdf#469]
**When I switch from 40-bit to 128-bit, no .PDF gets created (and same problem when I switch from 9.1.1 to 10.0.1)**

I've got a couple of issues:

1. First, the following works for me:

`RUN F:\qpdf-9.1.1\bin\qpdf.exe --encrypt "" "password" 40 --print=y --modify=n --extract=n --annotate=n -- <Unprotected Pdf> <Final PDF>
`
but the 2nd one does not create a .PDF:

`F:\qpdf-10.0.1\bin\qpdf.exe --encrypt "" "password" 40 --print=y --modify=n --extract=n --annotate=n -- <Unprotected Pdf> <Final PDF>`

Why?

2. Secondly, when I switch from 40 to 128 for the **key_length**, the .PDF no longer gets created.

`RUN F:\qpdf-9.1.1\bin\qpdf.exe --encrypt "" "password" 128 --print=y --modify=n --extract=n --annotate=n -- <Unprotected Pdf> <Final PDF>`

nor:

`RUN F:\qpdf-9.1.1\bin\qpdf.exe --encrypt "" "password" 128--use-aes=y --print=y --modify=n --extract=n --annotate=n -- <Unprotected Pdf> <Final PDF>`

nor:

`RUN F:\qpdf-9.1.1\bin\qpdf.exe --encrypt "" "password" 128--use-aes=y --print=full --modify=n --extract=n --annotate=n -- <Unprotected Pdf> <Final PDF>`

I do really appreciate the document **qpdf-manual.pdf** but it's either not correct or I'm not correctly specifying options or QPDF itself isn't properly executing the options I'm specifying.

**Comment by jberkenbilt** [comment]
I'm not able to reproduce this. Are you getting any kind of error message? Does it happen with all PDF files? I can think of no reason why qpdf wouldn't work fine with 128 if it works with 40.

**Comment by abergquist** [comment]
Thanks so much for your rapid response!  No error message.  I had also tried to redirect output from the above commands by appending the following at the end:

` > qpdf_errors.txt`

Unfortunately, **qpdf_errors.txt** is always empty so it appears to be failing silently.

**Comment by jberkenbilt** [comment]
Hmm. That's very odd, and I don't really have anything to go on. I'd suggest maybe trying on a different system, making sure you don't have multiple versions of qpdf, and since it's Windows, maybe trying it with an admin and a non-admin account. Otherwise, I'm not sure I can offer much additional help.

**Comment by abergquist** [comment]
Thanks, Jay.  Good idea; I'll try that.
