### ISSUE TITLE
New :odd/ :even 3.5. 'Page Selection Options' irratic

### ISSUE THREAD

**Issue by xpseudonym** [qpdf/qpdf#470]
I have an issue with the very useful recent page selection option for odd/ even pages:
[http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.page-selection](url)

When running the following command:
`$ ~/AppImage/qpdf-10.0.1-x86_64.AppImage 20201001105653332.pdf o.pdf --rotate=180:1-z:even`
Some of the pages are not turned. I have a first section of the pdf file in which the pages are turned, followed by a section in which they are not turned, followed again by a section in which they are turned.  See attached between pp 10-14.
[20201001104727490_compressed.pdf](https://github.com/qpdf/qpdf/files/5335845/20201001104727490_compressed.pdf)
[o_compressed.pdf](https://github.com/qpdf/qpdf/files/5335846/o_compressed.pdf)

**Comment by jberkenbilt** [comment]
Thanks for posting here! It took me a few minutes to realize what's going on, but it's just a syntax error. You should use `--rotate=+180:1-z:even`. Note the `+`, which means to rotate the page by 180 degrees relative to its current orientation, where as 180 means to set the absolute orientation to 180. There is a typo in the documentation about this, which I will fix. This is a weird file in that some of the upside-down pages have orientation of 180 with images that are correct, and some of orientation of 0 with images that are rotated. The `+180` does what you want.

I'll leave this open and marked as a bug as a reminder to fix the documentation. The description is correct, but one of the examples is wrong. Thanks!

**Comment by xpseudonym** [comment]
Sorted!  Thank you.
Morgan.
