### ISSUE TITLE
merge multiple file with password

### ISSUE THREAD

**Issue by Solid-Metal** [qpdf/qpdf#471]
hello everyone, i try to merge multiple files, fortunately all this files have the same password, but how do i merge it with said password?, i try to put --password=${password} on it, but it didnt work, heres my merge code, i use nodejs and linux server

`qpdf --empty --pages ${filePath.join(' ')} -- ./stash/filefinal.pdf`

thank you

**Comment by jberkenbilt** [comment]
You need to put `--password` separately after each page in `--pages`, e.g., `qpdf --empty --pages 1.pdf --password=x 2.pdf --password=x ... -- ./stash/filefinal.pdf`. I'm sure you can figure out the javascript for that. Hopefully this helps.

**Comment by Solid-Metal** [comment]
i see, i need to do it separately, that make sense lol, thanks !
