### ISSUE TITLE
How to delete the last page of a pdf document?`

### ISSUE THREAD

**Issue by dfarmilant** [qpdf/qpdf#472]
I have a set of school notes that all have the same kind of last page (course information, date of lecture, etc.) which are all explicitly on the last page of each document.

I tried the following code:

`qpdf *.pdf *.pdf --pages . 1-~r1 --`

My guess is that this is a syntactical error. I was unable to find a document which describes each method, though I only started looking last night!

**Comment by jberkenbilt** [comment]
You'll have to do it separately for each file. I'm not sure where you're getting the `~` from. Is that in the docs? If so, it's an error. In Linux (or mac) with bash (or zsh), you could do something like this:

```
mkdir out
for i in *.pdf; do qpdf $i --pages . 1-r2 -- out/$i; done
```

`r2` is the second-to-last page.

**Comment by dfarmilant** [comment]
Hey, thanks for the prompt response.

I saw it on an SO post, though not the one that led me to QPDF. I understood it to be a logical NOT operator.

I'm a bit of a bash newbie, but understand the code you have included.

First, a directory is made, then we for-loop through the current directory, run the qpdf method pages for each index, create a new file in the directory we made, and then tell the computer we're done.

When I execute the code in the shell, this is returned:
`
. : read 1024 bytes
. : read 1024 bytes
...
. : read 1024 bytes
`
There are no files in `out`.

**Comment by jberkenbilt** [comment]
You're probably using an old version of qpdf. The `.` syntax in `--pages` was introduced in qpdf 8.4.0. If you have an older version, you'd get that error. In that case, update to the latest version, or repeat the filename:
```
for i in *.pdf; do qpdf $i --pages $i 1-r2 -- out/$i; done
```

**Comment by dfarmilant** [comment]
Worked like a charm!
