### ISSUE TITLE
splitting nlinearized PDF results in non-linearized one

### ISSUE THREAD

**Issue by akostadinov** [qpdf/qpdf#475]
Hi, I do this:
```
🐚 qpdf --version
qpdf version 10.0.1
🐚 qpdf my-linearized.pdf --pages . 1-2 -- --pages . 4-10 -- --pages . 651-z -- out.pdf
```

`qpdf --check out.pdf` reports non-linearized PDF.

Excuse me if this is expected but it looks like an area to improve.

**Comment by jberkenbilt** [comment]
It's expected. If you want the output files to be linearized, you have to explicitly specify `--linearize`. qpdf doesn't attempt to preserve whether the input is linearized, and changing it would be a major break in backward compatibility. Sorry for the confusion. This will do what you are looking for:

```
qpdf my-linearized.pdf --linearize --pages . 1-2 -- --pages . 4-10 -- --pages . 651-z -- out.pdf
```

**Comment by akostadinov** [comment]
Thank you, actually I did a mistake in original command. For anybody hitting this issue it should be
```
qpdf my-linearized.pdf --linearize --pages . 1-2 . 4-10 . 651-z -- out.pdf
```

**Comment by jberkenbilt** [comment]
@akostadinov Good catch. Here's an even easier way:
```
qpdf my-linearized.pdf --linearize --pages . 1-2,4-10,651-z -- out.pdf
```
