### ISSUE TITLE
PDF/UA support and check

### ISSUE THREAD

**Issue by leozachl** [qpdf/qpdf#479]
I'm looking for an automated PDF/UA checker.
Any idea if and how can this be done with qpdf as helper?
Maybe by adding tags and other necessary information to the json-output?

https://www.pdfa.org/resource/the-matterhorn-protocol-1-02/

**Comment by habere-et-dispertire** [comment]
Take a look at @verapdf.

**Comment by jberkenbilt** [comment]
I'm closing this as I have nothing to add and am hoping the existing comment was helpful. I have no plans to support PDF/UA or other subsets or specifications in qpdf. I am happy to help answer specific questions that may come up in an effort to do this, but I don't have knowledge of PDF/UA specifically nor do I have the time to study it. Thanks, and sorry I can't be more helpful here (and waited so long to acknowledge the issue).
