### ISSUE TITLE
libqpdf and PDF version string

### ISSUE THREAD

**Issue by shirat74** [qpdf/qpdf#48]
This is minor issue but I'll report it.

I'm currently writing a small program with libqpdf.

I found that if I try to set PDF version number string which is not in
the form of  "number.number",  then the process dies. libqpdf accepts
"1000.3" but not "2".

I compiled with g++ (GCC) version 4.6.2-1 on MinGW32/Windows 8.1.
Does this happen also in other environment?

**Comment by jberkenbilt** [comment]
This would be independent of the compiler or runtime environment and is a limitation of how qpdf parses the PDF header. As far as I know, the header is supposed to contain number.number, but I haven't seen any of the PDF 2.0 specification and am not sure if it's changed. In any case, I already have a planned enhancement to make qpdf more tolerant of headers that don't exactly match the specification, and I'll make sure I handle this case. I'm not sure when I will have time to fix it. I'm hoping to have time soon, but I will have to take leave from work to find time to work on it, and that's hard to do especially for an open source project.

Thanks for the report.

**Comment by jberkenbilt** [comment]
I have a feeling that the fix for #15 would handle this case as well.

**Comment by jberkenbilt** [comment]
This is fixed on master and will be in the next release.
