### ISSUE TITLE
Turning bunch of JPG/PNG into PDF?

### ISSUE THREAD

**Issue by Shohreh** [qpdf/qpdf#484]
Hello,

I went through the [doco](http://qpdf.sourceforge.net/files/qpdf-manual.html). Unless I missed it, it seems unable to turn JPG/PNG into a PDF:

qpdf.exe *.jpg merged.pdf
OR
qpdf.exe 1.jpg 2.jpg merged.pdf

Do you confirm it lacks this feature, and I need to look elsewhere?

Thank you.

**Comment by jberkenbilt** [comment]
Correct, qpdf does not have this feature. qpdf only knows about PDF files, not image files. You might want to look at ImageMagick or GraphicsMagick, both of which can create PDF files out of image files. There are other tools as well.

**Comment by rubyFeedback** [comment]
Shohreh, if it is of any help to you, the commandline use of imagemagick is
quite easy, e. g. "convert" in particular. You can use "higher" "scripting"
languages such as ruby or python or whatever else is simple to use to
"glue" this together. I use qpdf in particular to delete specific .pdf pages
from a large book, for study/acquiring new knowledge, all on the 
commandline (but there are also GTK bindings possible in ruby
and python, and www-related stuff, so you really can do a LOT on
your own. And the advantage is that e. g. ruby and python are 
really quite simple languages, compared to, say, C and C++).

**Comment by Shohreh** [comment]
Got answer to my question.
