### ISSUE TITLE
Add progress callbacks to C API

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#487]
Received a request for this by email. This is to track.

**Comment by GitHubRulesOK** [comment]
@jberkenbilt 
I am guessing this is source reason for
printf("%s progress: %d%%\n", (char const*)(data), percent);

It is a standard way of providing console output but the \n results in a continuous stream of line feeds
there are other more informative console output techniques such as %....5....10....15 etc.

However the simplest change is to ONLY apply \n after 100% has overwritten 99%

My request is to augment say perhaps have an alternative option such as --progress-no-nl
