### ISSUE TITLE
libqpdf removes DecodeParms

### ISSUE THREAD

**Issue by shirat74** [qpdf/qpdf#49]
I'm currently writing a PNG to PDF converter program with libqpdf.
I found that Flate compression predictor is quite useful for reducing file size.
However, whenever I try to set parameters for Flate predictor with DecodeParms
dictionary entry in Image dictionary, libqpdf removes it.

Is there any way to set DecodeParms?

**Comment by jberkenbilt** [comment]
Right now, libqpdf only supports the "up" filter for PNG, so any other predictor type isn't supported. It's a limitation I'd like to fix but haven't had a chance to get to. The reason for this limitation is that the up filter with PNG is typically used for compressing xref streams, but I had never added general support for the PNG filter or any of the other filters primarily used for images.

**Comment by shirat74** [comment]
As choosing an adequate predictor function requires knowledge on data to be compressed, I want
flexible control for selecting it and am not expecting application of predictor filter to be supplied as
libqpdf's function. Is it possible to modify libqpdf so that it simply leave DecodeParms
entry supplied by user undeleted?

**Comment by jberkenbilt** [comment]
I think this is already what qpdf does. Do you have some code you're writing against the library, or are you using the command-line tool? qpdf preserves compression of any stream that it doesn't know how to decode, but it obviously can't encode a stream using a predictor function that it doesn't understand. If you can provide a little more detail as to what you're doing and what you're seeing, perhaps I can provide some assistance. Maybe there's a bug, or maybe you're not using the API the way it needs to be used for this purpose. Or maybe qpdf just can't quite do what you want in this case. I would still like to code up the other predictor functions, but I don't have good test data. If you can provide some streams compressed with different predictor functions that are suitable for me to include in the test suite, that would provide some extra incentive for me to code up the other predictor functions. I'm guessing they aren't that hard, but I haven't looked at the algorithms from the PDF spec for a long time.

**Comment by shirat74** [comment]
Maybe I am misunderstanding something. 
I am just doing

     image.replaceStreamData(raster, QPDFObjectHandle::newNull(), parms);

where raster is image data and parms represents dictionary object for DecodeParms.  Maybe I need to supply the second

**Comment by shirat74** [comment]
Sorry I did something wrong. 

Maybe I need to supply the second argument and do the whole compression process by myself if I want to use predictor filter?

**Comment by jberkenbilt** [comment]
I think qpdf can't do what you want to do directly. While I wrote that code a long time ago and don't remember exactly, as I read the code, I don't see any facility to replace stream data with filters or decode parameters that qpdf doesn't support.

I think you might be able to fake it out in a forward-compatible way though. If you lie about the filter and decode parameters (just say they're empty) and compress the data yourself and provide that data, you will get a stream with the right final data but the wrong /Filter and /DecodeParms. Then, once you've done that, you can probably go in and directly modify those parameters in the stream dictionary. I believe this should work fine, but I haven't actually tested it.

Ultimately, what we probably need is another version of replaceStreamData that includes a flag that indicates that you are supplying compressed (filtered) data and that it should just preserve filter and decode_parms as passed in rather than using them to control how the data is processed.

Does this help?

**Comment by shirat74** [comment]
Thank you for your help.

It would be nice if qpdf supports various predictor filters to be applied to stream data.
But I simply want to pass data which is already filtered via predictor function and let libqpdf do actual part of flate compression, thus I just want to notify libqpdf that data is filtered with predictor filter and /DecodeParms should not be removed. 

The following change

    --- QPDFWriter.cc.orig  2015-05-16 23:08:03 +0900
    +++ QPDFWriter.cc       2015-05-16 23:08:22 +0900
    @@ -1318,7 +1318,7 @@
                     // We will supply our own filter and decode
                     // parameters.
                     object.removeKey("/Filter");
    -                object.removeKey("/DecodeParms");
    +                // object.removeKey("/DecodeParms");
                 }
                 else
                 {

works for me, but I don't know if there are side-effects.

I will consider preparing sample data with various predictor function applied.

**Comment by jberkenbilt** [comment]
Just looking through older issues...a relatively recent version of qpdf added support for the remaining PNG filters. qpdf still doesn't automatically apply them, but it would be possible for your own code to apply them.

**Comment by jberkenbilt** [comment]
I'm going to close this, but please feel free to reopen if you're still having a problem with this.
