### ISSUE TITLE
qpdf: an output file name is required; use - for standard output

### ISSUE THREAD

**Issue by rajeshkr7** [qpdf/qpdf#497]
Hi experts,
I am using QPDF as process command in symfony , but having an error while execution of that.
**qpdf version**: 8.0.2

```
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

$file1= 'abc/file.pdf';
$file2= 'bbc/file.pdf';
$process = new Process(['qpdf', "qpdf --encrypt raj123 raj123 256 -- $file $file2"]);
        $process->run(function ($type, $buffer) {
            if (Process::ERR === $type) {
                echo 'ERR > '.$buffer;
            } else {
                echo 'OUT > '.$buffer;
            }
        });
```
When I run this as raw it work fine
```
qpdf --encrypt raj123 raj123 256 -- abc/file.pdf bbc/file.pdf
```
the error I am getting 
```
qpdf: an output file name is required; use - for standard output

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help
```
Can any one of you suggest me what should I do?
Thanks

**Comment by dreua** [comment]
That's probably unrelated to qpdf and you just need to split the arguments passed to `new Process`, see [The Process Component (Symfony Docs)](https://symfony.com/doc/current/components/process.html#using-features-from-the-os-shell).

**Comment by rajeshkr7** [comment]
@dreua I understand what you have said but the error I am getting related ot QPDF.
So I was looking for that solution from qpdf team or any members.

Like when I am giving input and output file name than I am getting qpdf error 
and how and where I should use that (-).

And I check the symfony docs and after that I reached here and write that code.

IF  I remove command and write just --help than its working.

**Comment by dreua** [comment]
Could you just give it a try with this?
```php
new Process(['qpdf', "--encrypt", "raj123", "raj123", "256", "--", "file.pdf", "out.pdf"]
```
(You also had a duplicate qpdf in there originally.)
I don't have a Symfony ready to try but I'm really confident this will work. Btw, ti turns out someone has posted a very similar issue here: https://github.com/symfony/symfony/issues/39770

**Comment by rajeshkr7** [comment]
@dreua thank you for your reply and time. it actually worked.
