### ISSUE TITLE
qpdfview opening delay

### ISSUE THREAD

**Issue by BStevenFr** [qpdf/qpdf#500]
Hey, 
I'm using Linux Mint Mate 20.1 and whenever I open qpdfview it is very delayed (~30sec.).
That occurs when I double click on a pdf file from the file manager, or when opening qpdfview without opening a pdf.
When qpdf is already open and I open another pdf via Ctrl + O or Ctrl +T it is not delayed.
My System details are:

System:
  Kernel: 5.4.0-62-generic x86_64 bits: 64 Desktop: MATE 1.24.0 
  Distro: Linux Mint 20.1 Ulyssa 
Machine:
  Type: Convertible System: LENOVO product: 20M8S01400 v: ThinkPad L380 Yoga 
  serial: <filter> 
  Mobo: LENOVO model: 20M8S01400 serial: <filter> UEFI: LENOVO 
  v: R0RET42W (1.25 ) date: 06/29/2020 
Battery:
  ID-1: BAT0 charge: 17.6 Wh condition: 24.3/45.7 Wh (53%) 
CPU:
  Topology: Quad Core model: Intel Core i5-8250U bits: 64 type: MT MCP 
  L2 cache: 6144 KiB 
  Speed: 901 MHz min/max: 400/3400 MHz Core speeds (MHz): 1: 900 2: 900 
  3: 900 4: 900 5: 900 6: 900 7: 900 8: 900 
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz, 1920x1200~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.2.6 
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio driver: snd_hda_intel 
  Device-2: N/A type: USB driver: hid-generic,snd-usb-audio,usbhid 
  Sound Server: ALSA v: k5.4.0-62-generic 
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e 
  IF: enp0s31f6 state: down mac: <filter> 
  Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi 
  IF: wlp2s0 state: up mac: <filter> 
  Device-3: Realtek RTL8153 Gigabit Ethernet Adapter type: USB driver: r8152 
  IF: enx0024322244a4 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 238.47 GiB used: 119.75 GiB (50.2%) 
  ID-1: /dev/nvme0n1 vendor: Lenovo model: LENSE20256GMSP34MEAT2TA 
  size: 238.47 GiB 
Partition:
  ID-1: / size: 185.18 GiB used: 119.74 GiB (64.7%) fs: ext4 
  dev: /dev/nvme0n1p2 
Sensors:
  System Temperatures: cpu: 38.0 C mobo: 1.0 C 
  Fan Speeds (RPM): cpu: 0 
Info:
  Processes: 267 Uptime: 25m Memory: 7.67 GiB used: 2.87 GiB (37.4%) 
  Shell: bash inxi: 3.0.38

**Comment by jberkenbilt** [comment]
Hello. qpdfview is an entirely unrelated project from qpdf. You can find information about qpdfview at https://launchpad.net/qpdfview. Sorry for the confusion.
