### ISSUE TITLE
Number of Search Entries

### ISSUE THREAD

**Issue by felix-seifert** [qpdf/qpdf#508]
When I am performing a search in a document (CTRL + F), I want to see how many entries with the matching search term were found. When I go through the search terms, I also want to know at which entry I am currently.

## Example Workflow
1. I press CTRL + F to search.
2. I key in my search term and press ENTER.
3. I am directed to the closest entry which matches my search term. (Close means current page or later.)
4. I see a number which indicates how many entries where found (e.g. 10).
5. I see at which entry I am (e.g. 4/10). The first found entry receives number one (first from beginning of document). The following entries are numbered based on how late they appear in the document (later in the document means higher number).
6. When I use ENTER to scroll through the found entries, I go to the next highest number (pages from beginning to ending) and the entry number increases (e.g. first 4/10, then 5/10, then 6/10). At the end of the list of entries, it jumps to the beginning again.

An example can be found with the commercial Adobe Acrobat.

**Comment by jberkenbilt** [comment]
I'm guessing this is an issue with https://launchpad.net/qpdfview, not qpdf. qpdf is a command-line tool and C++ library and doesn't have a GUI.

**Comment by felix-seifert** [comment]
Thanks for the hint. I checked the about menu and realised that the software is qpdfview. For the ones who are interested, I filed this issue also for qpdfview: [https://bugs.launchpad.net/qpdfview/+bug/1916604](https://bugs.launchpad.net/qpdfview/+bug/1916604).
