### ISSUE TITLE
Compile-related problem with qpdf-10.2.0 - undefined reference to `EVP_MD_CTX_init'

### ISSUE THREAD

**Issue by rubyFeedback** [qpdf/qpdf#511]
Hey there,

Today I tried to compile qpdf 10.2.0.

It fails via:

    libtool: link: (cd "libqpdf/build/.libs" && rm -f "libqpdf.so.28" && ln -s "libqpdf.so.28.2.0" "libqpdf.so.28")
    libtool: link: (cd "libqpdf/build/.libs" && rm -f "libqpdf.so" && ln -s "libqpdf.so.28.2.0" "libqpdf.so")
    libtool: link: ( cd "libqpdf/build/.libs" && rm -f "libqpdf.la" && ln -s "../libqpdf.la" "libqpdf.la" )
    /bin/bash ./libtool --mode=link g++  -fPIC -fvisibility=hidden   -Wconversion -Wsign-conversion -Wshadow=local   -Wold-style-cast -Wall  qpdf/build/qpdf.o -o qpdf/build/qpdf -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -Wl,--as-needed -latomic  -lqpdf -lz -ljpeg -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto -lgnutls
    /bin/bash ./libtool --mode=link g++  -fPIC -fvisibility=hidden   -Wconversion -Wsign-conversion -Wshadow=local   -Wold-style-cast -Wall  qpdf/build/fix-qdf.o -o qpdf/build/fix-qdf -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -Wl,--as-needed -latomic  -lqpdf -lz -ljpeg -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto -lgnutls
    /bin/bash ./libtool --mode=link g++  -fPIC -fvisibility=hidden   -Wconversion -Wsign-conversion -Wshadow=local   -Wold-style-cast -Wall  qpdf/build/pdf_from_scratch.o -o qpdf/build/pdf_from_scratch -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -Wl,--as-needed -latomic  -lqpdf -lz -ljpeg -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto -lgnutls
    /bin/bash ./libtool --mode=link g++  -fPIC -fvisibility=hidden   -Wconversion -Wsign-conversion -Wshadow=local   -Wold-style-cast -Wall  qpdf/build/test_driver.o -o qpdf/build/test_driver -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -Wl,--as-needed -latomic  -lqpdf -lz -ljpeg -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto -lgnutls
    libtool: link: g++ -fPIC -fvisibility=hidden -Wconversion -Wsign-conversion -Wshadow=local -Wold-style-cast -Wall qpdf/build/qpdf.o -o qpdf/build/.libs/qpdf -Wl,--as-needed  -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -latomic /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so -lz /usr/lib/libjpeg.so -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto /usr/lib/libgnutls.so -pthread
    libtool: link: g++ -fPIC -fvisibility=hidden -Wconversion -Wsign-conversion -Wshadow=local -Wold-style-cast -Wall qpdf/build/pdf_from_scratch.o -o qpdf/build/.libs/pdf_from_scratch -Wl,--as-needed  -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -latomic /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so -lz /usr/lib/libjpeg.so -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto /usr/lib/libgnutls.so -pthread
    libtool: link: g++ -fPIC -fvisibility=hidden -Wconversion -Wsign-conversion -Wshadow=local -Wold-style-cast -Wall qpdf/build/fix-qdf.o -o qpdf/build/.libs/fix-qdf -Wl,--as-needed  -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -latomic /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so -lz /usr/lib/libjpeg.so -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto /usr/lib/libgnutls.so -pthread
    libtool: link: g++ -fPIC -fvisibility=hidden -Wconversion -Wsign-conversion -Wshadow=local -Wold-style-cast -Wall qpdf/build/test_driver.o -o qpdf/build/.libs/test_driver -Wl,--as-needed  -Llibqpdf/build -L/usr//lib -L/home/Programs/Libjpegturbo/2.0.6/lib -latomic /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so -lz /usr/lib/libjpeg.so -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto /usr/lib/libgnutls.so -pthread
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_MD_CTX_init'
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_CIPHER_CTX_init'
    collect2: error: ld returned 1 exit status
    make: *** [qpdf/build.mk:53: qpdf/build/pdf_from_scratch] Error 1
    make: *** Waiting for unfinished jobs....
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_MD_CTX_init'
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_CIPHER_CTX_init'
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_MD_CTX_init'
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_CIPHER_CTX_init'
    collect2: error: ld returned 1 exit status
    make: *** [qpdf/build.mk:53: qpdf/build/fix-qdf] Error 1
    collect2: error: ld returned 1 exit status
    make: *** [qpdf/build.mk:53: qpdf/build/test_driver] Error 1
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_MD_CTX_init'
    /usr/bin/ld: /home/Temp/rbt/qpdf-10.2.0/libqpdf/build/.libs/libqpdf.so: undefined reference to `EVP_CIPHER_CTX_init'
    collect2: error: ld returned 1 exit status
    make: *** [qpdf/build.mk:53: qpdf/build/qpdf] Error 1

Note that older qpdf, I think even 10.1.0, did not have this problem on my linux machine.

I am not yet sure what EVP_ is. I may try to look more closely into that issue; perhaps it
is some problem on my computer. But just in case, I wanted to make sure that I report
it before I forget (I am currently updating lots of stuff on my machine, so I move through
different programs as-is; haven't yet had much time for investigating where the error is).

IF however had EVP_ may be provided by some other packages, could there perhaps
be some prior check or notification? For example wherever EVP_ may be defined (I
currently don't know, will check some later time).

Thanks for reading - long live qpdf! :)

**Comment by jberkenbilt** [comment]
Sorry for not replying. Since qpdf started using cmake, many issues like this have disappeared. I'm closing this, but if it is still a problem, feel free to reopen or create a new issue.
