### ISSUE TITLE
erronous make test outcome

### ISSUE THREAD

**Issue by matzeri** [qpdf/qpdf#513]
It is more an annoy outcome that confuses automatic build

all tests are passed but make reports fail
qpdf-10.2.0 on Cygwin (it seems to appear between 10.0.1 and 10.0.2 )
--------------------------------
Overall test suite                                             ... PASSED
TESTS COMPLETE.  Summary:
Total tests: 5251
Passes: 5251
Failures: 0
Unexpected Passes: 0
Expected Failures: 0
Missing Tests: 0
Extra Tests: 0

*** ERROR: make failed
-------------------------------

**Comment by jberkenbilt** [comment]
There's not enough information here for me to do anything with this.
