### ISSUE TITLE
Make QPDF::findPage public

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#516]
`QPDF::findPage` is currently a private function. I believe it would be useful to pikepdf and possibly API users to lookup the page number of a given page object without iterating through all pages via ``getAllPages()``.

It would be perfectly fine to export it through a helper class if you prefer.

**Comment by jberkenbilt** [comment]
Yes, it's probably worth either exporting this or providing some equivalent way to do it that uses the cache, now that I've decided not to rewrite the internal page handling stuff.
