### ISSUE TITLE
About encryption

### ISSUE THREAD

**Issue by zuozhehao** [qpdf/qpdf#531]
Do not set the user password, just set the owner password, how to operate this, I did not find the relevant documents.

My document allows users to view and print, but does not allow users to modify and copy.

**Comment by jberkenbilt** [comment]
The documentation states that either or both of the user/owner password may be empty strings. You specify an empty string with "", so

```
qpdf --encrypt "" owner-password 256 -- infile.pdf outfile.pdf
```

will create a PDF with an empty user password.

**Comment by jberkenbilt** [comment]
I'll go ahead and close this, but feel free to reopen if you have further difficulty with it.
