### ISSUE TITLE
libraries: libgmp.so.10: cannot open shared object file:

### ISSUE THREAD

**Issue by zuozhehao** [qpdf/qpdf#534]
https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.2/qpdf-10.3.2-bin-linux-x86_64.zip

I used this, prompt `./qpdf: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory`，Do I need to install it manually？

**Comment by jberkenbilt** [comment]
That's not an end-user focused distribution. It's intended for use in docker containers, AWS lambda functions, or other minimal environments. You could potentially use it by extracting this zip file under /usr/local (or even under /usr) or by setting the LD_LIBRARY_PATH environment variable to the full path of the lib directory, but that's not really the intention. For additional details, see https://github.com/qpdf/qpdf/blob/master/README-what-to-download.md

I'll leave this ticket open as a reminder to myself to make sure the release notes include a link to this download information file.

**Comment by rubyFeedback** [comment]
> Do I need to install it manually

libgmp is part of gmp: most recent source archive of gmp is at https://ftp.gnu.org/pub/gnu/gmp/gmp-6.2.1.tar.xz

Compiling this yields me in /usr/lib/ with libgmp.so, libgmp.so.10 and libgmp.so.10.4.1, two of which are just symlinks onto the real version libgmp.so.10.4.1 (at the least from that tarball archive).

Your host system probably is missing that .so shared object file. You could try to install relevant libgmp.so* files, but you most likely already have some version of libgmp. You could try gmp into a special prefix, be it /opt/ or any other, and then add the lib/ directory onto, for example, /etc/ld.so.conf then run ldconfig. But often there may be more than one problem, in particular when you have a larger application. So it all depends.

I avoid this by simply compiling everything from source. This has some drawbacks (time it takes), but one advantage is that I am not dependent on distribution maintainers and their own slowness. The LD_LIBRARY_PATH trick may also work; I just found it simpler to append paths onto /etc/ld.so.conf via the nano editor, than having to re-define ENV variables. If it is just gmp you could try to test-compile gmp from source into a special prefix though. Normally gmp is needed by the GCC stack (including mpc and mpfr; I need these for compiling gcc). Once GCC works, compiling the rest is usually trivial.

For qpdf perhaps it may be useful to specify in more detail what may be needed, and why (directly or indirectly) if jberkenbilt has time. This may even be worthwhile to add to a FAQ for similar entries.
