### ISSUE TITLE
QPDFNameTreeObjectHelper needs QPDF_DLL_CLASS

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#536]
I wish there were some rhyme or reason for when a class needs this - anyway, the linker insists on it for this class.

Error is: ``undefined symbol: _ZTI24QPDFNameTreeObjectHelper``

**Comment by jberkenbilt** [comment]
Basically QPDF_DLL_CLASS is needed whenever type information is needed across the boundary between library and application, which seems to happen when either a class is used as an exception or as a base class. Do you happen to be deriving a class from QPDFNameTreeObjectHelper? It's not really intended for that. If that's not it, then there must be some other reason.

**Comment by jbarlow83** [comment]
No inheritance is happening. `py::class_<QPDFNameTreeObjectHelper>(...)` triggers it, where the py namespace is pybind11. py::class_ is a class template that creates a related class to manage the Python encapulsation but does not derive from it. I do the same for several QPDF classes that are not marked QPDF_DLL_CLASS, so I am not sure why the linker decides it needs to look up type information for the symbol in this case. I suspect it has to do with the inner class ``::iterator``.

Both GCC and Clang give the same error.

Anyway, it worked to create a holder class that does nothing except hold a QPDFNameTreeObjectHelper. Not ideal, but I think it will be fine unless we come up with some explanation for why this occurs.
