### ISSUE TITLE
Manual -> describe the error messages

### ISSUE THREAD

**Issue by Olfried2** [qpdf/qpdf#539]
Hello,
I try to use qpdf to add a stamp.
I tried several combinations but if the commandline seems to be correct, the message
**_qpdf: underlay file already specified_** 
appears

Maybe I'm too dumb, my commandlines looks like
`qpdf -- underlay MY_STAMP.pdf Infile1.pdf outfile1_.pdf`

`qpdf -- underlay MY_STAMP.pdf Infile2.pdf outfile2_.pdf`
......

I got a result with the first run of qpdf using
`qpdf infile.pdf --overlay MY_STAMP.pdf outfile.pdf`
but after that any command like this will end in the errormessage

I'd like to have an explanation what to do when this errormessage appears. Even google shows nothing when I search for this.
Best would be if there are some examples how to do this things.

I use qpdf 9.1.1 in an ubuntu 20.04 windows for linux (but normally it does what a linux has to do)

**Comment by jberkenbilt** [comment]
You have an extraneous space between `--` and `underlay` in what you pasted above, but I think the problem is that you're missing the `--` after the file. You need

```
qpdf --underlay MY_STAMP.pdf -- Infile1.pdf outfile1_.pdf
```

**Comment by Olfried2** [comment]
Thank you, you saved my day.
My fault was as you said the missing -- after underlay*
Thanks again also for this tool !
