### ISSUE TITLE
Print locking broken on Mac OS 10.15.7 with no user password

### ISSUE THREAD

**Issue by moeealii** [qpdf/qpdf#543]
Hey guys I used this command using the latest qpdf to encrypt and block printing 

`qpdf --encrypt "" ownerspass 128 --print=none -- input.pdf --replace-input`

my file names are in this format 

`generated-preview-2021-07-12T14-31-48.250Z.pdf`

The print locking has worked everywhere else I tested but not on this slightly older version of MacOS, any ideas?

**Comment by jberkenbilt** [comment]
This would be a bug in whatever software you are using on the older version of MacOS and is most likely not related to qpdf. I'm going to close this, but feel free to reopen if you have any questions. The next release of qpdf will have a chapter in the manual that describes the ins and outs of exactly what the various encryption flags do internally to the PDF file and why PDF readers are so varied in how they respond.
