### ISSUE TITLE
How to batch list non searchable pdf's ; with --with-images ???

### ISSUE THREAD

**Issue by artofit** [qpdf/qpdf#547]
I wish to to be able to do return the following output:

A/ recursively list pdfs that can't be searched(images for instance): that is every page in the pdf is not searchable

B/ recursively list pdfs that have at least 1 page which is not searchable.
if at least 1 is an integer parameter, it would be great, as for example one might exclude:
pdfs having first page as a cover image
Of course if set to more that max nb of pages it ought to return the file name

I don't know if --warn-empty flag can achieve option A/, but I haven't been able to such command.

I do not understand the result of **--with-images**, but it seems it could the job.

I wish something as:

`find -type f -iname "*.pdf" -exec qpdf {} --nonSearchable >> NonSearchablePdfs.txt \;`

Thanks

**Comment by jberkenbilt** [comment]
Sorry for not replying. This is not the kind of thing qpdf can do out of the box as it requires deeper analysis of the PDF page content. However, if one wanted to write a tool to do this, it would be possible to use qpdf to handle the PDF parsing side of things.
