### ISSUE TITLE
Fail to merge pdfs with acroform

### ISSUE THREAD

**Issue by liujunwei4321** [qpdf/qpdf#548]
[sample.zip](https://github.com/qpdf/qpdf/files/6871740/sample.zip)

qpdf-10.3.2 Command: 
qpdf.exe --empty --pages *.pdf -- out.pdf

Error: 
QPDFObjectHandle from different QPDF found while writing.  Use QPDF::copyForeignObject to add objects from another file.

The command works for other normal pdfs, but fails with the sample files attached.

**Comment by jberkenbilt** [comment]
Thanks for the report. I am able to reproduce that this causes qpdf to crash. I will study it soon when I get a chance. I appreciate your taking the time to bringing this to my attention.

**Comment by jberkenbilt** [comment]
I got this down to a very small file and am going to now figure out what's going on here.
[crash.pdf](https://github.com/qpdf/qpdf/files/7475728/crash.pdf)

**Comment by jberkenbilt** [comment]
I figured it out. The fix will be in 10.4.
