### ISSUE TITLE
Failed to build the QPDF for windows 

### ISSUE THREAD

**Issue by shq251** [qpdf/qpdf#551]
Hi,

I have followed the qpdf/README-windows.md file to build the qpdf for Window but failed to build. Kindly find below logs .
-----------------------------------------------------------------------------------------------------------------------
WIN10TEST+Administrator@Win10Pro MSYS /c/LQ/QPDF
# ./config-msvc
make

+ cl
+ grep -q 'for x64'
+ wordsize=64
+ CC=cl
+ CXX='cl -TP -GR'
+ ./configure --disable-test-compare-images --enable-external-libs --enable-werror --with-buildrules=msvc --enable-crypto-openssl --disable-crypto-gnutls
configure: loading site script /etc/config.site
checking for autoconf... 1
checking for autoheader... 1
checking for aclocal... 1
checking for sha256sum... 1
sha256sum: 'configure.ac'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'aclocal.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'libqpdf/qpdf/qpdf-config.h.in'$'\r': No such file or directory
: FAILED open or readfig.h.in
sha256sum: 'm4/ax_cxx_compile_stdcxx.m4'$'\r': No such file or directory
: FAILED open or readcxx.m4
sha256sum: 'm4/ax_random_device.m4'$'\r': No such file or directory
: FAILED open or read4
sha256sum: 'm4/libtool.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/ltoptions.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/ltsugar.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/ltversion.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/lt~obsolete.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/pkg.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: WARNING: 11 listed files could not be read
configure: error: autofiles are outdated; rerun autogen.sh

Please run ./configure before running make

Makefile:51: *** unable to continue with build.  Stop.
-----------------------------------------------------------------------------------------------------------------------

Kindly let me know how to resolve and build the qpdf.

Regards
Saddam

**Comment by jberkenbilt** [comment]
Looks like your git clone probably added carriage returns. Do `git config core.autocrlf input` for your qpdf clone. This came up in another issue recently. I will be sure to mention it in the README-windows.md file before the next qpdf release.

**Comment by shq251** [comment]
Hi jberkenbilt,

I have check above also but same issue found.
Log as below. 
-----------------------------------------------------------------------------------------------------------
WIN10TEST+Administrator@Win10Te MSYS /c/LQ/QPDF_Git/qpdf
# git config --global core.autocrlf true

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git/qpdf
# cd ..

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git
# mkdir QPDF1

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git
# cd QPDF1

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git/QPDF1
# git config --global core.autocrlf true

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git/QPDF1
# git clone https://github.com/qpdf/qpdf.git
Cloning into 'qpdf'...
remote: Enumerating objects: 17689, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 17689 (delta 55), reused 80 (delta 41), pack-reused 17567
Receiving objects: 100% (17689/17689), 31.97 MiB | 1.96 MiB/s, done.
Resolving deltas: 100% (12014/12014), done.
Updating files: 100% (2007/2007), done.

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git/QPDF1
# dir
qpdf

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git/QPDF1
# cd qpdf

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git/QPDF1/qpdf
# git config --global core.autocrlf true

WIN10TEST+Administrator@Win10Test MSYS /c/LQ/QPDF_Git/QPDF1/qpdf
# ./config-msvc
+ cl
+ grep -q 'for x64'
+ wordsize=64
+ CC=cl
+ CXX='cl -TP -GR'
+ ./configure --disable-test-compare-images --enable-external-libs --enable-werror --with-buildrules=msvc --enable-crypto-openssl --disable-crypto-gnutls
configure: loading site script /etc/config.site
checking for autoconf... 1
checking for autoheader... 1
checking for aclocal... 1
checking for sha256sum... 1
sha256sum: 'configure.ac'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'aclocal.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'libqpdf/qpdf/qpdf-config.h.in'$'\r': No such file or directory
: FAILED open or readfig.h.in
sha256sum: 'm4/ax_cxx_compile_stdcxx.m4'$'\r': No such file or directory
: FAILED open or readcxx.m4
sha256sum: 'm4/ax_random_device.m4'$'\r': No such file or directory
: FAILED open or read4
sha256sum: 'm4/libtool.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/ltoptions.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/ltsugar.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/ltversion.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/lt~obsolete.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: 'm4/pkg.m4'$'\r': No such file or directory
: FAILED open or read
sha256sum: WARNING: 11 listed files could not be read
configure: error: autofiles are outdated; rerun autogen.sh
-----------------------------------------------------------------------------------------------------------

Kindly help me, How to successfully build the Qpdf.

Thanks in advance.

Regards,
Saddam

**Comment by jberkenbilt** [comment]
You need `core.autocrlf` to have the value of `input`. Setting it to `true` is what causes the problem.

**Comment by shq251** [comment]
core.autocrlf value initially it is false. So, I have changed to true/input and try to build as above command but this time also gave same errors.
I have checked with three inputs of core.autocrlf value false/true/input, but with that also same errors displayed.

**Comment by jberkenbilt** [comment]
Most likely you are making some kind of mistake in your use of git. If you are getting those errors, then you have incorrect line endings. Maybe try deleting the clone, setting `core.autocrlf` globally, and doing a fresh clone, or search online for solutions. In any case, this is not a qpdf problem, and it is not likely that I will be able provide any further assistance on it.

**Comment by jberkenbilt** [comment]
I'm going to close this, but if you run into further problems, you can reopen.
