### ISSUE TITLE
Repo missing basic description

### ISSUE THREAD

**Issue by TechnologyClassroom** [qpdf/qpdf#552]
The README and repo description are self-referential and depend on the [external website](http://qpdf.sourceforge.net/) to provide a basic description of what the project does.  I would suggest copying at least a brief one or two sentences to supplement the information to newcomers that find the repo before the main site such as `QPDF is a command-line program that does structural, content-preserving transformations on PDF files.`

**Comment by jberkenbilt** [comment]
Yes, you are correct. It's been a while since I've actually read the README carefully. I will definitely fix this. Thanks for bring it to my attention.

**Comment by jberkenbilt** [comment]
Looking at this reminds me of how it feels when someone tells you you have a big glop of food spilled on your shirt...you simultaneously appreciate that they told you and wonder how long you've been walking around like that and who has noticed. :-) I'm guessing I probably wrote this README originally for display once you'd navigated down into the files area on sourceforge, and when I moved stuff to github, I probably didn't think about adjusting it for its new context. Oh well. Now that I know about it, I can definitely make it a better first thing for someone to see.

**Comment by TechnologyClassroom** [comment]
It is an understandable oversight as the project moved from sourceforge to GitHub.  No reason to be embarrassed about it.

Improving it would help newcomers to the project and potentially boost the project's popularity overtime by lowering the barrier to entry.

**Comment by rubyFeedback** [comment]
> Looking at this reminds me of how it feels when someone tells you you have a big glop of food spilled on your shirt..
> you simultaneously appreciate that they told you and wonder how long you've been walking around like that and
> who has noticed.

Updating documentation is quite annoying. I struggle with that in regards to my own projects. I am trying to treat
documentation "equal" to code but it's less fun to write high-quality documentation compared to code that does
things on its own. Perhaps one day true A.I. could write high-quality documentation automatically.

More on topic, I think the main README can serve as an entry point to other articles or links just fine. Perhaps you
can also have contributors help, e. g. write a summary in the issue description by contributors, then attach it to the
wiki and/or some internal area in doc/ or wherever qpdf is storing descriptions. And perhaps even have more people
contribute to the docs easily - I remember in ruby-gtk3 I was able to modify the files via the browser directly. This
actually helps a LOT, in particular when people aren't super-knowledgable about git on the commandline.
