### ISSUE TITLE
QPDF encryption is not fully secure

### ISSUE THREAD

**Issue by abdmurid** [qpdf/qpdf#554]
Hi all

I am using qpdf version 10.3.2 on macOS Big Sur to encrypt a file to prevent printing.
The command line is the following : 
 qpdf --encrypt "" "owner password"  256 --print=none --extract=n  -- infile outfile 

The user password is left empty as anyone could be able to read the file

The owner password is set to enable pricing by the owner and whoever has this password.

**Unexpectedly the outfile can still be printed using TexShop and PDF reader.**

Please your help is begged on that issue

Kind regards

badou

**Comment by jberkenbilt** [comment]
PDF encryption is not secure. It's not a qpdf issue. The application software has full access to the file, and it's up to the software to enforce it. The software you site probably just ignores the restrictions. Even qpdf ignores the restrictions, as documented. There isn't anything qpdf could do to prevent this issue.

**Comment by abdmurid** [comment]
> PDF encryption is not secure. It's not a qpdf issue. The application software has full access to the file, and it's up to the software to enforce it. The software you site probably just ignores the restrictions. Even qpdf ignores the restrictions, as documented. There isn't anything qpdf could do to prevent this issue.

Thanks a lot
