### ISSUE TITLE
Why is QPDF adding an offset on top of the page when overlaying

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#557]
Hi,

Just a small question... see the screenshot below

- The picture on the left is a PDF with an hidden text layer (where I selected all the text) that is made by Tesseract OCR
- The picture in the middle is the original picture that is ocred
- The picture on the right is left and middle merged but then the text layer (that I have selected) get moved down somewhat... why is this?

The text layer in the left picture has the correct offset.

Sorry for the white blocks but there was some personal information I had to hide.

![image](https://user-images.githubusercontent.com/6692947/131377869-ceca6981-b00c-44ed-841c-4b8dca1ac557.png)

**Comment by jberkenbilt** [comment]
Are the page sizes identical? The C++ API will allow you to place things precisely, but the CLI just centers one page on the other, so if the page sizes are not the same, you might get this kind of effect.

**Comment by Sicos1977** [comment]
I guess that is the reason, I asumed the top offset was set to zero.
