### ISSUE TITLE
Building for iOS

### ISSUE THREAD

**Issue by andresarocho** [qpdf/qpdf#560]
Hello 👋

Would love to run some PDF modifications on an iOS application. Is there a way to build this library for iOS? 

Thank you

**Comment by jberkenbilt** [comment]
I'm reasonably certain that people have done it,but I have no familiarity with iOS or the iOS build ecosystem. qpdf has very few external dependencies, and those that it have build everywhere (openssl or gnutls, jpeg library, zlib). I know from other github issues that people have called qpdf from objective C code. Maybe someone else can answer.

**Comment by rubyFeedback** [comment]
I don't know either but the msys2 team built tons of stuff for windows. Perhaps some guys from the mac homebrew package manager could help - they compile tons of things on OSX so perhaps they know about iOS.

There even is a cross-platform GUI (libui) that, although super-limited, works on the three main operating systems (don't know of one for iOS though).

**Comment by jberkenbilt** [comment]
I'm going to close this issue since there's not anything I can really do to assist. Sorry I can't be of more help on this.
