### ISSUE TITLE
qpdf --help not helpful for basic operation

### ISSUE THREAD

**Issue by neuhaus** [qpdf/qpdf#571]
I wanted to merge two PDF files into a new file with qpdf, which is one of the most basic operations i suppose.
I've never used qpdf before.
I looked at `qpdf --help`, read it twice and did not understand how to do it.

Here are some things i tried:

    qpdf file1.pdf file2.pdf out.pdf
    qpdf --pages file1.pdf 1 file2.pdf 1 -- out.pdf
    qpdf --pages file1.pdf file2.pdf -- out.pdf
   
Nothing worked.
I then found the PDF manual and also the solution somewhere in an example in chapter 3.5 "Page selection options" (this is page 14):

    qpdf --empty out.pdf --pages *.pdf --

The documentation needs improvement for this basic operation and also the syntax is really terrible.

Anyway, i got it working in the end, thanks for qpdf!

**Comment by mara004** [comment]
> [...] and also the syntax is really terrible.

I'm also new to the QPDF command-line interface, but I think the syntax actually makes sense.

As special content like the table of contents can only be preserved for one PDF, you can either specify a file from which such content will be copied, or use `--empty` instead.

This is also explained in the documentation:
```
All non-page data (info, outlines, page numbers, etc.) are taken from the
primary input file. To discard this, use --empty as the primary input.
To discard this, use --empty as the primary input.
```

For example, this command would merge `doc_a.pdf` with `doc_b.pdf` and preserve outlines from `doc_a.pdf`
```bash
qpdf doc_a.pdf --pages doc_a.pdf doc_b.pdf -- out.pdf
```

Without a primary input file, you have to specify `--empty`:
```bash
qpdf --empty --pages doc_a.pdf doc_b.pdf -- out.pdf
```

By default, if no page range is given, QPDF takes over all pages. This can also be achieved with `1-z`.
Of course, you can also take specific pages, e. g.:
```bash
qpdf --empty --pages doc_a.pdf 1-3,5,8 doc_b.pdf 4,6,9 -- out.pdf
```

Or use a wild card to merge a pile of PDFs at once:
```
qpdf --empty --pages doc_*.pdf -- out.pdf
```

The `--` after options like `--pages` is required for clarity to be able to parse complex arguments.

From the QPDF help:
```
--pages options --      select specific pages from one or more files
```

This syntax may seem a bit weird at first glance, but I think it's very universal and well-usable.

**Comment by jberkenbilt** [comment]
I agree that the command-line syntax is complicated, but as @mara004 points out, it is to support a broad range of uses. There have been enough negative comments on the command-line syntax of `--pages` that I probably need to do something about it. It's very important for me not to break backward-compatibility though -- I don't want to break people's existing scripts and so forth. I've considered various possibilities. I wonder whether I could possibly add an alternative CLI syntax that would be activated by some flag that would have to appear first, like `qpdf --cliv2 ...new-options...`. For qpdf 11, I'm planning on creating a much better API for doing the stuff the command-line supports. It may be a good time to think about improving this.

That said, in the absence of specific input, I see no reason to keep this issue open. @neuhaus -- know that I have registered your comment about the CLI being confusing and the documentation being hard for at least some people to understand. It is on my radar.

I'm going to close this, but feel free to reopen if there is a specific suggestion. Maybe I will start a wiki or open a discussion about improving the command-line syntax when I'm ready to really start digging into it, which I hope will be soon.
