### ISSUE TITLE
For qpdf 11: update API to strengthen checks around weak/insecure cryptographic algorithms

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#576]
See #358 for context. /cc @zdohnal 

In QPDF 11, we will make qpdf refuse to write new files with weak crypto (RC4) unless a specific method is called to explicitly allow it. QPDF will always continue to support older, weak crypto in order to be able to read older files and to be able to write files that are compatible with older readers. These changes are to prevent people from unknowingly using insecure crypto. The details are tracked in qpdf's TODO file. This ticket is to track progress. This is targeted for the next major QPDF version since it will break binary compatibility and potentially change behavior when existing APIs are called. The intention is for this to be a very low impact change for developers (one command-line flag or one additional library call).

**Comment by jberkenbilt** [comment]
A few additional notes:
* Whatever the change, it will not result in a situation where code that worked one way in qpdf 10.x works a different way in qpdf 11.x with no changes. For example, if we *just* required an additional call to QPDFWriter, then code would recompile with qpdf 11 and suddenly no longer be able to create files with weak crypto. I think this would create an unacceptable user/developer experience.
* Possible ways to mitigate this include having everything work exactly as it does now except require an extra call to suppress a WARNING rather than an ERROR. The problem with this is that it will be the users, not the developers, who are first alerted to the change. Another option would be to change name of all the library calls that can potentially write weak crypto. In this case, we could use a phased approach:
  * soon (qpdf 10.x or qpdf 11, whatever's next): add deprecation tags on methods that write weak crypto and have those methods generate warnings at runtime in case developers ignore the deprecation tags. Add new methods with `Weak` in their names that do the same thing without warning.
  * Next major release: remove the deprecated methods; the mechanism for opting in will be just to call the newly named methods.

**Comment by jberkenbilt** [comment]
What I have decided to do:
* Remove older deprecated (pre 8.4) API for creating encrypted files
* Add `Insecure` to the end of the names of all the `QPDFWriter` methods that write insecure files without otherwise changing their functionality (along with similar changes in the C API)
* Make lack of `--allow-weak-crypto` an error rather than a warning for the same cases it previously warned about
* Do nothing about `--copy-encryption` (or `QPDFWriter::copyEncryptionParameters`) or preservation of encryption for reasons that are discussed in the manual.

The qpdf 11 manual will have a section describing the changes and how to move forward.

**Comment by zdohnal** [comment]
Thank you for tackling this one, Jay! Kudos!
