### ISSUE TITLE
overflow reading bit stream

### ISSUE THREAD

**Issue by merco** [qpdf/qpdf#581]
[1015110462_spare parts catalogue.pdf](https://github.com/qpdf/qpdf/files/7580423/1015110462_spare.parts.catalogue.pdf)

What kind of problem is this?

**Comment by jberkenbilt** [comment]
You haven't given me much to go on here, but I see that if I run `qpdf --check` on the attached file, I get that error. This would be some kind of error thrown in the library for an error in the linearization hint stream that is not getting caught and converted properly into a warning. Running the file again through qpdf will resolve it. I will mark this as a bug and track it down. All errors in linearization tables should be converted to warnings when qpdf checks the file. In any case, it's only the linearization data that's bad. Most likely that would not affect the usability of the PDF file in any environment.
