### ISSUE TITLE
libqpdf/Pl_Flate.cc functions

### ISSUE THREAD

**Issue by jinghuazhao** [qpdf/qpdf#582]
Hi,

I compiled 10.3.2 without issues on our system earlier but is no longer the case and I tried to get around with 10.4.0 and got the same error, 

/bin/bash ./libtool --quiet --mode=compile --tag=CXX /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-6.5.0-dtb6lagchexqdijlx6xgkin3zlfddpzi/bin/g++  -g -O2 -fvisibility=hidden -I/usr/local/software/archive/linux-scientific7-x86_64/gcc-9/zlib-1.2.11-lnf7bswyozdhprbg7jo6n5ha5633ftj2/include       -Wconversion -Wsign-conversion -I/rds/user/jhz22/hpc-work/include    -I/usr/local/software/archive/linux-scientific7-x86_64/gcc-9/zlib-1.2.11-lnf7bswyozdhprbg7jo6n5ha5633ftj2/include -I/rds/user/jhz22/hpc-work/include -I/usr/include/p11-kit-1    -Wold-style-cast -Wall -MD -MF libqpdf/build/Pl_Flate.tdep -MP -Iinclude -Ilibqpdf  -c libqpdf/Pl_Flate.cc -o libqpdf/build/Pl_Flate.o; sed -e 's/\.o:/.lo:/' < libqpdf/build/Pl_Flate.tdep > libqpdf/build/Pl_Flate.dep
libqpdf/Pl_Flate.cc:75:73: error: no 'void Pl_Flate::setWarnCallback(std::function<void(const char*, int)>)' member function declared in class 'Pl_Flate'
 Pl_Flate::setWarnCallback(std::function<void(char const*, int)> callback)
                                                                         ^
libqpdf/Pl_Flate.cc:81:41: error: no 'void Pl_Flate::warn(const char*, int)' member function declared in class 'Pl_Flate'
 Pl_Flate::warn(char const* msg, int code)
                                         ^
libqpdf/Pl_Flate.cc: In member function 'void Pl_Flate::handleData(unsigned char*, size_t, int)':
libqpdf/Pl_Flate.cc:187:19: error: 'class Pl_Flate' has no member named 'warn'
             this->warn(
                   ^~~~
/bin/bash: libqpdf/build/Pl_Flate.tdep: No such file or directory
make: *** [libqpdf/build/Pl_Flate.lo] Error 1

I sense it might be due to availaibility of related software -- is there possible to find out?

Thanks,

Jing Hua

**Comment by jberkenbilt** [comment]
My guess is that you have an older version of qpdf installed on your system (or in one of the locations you have explicitly included in your include path) and the build is picking up headers from that instead of from the current version. Could that possibly be the case?

**Comment by jinghuazhao** [comment]
I would have thought the new installation will replace those at --prefix. However I would see if I can implement your suggestion.

**Comment by jinghuazhao** [comment]
I just pressed the wrong key -- I gather your sense was right! I dropped -I${PREFIX}/include and it continues steadily.

**Comment by jinghuazhao** [comment]
It is all done now -- after also sorting out hiccups over gnutls and nettle. Thank you!
