### ISSUE TITLE
Data sent by TestDriver::report isn't recognized in qtest-driver

### ISSUE THREAD

**Issue by tschoening** [qpdf/qpdf#59]
I'm building QPDF and its tests on my own and it looks like this is successful now, I get a green "PASSED" froom all of the tests. The summary of the tests is still wrong:

	Total tests: 0
	Passes: 0
	Failures: 0
	Unexpected Passes: 0
	Expected Failures: 0
	Missing Tests: 0
	Extra Tests: 0

On the shell I get the following error:

    invalid results from subsidiary test driver

I've debugged the testsuite and found that the following lines always succeed:

	my $line = <$for_parent>;
	if (! ((defined $line) && ($line =~ m/^TEST_DRIVER_CLIENT 1$/)))
	{
            [...]
	}

but those afterwards don't:

	waitpid $pid, 0;
	my $results = <$for_parent>;
	close($for_parent);

`$results` is always undef for some reason. The interesting part besides that the first read always succeeds is, that in Wireshark I can actually see that the output of TestDriver::report gets send AND the server part of the socket ACKs on TCP level. So the data should be there, but it simply isn't. I've tested all kinds of things like commenting waitpid, adding some sleeps, reading before waitpid with/without some sleeps, using `$for_parent->getlines()` in list context to read all the available data at once etc... Nothing worked, I always only get the first line `TEST_DRIVER_CLIENT 1`.

My env is Win 8.1 x64 and I don't use Cygwin or such, but have a simple MSYS Git env where sh.exe and such is used from. Same goes for perl.exe, which claims to be 5.8.8 and pretty old, but reading the first line succeeds for every test and I would expect the same for the rest.

I'm lost on this and would be very thankful for any ideas. I can live without the summary as long as all the tests pass, but would prefer a complete successful execution of the testsuite.

[dumpfile.pcap.txt](https://github.com/qpdf/qpdf/files/39358/dumpfile.pcap.txt)

**Comment by tschoening** [comment]
I've tested a bit more and found that the problem really is the Perl shipped with MSYS Git. If I change PATH so that sh.exe from the MSYS folder is found, but add my native Perl bin folder as the first folder in PATH afterwards, the test results are successfully communicated to the server using the socket. The only difference to the former setup is that not perl from MSYS is used anymore.

	TESTS COMPLETE.  Summary:

	Total tests: 73
	Passes: 73
	Failures: 0
	Unexpected Passes: 0
	Expected Failures: 0
	Missing Tests: 0
	Extra Tests: 0

Change PATH:

	for /F "delims=" %%i in ('which perl.exe') do set perlPath=%%~dpi
	set PATH=%perlPath%;%ProgramFiles(x86)%\Git\bin;%PATH%

**Comment by jberkenbilt** [comment]
Check out README-windows.txt. It actually specifically mentions that msys perl doesn't work with this.

**Comment by tschoening** [comment]
Thanks, I had a look at that file while I started building, but didn't read any explanation on why I should rename the binaries and must admit that I tend to ignore such things unless I get a good explanation about the cause. Renaming files in installed software always feels like a dirty hack to me, open for all kinds of negative side effects...

So, may I suggest some additional wording linking to this issue for people like me? :-) Additionally, I can provide some alternative solutions, which are less invasive and I do use currently.

I'll create a pull request which you can review if you are interested. Feel free to close this issue again if not... Thanks!
