### ISSUE TITLE
Not all exceptions converted to error messages in the C interface

### ISSUE THREAD

**Issue by lklein53** [qpdf/qpdf#590]
Hi together,

According to the documentation in the C interface all exceptions thrown by the C++ interface should be converted to error messages in the C interface. I think this is not the case if a pdf document contains an invalid root.

The implementation of `qpdf_get_root` is the following:

```
qpdf_oh qpdf_get_root(qpdf_data qpdf)
{
    QTC::TC("qpdf", "qpdf-c called qpdf_get_root");
    return new_object(qpdf, qpdf->qpdf->getRoot());
}
```

and the C++ implementation of `getRoot` is:

```
QPDFObjectHandle
QPDF::getRoot()
{
    QPDFObjectHandle root = this->m->trailer.getKey("/Root");
    if (! root.isDictionary())
    {
        throw QPDFExc(qpdf_e_damaged_pdf, this->m->file->getName(),
                      "", this->m->file->getLastOffset(),
                      "unable to find /Root dictionary");
    }
    return root;
}
```
In case the root is not a dictionary an unhandled exception will be thrown if i am not missing something.

Thanks and kind regards,
Lars

**Comment by jberkenbilt** [comment]
Coincidentally, someone else just found this same issue. A fix is in progress.

**Comment by lklein53** [comment]
Great thanks a lot

**Comment by jberkenbilt** [comment]
I pushed a fix for this. It will be in qpdf 10.5 which I will try to get out soon as there are a handful of fixes that need to get out.
