### ISSUE TITLE
C-API: add bindings to document page functions 

### ISSUE THREAD

**Issue by ancwrd1** [qpdf/qpdf#594]
Would be great to have C bindings for page functions on the document level, e.g. add_page, remove_page, get_all_pages, etc.
Very helpful for FFI bindings in other languages, so no need to write a custom C++ bridge code.

**Comment by jberkenbilt** [comment]
Interestingly, you're the second person to ask for this in the last week (the other one in private email in the context of a separate discussion). I'll see if I can work this in for 10.5, but if not, I'll try to get something in soon.

**Comment by jberkenbilt** [comment]
This is what I'm planning to add:
```C
    /* PAGE FUNCTIONS */

    /* The first time a page function is called, qpdf will traverse
     * the /Pages tree. Subsequent calls to retrieve the number of
     * pages or a specific page run in constant time as they are
     * accessing the pages cache. If you manipulate the page tree
     * outside of these functions, you should call
     * qpdf_update_all_pages_cache. See comments for getAllPages() and
     * updateAllPagesCache() in QPDF.hh.
     */

    /* For each function, the corresponding method in QPDF.hh is
     * referenced. Please see comments in QPDF.hh for details.
     */

    /* calls getAllPages() */
    QPDF_DLL
    size_t qpdf_get_num_pages(qpdf_data data);
    /* returns uninitialized object if out of range */
    QPDF_DLL
    qpdf_oh qpdf_get_page_n(qpdf_data data, size_t zero_based_index);

    /* updateAllPagesCache() */
    QPDF_DLL
    QPDF_ERROR_CODE qpdf_update_all_pages_cache(qpdf_data data);

    /* findPage() -- return zero-based index. If page is not found,
     * return -1 and save the error to be retrieved with
     * qpdf_get_error.
     */
    QPDF_DLL
    int qpdf_find_page_by_id(qpdf_data data, int objid, int generation);
    QPDF_DLL
    int qpdf_find_page_by_oh(qpdf_data data, qpdf_oh oh);

    /* pushInheritedAttributesToPage() */
    QPDF_DLL
    QPDF_ERROR_CODE qpdf_push_inherited_attributes_to_page(qpdf_data data);
    /* addPage() */
    QPDF_DLL
    QPDF_ERROR_CODE qpdf_add_page(
        qpdf_data data, qpdf_oh newpage, QPDF_BOOL first);
    /* addPageAt() */
    QPDF_DLL
    QPDF_ERROR_CODE qpdf_add_page_at(
        qpdf_data data, qpdf_oh newpage,
        QPDF_BOOL before, qpdf_oh refpage);
    /* removePage() */
    QPDF_DLL
    QPDF_ERROR_CODE qpdf_remove_page(qpdf_data data, qpdf_oh page);
```

cc @m-holger

**Comment by ancwrd1** [comment]
Looks great, thanks for a quick response!

**Comment by jberkenbilt** [comment]
> Looks great, thanks for a quick response!

You got lucky. I happened to be working on the C API. ;-)

**Comment by ancwrd1** [comment]
For XObject manupulation would be nice to also have something like `get_page_stream` (which translates to getPageContents and returns a combined stream data) and it's counterpart, `set_page_stream` or similar.
The use case is for example creating an N-up document or a booklet from the original PDF. A similar approach is used in the pdftopdf CUPS filter which uses QPDF C++ API.
Sorry if I am asking too much, your work is highly appreciated! :)

**Comment by jberkenbilt** [comment]
No problem asking for stuff. I'm not sure how a stream API should look from the C code. You might need more of a C++ bridge in that case. Adding code to work with stream data would be a bit more complex. For now, I'm trying to limit the C API to simple wrappers around C++ calls. If you're interested, you can take a look at #593 and see if you have any ideas to throw into the mix. I'm trying to come up with some a little more generalized to help expose more of the qpdf CLI functionality through the library and create an interface based on json that will make it easier to do more generalized stuff from non C/C++ languages.

For 10.5, I think I'll stick to the methods I've already added as they are all more or less one liners -- just call some C++ code and convert exceptions into error codes.

**Comment by jberkenbilt** [comment]
What I ended up adding was close to what I pasted above but with the added facility to allow add_page (et al) to be called with objects from other files. This round will not include functions for getting at the stream data.

**Comment by ancwrd1** [comment]
Thanks a lot for your answer and efforts, I will create a separate ticket for page contents and write something in there.

**Comment by jberkenbilt** [comment]
> I will create a separate ticket for page contents and write something in there.

Perfect. Thanks!
