### ISSUE TITLE
Annotations on duplicated pages 

### ISSUE THREAD

**Issue by m-holger** [qpdf/qpdf#600]
When a page is added by qpdf to an output file multiple times (eg using  ` --pages . 1,1 --`), all copies of the page share the same `Annots` array (if present) and `Annots` dictionaries.

This is non-compliant with ISO 32000-1 which specifies in "12.5.2 Annotation Dictionaries"

 > A given annotation dictionary shall be referenced from the Annots array of only one page

Sharing of the `Annots` array/dictionaries causes unexpected behaviour that for the user of the PDF file may be difficult to understand, such as:
 
- editing an annotation on one page changes the the annotations on all copies of the page
- a newly added annotation may or may not appear on all copies of the page (depending on whether the copied page had a (possibly empty) `Annots` array

**Comment by jberkenbilt** [comment]
Thanks for the report. I'll have to look at this more deeply. `QPDFPageObjectHelper::copyAnnotations` is supposed to deal with this. Either it's not complete or I'm not calling it in some cases where it should be called. Being able to add the same page more than once is a recent addition, and it's likely that I am not replicating everything that needs to be replicated. Once I have the new CLI framework in place, I intend to completely overhaul how page copying works. There's a comment in TODO about a possible `QPDFPageCopier` class that mentions looking for issues tagged with `pages`, so I have added that tag here.
