### ISSUE TITLE
Possible issues with pdf_doc encoding 

### ISSUE THREAD

**Issue by regebro** [qpdf/qpdf#606]
I'm looking at the pdf_doc encoding, and my C++ is rather rusty so I might misunderstand something, but my understanding seems to match with the behavior of Pikepdf's pdfdoc encoding, that uses qpdf, so I think the description below is correct.

It seems to me that for any character under 128, the character will be passed through unchanged into UTF8 when converting from pdf_doc to UTF8. However, in the PDF specification 1.7, Appendix D.3, characters from 0x18 to 0x1f have mappings to other Unicode characters, but that seems to not be the case in QPDF?

In addition there is the question of 0x7f which doesn't map to anything in Unicode, and if undefined characters should be allowed at all, or if they should raise an error. There's plenty more undefined characters, of course, but the appendix does specify a mapping for those, so mapping them that way is a reasonable interpretation. But 0x7f, for reasons I'm not sure, is empty and doesn't have a mapping.

Have I misunderstood something?

**Comment by jberkenbilt** [comment]
I'll recheck the spec -- I may have omitted handling of 0x18 through 0x1f and 0x7f by oversight. qpdf maps undefined characters to 0xfffd. I'll look into this more and get back to you. Thanks.

**Comment by jberkenbilt** [comment]
It always amazes me when things like this lurk in qpdf for so long. You are right -- I overlooked these characters somehow. I will push up a fix momentarily.
