### ISSUE TITLE
`make install` fails:  cp: doc/qpdf-manual.html: No such file or directory

### ISSUE THREAD

**Issue by lawlist** [qpdf/qpdf#61]
`doc/qpdf-manual.html` and  `qpdf-manual.pdf` are both missing, which causes `make install` to fail.

    /private/tmp/qpdf-master $ make install
    ./mkinstalldirs /private/tmp/qpdf/lib/pkgconfig
    mkdir /private/tmp/qpdf
    mkdir /private/tmp/qpdf/lib
    mkdir /private/tmp/qpdf/lib/pkgconfig
    ./mkinstalldirs /private/tmp/qpdf/bin
    mkdir /private/tmp/qpdf/bin
    ./mkinstalldirs /private/tmp/qpdf/include/qpdf
    mkdir /private/tmp/qpdf/include
    mkdir /private/tmp/qpdf/include/qpdf
    ./mkinstalldirs /private/tmp/qpdf/share/doc/qpdf
    mkdir /private/tmp/qpdf/share
    mkdir /private/tmp/qpdf/share/doc
    mkdir /private/tmp/qpdf/share/doc/qpdf
    ./mkinstalldirs /private/tmp/qpdf/share/man/man1
    mkdir /private/tmp/qpdf/share/man
    mkdir /private/tmp/qpdf/share/man/man1
    /bin/bash ./libtool --mode=install ./install-sh \
    		libqpdf/build/libqpdf.la \
    		/private/tmp/qpdf/lib/libqpdf.la
    libtool: install: ./install-sh libqpdf/build/.libs/libqpdf.17.dylib /private/tmp/qpdf/lib/libqpdf.17.dylib
    libtool: install: (cd /private/tmp/qpdf/lib && { ln -s -f libqpdf.17.dylib libqpdf.dylib || { rm -f libqpdf.dylib && ln -s libqpdf.17.dylib libqpdf.dylib; }; })
    libtool: install: ./install-sh libqpdf/build/.libs/libqpdf.lai /private/tmp/qpdf/lib/libqpdf.la
    libtool: install: ./install-sh libqpdf/build/.libs/libqpdf.a /private/tmp/qpdf/lib/libqpdf.a
    libtool: install: chmod 644 /private/tmp/qpdf/lib/libqpdf.a
    libtool: install: ranlib /private/tmp/qpdf/lib/libqpdf.a
    ranlib: file: /private/tmp/qpdf/lib/libqpdf.a(QPDFObject.o) has no symbols
    /bin/bash ./libtool --finish /private/tmp/qpdf/lib
    /bin/bash ./libtool --mode=install ./install-sh \
    		qpdf/build/qpdf \
    		/private/tmp/qpdf/bin/qpdf
    libtool: install: ./install-sh qpdf/build/.libs/qpdf /private/tmp/qpdf/bin/qpdf
    /bin/bash ./libtool --mode=install ./install-sh \
    		zlib-flate/build/zlib-flate \
    		/private/tmp/qpdf/bin/zlib-flate
    libtool: install: ./install-sh zlib-flate/build/.libs/zlib-flate /private/tmp/qpdf/bin/zlib-flate
    cp qpdf/fix-qdf /private/tmp/qpdf/bin
    cp include/qpdf/*.h /private/tmp/qpdf/include/qpdf
    cp include/qpdf/*.hh /private/tmp/qpdf/include/qpdf
    cp doc/stylesheet.css /private/tmp/qpdf/share/doc/qpdf
    cp doc/qpdf-manual.html /private/tmp/qpdf/share/doc/qpdf
    cp: doc/qpdf-manual.html: No such file or directory
    make: *** [install] Error 1
    /private/tmp/qpdf-master $

**Comment by jberkenbilt** [comment]
Thanks for reporting this, and sorry for the long delay in acknowledging. I have pushed a fix for this to master. It will be fixed in the next qpdf release. Thanks!
