### ISSUE TITLE
New GCC 12 warnings

### ISSUE THREAD

**Issue by marxin** [qpdf/qpdf#618]
Newly printed warnings with GCC 12:

```
[   25s] In file included from libqpdf/qpdf/ContentNormalizer.hh:4,
[   25s]                  from libqpdf/ContentNormalizer.cc:1:
[   25s] include/qpdf/QPDFObjectHandle.hh:1423:33: error: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Werror=deprecated-declarations]
[   25s]  1423 |     class iterator: public std::iterator<
[   25s]       |                                 ^~~~~~~~
[   25s] In file included from /usr/include/c++/12/string:45,
[   25s]                  from include/qpdf/QPDFObjectHandle.hh:29:
[   25s] /usr/include/c++/12/bits/stl_iterator_base_types.h:127:34: note: declared here
[   25s]   127 |     struct _GLIBCXX17_DEPRECATED iterator
[   25s]       |                                  ^~~~~~~~
[   25s] include/qpdf/QPDFObjectHandle.hh:1513:33: error: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Werror=deprecated-declarations]
[   25s]  1513 |     class iterator: public std::iterator<
[   25s]       |                                 ^~~~~~~~
[   25s] /usr/include/c++/12/bits/stl_iterator_base_types.h:127:34: note: declared here
[   25s]   127 |     struct _GLIBCXX17_DEPRECATED iterator
[   25s]       |                                  ^~~~~~~~
[   25s] cc1plus: all warnings being treated as errors
```

Note the type is deprecated with C++17 standard.
Ccing libstdc++ maintainer: @jwakely.

**Comment by jwakely** [comment]
The recommended approach is to just define the typedefs directly, instead of deriving from `std::iterator` to define them.

**Comment by jwakely** [comment]
That will work for every version of C++.

**Comment by jwakely** [comment]
`std::iterator` is an empty class that does nothing but define some typedefs. So instead of deriving from it, and inheriting the typedefs, just define the typedefs yourself.

It's only an ABI break if any classes inherits from two different iterator types that have the exact same `std::iterator` specialization as a base class. In practice that is very unlikely. Nobody inherits from iterators, let alone from two different ones at once.

**Comment by jberkenbilt** [comment]
@jwakely Thanks for the additional information. This is very helpful.

**Comment by marxin** [comment]
Thanks for the fix. Btw. do you plan to make a release any time soon?

**Comment by jberkenbilt** [comment]
@marxin Yes, I will be releasing within the next few days. I'm trying to get 10.6 out in front of the Ubuntu 22.04 code freeze and am in the final stages of preparing the release.
