### ISSUE TITLE
ask some question

### ISSUE THREAD

**Issue by fengshaoxie** [qpdf/qpdf#636]
I want to merge 1.pdf,2.pdf and 3.pdf becomes a new PDF file new.pdf, and add bookmarks, how can I call the API.

**Comment by jberkenbilt** [comment]
Sorry, I am not able to use issues to answer very basic questions about qpdf usage. Please consult the manual at https://qpdf.readthedocs.io and look at explanatory comments in the qpdf header files, especially [QPDF.hh](https://github.com/qpdf/qpdf/blob/main/include/qpdf/QPDF.hh) and [QPDFObjectHandle.hh](https://github.com/qpdf/qpdf/blob/main/include/qpdf/QPDFObjectHandle.hh)
