### ISSUE TITLE
PdfDocEncoding of 0xAD

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#637]
0xAD should not decode to U+00AD as QPDF currently does for PdfDocEncoding; it should also be undefined or I suppose U+FFFD. Surprisingly Table D.2 in the reference manual has this with no explanation. 

0x7F, 0x9F and 0xAD are all defined to have no Unicode equivalent.

**Comment by jberkenbilt** [comment]
Good catch. Searching for Undefined in D.3 of the latest ISO spec (which I purchased as a gift for myself recently), it seems that 0xAD is the only one I still missed. In the notes for D.2 (Latin character set and encodings):

> 5. The hyphen (U+002D) character is also encoded as 255 (octal) in WinAnsiEncoding. Windows
Code Page 1252 associates this character code with the soft hyphen (U+00AD) character. If the
PDF producer intends to map this character code to the "softhyphen" character from the Adobe
Glyph List, this may be specified using a Differences array in the encoding dictionary as shown
in the example below.

I'll fix this for 10.6, which I release as soon as this gets through CI.
