### ISSUE TITLE
getAllPages is return nullptr

### ISSUE THREAD

**Issue by fengshaoxie** [qpdf/qpdf#638]
QPDF inpdfa;
    inpdfa.processFile("D:\\1.pdf");
    std::vector<QPDFObjectHandle> apages = inpdfa.getAllPages();

 the apages size is 0，getAllPages  error

**Comment by jberkenbilt** [comment]
I wonder whether you might be running into the issue discussed in #199

**Comment by fredemmott** [comment]
Yeah, I've seen exactly this *sometimes* due to that; varies by run. Also frequently shows up as a non-emtpy vector but with invalid elements
