### ISSUE TITLE
--is-encrypted, and probably --encrypted, are problematic: the example file I am aware of

### ISSUE THREAD

**Issue by ZjYwMj** [qpdf/qpdf#645]
Consider https://download.brother.com/welcome/doc100417/cv_mfc880dw_uke_oug.pdf .
```
$ qpdf --is-encrypted cv_mfc880dw_uke_oug.pdf  # 0 exit status
$ qpdf --encrypt 123 123 256 -- cv_mfc880dw_uke_oug.pdf encrypted_cv_mfc880dw_uke_oug.pdf  # 0 exit status
$ qpdf --is-encrypted encrypted_cv_mfc880dw_uke_oug.pdf  # 0 exit status
```
encrypted_cv_mfc880dw_uke_oug.pdf is encrypted in the sense that I am asked for a password when opening it. I don't know if it is actually encrypted.
```
$ file cv_mfc880dw_uke_oug.pdf 
cv_mfc880dw_uke_oug.pdf: PDF document, version 1.6
$ file encrypted_cv_mfc880dw_uke_oug.pdf 
encrypted_cv_mfc880dw_uke_oug.pdf: PDF document, version 1.7, 1 pages
```
After opening it, encrypted_cv_mfc880dw_uke_oug.pdf has much more then 1 page. Skimming it, it looks like the expected content.
```
$ qpdf --version                                  ~
qpdf version 10.5.0
Run qpdf --copyright to see copyright and license information.
```
I haven't tried other documents from brother.com. http://support.brother.com/g/b/manuallist.aspx?c=as_ot&lang=en&prod=mfcj480dw_us_eu_as&flang=English&type3=10103&type2=5 -> Click to choose -> English, upper line, states the release date (version) of the file I tested is 03/06/2015 (0).

**Comment by jberkenbilt** [comment]
This appears to be operating as designed. What are you trying to achieve, and what are you expecting?

**Comment by ZjYwMj** [comment]
```
$  qpdf --help | grep -A1 ^--is-encrypted
--is-encrypted          silently exit 0 if the file is encrypted or 2
                        if not; useful for shell scripts
```
I downloaded https://download.brother.com/welcome/doc100417/cv_mfc880dw_uke_oug.pdf. If it is not encrypted, why do I get a 0 exit code when using --is-encrypted? If it is encrypted, why am I not asked for a password? And what is its password?

**Comment by jberkenbilt** [comment]
Password-protection is not the same as encryption. You can have an encrypted file without a password. In brief, a PDF file has a user password and an owner password. With a conforming reader such as Acrobat Reader, you need the owner password to bypass or modify security restrictions on the file, and you need the user password to open the file subject to its limitations. It's common to apply restrictions to a file, such as disallowing printing or text extraction, without requiring a password by creating a file with an empty user password and a non-empty owner password. When you see a file that is encrypted but doesn't require a password, this is what is happening.

For a technical explanation, I refer you to https://qpdf.readthedocs.io/en/stable/encryption.html which I actually just put up a few days ago.

**Comment by ZjYwMj** [comment]
As explained above. I misunderstood what is behind --is-encrypted.
