### ISSUE TITLE
Is there any way to specify a file whose name begins with a `-`?

### ISSUE THREAD

**Issue by lemniscati** [qpdf/qpdf#646]
This makes `outfile.pdf` from `infile.pdf`.
```
qpdf infile.pdf outfile.pdf
```

Then, how to make `-outfile.pdf` from `-infile.pdf`?
And, this fails, of course.
```
qpdf -infile.pdf -outfile.pdf
```
Is there any workaround for it?

Additionally, how to make `@outfile.pdf` from `@infile.pdf` even when both of `infile.pdf` and `outfile.pdf` exist?
This fails in the case.
```
qpdf @infile.pdf @outfile.pdf
```

**Comment by jberkenbilt** [comment]
Try specifying a full path or a relative path with a slash, like `qpdf ./-infile.pdf ./-outfile.pdf`. Same thing should work with `@infile.pdf` or `@outfile.pdf`. As an alternative, with qpdf 10.6 (just released this past week), there's a `--job-json-file` option that takes a json file with an alternative command-line syntax. You could create a json file like
```json
{"inputFile": "-infile.pdf", "outputFile": "-outfile.pdf"}
```
and run with `--job-json-file`. Run `qpdf --help=--job-json-file` for details. This requires 10.6.0 or 10.6.1.

**Comment by lemniscati** [comment]
Thank you! It works.
