### ISSUE TITLE
can qpdf recognize UTF-16LE?

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#649]
cc @mara004
See pikepdf/pikepdf#288
The attached file has UTF-16LE strings it, e.g. `/Name <fffe5300630068006f006f006c000000>`
Although this is not compliant PDF, some other viewers handle it. It probably wouldn't be hard for qpdf to handle it as well.

**Comment by mara004** [comment]
I don't know what your usual policy is for PDFs that are not perfectly valid - while some say libraries should be very tolerant when reading, other developers (e. g. the author of img2pdf) tend to refuse changing their code to read invalid files.

**Comment by jberkenbilt** [comment]
qpdf is full of changes to support invalid PDF files. In this case, the change would be pretty low impact...most likely I would implement it by having the call to QPDFObjectHandle::getUTF8Value detect UTF16-LE, which means it would only detect and correct if you specifically asked for a Unicode string. That means qpdf would preserve the incorrect encoding in all transformations. If str(o) in pikepdf does this, then it would have been correct in your code. One tricky thing would be whether qpdf should issue a warning...the problem is that the part of the code that would notice is disconnected from anything that would be able to issue a warning other than just writing to stderr. What I would probably do would be to see how a handful of other readers handle it, including Adobe Reader, okular, evince, firefox (pdfjs), and chrome. If most of these seem to handle it silently, then I could assume that files like this are out there in the wild and that their authors have never noticed their errors. It would be pretty easy for a Windows programmer that was trying to generate PDFs but not doing it right to end up in exactly this place. I wonder whether, if you ran your script and piped through cat -v, you would see that every other character is a null.

**Comment by jberkenbilt** [comment]
I opened the issue myself because, looking at the code, it would probably be about 15 lines of code to support this. Anyway, I'm not planning any work on qpdf for a little while, so I'll just leave this open as a reminder.

**Comment by mara004** [comment]
Thanks for the detailed response.

> What I would probably do would be to see how a handful of other readers handle it, including Adobe Reader, okular, evince, firefox (pdfjs), and chrome.

Okular (with debugging output turned on for the PDF generator in `kdebugsettings`) seems to accept it silently.
PyMuPDF does not seem to issue a warning either.

> I wonder whether [...] you would see that every other character is a null.

Yes, I think so. With an older version of pikepdf, the layer names output looked like this:
```
ordered_names ['Title Block', 'ÿþL\x00a\x00y\x00e\x00r\x00s\x00\x00\x00', 'ÿþG\x00r\x00a\x00t\x00i\x00c\x00u\x00l\x00e\x00\x00\x00', 'ÿþO\x00t\x00h\x00e\x00r\x00\x00\x00', 'ÿþL\x00a\x00b\x00e\x00l\x00s\x00\x00\x00', 'Road - Highway', 'Road - Major', 'Road - Minor', 'ÿþS\x00c\x00h\x00o\x00o\x00l\x00\x00\x00', 'River Annotation', 'ÿþF\x00i\x00r\x00e\x00 \x00S\x00t\x00a\x00t\x00i\x00o\x00n\x00\x00\x00', 'ÿþS\x00c\x00h\x00o\x00o\x00l\x00 \x00S\x00i\x00t\x00e\x00\x00\x00', 'ÿþR\x00o\x00a\x00d\x00\x00\x00', 'ÿþT\x00r\x00e\x00a\x00t\x00m\x00e\x00n\x00t\x00 \x00A\x00r\x00e\x00a\x00\x00\x00', 'CL-1 Project', 'ÿþF\x00i\x00r\x00e\x00 \x00D\x00i\x00s\x00t\x00r\x00i\x00c\x00t\x00\x00\x00', 'ÿþC\x00o\x00l\x00o\x00m\x00a\x00 \x00L\x00o\x00t\x00u\x00s\x00 \x00F\x00S\x00C\x00\x00\x00', 'Vegetation and Topography']
```

> Anyway, I'm not planning any work on qpdf for a little while, so I'll just leave this open as a reminder.

Ubuntu 22.04 feature freeze, I guess?

**Comment by rubyFeedback** [comment]
Just a quick comment to the "strict versus not-strict parsing". I believe ideally one should be able to support
both, for different use cases. The strict mode for ensuring that the pdf files that you have are nice, decent
and well-behaving. And the not-so-strict mode to accept that the world is full of pdf files that may have 
problems. That way users or devs can select which variant to prefer. Of course there may be trade offs
(more code, harder to support and maintain), so this is what one may have to consider. May be useful to
specify the policy in place for qpdf somewhere, so people can look at it (thus also giving similar questions
as one asked by mara004 validity).

> One tricky thing would be whether qpdf should issue a warning.

This may also depend on the use case. For a developer who can fix stuff a warning may be useful; for
a user who can not fix this a warning may be distracting, but may still be useful. Perhaps commandline
flags that are simple to use, such as --verbose or --verbose-warnings or something like that. Personally
I like warnings if they are useful/helpful. I actually prefer warnings over "don't warn but also swallow
problems silently". I guess qpdf caters more to developers and advanced users, so from that point of
view having warnings is more beneficial than showing no warnings.

I remember in ruby, though, one developer (mame) added more warnings, and it seemed harmless.
Then the rails-guys complained that the warnings show up every time someone creates a new scaffold
via rails, so the warning situation got reverted. I just mention this in case to look at the scope of a 
warning; I don't expect this for qpdf to be the case, but mame did not expect this to happen in rails
(and he does not really use rails extensively, so he had no real easy way to determine how the 
warnings would affect users. Having warnings that you can not easily suppress, but also can not
fix, can be SUPER frustrating though.)

**Comment by rubyFeedback** [comment]
That reminds me - qpdf sometimes tells me when I remove pages from a .pdf file that the pdf file
at hand has some error or is malformed. I don't mind these warnings. While they do not give me
that much useful information (I don't know how to fix these issues), I don't mind since my use case
is primarily to remove pdf pages (among other use cases, though). Interestingly this seems to be
linked to some early pages, because I remember the warnings disappearing when some pages
were removed - so perhaps the .pdf files that come early, carry more meta-data that can cause
warnings. But by and large I personally do not mind the warnings in this case at the least. It may
be different if qpdf would report every time a page is removed "WARNING: there be dragons
if a pdf page is removed!". ;)

**Comment by rubyFeedback** [comment]
mara wrote:

> other developers (e. g. the author of img2pdf) tend to refuse changing their code to read invalid files.

Well - while this is understandable (less code to maintain), I'd think it is still better to be flexible and
offer two APIs or formats, and to default to the strict one to encourage people to create/maintain
valid pdf files. But perhaps he does not want more code to maintain, which I can understand too -
the icewm author explained this once, where some changes to icewm will not happen because 
it would lead to too much code to maintain. I can absolutely understand this point of view too -
it's ultimately a trade off, how versatile you want to make a specific piece of software.

**Comment by jberkenbilt** [comment]
@rubyFeedback I agree with pretty much all your comments. It's a balancing act. You are not the only one who would like to see more granularity in which warnings are issued. I've been in a long dialog with another user about warnings when objects are accessed using accessors for the wrong type. Users can almost never fix these, but they matter to developers. I have found bugs in qpdf because of users reporting questions about those warnings, and I've certainly caught mistakes during my own development.

The pragmatic situation in this case though is that there is no such machinery for granular warnings in qpdf, and adding it would be a huge effort and require breaking API changes, and it's too low priority. In this case, looking at the balance carefully, I think I would have to go with the idea that it's much more likely for a user to encounter a file with bad UTF-16 than for a developer to make that mistake and find it because they are using qpdf. If they are already using qpdf, then they should be working with utf-8 and letting qpdf do the transcoding for them.

In an ideal world, I would issue warnings upon encountering such a string, and those warnings would be tagged with some code or verbosity level and be able to be trapped using the existing mechanisms for trapping/suppressing warnings. As it is, catching this is way down in transcoding functions which are disconnected from QPDF objects or QPDFObjectHandle objects. There would be no way to communicate the warning back up to a place where anything could trap it. This would make it very hard for library users to write code that wouldn't occasionally have qpdf spitting stuff out to stderr without their ability to do anything about it, and I don't think qpdf should behave that way.

If I had the luxury of devoting myself full time to qpdf, I might want to fix this. But if I could do that, maybe I'd rewrite it from scratch in rust. :-) But anyway, the bottom line is that it would be fairly trivial for qpdf to gracefully handled UTF-16LE strings but quite difficult for it to do so other than silently. This is the first case of this that I've encountered in qpdf, so I imagine it's not really that big a deal.

In any case, I appreciate your comments and your participation in this and so many other discussions, @rubyFeedback.

**Comment by jberkenbilt** [comment]
Every reader I'm testing, including Acrobat Reader, accepts UTF-16LE, so I'm going to go the route of silently accepting it. Since it's a very small code change and I have to release 10.6.2 for an unrelated reason, I'm going to just do it now and get it out.

**Comment by mara004** [comment]
Thanks a lot!

**Comment by jberkenbilt** [comment]
@rubyFeedback Regarding warnings that disappear after you remove pages, as far as I know, qpdf never write a file that would have warnings it would detect when removing pages, which is a fairly high-level operation. The warnings qpdf would find in that case would usually be structural things that it would correct when it writes the file out. There may be exceptions to that, but for the most part, I'd guess that's why warnings disappear after you remove the pages.
