### ISSUE TITLE
ObjectIds of new objects added to an existing pdf file are different from the those saved in file

### ISSUE THREAD

**Issue by parapente** [qpdf/qpdf#66]
I have created a very simple program to add an image to the first page of a pdf file using qpdf and a couple of classes from Qt4 (https://github.com/parapente/qpdfImageEmbed). All goes well until I try to use /SMask to specify a soft mask for the image to enable trasparency. As far as I can tell you can use /SMask with the object ID of the XObject that describes the transparency mask. If I create a new stream and get the objectID to use it in SMask, that ID is completely different from the one saved in the pdf file. If I convert the resulting pdf using "qpdf -qdf in.pdf out.pdf" I get a file in which the XObject has the same ID as the one the library was returning. Is this normal?

(Using qpdf 5.1.2)

**Comment by jberkenbilt** [comment]
There is no expectation that object numbers will be preserved by qpdf. qpdf will preserve all referential integrity though so any reference to the old object number in the original file will be converted to a reference to the new object number in the new file.

**Comment by parapente** [comment]
I don't expect qpdf to preserve the old object numbers after I make changes to a pdf file. Perhaps I didn't explain it clearly. The problem is that when I create a new object and for some reason I need to use its object number and generation I cannot be sure that when I save the file the object number will be the same. This breaks references of objects in the pdf file making it unreadable. As an example you can see SMask that has to be followed by an XObject ID and generation. Could it be there is another way to do such things using libqpdf?

**Comment by jberkenbilt** [comment]
If you're using libqpdf as intended, you should never actually have to work with an explicit object ID or generation number. If you have some code, I may be able to help guide you. For an example, take a look at pdf-create.cc in the examples directory with the qpdf distribution. You would add a new object to the file by calling either the makeIndirectObject method or the newStream (or one of its variants) method of QPDF. These return a QPDFObjectHandle that you can directly use as a dictionary key or in any other place where an indirect object reference could go. References here are to the examples in qpdf 5.1.2 to match what you're using.

If you look at [line 83 of pdf-create.cc](https://github.com/qpdf/qpdf/blob/release-qpdf-5.1.2/examples/pdf-create.cc#L83), you can see where we create the font dictionary. In [line 118](https://github.com/qpdf/qpdf/blob/release-qpdf-5.1.2/examples/pdf-create.cc#L118), we use it as the value of the /F1 key in the resource font dictionary. At [line 96](https://github.com/qpdf/qpdf/blob/release-qpdf-5.1.2/examples/pdf-create.cc#L96), we create the image object as a stream. That gets placed as the value of /Im1 in [line 121](https://github.com/qpdf/qpdf/blob/release-qpdf-5.1.2/examples/pdf-create.cc#L121). By doing it this way, you avoid the need to ever work with object numbers.

Does this help?

**Comment by jberkenbilt** [comment]
For what it's worth QPDFObjectHandle::parse was added late to the library. Most of this example predates it, so mostly it uses the more cumbersome methods of cobbling together objects. If you wanted to include an indirect object reference in something you were creating using QPDFObjectHandle::parse, use a place-holder that's not an indirect object (it could be anything including null or just omitting it entirely) and then use one of the other methods, like replaceKey, to drop the indirect object in place.

**Comment by parapente** [comment]
You are absolutely correct. I don't know why I missed the obvious in the examples :-/ Thanks for this marvelous piece of software called qpdf! :+1:

**Comment by jberkenbilt** [comment]
You are welcome. :-)
