### ISSUE TITLE
singlehtml: In some, possibly corner, circumstances, left mouse click is hardly as expected

### ISSUE THREAD

**Issue by ZjYwMj** [qpdf/qpdf#663]
This is probably a corner case. It is with old hardware. Or that with new hardware it is much less likely to be seen. And also concerns accessibility.
I am not sure if the problem is with the qpdf documentation. Though it looks to me qpdf is to blame. The qpdf version is 10.6.2.
It happens only when viewing the singlehtml version. Assuming online sites serve the multiple html pages, that can explain why only locally installed documentation is affected. Though with the multiple html docs, one can claim it will constantly requires some readers to zoom in the page.
After learning how to circumvent the problem, as described below, I think it worth comparing what happens with mouse clicks at similar links in the local single, and multiple, html. It could be  the problem is there.
The old hardware part is the monitor used to demonstrate the issue. It is an old, 3:4 aspect ratio monitor. Not the newer 16:9 ones. It might also gets identified by CSS as an 1024x768 resolution display.
How to reproduce?
It could be that firefox cache is complicating things here. The problem is there, I have no doubt about that. I can reproduce it with a few trial and error attempts, if it does not seen at the first attempt. Yet, sometimes, I have to try somewhat different sequences of mouse clicks to reproduce it again and again myself.
I start with the home page, loading singlegtml/index.html with firefox. I prefer larger fonts, so I issue a couple of View → Zoom → Zoom in commands. At some point, the presentation changes. The table of content at the left side disappears. And a 3 horizontal bars button appears at the top left corner of the screen. I assume this is by design, possibly an automatic thing of CSS. I stop zooming in at the first screen where the 3 horizontal bars button appears. At this point I regret. I do want to choose an entry from the table of content. Where is it? A left click at the 3 horizontal bars button puts the table of contents back. With a large, non proportional, width, comparing to the right side. But never mind. I will restore the previous font size of the text once   I will get to the chapter I am looking for. So I am choosing some internal link at random from the table of content. The right side of the screen, where the text is shown, gets to the desired chapter. But how do I get the text to be displayed in a readable manner, with the former large font? The non proportional wide left table of content is still here. Trying to zoom in, or zoom out, a couple of times does not give back the text in the readable manner, and font size, that I am looking for. And so does other attempts, such as left clicking on the home button, the one with the home icon.
A related issue, or, possibly the same issue, is that there seem be no way to scroll the right side of the screen, the one with the text, up. Or down.
Surprise. Took me a long time. Now I notice that a right click on the links show a small menu. It looks like any internal link now requires to be opened in a new tab to be readable in the desired font size. Or a new window is required.
Another related problem might be that sometimes, once I got into firefox reader view, I couldn’t get out of it, into the usual presentation. The usual firefox buttons to get out of reader view did nothing. But this is harder for me to reproduce.

**Comment by jberkenbilt** [comment]
I didn't completely follow, but the qpdf documentation is built with sphinx using the sphinx_rtd theme, and I haven't done anything to customize it. Any issues with the qpdf documentation are probably sphinx issues. If you felt adventurous, you could look at how qpdf's docs are built (actually it's pretty vanilla sphinx) and try to reproduce the behavior and report to sphinx. I don't have the inclination or particular skill/knowledge of the way the docs are implemented to really address any issues with how the docs render. If there were something that was obvious or always happened that might be a reflection of the docs being improperly packaged or installed, that would be different, but it doesn't sound like that's the case here.

**Comment by ZjYwMj** [comment]
https://github.com/readthedocs/sphinx_rtd_theme/issues/880

**Comment by jberkenbilt** [comment]
@ZjYwMj Great, thanks so much for doing that. Is it okay to close this?

**Comment by ZjYwMj** [comment]
Not reported by me. It is a year old. I will click `Close with comment`. I hope this is O.K. Not sure the site will approve that.
