### ISSUE TITLE
Build fail with Visual studio 2019

### ISSUE THREAD

**Issue by fengshaoxie** [qpdf/qpdf#667]
Administrator@DESKTOP-C4Q82VV MSYS /d/Work/03DemoTest/14QtPdfTest/qpdf-release-qpdf-10.6.2
# ./config-msvc
+ cl
+ grep -q 'for x64'
+ wordsize=32
+ CC=cl
+ CXX='cl -TP -GR'
+ ./configure --disable-test-compare-images --enable-external-libs --enable-werror --with-buildrules=msvc --enable-crypto-openssl --disable-crypto-gnutls
configure: loading site script /etc/config.site
checking for autoconf... 0
checking for autoheader... 0
checking for aclocal... 0
checking for sha256sum... 1
checking for gcc... cl
checking whether the C compiler works... no
configure: error: in `/d/Work/03DemoTest/14QtPdfTest/qpdf-release-qpdf-10.6.2':
configure: error: C compiler cannot create executables
See `config.log' for more details

Administrator@DESKTOP-C4Q82VV MSYS /d/Work/03DemoTest/14QtPdfTest/qpdf-release-qpdf-10.6.2
#

![image](https://user-images.githubusercontent.com/37693004/157023630-0d8dd531-49bd-4e9d-bb76-fbdd41a69b47.png)

**Comment by jberkenbilt** [comment]
I'm not fixing any bugs with the existing build. The next qpdf will be built with cmake, and I'm almost finished putting the cmake files together. If you use this, you need to have MSVC commands in your path by running from a shell started from the MSVC as described in README-windows.md. For an example, you can consult build-scripts/build-windows.bat which is what is used to build in github actions.

**Comment by fengshaoxie** [comment]
hello,how to build vs2019 use cmake
