### ISSUE TITLE
Usage displays arguments unspaced of the command qpdf--help

### ISSUE THREAD

**Issue by Tyrben** [qpdf/qpdf#668]
On Windows, last released version.

qPdf basic command without arguments displays the "usage" as expected.

But the appearance is degraded, the options / arguments are glued to the command

> \>qpdf
>
>qpdf: an input file name is required
>
>For help:
>  qpdf--help=usage       usage information
>  qpdf--help=topic       help on a topic
>  qpdf--help=--option    help on an option
>  qpdf--help             general help and a topic list
>

**Comment by jberkenbilt** [comment]
Thanks -- this is already fixed and will appear in 10.6.3 which should be coming out as early as today.
