### ISSUE TITLE
Tracker link on website is broken

### ISSUE THREAD

**Issue by mohag** [qpdf/qpdf#67]
The "tracker" link on http://qpdf.sourceforge.net/ should likely link to https://sourceforge.net/p/qpdf/_list/tickets or https://github.com/qpdf/qpdf/issues . The current link gives a 404.

**Comment by jberkenbilt** [comment]
Thanks. What I really need to do is to point it to github. I'll take a top-to-bottom look at that very short page and make sure it's up-to-date.

**Comment by mohag** [comment]
The download link works, but goes through a redirect, schecking sf's

**Comment by jberkenbilt** [comment]
Let's leave this open as a reminder. Thanks for the report.

**Comment by mohag** [comment]
Sorry about the close, accidentally clicked something when I wanted to cancel my comment mentioning that the download link, while working, goes via a redirect...

**Comment by jberkenbilt** [comment]
I fixed the tracker link. Thanks for reporting.
