### ISSUE TITLE
Add multi attachment files to PDF

### ISSUE THREAD

**Issue by Andolini-Corleone** [qpdf/qpdf#678]
Hello,

About qpdf 10.6.3, I just would like to know how to add multi attachment files to PDF.

I tested as below.

Please advise.

Thank you in advance.

Best regards,
Ando

===== Test =====

[root@sv tmp]# qpdf --add-attachment a/testtest.jpg -- z.pdf zz.pdf
[root@sv tmp]# qpdf --list-attachments -- zz.pdf
testtest.jpg -> 24,0

[root@sv tmp]# qpdf --add-attachment a/test.jpg -- z.pdf zz.pdf
[root@sv tmp]# qpdf --list-attachments -- zz.pdf
test.jpg -> 24,0

[root@sv tmp]# ls -1 a/
test.jpg
testtest.jpg

[root@sv tmp]# qpdf --add-attachment a/* -- z.pdf zz.pdf
[root@sv tmp]# qpdf --list-attachments -- zz.pdf
testtest.jpg -> 24,0

[root@sv tmp]# qpdf --add-attachment a/testtest.jpg a/test.jpg -- z.pdf zz.pdf
[root@sv tmp]# qpdf --list-attachments -- zz.pdf
test.jpg -> 24,0

[root@sv tmp]# qpdf --add-attachment a/test.jpg a/testtest.jpg -- z.pdf zz.pdf
[root@sv tmp]# qpdf --list-attachments -- zz.pdf
testtest.jpg -> 24,0

[root@sv tmp]# qpdf --add-attachment a/test.jpg --add-attachment a/testtest.jpg -- z.pdf zz.pdf

qpdf: unrecognized argument --add-attachment (attachment options must be terminated with --)

For help:
  qpdf --help=usage       usage information
  qpdf --help=topic       help on a topic
  qpdf --help=--option    help on an option
  qpdf --help             general help and a topic list

[root@sv tmp]#

**Comment by mschilli87** [comment]
You were so close (plus the error mesage gave you the right hint) :wink::

```sh
qpdf --add-attachment a/test.jpg -- --add-attachment a/testtest.jpg -- z.pdf zz.pdf
```

maybe more clear with some linebreaks:
```sh
qpdf \
  --add-attachment a/test.jpg -- \
  --add-attachment a/testtest.jpg -- \
  z.pdf zz.pdf
```

**Comment by jberkenbilt** [comment]
Because each `--add-attachment` can take extra arguments like overriding the filename, time, etc., the wildcard syntax won't work. As you say, there are shell-based options such as

```
qpdf $(foreach f in a/*; do echo -e "--add-attachment $f --"; done) z.pdf zz.pdf
```

**Comment by Andolini-Corleone** [comment]
OK I understand. 
Thank you so much. I really appreciate your help.
I just made another shell-based option, but yours is good.
