### ISSUE TITLE
[Feature request] zopfli compression for compressed streams

### ISSUE THREAD

**Issue by lordsutch** [qpdf/qpdf#68]
For large PDF files that are being served on the web, optionally using the zopfli brute-force compression algorithm for DEFLATE would likely lead to reduced bandwidth needs without increasing decompression overhead.

**Comment by KurtPfeifle** [comment]
It is of not much practical use to implement such a feature into QPDF...

The "allowed" compression scheme for the streams of PDF objects is defined in the ISO document that *standardizes* PDF-1.7, ISO-32000-1. It is not appropriate to implement new "features" into a standardized file format for a single application. If it did so, only this application would be able to process and display that feature, all other PDF readers would no longer do so, and the PDF document in question would have stopped to be *portable*.

If you think zopfli is a good thing to be added to the list of PDF compression schemes, you should start lobbying or becoming active in the ISO committee working on defining the standard of the next version of PDF (2.0), which will become ISO32000-2. Or better even, join the [PDF Association (PDFA.org)](http://www.pdfa.org/) and work from there towards ISO. 

Once zopfli is part of the PDF standard, it is guaranteed that other applications and PDF reader would have enough of incentive to also implement zopfli compression.

Good luck!

**Comment by lordsutch** [comment]
Zopfli is an optimized compressor that outputs 100% compliant DEFLATE streams. (Perhaps you're confusing it with Brotli, which is a new compression format.) See https://github.com/google/zopfli for details.

**Comment by Djfe** [comment]
just to point out further what lordsutch means:
Zopfli is just an optimized deflate compressor.
Every(!) deflate decoder can decompress streams encoded by zopfli.

so it's just something for the encoder end.
You can compare zopfli with what the lame mp3 encoder did for the mp3 specification.
(far higher compression, but still 100% compatibility)
another example would be x264

zopfli is no new compression scheme, just an encoder

currently it's the best deflate encoder and it has been used to further shrink png's without sacrificing any quality
[Zopfli Optimization: Literally Free Bandwidth](https://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/)

if you implement this, then the user should have an option to disable it, because for what it does, it needs a lot of time

**Comment by jarnoh** [comment]
I made a quick test how zopfli works with qpdf: https://github.com/jarnoh/qpdf/commit/6567153651084e1451faa6d265fc35f91fb807e2

**Comment by KurtPfeifle** [comment]
Wouldn't it help the discussion along if someone would take a sample of, say, 100 different real-world PDF files (originating from different PDF generating software apps) and did run a kind of benchmark re-compression test? Then publish the results, answering questions like:

* How much did the complete sample shrink?
* What was the average shrinking percentage?
* What was the smallest/biggest shrink?
* How much time did the re-sampling need for each file and how much on average?
* Which type of PDF files are most rewarding for this re-processing? (Obviously, it must be those which do not use any stream compressions at all, or which use lots of standard deflate, or whose deflate is sub-optimal...)
* etc.pp...

The Zopfli compression idea *sounds* nice (thanks for the explanation, @lordsutch) -- but how *relevant* is it in terms of real-world gains to be harvested?

**Comment by jarnoh** [comment]
I can share my figures, using zopfli enabled qpdf for compressing vector art.

Here is the listing of original files (already processed with qpdf)

```
-rw-------  1 jarnoh  staff   55729 22 Hel 09:33 animal01.pdf
-rw-------  1 jarnoh  staff   71811 22 Hel 09:34 animal02.pdf
-rw-------  1 jarnoh  staff   75100 22 Hel 09:34 animal03.pdf
-rw-------  1 jarnoh  staff   69100 22 Hel 09:34 animal04.pdf
-rw-------  1 jarnoh  staff   84733 22 Hel 09:34 animal05.pdf
-rw-------  1 jarnoh  staff   51422 22 Hel 09:34 animal06.pdf
-rw-------  1 jarnoh  staff   44245 22 Hel 09:34 animal07.pdf
-rw-------  1 jarnoh  staff   34296 22 Hel 09:34 animal08.pdf
-rw-------  1 jarnoh  staff  194651 22 Hel 09:34 animal09.pdf
-rw-------  1 jarnoh  staff  217621 22 Hel 09:34 animal10.pdf
-rw-------  1 jarnoh  staff  147296 22 Hel 09:34 animal11.pdf
-rw-------  1 jarnoh  staff  158499 22 Hel 09:34 animal12.pdf
-rw-------  1 jarnoh  staff  241414 22 Hel 09:34 animal13.pdf
-rw-------  1 jarnoh  staff  318206 22 Hel 09:34 animal14.pdf
-rw-------  1 jarnoh  staff  166594 22 Hel 09:34 animal15.pdf
-rw-------  1 jarnoh  staff  122656 22 Hel 09:34 animal16.pdf
-rw-------  1 jarnoh  staff  189788 22 Hel 09:34 animal17.pdf
-rw-------  1 jarnoh  staff  231674 22 Hel 09:34 animal18.pdf
-rw-------  1 jarnoh  staff  247249 22 Hel 09:34 animal19.pdf
-rw-------  1 jarnoh  staff  160603 22 Hel 09:34 animal20.pdf

```
running zlib based qpdf for these files takes abut 5 seconds:
`        5.17 real         4.33 user         0.55 sys
`
Now, using zopfli enabled version to compress (output by separate shell script):

```
animal01.pdf: was 55729 optimized 51161 bytes (success!)
animal02.pdf: was 71811 optimized 65932 bytes (success!)
animal03.pdf: was 75100 optimized 69092 bytes (success!)
animal04.pdf: was 69100 optimized 63426 bytes (success!)
animal05.pdf: was 84733 optimized 77807 bytes (success!)
animal06.pdf: was 51422 optimized 47133 bytes (success!)
animal07.pdf: was 44245 optimized 40468 bytes (success!)
animal08.pdf: was 34296 optimized 31280 bytes (success!)
animal09.pdf: was 194651 optimized 174846 bytes (success!)
animal10.pdf: was 217621 optimized 198036 bytes (success!)
animal11.pdf: was 147296 optimized 133068 bytes (success!)
animal12.pdf: was 158499 optimized 143675 bytes (success!)
animal13.pdf: was 241414 optimized 219349 bytes (success!)
animal14.pdf: was 318206 optimized 286062 bytes (success!)
animal15.pdf: was 166594 optimized 150502 bytes (success!)
animal16.pdf: was 122656 optimized 112917 bytes (success!)
animal17.pdf: was 189788 optimized 170020 bytes (success!)
animal18.pdf: was 231674 optimized 209126 bytes (success!)
animal19.pdf: was 247249 optimized 224248 bytes (success!)
animal20.pdf: was 160603 optimized 146318 bytes (success!)
       45.71 real        43.87 user         1.45 sys

```       
Originals are total of 2882687 bytes and zopfli compressed total for 2614466, giving about 260kB (10%) space savings in exchange for 40 seconds (~800%) increase in runtime.

**Comment by Djfe** [comment]
doesn't sound that useful sadly (except if many many people will be downloading your file over the internet)
which cpu are you using?
and what are your compression settings for zopfli?

**Comment by lordsutch** [comment]
I wouldn't necessarily want it to be the default setting, but for some applications (PDFs hosted on websites, especially combined with linearization) it could be a real bandwidth win for relatively low cost.

**Comment by jarnoh** [comment]
@Djfe CPU is i7 2.5GHz.  zopfli encoding uses all default settings, I think it's 15 iterations.

We use these PDFs for a digital coloring book downloads, and while the bandwidth cost is marginal, I think it's always win if the results is a faster download for the end user.  Originally, the files were 3869226 bytes, but I'll still take 33% (zopfli) saving over 25% (zlib).

**Comment by TPS** [comment]
If this is something even contemplated, maybe better to _not_ use official (https://github.com/google/zopfli), but optimized Zopfli (e.g., https://github.com/MrKrzYch00/zopfli) instead?

**Comment by jberkenbilt** [comment]
One of the selling points of qpdf is that it has very few external dependencies. In 7.0.0, only zlib will remain as I am actively removing pcre as an external dependency. I'm not at all interested in having qpdf built standard with an alternative zlib implementation that has to be a build-time dependency, though I would consider, if the licensing terms permit it, embedding some of this into qpdf and dropping zlib as a dependency. I'd have to take a closer look. Probably not for 7.0.0, but we'll see.

**Comment by jberkenbilt** [comment]
Once again, I appreciate the suggestion, but I'm going to not change the zlib encoding from zlib in qpdf. I think the need to preserve compatibility with previous output files for testing purposes and the very strong desire to keep as free as possible of external dependencies exceeds the potential speed or time benefit. Of course, users are free to rebuild qpdf on their own with alternative libraries, and I will certainly consider patches to the build code or otherwise that make it easier to do this.

**Comment by jberkenbilt** [comment]
To anyone following, zopfli support will be in qpdf 11.10. See #1323.
