### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#683]
Hi,

I'm programming agains the JSON interface and try to encrypt a file with these settings, but that always fails. Do you know what I'm doing wrong?

```json
{
  "inputFile": "TestFiles\test.pdf",
  "outputFile": "C:\\3eb6fc52-800f-4c32-a5fb-9ad1709d5260\\output_encryption_256_bit.pdf",
  "linearize": "",
  "encrypt": {
    "256bit": {
      "accessibility": "y",
      "annotate": "y",
      "assemble": "y",
      "extract": "y",
      "form": "y",
      "modifyOther": "y",
      "modify": "all",
      "print": "full",
      "cleartextMetadata": "y"
    },
    "userPassword": "user",
    "ownerPassword": "owner"
  }
}
```

**Comment by Sicos1977** [comment]
Is it also possible to write something back to the console when something goes wrong so that I have a clue why it is failing. The only thing I now have is an exit code but that does not point me to the place where it is failing.

**Comment by Sicos1977** [comment]
It seems to be failing on the `cleartextMetadata `property, but the manual says that this is an option of the 256 bit encryption

**Comment by Sicos1977** [comment]
Also have a question about the related options --> https://qpdf.readthedocs.io/en/stable/cli.html?highlight=ranges#id13

Do they only work when encrypting or can these also be used without it?

**Comment by jberkenbilt** [comment]
One thing is that  you will need to quote your backslashes (`C:\\whatever`) or use forward slashes (`C:/whatever`) which should work fine. I'll read the rest and reply when I get a chance -- I'm in meetings and appointments most of the day.

**Comment by Sicos1977** [comment]
The double \\ were in the JSON, I just removed them for readability.

**Comment by jberkenbilt** [comment]
> It also seems that this is not correct in the manual
> 
> --modify=[y|n]	restrict document modification
> --print=[y|n]	restrict printing
> It expects an enum instead of a y or n value

It's not wrong. The table header shows that as 40-bit only. The enum is for 128-bit and 256-bit.

**Comment by jberkenbilt** [comment]
The value should be the empty string, not `"y"`. It's confusing, but this is based on the CLI, and from the CLI, it's `--cleartext-metadata`, not `--cleartext-metadata=y`. If I run `qpdf --job-json-file=yourfile.json`, I see
```
qpdf: error with job-json file /tmp/a.json: .encrypt.256bit.cleartextMetadata: value must be the empty string
Run qpdf--job-json-help for information on the file format.

For help:
  qpdf --help=usage       usage information
  qpdf --help=topic       help on a topic
  qpdf --help=--option    help on an option
  qpdf --help             general help and a topic list
```

As far as I know, this would go to the console.

**Comment by jberkenbilt** [comment]
> The double \ were in the JSON, I just removed them for readability.

Noted, but it doesn't improve readability to replace a syntactically correct json with a syntactically incorrect json. :-)

**Comment by jberkenbilt** [comment]
Sorry for all the little messages. I believe I have answered your question. Please let me know if I have not answered something that you asked or if you have follow-up questions. Thanks!

**Comment by Sicos1977** [comment]
Is it possible to add a callback option the the qpdfjob_run_from_json method so that I can get back what is output in stdout en stderr so that I can get back error messages and things like that. 

I tried to capture the console output from C# but this far I have no luck getting anything back.

**Comment by Sicos1977** [comment]
I also see this in the QPDFJob class, is there a way to set them from the API?

    // Override streams that errors and output go to. Defaults are
    // std::cout and std::cerr. Pass nullptr to use the default.
    QPDF_DLL
    void setOutputStreams(std::ostream* out_stream, std::ostream* err_stream);

**Comment by Sicos1977** [comment]
In C# I can do something like this that calls into the QPDF dll

```c#
        var instance = QPdfApi.Native.Init();
        var result = QPdfApi.Native.RunFromJSON(json);
        var warning = QPdfApi.Native.MoreWarnings(instance);
        var hasError = QPdfApi.Native.HasError(instance);
        if (hasError)
        {
            var error = QPdfApi.Native.GetErrorFullText(instance);
        }
```

But hasError always gives me a `false` but I guess that is because the pointer I have got from Init is not the same as where the RunFromJSON (that calls qpdfjob_run_from_json) point to

**Comment by jberkenbilt** [comment]
The qpdf-c.h and qpdfjob-c.h APIs are disjointed. Being able to trap stdout, etc., is definitely on the roadmap. Sorry if the qpdfjob API seems bare. It is really just a json wrapper around passing command-line arguments and is just slightly tighter integration than communicating with qpdf as a subprocess. So right now it doesn't really do enough for a full qpdf wrapper into another language except for stuff that could be done with the CLI. Your questions are helpful in letting me know what the priorities should be though. A few of the other items I'd like to consider are

* Making sure json output can replace all the calls that currently print information to stdout (`--check`, `--show-object`, --show-linearization`, etc.)
* Custom progress reporter
* Some kind of interface for replacing objects (maybe)
* Possibly json output mode instead of stdout/stderr
* Job chaining -- essentially the ability to do something that would cover multiple qpdf commands, though you can often combine multiple operations

This is not terribly high priority. There are two big things in front of it: JSON v2 (full bidirectional serialization/deserialization between PDF and JSON) and a higher-level document manipulation API that I will probably reimplement much of QPDFJob on top of. This in turn clears the way for supporting many more document-level features in page splitting, which are by far the most requested features.

**Comment by Sicos1977** [comment]
So that I understand it correctly

_Making sure json output can replace all the calls that currently print information to stdout (--check, --show-object, --show-linearization`, etc.)_

So at the moment these commands sent nothing to the console?

**Comment by Sicos1977** [comment]
Is it possible for you to add this as a temporary solution so that I can get the output from qpdf. I tried every possible solution in C# but am not able to get the output from the console.

https://stackoverflow.com/questions/2513312/nunit-does-not-capture-output-of-stdcerr

**Comment by jberkenbilt** [comment]
@Sicos1977 You are asking for capture of stdout/stderr? How would you want the feature to work? What I had in mind was that it would be possible to pass in a function that would take `(char const* data, unsigned int len, QPDF_BOOL error)` that would be called for errors. It's not a quick change as it would potentially touch every place in the code where an error or output might be generated, and it's not something I would release before qpdf 11 because I have made major code changes that are ABI breaking that would make it very hard for me to release anything in the 10.x series. I'm not committing to the exact specification above, but that's the general idea of what I had in mind. I will have to make something that is possible to implement and that can work well with the C and C++ API.

**Comment by Sicos1977** [comment]
The problem I have now that most methods works, but for example the Check method dumps all the information to the console (stdout) and errors are going to (stderr). For some reason visual studio 2022 can capture them but what every I try myself to capture both those streams I always end up with an empty string. 

I tried all different kind of solution I found with Google but so far no luck. The only quick solution that I found is the one that is mentioned on stackoverflow. I tried to add it myself but I even can't get the code to build on my Windows 11 system.

What they mention on stack trace is to replace the output en error stream and then they get the output like this.

```c#
public static class Redirector
{
    // PRIVATE ------------------------------------------------------------
    private const String LibraryName = "MyCpp.dll";

    [DllImport(LibraryName, CharSet = CharSet.Ansi)]
    private static extern IntPtr getCerr();

    // PUBLIC -------------------------------------------------------------
    [DllImport(LibraryName, CharSet = CharSet.Ansi)]
    public static extern bool Redirect();

    [DllImport(LibraryName, CharSet = CharSet.Ansi)]
    public static extern void Revert();

    [DllImport(LibraryName, CharSet = CharSet.Ansi)]
    internal static extern void freeCharPtr(IntPtr ptr);

    public static string GetCerr()
    {
        IntPtr temp = getCerr();
        string result = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(temp);
        freeCharPtr(temp);
        return result;
    }
}
```

That seems to be a quick temporary fix before implementing a solid solution. I'm still looking if I can get the output another way but I have no idea how Visual Studio manages to capture it.

**Comment by Sicos1977** [comment]
Can you tell me with what tool qpdf is written? I tried to search for a project file in the sources but did not find any that I know.

**Comment by Sicos1977** [comment]
@jberkenbilt : I don't know if this message is also for Windows users

```
if(${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_BINARY_DIR})
  message(FATAL_ERROR "
Please build with cmake in a subdirectory, e.g.
 mkdir build
 cmake ..
 cmake --build .
Please remove CMakeCache.txt and the CMakeFiles directories.")
endif()
```

But on Windows it needs to be

```
if(${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_BINARY_DIR})
  message(FATAL_ERROR "
Please build with cmake in a subdirectory, e.g.
 md build
 cd build
 cmake ..
 cmake --build .
Please remove CMakeCache.txt and the CMakeFiles directories.")
endif()
```

**Comment by Sicos1977** [comment]
When switching to release mode it builds without any problems... so it has something todo with debug mode.

**Comment by jberkenbilt** [comment]
It's in the docs -- the external-libs release with qpdf only supports release mode. Debugging runtimes are not redistributable. If you need debugging versions, you will have to obtain debugging versions of the external libraries or build them yourself. For debugging purposes, you can get by with native crypto. qpdf's native crypto implementation is at functional parity and has no known vulnerabilities, but it isn't as performant as the external libraries and is considered a security risk because it won't benefit from security fixes in the external libraries which get more scrutiny than qpdf. (There may come a day when qpdf will require external crypto if I ever implement digital signature support, which I hope to do.)

**Comment by Sicos1977** [comment]
At the moment I'm trying to add a new method to the library to see if I can make my C# code work with that. I tried to return a parameter by reference.

```c++
int
qpdfjob_run_from_json_with_result(char const* json, char const*& cout_result, char const*& cerr_result)
{
    std::streambuf* old_cout_stream_buf = std::cout.rdbuf();
    std::streambuf* old_cerr_stream_buf = std::cerr.rdbuf();

    std::ostringstream stream_cout;
    std::cout.rdbuf(stream_cout.rdbuf());
    std::ostringstream stream_cerr;
    std::cerr.rdbuf(stream_cerr.rdbuf());

    QPDFJob j;
    try {


        j.initializeFromJson(json);
        j.run();

    }
    catch (std::exception& e) {
        std::cerr << "qpdfjob json: " << e.what() << std::endl;
        return QPDFJob::EXIT_ERROR;
    }

    const std::string& cout_tmp = stream_cout.str();
    cout_result = cout_tmp.c_str();
    const std::string& cerr_tmp = stream_cout.str();
    cerr_result = cerr_tmp.c_str();

    std::cout.rdbuf(old_cout_stream_buf);
    std::cerr.rdbuf(old_cerr_stream_buf);

    return j.getExitCode();
}
```

```c++
    QPDF_DLL
    int qpdfjob_run_from_json_with_result(char const* json, char const*& cout_result, char const*& cerr_result);
```

It gives a compile error and after searching on Google I did read that references are not supported in C so I think that is the reason.

Do you have soms tips about how to do this and otherwise I try to make some other solution tomorrow because it is already 10PM overhere.

What I hope to achieve is that I can return the result from cout and cerr this way as a quick fix until a better solution is made.

**Comment by jberkenbilt** [comment]
C has pointers but not references, so this would have to be `char const** cout_result`. I doubt I would accept a pull request that does this though. I don't think the qpdf library should provide a solution that allocates and copies a potentially very large amount of memory, which could happen if someone wants to write a PDF file to stdout, and I'd have to give this some more thought before committing to a specific API.

That said, implementing such functionality from C++ would be fairly easy. Using `QPDFJob::setOutputStreams` takes `std::ostream*`. It would be possible to pass pointers to `std::ostringstream` objects. You could write a function something like this (not tested):

```c++
#include <qpdf/QPDFJob.hh>
#include <qpdf/QUtil.hh>
#include <sstream>

extern "C" int
qpdfjob_run_from_json_with_result(
    char const* json, char const** cout_result, char const** cerr_result)
{
    int result = 0;
    std::ostringstream cout;
    std::ostringstream cerr;
    QPDFJob j;
    j.setOutputStreams(&cout, &cerr);
    try {
        j.initializeFromJson(json);
        j.run();
        result = j.getExitCode();
    } catch (std::exception& e) {
        std::cerr << "qpdfjob json: " << e.what() << std::endl;
        result = QPDFJob::EXIT_ERROR;
    }
    *cout_result = QUtil::copy_string(cout.str());
    *cerr_result = QUtil::copy_string(cerr.str());
    return result;
}
```

`cout_result` and `cerr_result` would be initialized to dynamically allocated memory that would have to be freed with `delete[]` so you might have to write something like

```c++
extern "C" void
free_string(char const* str)
{
    delete[] str;
}
```

to which you would have to pass the cout_result and cerr_result pointers. Note that you would pass the address of the pointers to the first function and the pointers themselves to the second function. It would also be possible to allocate the string with malloc by adding a new `QUtil`` method along with the other three styles of string copiers.

I'm not totally opposed to this, but I'd rather come up with an interface that would be safer and more responsive than put this in the library. But maybe it can get you unstuck.

**Comment by Sicos1977** [comment]
Thanks you are a life safer, that was exactly what I needed. I agree that it is better to have somethink like the way how Ghostscript does it but that is way to difficult for me to implement it myself. What I said... it is yearssss ago since I have written something in C or C++ and yes I can read and somewhat understand wat qpdf is doing but it would take me forever to implement something.

![image](https://user-images.githubusercontent.com/6692947/163731899-be746c01-90c3-4741-9bc5-87a907ef7244.png)

For the moment this will do fine.

**Comment by Sicos1977** [comment]
I now implemented it like this

```c++
int
qpdfjob_run_from_json_with_result(char const* json, char const** cout_result, char const** cerr_result)
{
    int result = 0;

    std::ostringstream cout;
    std::ostringstream cerr;
    QPDFJob j;

    j.setOutputStreams(&cout, &cerr);

    try {
        j.initializeFromJson(json);
        j.run();
        result = j.getExitCode();
    }
    catch (std::exception& e) {
        std::cerr << "qpdfjob json: " << e.what() << std::endl;
        result = QPDFJob::EXIT_ERROR;
    }

    *cout_result = QUtil::copy_string(cout.str());
    *cerr_result = QUtil::copy_string(cerr.str());
    return result;
}

void
qpdfjob_run_from_json_with_result_free_string(char const* str)
{
    delete[] str;
}
```

**Comment by Sicos1977** [comment]
Releasing the memory with free_string seems not needed in C# there is a method that does the same called `Marshal.FreeCoTaskmem`

In C# my method now looks like this and is working fine.

```c#
    #region Run
    /// <summary>
    ///     Runs the job with the given parameters
    /// </summary>
    /// <returns>
    ///     <see cref="ExitCodes" />
    /// </returns>
    public ExitCodes Run(out string output)
    {
        var settings = new JsonSerializerSettings
        {
            DefaultValueHandling = DefaultValueHandling.Ignore, 
            Formatting = Formatting.Indented
        };

        settings.Converters.Add(new StringEnumConverter());

        var json = JsonConvert.SerializeObject(this, settings);

        var result = QPdfApi.Native.RunFromJSONWithResult(json, out var outPointer, out var errorPointer);

        var outResult = Marshal.PtrToStringAnsi(outPointer);
        var errorResult = Marshal.PtrToStringAnsi(errorPointer);

        Marshal.FreeCoTaskMem(outPointer);
        Marshal.FreeCoTaskMem(errorPointer);

        //output = builder.ToString();

        output = string.Empty;

        return result;
    }
    #endregion
```

**Comment by Sicos1977** [comment]
The only things that I seem to be missing are the warnings. But that will be something to look into for tomorrow... already to late here.

![image](https://user-images.githubusercontent.com/6692947/163732528-fb7ae169-cbba-4a60-8262-754820394e1c.png)

**Comment by Sicos1977** [comment]
Is there a reason that the exception details do not get into the cerr stream? Is that because of pointers?

![image](https://user-images.githubusercontent.com/6692947/163801381-5afd9946-5230-4ac0-8da7-ad5a51a6a59c.png)

**Comment by jberkenbilt** [comment]
It's because the exception should be `cerr`, not `std::cerr`.

**Comment by Sicos1977** [comment]
Yes that solved it... now I understand it was writing the error to the default cerr stream instead of the one I needed to get it returned.

**Comment by Sicos1977** [comment]
Really have to get used to the way C and C++ is doing its things compared to C# :-)

**Comment by jberkenbilt** [comment]
In spite of having worked in a wide range of languages, I have never used C#.

**Comment by Sicos1977** [comment]
> In spite of having worked in a wide range of languages, I have never used C#.

There are just to many programming languages and ways to solve the same problem.

I gave it up years ago to get good in every kind of programming language and did stick with c#

**Comment by Sicos1977** [comment]
> The only things that I seem to be missing are the warnings. But that will be something to look into for tomorrow... already to late here.
> 
> ![image](https://user-images.githubusercontent.com/6692947/163732528-fb7ae169-cbba-4a60-8262-754820394e1c.png)

Do you also have some hints for me about how to get these warnings into cerr or cout?

I see that this code produces those errors but have no idea how they end up in the console in the end

```c++
            if (length != h_length) {
                errors.push_back(
                    "shared object " + QUtil::int_to_string(i) +
                    " length mismatch: hint table = " +
                    QUtil::int_to_string(h_length) +
                    "; computed = " + QUtil::int_to_string(length));
            }
```

**Comment by Sicos1977** [comment]
I manged to get them by adding the last line in the code below

```c+
void
QPDFJob::run()
{
    checkConfiguration();
    std::shared_ptr<QPDF> pdf_ph;
    try {
        pdf_ph = processFile(m->infilename.get(), m->password.get(), true);
    } catch (QPDFExc& e) {
        if ((e.getErrorCode() == qpdf_e_password) &&
            (m->check_is_encrypted || m->check_requires_password)) {
            // Allow --is-encrypted and --requires-password to
            // work when an incorrect password is supplied.
            this->m->encryption_status =
                qpdf_es_encrypted | qpdf_es_password_incorrect;
            return;
        }
        throw e;
    }
    QPDF& pdf = *pdf_ph;

    pdf.setOutputStreams(this->m->cout, this->m->cerr);
```

**Comment by Sicos1977** [comment]
How does this exactly work --> https://qpdf.readthedocs.io/en/stable/cli.html?highlight=ranges#option-show-object

Are there a fixed kind of object that I can put in an enum or can it be anything?

**Comment by jberkenbilt** [comment]
Yes, good catch on the output streams. I think this is the correct fix, but I will want to add some tests.
```patch
diff --git a/libqpdf/QPDFJob.cc b/libqpdf/QPDFJob.cc
index b8d91b69..af7a7c38 100644
--- a/libqpdf/QPDFJob.cc
+++ b/libqpdf/QPDFJob.cc
@@ -703,6 +703,7 @@ QPDFJob::getEncryptionStatus()
 void
 QPDFJob::setQPDFOptions(QPDF& pdf)
 {
+    pdf.setOutputStreams(this->m->cout, this->m->cerr);
     if (m->ignore_xref_streams) {
         pdf.setIgnoreXRefStreams(true);
     }
```

**Comment by jberkenbilt** [comment]
> How does this exactly work --> https://qpdf.readthedocs.io/en/stable/cli.html?highlight=ranges#option-show-object
> 
> Are there a fixed kind of object that I can put in an enum or can it be anything?

It is either `trailer` or a numeric object or object,generation to name an object in the PDF. This is a basic aspect of PDF structure. A good tip for understand how things are to be used is to look for them in the test suite. qpdf's test suite is extremely thorough and should exercise the full functionality of the library and CLI.

**Comment by Sicos1977** [comment]
If you are curious about what I'm doing in C#, here you can find what I have made so far .. the most options are in the Job class --> https://github.com/Sicos1977/QPdfNet/blob/main/QPdfNet/Job.cs

The more advanced options I still have to add because that requires me to build classes for them. You can see some examples overhere that I already made to encrypt PDF's --> https://github.com/Sicos1977/QPdfNet/tree/main/QPdfNet

**Another thing wat I think is missing is the NoWarn option in the qpdfJob class.. When I set it I still get the warnings so I think this option is not passed to the PDF object**

**Comment by jberkenbilt** [comment]
A fix for the not passing cout/cerr is in CI. I'm not sure what you mean about NoWarn. As far as I can recall, there is no such option for QPDFJob other than just as part of the regular config. Are you saying `config()->noWarn()` doesn't work? That option only disables warnings about the PDF. It doesn't disable usage warnings, etc.

**Comment by Sicos1977** [comment]
What I mean is this. When I run my test.pdf file I now get the following:

This is the output with `WARNING:` lines
![image](https://user-images.githubusercontent.com/6692947/163841570-7c575b9b-96ef-4220-afe4-60f76b4f1d2c.png)

With the .NoWarn option I would expect for those lines to disapear... or am I making a wrong assumption?

![image](https://user-images.githubusercontent.com/6692947/163841814-0c7b9c64-3e9b-43b7-9908-3c8914bfa104.png)

**Comment by Sicos1977** [comment]
--no-warn[](https://qpdf.readthedocs.io/en/stable/cli.html?highlight=ranges#option-no-warn)
Suppress writing of warnings to stderr. If warnings were detected and suppressed, qpdf will still exit with exit code 3. To completely ignore warnings, also specify [--warning-exit-0](https://qpdf.readthedocs.io/en/stable/cli.html?highlight=ranges#option-warning-exit-0). Use with caution as qpdf is not always successful in recovering from situations that cause warnings to be issued.

**Comment by Sicos1977** [comment]
WarningExit0 works as expected (_warningExit0)

**Comment by jberkenbilt** [comment]
These are linearization warnings. Most likely the issue is that linearization warnings aren't treated in the same way, in spite of the WARNING prefix, because linearization checks are only run when specifically requested (via `--check` or `--check-linearization` or perhaps `--show-linearization`) and are otherwise ignored. Combining `--check` with ``-no-warn` seems like an odd usage pattern. All linearization errors are considered warnings since qpdf doesn't depend on correct linearization tables for any operation, so combining `--check` with `--no-warn` would always suppress any useful information from linearization checks. The linearization checks follow probably the oldest code path in qpdf that hasn't been updated. It would be good to rewrite it, but it's low priority.

**Comment by Sicos1977** [comment]
I have no problems with it that the warnings don't go away but just was making unit tests and ran into that issue. Since I never used qpdf before with those options I didn't know what to expect... so I was wondering if I did something wrong.

**Comment by Sicos1977** [comment]
Is it possible to add a section on the qpdf github page so that they know there will be C# wrapper for it?

For example a section... Other language bindings ... or something like that.

https://github.com/Sicos1977/QPdfNet

**Comment by Sicos1977** [comment]
Do you have an example somehere how the json will look like for the pages option?

https://qpdf.readthedocs.io/en/stable/cli.html#option-pages

**Comment by Sicos1977** [comment]
Nevermind... have to read :-) ... guess that is part of the pages option :-)

```json
{
  "inputFile": "infile.pdf",
  "outputFile": "outfile.pdf",
  "pages": [
    {
      "file": "."
    },
    {
      "file": "other.pdf",
      "password": "x",
      "range": "1-5"
    }
  ],
  "encrypt": {
    "userPassword": "user",
    "ownerPassword": "owner",
    "256bit": {
      "print": "low"
    }
  },
  "objectStreams": "generate"
}
```

**Comment by Sicos1977** [comment]
At the moment I'm making unit test and want to say how well your json implementation works... very nice work that you did here.

**Comment by jberkenbilt** [comment]
As you unit test, keep in mind that things like the exact wordings of qpdf messages may change from version to version. They are fairly stable, but if I were to do something like clean up the linearization warnings or change the internal error message API (which I intend to do before qpdf 11) and clarify/reword messages, these things could change. As always with writing wrappers, you should try to make sure your unit tests are testing your wrapper rather than testing qpdf through your wrapper. Having some dependency on qpdf will be unavoidable, but you will want to try to see if you can minimize the impact of new qpdf versions on your tests.

Regarding mentioning your project from the qpdf docs, what I've done is to create a [wiki page](https://github.com/qpdf/qpdf/wiki/qpdf-Wrappers) and listed it there. I'd consider mentioning it in the manual if it becomes a mature, fully-featured C# interface for qpdf the way pikepdf is for Python, but I don't think that's actually a goal. In any case, I have added a link to the wiki page, so people reading the section in the qpdf manual about using qpdf from other languages can discover it.

**Comment by Sicos1977** [comment]
Thanks, that is a good solution adding a wiki page. I'll just want to avoid that people try to reinvent the same wheel more then once because I know how much work it can be to write something "simple" as a wrapper around another library.

I also don't mind if there are some breaking changes in the json interface, that is something you sometimes can't avoid and that is because I'm making unit test to make sure that I detect breaking changes before releasing a new package.  

It is also not a problem if the versions get somewhat out of sync because I include a compiled version of qpdf in the .net package that I'm going to release on nuget (because I also modified the json interface somewhat to get back everything from cout and cerr) so that people just have to install the package in there C# ide and have everything they need.

I also want to include some more advanced options in the C# nuget package but the current to be released package is a good starting point for most people if they want to do the basic things. Making wrappers from C# to C++ sometimes can be very difficult because of the different object types you have between both programming languages. I find is sometimes very difficult to marshal object from C# to C++ because of the ways interfaces are made in both languages, very often they are simular but makes it a hell of a job to make them work without crashing,

**Comment by Sicos1977** [comment]
I copied some information from the read.me on your GitHub page to my GitHub page, hope you don't mind. If you do then let me know and I will remove it. It is just to point people in the good direction if they are looking for more information about QPDF

**Comment by jberkenbilt** [comment]
No objections -- you don't need my permission to copy from/reference my readme in yours.

**Comment by Sicos1977** [comment]
Why does the check method needs an output file?

The manual says --> Check the file’s structure as well as encryption, linearization, and encoding of stream data, and write information  about the file to standard output

Is the standard output not just writing to the console?

![image](https://user-images.githubusercontent.com/6692947/164291579-c8319e44-1a6d-4a7e-84b4-dab17f036dd4.png)

**Comment by Sicos1977** [comment]
When using this code in my test project

```c#
            var job = new Job();
            var result = job.InputFile(Path.Combine("TestFiles", "withattachment.pdf"))
                .ShowAttachments("20_pages.pdf")
                .Run(out var output);
```

I would expect that the attachment is written to the redirected output stream but instead it is written to cout. So I suspect that somewhere the redirection of the error and output streams is not set.

**Comment by Sicos1977** [comment]
I think the problem is in this code

```c++
    QPDFEmbeddedFileDocumentHelper efdh(pdf);
    auto fs = efdh.getEmbeddedFile(m->attachment_to_show);
    if (!fs) {
        throw std::runtime_error(
            "attachment " + m->attachment_to_show + " not found");
    }
    auto efs = fs->getEmbeddedFileStream();
    QUtil::binary_stdout();
    Pl_StdioFile out("stdout", stdout);
    efs.pipeStreamData(&out, 0, qpdf_dl_all);
```

**Comment by jberkenbilt** [comment]
Yes, please create a separate issue for that.

**Comment by jberkenbilt** [comment]
It's not a trivial fix because of FILE* vs. std::ostream. I'll probably have to add a new pipeline.

**Comment by Sicos1977** [comment]
Okey I did make a new issue

**Comment by Sicos1977** [comment]
I'm trying to remove an attachment from a PDF file like this

```json
{
  "inputFile": "TestFiles\\withattachment.pdf",
  "outputFile": "test.pdf",
  "removeAttachment": [
    "20_pages.pdf"
  ]
}
```

But get this error, I guess the json is wrong but what does QPDF expect to get?

`qpdfjob json: JSON handler: value at .removeAttachment is not of expected type`

**Comment by Sicos1977** [comment]
When running this json command

```json
{
  "inputFile": "TestFiles\\20_pages.pdf",
  "outputFile": "output.pdf",
  "overlay": {
    "file": "TestFiles\\test.pdf"
  }
}
```

I would expect all the 20 pages to have the overlay but only the first page has it.

[output.pdf](https://github.com/qpdf/qpdf/files/8549921/output.pdf)

**Comment by Sicos1977** [comment]
That is all I found with my unit test, for the rest everything is working according to the manual.

**Comment by jberkenbilt** [comment]
It's a bug that `removeAttachment` doesn't take an array. Thanks for catching that. I guess I don't have any test cases for that specifically. I'll check to see if any other repeatable options are not correct.

The overlay/underlay is working according to expectation, assuming your test.pdf has one page. Perhaps the documentation needs to be clarified? The `"to"` argument restricts which pages of the output to apply the overlay to but doesn't otherwise change the behavior that overlay stops when the source file runs out of pages unless `"repeat"` is given.

**Comment by Sicos1977** [comment]
> It's a bug that `removeAttachment` doesn't take an array. Thanks for catching that. I guess I don't have any test cases for that specifically. I'll check to see if any other repeatable options are not correct.

I made a new issue for this bug.

> 
> The overlay/underlay is working according to expectation, assuming your test.pdf has one page. Perhaps the documentation needs to be clarified? The `"to"` argument restricts which pages of the output to apply the overlay to but doesn't otherwise change the behavior that overlay stops when the source file runs out of pages unless `"repeat"` is given.

You are right, the test.pdf has only one page.

**Comment by Sicos1977** [comment]
I just released a first nuget package for C# so that people can use QPDF from C# .NET. You can find it over here --> https://www.nuget.org/packages/QPdfNet/
