### ISSUE TITLE
Docs doesn't mention the need to keep QPDF instances around on copying pages.

### ISSUE THREAD

**Issue by tschoening** [qpdf/qpdf#69]
Today I ran into different access violations on merging 2 PDF files because I created QPDF instances for both files locally, merged them by pages depending on some condition and returned only one of both objects as needed. So the other one got destroyed in the mean time and that lead to access violations on writing the kept object in QPDFWriter::write.

I don't find that behavior obvious, because to me the docs read like I could only keep that object which was the merge target and contains those pages I want to write into a file again. But that doesn't seem to work for me, I need to keep the source object around as well. Currently I have only two files, but think of merging tens of them... To me the docs don't read like I need to keep all those src instances around until the data was written.

Or am I doing something wrong? My test is pretty easy, leaking the src object and everything works, keep it in local scope and let it beeing destroyed and access violations occur.

If this is intended, please add some sentence saying so in the manual AND in the QPDF.hh. Thanks!

**Comment by jberkenbilt** [comment]
I will look into this and make sure the documentation is clear before the next release of qpdf. Thanks for taking the time to report this. Sorry for taking so many months to reply.
