### ISSUE TITLE
I'm trying to remove an attachment from a PDF file like this in a test case

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#693]
I'm trying to remove an attachment from a PDF file like this in a test case

```json
{
  "inputFile": "TestFiles\\withattachment.pdf",
  "outputFile": "test.pdf",
  "removeAttachment": [
    "20_pages.pdf"
  ]
}
```

But get this error, I guess the json is wrong but what does QPDF expect to get?

`qpdfjob json: JSON handler: value at .removeAttachment is not of expected type`

In the code I see that it expects a string as input

```c++
QPDFJob::Config::removeAttachment(std::string const& parameter)
{
    o.m->attachments_to_remove.push_back(parameter);
    return this;
}
```

But the manual says that 

--remove-attachment=key[](https://qpdf.readthedocs.io/en/stable/cli.html?highlight=remove-attachment#option-remove-attachment)
Remove the specified attachment. This doesn’t only remove the attachment from the embedded files table but also clears out the file specification to ensure that the attachment is actually not present in the output file. That means that any potential internal links to the attachment will be broken. Run with [--verbose](https://qpdf.readthedocs.io/en/stable/cli.html?highlight=remove-attachment#option-verbose) to see status of the removal. Use [--list-attachments](https://qpdf.readthedocs.io/en/stable/cli.html?highlight=remove-attachment#option-list-attachments) to find the attachment key. **`This option may be repeated to remove multiple attachments.`**

So I would expect it to use an array as input... or is this a wrong assumption?

As far as I know keys in json must be unique so generating something like this would be invalid json

```json
{
  "inputFile": "TestFiles\\withattachment.pdf",
  "outputFile": "test.pdf",
  "removeAttachment": "1.pdf"
  "removeAttachment": "2.pdf"
}
```

https://datatracker.ietf.org/doc/html/rfc8259#section-4

So I would expect this

```json
{
  "inputFile": "TestFiles\\withattachment.pdf",
  "outputFile": "test.pdf",
  "removeAttachment": [
    "1.pdf",
    "2.pdf"
  ]
}
```

My test with the jsonKey works as I would expect removeAttachment to work

```json
{
  "inputFile": "TestFiles\\withattachment.pdf",
  "json": "",
  "jsonKey": [
    "attachments",
    "encrypt"
  ]
}
```

_Originally posted by @Sicos1977 in https://github.com/qpdf/qpdf/issues/683#issuecomment-1107842023_

**Comment by jberkenbilt** [comment]
Thanks -- a fix will be in main as soon as it gets through CI. I appreciate your thorough testing.
