### ISSUE TITLE
Question: Is there an easy way to get this kind of information

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#697]
With the JSON method I can return a json string with all the objects that are inside the PDF.

One of the objects contains the information below.

```json
    "2 0 R": {
      "/Author": "",
      "/CreationDate": "D:20190812073543",
      "/Creator": "ECM Document Services",
      "/ModDate": "D:20190812073543+02'00'",
      "/Producer": "ECM Document Services",
      "/Subject": ""
    },
```

Is there a way so that I always only get this information back? I want to parse this information out of the json string but I need to find it somehow.

**Comment by jberkenbilt** [comment]
You have to understand the PDF spec to mine information from the JSON in general. For example, this stuff comes from the information dictionary which is the destination of `/Info` in the trailer dictionary, so the `"trailer"` entry will have an `/Info` key with the value `"2 0 R"`. Note that I am changing this around for json v2 which will be more powerful. You will still have to understand the PDF specification to mine the PDF for information using JSON though. Think of it is just a simpler syntax for the semantics.
