### ISSUE TITLE
Question about repairing a PDF

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#698]
Hi,

I have a PDF that gives this error, another program that tries to work with that PDF crashes  because of that.

Is there a way to repair this PDF with QPDF so that I get rid of this warning?

WARNING: $-9162465d-21b4-4163-b0c7-b8ab9449175e#-2022-05-01-14-49-15.pdf (object 1018 0): object has offset 0
qpdf: operation succeeded with warnings; resulting file may have some problems

**Comment by jberkenbilt** [comment]
qpdf will always attempt repair this. It will never write an output file that is structurally invalid. Just run `qpdf in.pdf out.pdf`, and the output file will not have this issue. Depending on the nature of the damage, there is no guarantee that `out.pdf` will contain all the data intended in `in.pdf`, but that's true of any situation in which qpdf tries to repair a broken file.
