### ISSUE TITLE
Exception: unknown object type inspecting /Contents key in page dictionaryAdded option MediaType

### ISSUE THREAD

**Issue by zhangyonglin911** [qpdf/qpdf#703]
When I print a PDF document on cups, I encounter some error messages. I want cups to ask for help. I was told that there may be something wrong with libqpdf, so I ask a question here and hope to get some help. I will cooperate with enthusiastic people. Thank you. I hope you can give me some suggestions.

**Comment by zhangyonglin911** [comment]
D [17/May/2022:09:40:38 +0800] [Job 14077] Printer model: Brother HL-2240 Foomatic/hl1250 (recommended)
D [17/May/2022:09:40:38 +0800] [Job 14077] Job title: whatever.pdf
D [17/May/2022:09:40:38 +0800] [Job 14077] File(s) to be printed:
D [17/May/2022:09:40:38 +0800] [Job 14077]
D [17/May/2022:09:40:38 +0800] [Job 14077] Ghostscript extra search path ('GS_LIB'): /usr/share/cups/fonts
D [17/May/2022:09:40:38 +0800] [Job 14077] Printing system options:
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'fit-to-page'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown boolean option "fit-to-page".
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'print-scaling=fit'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option print-scaling=fit.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'sides=one-sided'
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'page-ranges=1-8'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option page-ranges=1-8.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'job-uuid=urn:uuid:fa348708-2068-337d-5b07-d4a6036f08d5'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option job-uuid=urn:uuid:fa348708-2068-337d-5b07-d4a6036f08d5.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'job-originating-host-name=localhost'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option job-originating-host-name=localhost.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'date-time-at-creation='
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option date-time-at-creation=.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'date-time-at-processing='
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option date-time-at-processing=.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'time-at-creation=1652751633'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option time-at-creation=1652751633.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option 'time-at-processing=1652751633'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option time-at-processing=1652751633.
D [17/May/2022:09:40:38 +0800] [Job 14077] Options from the PPD file:
D [17/May/2022:09:40:38 +0800] [Job 14077] ================================================
D [17/May/2022:09:40:38 +0800] [Job 14077] File:
D [17/May/2022:09:40:38 +0800] [Job 14077] ================================================
D [17/May/2022:09:40:38 +0800] [Job 14077] Sending stdin for job...
D [17/May/2022:09:40:38 +0800] [Job 14077] STATE: +connecting-to-device
D [17/May/2022:09:40:38 +0800] [Job 14077] Looking up "xxxxx.xxx.xxx.com"...
D [17/May/2022:09:40:38 +0800] [Job 14077] Set job-printer-state-message to "Exception: unknown object type inspecting /Contents key in page dictionary", current level=ERROR
D [17/May/2022:09:40:38 +0800] [Job 14077] Cannot process "": Unknown filetype.
D [17/May/2022:09:40:38 +0800] [Job 14077] Process is dying with "Could not print file
D [17/May/2022:09:40:38 +0800] [Job 14077] ", exit stat 2
D [17/May/2022:09:40:38 +0800] [Job 14077] Cleaning up...
D [17/May/2022:09:40:38 +0800] [Job 14077] PID 14484 (/usr/lib/cups/filter/pdftopdf) stopped with status 5.
D [17/May/2022:09:40:38 +0800] [Job 14077] Hint: Try setting the LogLevel to "debug" to find out more.
D [17/May/2022:09:40:38 +0800] [Job 14077] PID 14485 (/usr/lib/cups/filter/foomatic-rip) stopped with status 2.
D [17/May/2022:09:40:38 +0800] [Job 14077] Hint: Try setting the LogLevel to "debug" to find out more.
D [17/May/2022:09:40:38 +0800] [Job 14077] STATE: -connecting-to-device
D [17/May/2022:09:40:38 +0800] [Job 14077] xxxxxxx.xxxx.xxxx.com=11x.15x.20x.11x
D [17/May/2022:09:40:38 +0800] [Job 14077] hrDeviceDesc="Unknown"
D [17/May/2022:09:40:38 +0800] [Job 14077] prtGeneralCurrentLocalization type is 0, expected 2!
D [17/May/2022:09:40:38 +0800] [Job 14077] backendWaitLoop(snmp_fd=5, addr=0x563aed739d18, side_cb=0x563aec458e60)
D [17/May/2022:09:40:38 +0800] [Job 14077] PID 14486 (/usr/lib/cups/backend/ipp) exited with no errors.
D [17/May/2022:09:40:38 +0800] [Job 14077] End of messages
D [17/May/2022:09:40:38 +0800] [Job 14077] printer-state=3(idle)
D [17/May/2022:09:40:38 +0800] [Job 14077] printer-state-message="Exception: unknown object type inspecting /Contents key in page dictionary"
D [17/May/2022:09:40:38 +0800] [Job 14077] printer-state-reasons=none

**Comment by zhangyonglin911** [comment]
[https://crp.tatax.com.cn/dl_preview?openid=issue&fs_id=d14086-001](https://github.com/OpenPrinting/cups/issues/url)

**Comment by zhangyonglin911** [comment]
https://github.com/OpenPrinting/cups/issues/396#issue-1237920643

**Comment by jberkenbilt** [comment]
Those exceptions don't come from qpdf. They probably come from pdftopdf. They also probably indicate a damaged or invalid PDF file.

**Comment by zhangyonglin911** [comment]
ok     thanks
