### ISSUE TITLE
allow lossy recompression of images (with a different quality)

### ISSUE THREAD

**Issue by imz** [qpdf/qpdf#712]
I wanted to recompress the images on some of the pages (of a scanned document) to a lower quality. To make the file smaller.

Ideally, there would be an option like `--quality N:PAGES`.

Since there is no such option/tool, first, I simplified the task for myself by recompressing all images from the original, saving that as a new file, and finally joining pages from the two files the way I want.

As for recompression, a script can be written on top of pikepdf (the Python module often mentioned here in the issues).

And actually a tool that uses pikepdf, ocrmypdf, already has a module for this purpose: [optimize.py](https://github.com/ocrmypdf/OCRmyPDF/blob/603da52026685d45aeec1fb7a4d934f995c62e5a/src/ocrmypdf/optimize.py).

One can either tweak the options of `ocrmypdf` not to do the OCR, but just the recompression (see below in my example with a Makefile). Or, the file `optimize.py` is actually almost ready to be run as a standalone script.

First, to run it as a standalone script, one has to copy it out of the package tree (otherwise, some imports try to import a wrong module from the same package instead of taking the global one: `subprocess.py` is present in both places, and if you run the script from the package's tree, it first finds the one in the package).

Then I made small modifications to the script to make it more convenient:

```
--- OCRmyPDF/src/ocrmypdf/optimize.py	2022-06-08 06:21:51.659092559 +0300
+++ optimize.py	2022-06-08 07:15:52.993430611 +0300
@@ -46,7 +46,7 @@
 from ocrmypdf.exceptions import OutputFileAccessError
 from ocrmypdf.helpers import IMG2PDF_KWARGS, safe_symlink
 
-log = logging.getLogger(__name__)
+log = logging.getLogger("ocrmypdf")
 
 DEFAULT_JPEG_QUALITY = 75
 DEFAULT_PNG_QUALITY = 70
@@ -78,7 +78,10 @@
     del pike  # unused args
     del root
 
+    log.debug(f"start extract_image_filter xref {xref}")
+
     if image.Subtype != Name.Image:
+        log.debug(f"extract_image_filter xref {xref}: {image.Subtype} != Name.Image")
         return None
     if image.Length < 100:
         log.debug(f"xref {xref}: skipping image with small stream size")
@@ -278,6 +281,7 @@
 
     working_xrefs = include_xrefs - exclude_xrefs
     for xref in working_xrefs:
+        log.debug(f"about to extract xref {xref}")
         image = pike.get_object((xref, 0))
         try:
             result = extract_fn(
@@ -677,9 +681,12 @@
         safe_symlink(target_file, output_file)
 
 
-def main(infile, outfile, level, jobs=1):
+def main(infile, outfile, level, jpegq, pngq, jobs=1):
     from shutil import copy  # pylint: disable=import-outside-toplevel
     from tempfile import TemporaryDirectory  # pylint: disable=import-outside-toplevel
+    from ocrmypdf.api import Verbosity, configure_logging
+
+    configure_logging(Verbosity.debug)
 
     class OptimizeOptions:
         """Emulate ocrmypdf's options"""
@@ -702,8 +709,8 @@
         input_file=infile,
         jobs=jobs,
         optimize_=int(level),
-        jpeg_quality=0,  # Use default
-        png_quality=0,
+        jpeg_quality=int(jpegq),  # 0 for default
+        png_quality=int(pngq),
         jb2lossy=False,
     )
 
@@ -724,4 +731,4 @@
 
 
 if __name__ == '__main__':
-    main(sys.argv[1], sys.argv[2], sys.argv[3])
+    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
```

And here is my example where I test how it works in the form of a Makefile:

```
ALL := $(foreach join,jam qpdf,\
	$(foreach recompr,ocrmypdf optimize,\
		pages_$(join)_$(recompr).pdf))

all: $(ALL)

clean::
	rm -fv $(ALL)

# Two methods to recompress:

%_ocrmypdf.pdf: %.pdf
	ocrmypdf --output-type pdf \
		--verbose 2 \
		--skip-big 1 \
		--optimize 3 --jpeg-quality 5 \
		$< -- \
		$@

%_optimize.pdf: %.pdf
	python3 optimize.py $< $@ 2 5 0

# Two methods to create a PDF by joining pages:

pages_jam.pdf: scan.pdf
	pdfjam --fitpaper true \
		$^ $^ \
		--landscape --angle 270 \
		--outfile $@

clean::
	rm -fv pages_jam.pdf

pages_qpdf.pdf: scan.pdf
	qpdf --empty \
		--pages $^ $^ -- \
		--rotate=90 \
		$@

clean::
	rm -fv pages_qpdf.pdf
```

The original `scan.pdf` will be attached so that you can re-run my example.

[scan.pdf](https://github.com/qpdf/qpdf/files/8860128/scan.pdf)

The results:

```
$ du -shL scan.pdf pages*.pdf
112K	scan.pdf
212K	pages_jam_ocrmypdf.pdf
212K	pages_jam_optimize.pdf
212K	pages_jam.pdf
28K	pages_qpdf_ocrmypdf.pdf
24K	pages_qpdf_optimize.pdf
108K	pages_qpdf.pdf
```

If the processed file was created by `qpdf`, then recompression works.

If by `pdfjam`, then not. It's due to the objects containing the images having some different (unexpected) type in the PDF:

```
$ make pages_jam_optimize.pdf
python3 optimize.py pages_jam.pdf pages_jam_optimize.pdf 2 5 0
xref 7: treating as an optimization candidate
xref 82: treating as an optimization candidate
about to extract xref 82
start extract_image_filter xref 82
extract_image_filter xref 82: /Form != Name.Image
about to extract xref 7
start extract_image_filter xref 7
extract_image_filter xref 7: /Form != Name.Image
Optimizable images: JPEGs: 0 PNGs: 0
xref 7: treating as an optimization candidate
xref 82: treating as an optimization candidate
about to extract xref 82
start extract_image_filter xref 82
extract_image_filter xref 82: /Form != Name.Image
about to extract xref 7
start extract_image_filter xref 7
extract_image_filter xref 7: /Form != Name.Image
xref 7: treating as an optimization candidate
xref 82: treating as an optimization candidate
about to extract xref 82
start extract_image_filter xref 82
extract_image_filter xref 82: /Form != Name.Image
about to extract xref 7
start extract_image_filter xref 7
extract_image_filter xref 7: /Form != Name.Image
Optimizable images: JBIG2 groups: 0
Optimize ratio: 1.01 savings: 0.5%
os.symlink(/tmp/tmpsidiaa4n/out.opt.pdf, /tmp/tmpsidiaa4n/out.pdf)
```

Note the debugging message:

```
extract_image_filter xref 82: /Form != Name.Image
```

that explains the failure to find and process those images. Reported this at <https://github.com/ocrmypdf/OCRmyPDF/issues/977>.

**Comment by jberkenbilt** [comment]
Thanks for this and for pointing to here from all those other issues. I may have mentioned somewhere that I have a tool I wrote for work that does image resampling of this type with a few restrictions, but it uses the GraphicsMagick++ library and ghostscript. I could make it open source with a few small enhancements. I don't see myself putting image handling logic into qpdf but I might consider it at some point. I have some code I wrote 20 years ago at the same time I was originally working on qpdf that implements generalized image filtering, but it only supports tiff, png, and jpeg files (using the respective third-party libraries) and has a limited collection of things it can do. When I wrote it originally, it was 10x or 100x faster than ImageMagick depending on the operation, but these days, other graphics libraries are comparable in performance or faster. I wrote it at a time when I was optimizing for memory usage more than performance. Using that tool, I was able to create elaborate pipelines where I could read an image and generate multiple output images of differing characteristics in a single pass all without loading more than a few scanlines of any image into memory at once. I still have that code, and it still runs and passes its test suites. (I revived it not that long ago and brought it up to date.) We'll see. Clearly this is a feature that a lot of people are interested in.

Hopefully people will find your solution at least in the interim. Thanks for sharing

**Comment by benbro** [comment]
Is there a plan to show images inside Form XObjects in page.images in qpdf/pikepdf?

**Comment by jberkenbilt** [comment]
@benbro It could be done. Please open a separate issue with this, and I'll tag it as an enhancement.

**Comment by rubyFeedback** [comment]
imz: how much compression did you achieve? Like on average or so?

**Comment by rubyFeedback** [comment]
jberkenbilt wrote:

> I don't see myself putting image handling logic into qpdf but I might consider it at some point

Actually, many .pdf files are so simple that they don't even have any images. I oddly enough have
tons of old .pdf files that are just emails actually, or FAX. One page or two pages maximum.

Right now I am testing qpdf --compress-streams=y --object-streams=generate and that actually
makes some noticable reduction in file size. So of course not disagreeing - just pointing out that
use cases may vary among different folks.

**Comment by quite** [comment]
@imz thank you, your hacked up optimize.py saved me... I could not find any other working way to recompress jpegs inside a pdf to get slightly lower quality, to be able to get the overall pdf size below a threshold. Various long gs (ghostscript) cmdline incantations I found that claimed to do it just would not change the final pdf at all.

**Comment by gareth-shakewell** [comment]
Firstly, @jberkenbilt, qpdf is awesome. Such a great tool (I work a lot in enterprise publishing space). I ended up on this comment thread while researching the best way to programmatically compress PDF. I found the combination of GhostScript and qpdf works really well and both can be installed easily on macOS with Homebrew.
For benefit of others, here is what worked well for me (reduced filesize by 86% for design-heavy PDF):

**Step 1 - install dependencies**
```
brew install ghostscript
brew install qpdf
```

**Step 2 - downsample images to 72dpi in GhostScript**
```
gs \
  -o downsampled.pdf \
  -sDEVICE=pdfwrite \
  -r72 \
  -dConvertCMYKImagesToRGB=true \
  -dDownsampleColorImages=true \
  -dDownsampleGrayImages=true \
  -dDownsampleMonoImages=true \
  -dColorImageResolution=72 \
  -dGrayImageResolution=72 \
  -dMonoImageResolution=72 \
  -dColorImageDownsampleThreshold=1.0 \
  -dGrayImageDownsampleThreshold=1.0 \
  -dMonoImageDownsampleThreshold=1.0 \
  -sColorImageDownsampleType=Bicubic \
  -sGrayImageDownsampleType=Bicubic \
  -sMonoImageDownsampleType=Subsample \
   input.pdf
```

**Step 3 - compress object streams in qpdf**
```
qpdf --compress-streams=y --object-streams=generate downsampled.pdf compressed.pdf
```

**Comment by jberkenbilt** [comment]
@gareth-shakewell Thanks for taking the time to share this. Posts like this are very helpful as they demonstrate that the best results can often be obtained by using multiple tools, each for their strengths. I have also combined ghostscript and qpdf in my work. I'm glad to see that this worked well for you.
