### ISSUE TITLE
qpdf is very slow at loading some streams from pdfs

### ISSUE THREAD

**Issue by RedMindZ** [qpdf/qpdf#714]
I am building a pdf viewer with the qpdf-c api to read pdf files, and I encountered some files that have some streams that take a very long time to load.

Specifically, I have this pdf: [Gradient.pdf](https://github.com/qpdf/qpdf/files/8885497/AutoCAD.Gradient.pdf)
This pdf has an `XObject` named "/Xop1" in the resource dictionary of the first page that takes about 6 seconds to load; When opening the pdf with both Google Chrome and Adobe Acrobat, it loads nearly instantly, so its most likely a bug in qpdf.

To load the `XObject`, I call `qpdf_oh_get_stream_data` with `decode_level` set to `all`; This call takes about 6 seconds to return; This is also true for `decode_level` set to `generalized`.
When calling `qpdf_oh_get_stream_data` with `decode_level` set to `none` the call returns almost instantly (less then 1ms), so this is likely a bug with the decoding. The filters set on this stream are `FlateDecode` and `ASCII85Decode`.

If someone could take a look at the decoding and potentially fix it, that would be greatly appreciated.

**Comment by jberkenbilt** [comment]
I ran this sample code on your file. On my system, it takes 0.174 seconds. The ASCII85 decoder is coded fairly tightly. There could be some room for optimization (some memory is copied), but it looks reasonably efficient. My system has an 3.6 GHz i9 processor from 2018. qpdf is single-threaded.

```c
#include <qpdf/qpdf-c.h>
#include <stdio.h>

int main()
{
    qpdf_data qpdf = qpdf_init();
    qpdf_oh oh;
    QPDF_BOOL filtered = QPDF_FALSE;
    unsigned char* buf = 0;
    size_t len = 0;
    qpdf_read(qpdf, "/home/ejb/tmp/net/AutoCAD.Gradient.pdf", 0);
    oh = qpdf_get_object_by_id(qpdf, 2, 0);
    QPDF_ERROR_CODE e =
        qpdf_oh_get_stream_data(qpdf, oh, qpdf_dl_all, &filtered, &buf, &len);
    printf("%d, %lu\n", e, len);
    return 0;
}
```

I wonder whether there could be something else causing the slowness. What system/OS are you using? From what language are you accessing the C API?

**Comment by RedMindZ** [comment]
I am running on Windows 10 build 19044.1706 and calling the C API from C# like so:
```C#
[DllImport("qpdf28.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "qpdf_oh_get_stream_data")]
public static extern QpdfErrorType QpdfOhGetStreamData(QpdfData qpdf, QpdfObjectHandle streamOh, QpdfStreamDecodeLevel decodeLevel, int* filtered, byte** bufp, nuint* len);
```

I imagine something strange could be happening with the marshalling, but all types in the signature should be blittable, making the marshaling simple. The stream data isn't copied back by the marshaller, so that shouldn't be the cause of the issue either.

**Comment by jberkenbilt** [comment]
I'll try running my sample code on Windows when I get a chance. I have a Windows vm for local testing. Any possible issues like using a network file system?

**Comment by RedMindZ** [comment]
My file is stored on a local hard drive, and I also tested reading the file into a memory buffer and then using `qpdf_read_memory` and it still takes about 6 seconds.

**Comment by RedMindZ** [comment]
I just tested my code in a Windows 11 VM (running on my machine) and it actually ran very quickly, much faster than 6 seconds, so it seems like qpdf on windows isn't the problem by itself. What exactly does qpdf do when it decodes a stream? Does it use any external dependencies? Because it seems like the problem is with my specific environment.

**Comment by RedMindZ** [comment]
I found a new clue: if I delete the 'Path' environment variable of the process (setting it to the empty string) then the time the call takes goes down from 6 seconds to 3.5 seconds. If I also delete the rest of the environment variables then it goes down to 0.4 seconds. It also looks like the stream is still decoded correctly. Seems like qpdf is looking for something in the environment variables when it decodes a stream.

**Comment by jberkenbilt** [comment]
qpdf doesn't look at the environment or use external dependencies. I think it's unlikely that it is a qpdf issue.

**Comment by RedMindZ** [comment]
I think I found out the source cause for the slowdown: turns out qpdf ***is*** reading environment variables while decoding ASCII85. Specifically, [`Pl_ASCII85Decoder::flush`](https://github.com/qpdf/qpdf/blob/5c6808b484d954de68b26d7108b2f26e3c958c21/libqpdf/Pl_ASCII85Decoder.cc#L77) calls [`QTC::TC`](https://github.com/qpdf/qpdf/blob/5c6808b484d954de68b26d7108b2f26e3c958c21/libqpdf/QTC.cc#L15) in line 96.
[`QTC::TC`](https://github.com/qpdf/qpdf/blob/5c6808b484d954de68b26d7108b2f26e3c958c21/libqpdf/QTC.cc#L15) then calls [`tc_active`](https://github.com/qpdf/qpdf/blob/5c6808b484d954de68b26d7108b2f26e3c958c21/libqpdf/QTC.cc#L8) in line 19 which in turn calls [`QUtil::get_env`](https://github.com/qpdf/qpdf/blob/5c6808b484d954de68b26d7108b2f26e3c958c21/libqpdf/QUtil.cc#L854) in line 11.
Then, on Windows, [`QUtil::get_env`](https://github.com/qpdf/qpdf/blob/5c6808b484d954de68b26d7108b2f26e3c958c21/libqpdf/QUtil.cc#L854) calls [`GetEnvironmentVariable`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable) which retrieves the environment variable.

I built qpdf from source and ran visual studio's profiler on your test code, and it reports ~98% of the time being spent on the call chain I wrote above.

Should I just remove the call to `QTC::TC` (which I believe is not functionally important, correct me if I'm wrong) for now?

**Comment by jberkenbilt** [comment]
In qpdf 11, QTC will be stubbed out inside the library by default. This is done in a manner that still makes QTC::TC available for users of the library, but inside the library itself, there will be zero overhead from the existence of the coverage calls. Also, when it is turned on, the result of getenv is cached. Even on Linux, there is a measurable (but small) performance gain. I suspect you will notice a big different in performance with qpdf 11 in this area.

**Comment by jberkenbilt** [comment]
I am hoping to release qpdf 11 no later than early September, but as always, I am not committing to a specific date. I just a few more items to finish before the release.

**Comment by jberkenbilt** [comment]
qpdf 11 is out and includes the fix for this issue
