### ISSUE TITLE
Form content lost when joining pages on a sheet as sub pages (N-up)

### ISSUE THREAD

**Issue by tillkamppeter** [qpdf/qpdf#72]
I got the following Ubuntu bug report:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1564249
Here a user has a PDF file with filled forms and want to print it via CUPS. The file gets filtered through the pdftopdf filter of cups-filters then to execute page management options like N-up, fit-to-page, page-ranges, ... pdftopdf is based on QPDF.
The user gets the filled form correctly printed when he does not use the fit-to-page option but the form comes out empty with fit-to-page set. In the former case each page gets added to the output by calling proc.add_page(page,0), with proc being the output, in the latter case an empty page is added to the output via proc.new_page(width,height) and the page is put into this empty page with outpage->add_subpage(page,xpos,ypos,scale,&rect), with outpage being the empty page previously added to proc.
For me this looks like that the add_page() keeps the form content conserved but the add_subpage() method looses the form content. The content has to stay always conserved.

**Comment by tillkamppeter** [comment]
I have found the old discussion which I did not find yesterday (remembering there was something earlier):
https://bugs.linuxfoundation.org/show_bug.cgi?id=1315
So it is probably too complex to implement preservation of forms in QPDF (feature request?) due to the fact that QPDF is not a PDF interpreter.

**Comment by SilvanScherrer** [comment]
I also vote for a fix it this, as one always has to remember to disable fit-to-page, when printing with cups.

**Comment by jberkenbilt** [comment]
I'm hoping to get to this for the next qpdf release, but I'm not sure. I'm going to tag it "next", but most of the items I'm targeting are either very small fixes or improvements to error handling. I have to still study this and figure out how hard this is.

**Comment by jberkenbilt** [comment]
Note to self: "next" tag indicates intent to analyze this and either do it or describe why it can't be done eaislyh.

**Comment by SilvanScherrer** [comment]
I saw you actively work on qpdf. could you look at this issue as well?

**Comment by jberkenbilt** [comment]
@SilvanScherrer Active work is being done on this issue as part of a google summer of code project. The work was not ready to be incorporated into qpdf 7.0, but it will likely be incorporated before too long. It is also likely that a fix will go into cups-filters so that the specific problem that triggered this request will be addressed at that level.

**Comment by smilingthax** [comment]
Hint: Some pdfs viewer seem to generate appearance streams without the (mandatory) /Subtype /Form dictionary entry. Adding it (when missing) during the flattening pass makes (at least) xpdf/poppler happy (otherwise it'll print a warning and *does not* draw the xobject).

**Comment by smilingthax** [comment]
Note: In the flags entry controlling various aspects of a widget/annotation/field, one bit is used to specify whether it should appear in print. Therefore the flattening process has do include/exclude such a field (e.g. push button) depending on the intended use (the main purpose of flattening outside of a pdf viewer seems to be to obtain the "print" representation of a given PDF).

**Comment by tillkamppeter** [comment]
For the time being until the form-flattening gets fully implemented in QPDF I have now applied a solution where pdftopdf (cups-filters 1.17.4) detects PDF forms using QPDF (thanks to Tobias Hoffmann, smilingthax) and if there is a form uses an external utility for the flattening, preferrably pdftocairo, if not present, Ghostscript. After the flattening the original treatment by QPDF is performed.
If none of the utilities is available, no form-flattening is performed.
The originally planned QPDF-based solution will get added to cups-filters as soon as it gets completed. Depending on how reliable the QPDF solution is, I will perhaps allow for both using an external utility or QPDF on the user's/admin's/distribution's choice.

**Comment by jberkenbilt** [comment]
I am closing this issue now. The next version of qpdf will resolve everything discussed here.
