### ISSUE TITLE
"pdf: rename  .~qpdf-orig#: No such file or directory"

### ISSUE THREAD

**Issue by DUOLabs333** [qpdf/qpdf#728]
I'm trying to do ` qpdf --empty --pages input.pdf 1 -- --replace-input`. However, I get `pdf: rename  .~qpdf-orig#: No such file or directory`. It should be trying to get `.~qpdf-temp#`. Version 10.6.3.

**Comment by jberkenbilt** [comment]
`--replace-input` doesn't make sense with `--empty`. It would be better if qpdf just disallowed that combination of options. Are you trying to report that problem, or are you expecting this combination of options to do something?

**Comment by DUOLabs333** [comment]
I expected it to work. Why does that combination make no sense.

**Comment by mschilli87** [comment]
```sh
qpdf --help=--empty
```

```
Use in place of infile for an empty input. Especially useful
with --pages.

For detailed help, visit the qpdf manual: https://qpdf.readthedocs.io
```

```sh
qpdf --help=--replace-input
```

```
Use in place of outfile to overwrite the input file with the output.

For detailed help, visit the qpdf manual: https://qpdf.readthedocs.io
```

So one parameter says 'There is no input file.' and the other says 'Use the input file as the output file.'; Do you see now why they don't really fit well together?

**Comment by DUOLabs333** [comment]
Interesting: I just used the `qpdf --empty --pages in.pdf` paradigm without understanding why. Using `qpdf in.pdf --pages .` works. Maybe make it os that `--pages` doesn't need an additional input-file, and just use `in.pdf`?

**Comment by jberkenbilt** [comment]
> Maybe make it os that `--pages` doesn't need an additional input-file, and just use `in.pdf`?

That's with `.` is for, which you used.

**Comment by jberkenbilt** [comment]
Please leave this open so I can fix the CLI parsing.

**Comment by DUOLabs333** [comment]
> That's with `.` is for, which you used.
Yeah, but I meant that you shouldn't need to add `.`, but takes `in.pdf`. Why is there even an option to have another input at all?

**Comment by jberkenbilt** [comment]
Because you can use `--pages` to take pages from multiple files. I think you probably haven't looked at the documentation very carefully. There are plenty of examples of using `--pages`.

**Comment by mastershubham** [comment]
Suppose you have an existing file called revise.pdf and you want to use all pages(or some of the pages) of it and combine it with pages from different pdfs(say pages 1-2 of file.pdf) and you also want to replace revise.pdf with the newly formed pdf then the way to do that is:
`qpdf revise.pdf --pages revise.pdf file.pdf 1-2 -- --replace-input`

You have to place the replaceable file at the earlier `--empty` input.
