### ISSUE TITLE
Object split between streams

### ISSUE THREAD

**Issue by mottetm** [qpdf/qpdf#73]
I have document where the content of a page is split between multiple streams. The tricky part is that some of the arrays are also split between theses multiples streams. When I try to parse the stream where the array starts. I get an error (as the array object object is never initialized in parseInternal()).
Any idea of a fix or of a workaround for the problem?

**Comment by jberkenbilt** [comment]
This is an interesting problem. I haven't been in that part of the code for a while. Without looking at the code, my impulse would be to combine the content into a single stream before parsing it.  You might be able to do this my mutating the object to replace the array of streams with a single stream (or an array containing a single stream) by writing some stream content provider that merges the streams. There may be a fix in qpdf that allows the parsing to straddle across streams.

Is this failing with the qpdf command line tool, or are you writing C++ code? If you have a file and/or code you could share, I can try to take a deeper look.

**Comment by staar** [comment]
Hi jberkenbilt,

I can provide you with an example-pdf: 

[geology_03.pdf](https://github.com/qpdf/qpdf/files/200866/geology_03.pdf)

cheers,

Peter

**Comment by mottetm** [comment]
The problem is with c++ code and as @staar mentionned the sent pdf is one of those making some problem.

I'll try to workaround by concatenating the streams. I thought of it but wanted to check if there wasn't another way.

**Comment by jberkenbilt** [comment]
I'm going to see if I can address this for the next update. There are several issues around qpdf handling malformed PDF files that will require touching the same part of the code. I'm not sure whether this is incorrect PDF or not, but either way, if I'm in the code, maybe I can fix it.

**Comment by jberkenbilt** [comment]
saved example as qpdf/misc/bugs/73.pdf
