### ISSUE TITLE
Font changes after recompression

### ISSUE THREAD

**Issue by Theo641** [qpdf/qpdf#742]

**Comment by Theo641** [comment]
I have a pdf file uncompressed and changed one value.
After recompress (qpdf --stream-data=compress) I get an error about "can not take out AAAAA+Arial-BoldTM" font.
Also an image disappeared.
Please your help/comment.

**Comment by jberkenbilt** [comment]
There is not enough information here for me to help you. I'd guess user error.

**Comment by Theo641** [comment]
You are right.
When I open the recompressed pdf in Acrobat Pro DC, I get two error- or warning messages. Here are the screenshots:
![Screen Shot 08-05-22 at 08 29 AM](https://user-images.githubusercontent.com/110631917/183016180-cc4cb03c-18ed-43af-ab46-e7d8c8d0354e.PNG)
![Screen Shot 08-05-22 at 08 30 AM](https://user-images.githubusercontent.com/110631917/183016292-d231e260-79ad-4822-9113-ad451a253bd9.PNG)
It's in Dutch. The first is about the included font that can not be taken out.
The second says: there is an error at reading a stream. Both probably interconnected.
After that the file is diplayed with different font and there is an image missing.

**Comment by Theo641** [comment]
Related question:
How can (what options to use) I change a (part of) text (sign) in the file while leaving the rest original in fonts, images and meta-data?

**Comment by jberkenbilt** [comment]
I'm sorry -- there is nothing I can do with this. I'm closing. My guess is that the file was edited in a non-binary editor and that the file got corrupted by saving. qpdf doesn't have any support/knowledge of fonts and is not likely to get that feature. Thanks.
