### ISSUE TITLE
Tag QPDFNameTreeObjectHelper and QPDFNumberTreeObjectHelper as QPDF_DLL_CLASS

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#745]
For reasons not clear to me, GCC linking fails on account of typeinfo and vtable for QPDFNameTreeObjectHelper not being exported. In pikepdf, I introduced a helper class, which for reasons not clear to me, avoids this linker issue.

For reasons even less clear to me, QPDFNumberTreeObjectHelper has no such issues. But perhaps it should also be tagged QPDF_DLL_CLASS as a precaution.

**Comment by jberkenbilt** [comment]
See https://github.com/qpdf/qpdf/blob/main/README-maintainer#L186 . Most likely I need `QPDF_DLL_CLASS` and also to make the destructors explicit and not inline. I should probably update README-MAINTAINER to extend the rule to derived classes in the public API too but I'll look at it more closely. I'll see if I can figure out why one works and the other doesn't. I'm not sure I agree with how gcc/clang do this, but I've never implemented a C++ compiler, and I imagine it's not at all straightforward and/or would be hard to change without breaking existing code. Anyway, I'm pretty sure the fix I've proposed will work. If I add QPDF_DLL_CLASS, I will also decide whether to mark some things as explicitly private.

**Comment by jberkenbilt** [comment]
Okay, I'm not sure why either. I marked both classes with QPDF_DLL_CLASS and made their destructors explicit. Let's see if that helps. I can't say I particularly like making changes without fully understanding the reason, but I'm willing to forego analysis in favor of higher value activities in this case.

**Comment by jberkenbilt** [comment]
Running some experiments, I know why it's working the way it is but not why you actually need typeinfo for these. But if you need them, no problem.
