### ISSUE TITLE
how to print non-printable pdf ? 

### ISSUE THREAD

**Issue by TrevCan** [qpdf/qpdf#748]
Hello, that is the question. 

I have an encrypted pdf file. Which I can view on any web browser because the password is literally **nothing**. I was able to remove the decryption and `qpdf --check file` indeed showed that encryption had been removed.

But the problem is that with any of these two files, I'm unable to print it on a corporate HP Printer at my school. I have not verified if any of these are printable on my home printer, but I'll update. 

I tried re-saving it from other devices, printing to pdf from chromium, then sending to printing, **printing from a USB** but none worked.

What did work for me was using the [Okular](https://okular.kde.org/) pdf reader. (i'm seriously not trying to make an ad for KDE, this is the only thing that worked for me). I should also note that I was able to print it from Acrobat PDF on windows 10 without issues, but it's not available on **Linux**. I read it on a random stackoverflow page and re-printing it as PDF and re-sending it worked! I do not know why. 

My guess is there's some hidden proprietary format that it's using to tell the HP Printer **not** to print it. 

As of now I cannot share any of these files because they contain some PPI (personally identifiable info).

But I'd love to know if we can implement some way of removing this fake encryption.

I can share some of the logs:

```
> qpdf --check 0.non-printable-encrypted.pdf
checking 0.non-printable-encrypted.pdf
PDF Version: 1.4
R = 3
P = -1852
User password =
Supplied password is user password
extract for accessibility: not allowed
extract for any purpose: not allowed
print low resolution: allowed
print high resolution: allowed
modify document assembly: not allowed
modify forms: not allowed
modify annotations: not allowed
modify other: not allowed
modify anything: not allowed
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
```
---
```
> qpdf --check 0.non-printable-decrypted.pdf
checking 0.non-printable-decrypted.pdf
PDF Version: 1.4
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
```
---
```
# this was 'printed as PDF' from Okular
> qpdf --check 0.printable-decrypted.pdf
checking 0.printable-decrypted.pdf
PDF Version: 1.4
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect

```

**Comment by jberkenbilt** [comment]
I apologize for overlooking this. qpdf's `--decrypt` option, possibly combined with `--remove-restrictions` should help you here.
