### ISSUE TITLE
configure check for GNU make should run gmake --version

### ISSUE THREAD

**Issue by rklrkl** [qpdf/qpdf#75]
In qpdf 6.0.0, the configure script twice runs (at lines 15561 and 15562)  "make --version" to check the version of GNU make installed. Non-Linux systems often ship with a vendor-supplied "make" binary that isn't GNU make, so this check fails if the vendor make is ahead of GNU make in the PATH.

I would suggest running "gmake --version" twice instead - this is usually a soft-link to make on Linux systems and should be more portable to non-Linux systems.

**Comment by jberkenbilt** [comment]
Thanks for all your comments and suggestions to improve the portability of qpdf to non-gnu systems. As much as I would like to accept all these suggestions, I have very limited time to work on qpdf, and these changes affect a relatively small number of users. I may get to them sometime, but realistically, it will not be any time soon.
