### ISSUE TITLE
include/qpdf/QPDFExc.hh should #include <string>

### ISSUE THREAD

**Issue by rklrkl** [qpdf/qpdf#76]
In qpdf 6.0.0, include/qpdf/QPDFExc.hh makes several uses of std::string, but fails to #include <string> anywhere. I would suggest #include <string> is added somewhere near the top of the file - the lack of it causes non-g++ C++ compilers to baulk.

-

**Comment by jberkenbilt** [comment]
It's already there, and it's already included before anything that references std::string.
