### ISSUE TITLE
Build errors v11.0.0

### ISSUE THREAD

**Issue by Schamschula** [qpdf/qpdf#763]
The MacPorts port maintainer here.

I was trying to update qpdf to version 11.0.0 under macOS 12.5.1. I get the following build errors:

`
:info:build [ 71%] Built target test_renumber
:info:build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_textproc_qpdf/qpdf/work/qpdf-11.0.0/examples/pdf-create.cc:32:18: warning: 'ImageProvider::provideStreamData' hides overloaded virtual functions [-Woverloaded-virtual]
:info:build     virtual void provideStreamData(QPDFObjGen const&, Pipeline* pipeline);
:info:build                  ^
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:120:22: note: hidden overloaded virtual function 'QPDFObjectHandle::StreamDataProvider::provideStreamData' declared here: different number of parameters (3 vs 2)
:info:build         virtual void provideStreamData(int objid, int generation,
:info:build                      ^
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:123:22: note: hidden overloaded virtual function 'QPDFObjectHandle::StreamDataProvider::provideStreamData' declared here: different number of parameters (5 vs 2)
:info:build         virtual bool provideStreamData(
:info:build                      ^
:info:build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_textproc_qpdf/qpdf/work/qpdf-11.0.0/examples/pdf-create.cc:120:16: error: no member named 'writeString' in 'Pipeline'
:info:build             p->writeString(stripes[i]);
:info:build             ~  ^
:info:build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_textproc_qpdf/qpdf/work/qpdf-11.0.0/examples/pdf-create.cc:189:11: error: no matching member function for call to 'replaceStreamData'
:info:build     image.replaceStreamData(
:info:build     ~~~~~~^~~~~~~~~~~~~~~~~
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:1193:10: note: candidate function not viable: no known conversion from 'std::shared_ptr<QPDFObjectHandle::StreamDataProvider>' to 'PointerHolder<Buffer>' for 1st argument
:info:build     void replaceStreamData(PointerHolder<Buffer> data,
:info:build          ^
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:1202:10: note: candidate function not viable: no known conversion from 'std::shared_ptr<QPDFObjectHandle::StreamDataProvider>' to 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char>>') for 1st argument
:info:build     void replaceStreamData(std::string const& data,
:info:build          ^
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:1232:10: note: candidate function not viable: no known conversion from 'std::shared_ptr<QPDFObjectHandle::StreamDataProvider>' to 'PointerHolder<QPDFObjectHandle::StreamDataProvider>' for 1st argument
:info:build     void replaceStreamData(PointerHolder<StreamDataProvider> provider,
:info:build          ^
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:1243:10: note: candidate function not viable: no known conversion from 'std::shared_ptr<QPDFObjectHandle::StreamDataProvider>' to 'std::function<void (Pipeline *)>' for 1st argument
:info:build     void replaceStreamData(std::function<void(Pipeline*)> provider,
:info:build          ^
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:1249:10: note: candidate function not viable: no known conversion from 'std::shared_ptr<QPDFObjectHandle::StreamDataProvider>' to 'std::function<bool (Pipeline *, bool, bool)>' for 1st argument
:info:build     void replaceStreamData(
:info:build          ^
:info:build make[2]: Leaving directory /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_textproc_qpdf/qpdf/work/build
:info:build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_textproc_qpdf/qpdf/work/qpdf-11.0.0/examples/pdf-create.cc:294:23: error: no matching member function for call to 'provideStreamData'
:info:build             provider->provideStreamData(QPDFObjGen(), &b_p);
:info:build             ~~~~~~~~~~^~~~~~~~~~~~~~~~~
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:120:22: note: candidate function not viable: requires 3 arguments, but 2 were provided
:info:build         virtual void provideStreamData(int objid, int generation,
:info:build                      ^
:info:build /opt/local/include/qpdf/QPDFObjectHandle.hh:123:22: note: candidate function not viable: requires 5 arguments, but 2 were provided
:info:build         virtual bool provideStreamData(
:info:build                      ^
:info:build [ 71%] Built target pdf-count-strings
:info:build 1 warning and 3 errors generated.
`

**Comment by jberkenbilt** [comment]
It looks to me like you're building new examples against an old copy of the headers. Is that possible?

**Comment by Schamschula** [comment]
It is possible that it is finding the headers from the currently installed version (10.6.3)

**Comment by Schamschula** [comment]
Confirmed!

**Comment by Schamschula** [comment]
I got a clean build after deactivating the old version.

Unfortunately, the update also breaks `py-pikepdf`. I'll wait to push `qpdf` until `py-pikepdf` supports it.

**Comment by jberkenbilt** [comment]
Thanks for the followup. I thought the build was set up so that the qpdf source tree was in front of any previous installed versions when building. I've never found a formula for that that works across everywhere...I was hoping maybe cmake would solve that. I'll have to take a fresh look.

Regarding pikepdf, there is a feature branch in the pikepdf repo that is known to work with qpdf 11 as released. I always run pikepdf's test suite against qpdf as part of my release process, and I've been in communication with @jbarlow83 about it. I suspect it won't be long before a pikepdf that works with qpdf 11 is out.

**Comment by rubyFeedback** [comment]
(Not related to the issue here, but I just compiled qpdf 11.0.0 from source on linux via cmake and everything appears to be correct. I also confirmed that the new qpdf works on the use cases I have e. g. removing pages from .pdf files. This is just meant as a bit info for jberkenbilt.)

**Comment by Schamschula** [comment]
We have a workaround for the old headers: https://github.com/macports/macports-ports/pull/16093

**Comment by jberkenbilt** [comment]
@rubyFeedback Thanks. FYI I created #762 for general release discussion, though I appreciate your providing the feedback either way. Any further discussion not related to this issue can go in #762.

**Comment by jberkenbilt** [comment]
@Schamschula In qpdf 11.1, which I intend to release today if possible, I have internally set `CMAKE_INCLUDE_DIRECTORIES_PROJECT_BEFORE` to `ON`, which is supposed to force project include directories before system include directories. I am hoping this will alleviate the need for your workaround. I'll try to remember to follow up after I release 11.1.

**Comment by Schamschula** [comment]
I will test w/o the MacPort workaround.

**Comment by jberkenbilt** [comment]
> I will test w/o the MacPort workaround.

Great. I ran out of time for today but I have the release ready to go for tomorrow morning (US Eastern time).

**Comment by Schamschula** [comment]
I got a clean install with the old version (10.6.3) re-activated, after disabling the macPorts workaround. Looks good!
