### ISSUE TITLE
pikepdf needs QPDFWriter::ProgressReporter::~ProgressReporter DLL_EXPORT for qpdf 11

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#766]
Windows build complains that
`QPDFWriter::ProgressReporter::~ProgressReporter` is not exported from qpdf29.dll

```
 Creating library build\temp.win-amd64-cpython-37\Release\src/qpdf\_qpdf.cp37-win_amd64.lib and object build\temp.win-amd64-cpython-37\Release\src/qpdf\_qpdf.cp37-win_amd64.exp
        qpdf.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl QPDFWriter::ProgressReporter::~ProgressReporter(void)" (??1ProgressReporter@QPDFWriter@@UEAA@XZ)
        build\lib.win-amd64-cpython-37\pikepdf\_qpdf.cp37-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
        C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-zr7_phmk\overlay\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
          warnings.warn(msg, warning_class)
        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
```

I hadn't tried a full Windows build of qpdf and pikepdf, so not noticed earlier.

**Comment by jberkenbilt** [comment]
That's very odd. It's declared in such a way that it should be exported, and it has the workaround that I have previously found to resolve this issue, which is that the class is marked `QPDF_DLL_CLASS` and that the destructor is explicit and not inline. I'll have to look into it.

**Comment by jberkenbilt** [comment]
Actually, I see the mistake. I'll have to determine whether this requires a bump to 11.1. If I'm adding an API to the shared object, I'll have to do that (which is fife).

**Comment by jberkenbilt** [comment]
I have a fix in #770. Do I need to merge that for you to test?

**Comment by jberkenbilt** [comment]
Fix is merged but I'll leave this open pending confirmation. Feel free to close once confirmed or else report back and I'll close it.

**Comment by jbarlow83** [comment]
All clear for this issue. I got a Windows to build to mostly work, although some tests do not pass. Hopefully it's just not-official-build weirdness.

**Comment by jberkenbilt** [comment]
Great, thanks. The debian package transitioned to testing. I'll take a look at two build-related issues today and then release 11.1.
