### ISSUE TITLE
cmake settings for building libraries only?

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#767]
I've tried to set up build and install for qpdf that generates libraries only.

I don't know cmake that well so perhaps I'm doing something. This seems to mostly do the job....

```bash
cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build build --parallel --target libqpdf
cmake --install build --component lib
```

It does not install qpdf/include to the install folder however.
Perhaps the include headers need to be tagged as public_header as described here:
https://stackoverflow.com/questions/10487256/cmake-how-to-properly-copy-static-librarys-header-file-into-usr-include

It also seems non-ideal to need to set `--target libqpdf` to prevent building all of the other binaries. Maybe there's some what I can use `cpack`?

This is not critical to get pikepdf 6 released so understandable if you want to do other things first. It's just trying to get my CI to run faster, especially my poor little Linux ARM builder.

**Comment by jberkenbilt** [comment]
It was my intention for this to work, so I'll check it out.

**Comment by jberkenbilt** [comment]
I'm going to see if I can deal with this before 11.1. I think it should be trivial.

**Comment by jberkenbilt** [comment]
There's also an issue with `BUILD_SHARED_LIBS=0` that I will fix.

**Comment by jberkenbilt** [comment]
Actually it looks like two separate install commands are needed. It doesn't work to use `--component` twice. I'm testing instructions in the updated manual.
