### ISSUE TITLE
libqpdf/Pl_SHA2.cc calls functions that aren't defined in libqpdf/sha2big.c if SPH_64 isn't set to 1

### ISSUE THREAD

**Issue by rklrkl** [qpdf/qpdf#77]
In qpdf 6.0.0,  libqpdf/sha2big.c has several functions that are only defined if SPH_64 is set to 1 (via libqpdf/sph/sph_types.h). However, some of those functions are called from libqpdf/Pl_SHA2.cc with no check for SPH_64's value - examples are:

sph_sha384_init()
sph_sha512_init()
sph_sha384()
sph_sha512()
sph_sha384_close()
sph_sha512_close()

This causes compilation failures when SPH_64 isn't set to 1.

Note that this also impacts libtests/qtest/sha2.test, which fails with undefined function errors when SPH_64 isn't set to 1.

**Comment by jberkenbilt** [comment]
Sorry for the long delay on responding to this. I'm not going to fix this. However, I may implement #218, which would make this irrelevant. There are other parts of qpdf that won't work without a 64-bit type, so I don't think this is worth fixing.
