### ISSUE TITLE
`# warning` is invalid on MSVC

### ISSUE THREAD

**Issue by fredemmott** [qpdf/qpdf#775]
e.g. 

```
// #define POINTERHOLDER_TRANSITION 0 to suppress this warning, and see below.
// See also https://qpdf.readthedocs.io/en/stable/design.html#smart-pointers
# warning "POINTERHOLDER_TRANSITION is not defined -- see qpdf/PointerHolder.hh"
```

As `# warning` is invalid, this leads to a hard error (unless the steps in the comment are taken), which seems undesirable.

There doesn't seem to be a truly portable way to do this; the MSVC version is:

```
#pragma message ( "your warning text here" )
```

**Comment by jberkenbilt** [comment]
Oops.

Okay, I can rework this to just reply on `[[deprecated(...)]]` for the warning. Thanks. Weird, I had no idea `#warning` wasn't portable. I learned about it millions of years ago. Microsoft has become a vastly better citizen in my opinion over the past decade, but MSVC is still a hold-out, full of things that are different from everyone else.

**Comment by jberkenbilt** [comment]
I'm not sure if I'm going to actually fix this. `#pragma message` doesn't emit a warning, just a message. Here are reasons why this may not be so horrible:
1. the "fix" for developers is just define the symbol, which is what they need to do anyway
2. MSVC users are much less likely to have a qpdf thrust upon them than Linux or Mac users who may get a new version in their distribution or with a routine brew update and are also less likely to have to support multiple qpdf versions at the same time
3. While I can work around it with the deprecation messages on MSVC for PointerHolder.hh, I have no workaround for QPDFObject.hh
4. Adding the `#define` or equivalent build instruction won't break old versions

Do you think it's important to fix this?

This is tentative. I'm going to see if I can find a clever way to do it, like initializing a static variable with a deprecated inline function call or something. Time to boot up on Windows VM....

**Comment by jberkenbilt** [comment]
This generates a warning with g++. I'll try it on msvc. That may be a suitable workaround.

```c++
[[deprecated("warning")]]
inline int f()
{
    return 12;
}
static auto x = f();

int main()
{
    return 0;
}
```

**Comment by jberkenbilt** [comment]
Yeah, that generates a warning on Windows.

**Comment by jberkenbilt** [comment]
with msvc.

**Comment by jberkenbilt** [comment]
I wrote this up here: https://stackoverflow.com/a/73744173/7355313
I'm still not really sure it's worth doing though. @fredemmott What do you think? Is an obscure, hacky way to maybe get a warning in front of people better than leaving it as an error? I'm thinking I may just have to leave it as an error. A small workaround could be that, with MSVC, if `POINTERHOLDER_TRANSITION` is undefined, define it to 3, but if deprecation warnings are off, people won't see it.

Yeah, I think I may just have to leave it as it is. Open to ideas.

**Comment by fredemmott** [comment]
Honestly given the fix is so straightforward (and well-documented, thanks :) ) this doesn't seem worth going to those lengths :)

**Comment by jberkenbilt** [comment]
Okay, I'm going to close this, but thanks for reporting. When others also report this, which I'm sure they will, I'll just direct them here. Thanks for being such a helpful member of the qpdf community. :-)
