### ISSUE TITLE
Violation of the use of open source agreement

### ISSUE THREAD

**Issue by Lumilk233** [qpdf/qpdf#776]
This software has no explanation to use the QPDF core library for commercial purposes
**No original copyright and license statement without retaining**
**Call it independent research and development**
Official website：https://pdf.kfsafe.cn/
![图片](https://user-images.githubusercontent.com/110418934/190916674-10f59c7b-854c-422e-ac56-3bd78f05d5e1.png)
This is a digital signature
![图片](https://user-images.githubusercontent.com/110418934/190916877-9d6c6cae-0d89-4131-b183-30dac1cb9c5c.png)

This is a stolen source file
https://drive.lumine233.ml/api/raw/?path=/qpdf28.dll
Download link of installation package
https://static.cdn.pdf.kfsafe.cn/new_pdf/202209/new_pdf_c0_t1.exe

**Comment by jberkenbilt** [comment]
qpdf is licensed with the Apache license, which allows its use in commercial productions.

**Comment by Lumilk233** [comment]
> qpdf is licensed with the Apache license, which allows its use in commercial productions.

I'm sorry, not explained clearly
This software does not retain the original copyright and license declaration and calls it independent research and development

**Comment by Lumilk233** [comment]
> Understood. Thanks. I'm not sure what I can do about it. I don't think they necessarily need to acknowledge the qpdf copyright if they are just linking against the library. I don't read any language but English, but it seems that they are offering functionality beyond what qpdf offers and are probably just using qpdf for reading/writing PDF files. A lot of commercial products do that. I've seen several websites that offer services on PDF files that use qpdf behind the scenes. Sometimes I've stumbled across them, sometimes I've been contacted by their authors, and sometimes I've read about them in blog posts, etc. So I don't think there's a problem here. But I appreciate your drawing my attention to it.

Okay, thank you for your reply!
