### ISSUE TITLE
overlay on bleed scales pdf

### ISSUE THREAD

**Issue by pockhiss** [qpdf/qpdf#777]
I have a pdf with bleed and I am trying to overlay a pdf that does not have bleed. The result is that it scales to the bleed. Is there a workaround so there is no scaling?
qpdf.exe withbleed.pdf --overlay nobleed.pdf -- out.pdf

[nobleed.pdf](https://github.com/qpdf/qpdf/files/9594439/nobleed.pdf)
[out.pdf](https://github.com/qpdf/qpdf/files/9594441/out.pdf)
[withbleed.pdf](https://github.com/qpdf/qpdf/files/9594442/withbleed.pdf)

**Comment by jberkenbilt** [comment]
Not yet from the CLI, though it can be done programmatically. I am hoping that the next feature release of qpdf will allow much greater flexibility in this area.

**Comment by jberkenbilt** [comment]
You might try reversing the order and using `--underlay`, but whether or not that works would be an artifact of how the files were constructed, so it just be lucky if it does.
