### ISSUE TITLE
Non-portable GNU diff-only flags used in three scripts

### ISSUE THREAD

**Issue by rklrkl** [qpdf/qpdf#78]
In qpdf 6.0.0, GNU diff-only flags such as -a, -u and -U are used in three scripts:

qpdf/qtest/qpdf/diff-encrypted
qpdf/qtest/qpdf/diff-ignore-ID-version
qtest/module/TestDriver.pm

I removed the GNU diff-only flags from the three scripts and they worked fine with a non-GNU vendor-supplied diff binary.

**Comment by jberkenbilt** [comment]
Sorry for waiting 7 years to reply. :-( I'm going through old issues. Since this only impacts running the test suite, I'm not going to do anything about this.
