### ISSUE TITLE
configure.ac:4: error: Autoconf version 2.68 or higher is required

### ISSUE THREAD

**Issue by gitcnd** [qpdf/qpdf#79]
Seriously, is it *really* required?

**Comment by gitcnd** [comment]
Update: no it is not REQUIRED.

Change AC_PREREQ([2.68]) to something else - I put
AC_PREREQ([2.18])

and it works just fine.

**Comment by jberkenbilt** [comment]
What version of autoconf do you actually have? I'm pretty sure at least 2.5 is required. It seems to me that there was some feature I was using that required something newer than 2.5, though it's been several years since I did the autoconf work and I don't remember what it was.

**Comment by jberkenbilt** [comment]
I'm not going to change this because I don't have a good way of verifying what the actual minimum required version is. Please re-open if there is additional information. Usually you shouldn't need to run autoconf anyway as the autoconf-generated files are included in the distribution.
