### ISSUE TITLE
Select all pages but x,y,z

### ISSUE THREAD

**Issue by bengan** [qpdf/qpdf#790]
Hi,

Searched the manual and issues but I can't seem to find anything similar. I would like to select all pages from a pdf except some specific ones. I know I can manually list them all but If there are many it will be cumbersome to list them all. Would it possible to do something like this?

`qpdf in.pdf --pages in.pdf NOT 2,4,6,33,39,53,68,72,76 -- outfile.pdf`

**Comment by jberkenbilt** [comment]
There's nothing to support this at this time, but I'll tag this with `pages` to remind me of the feature suggestion. The next chunk of work I'm planning for qpdf is to address the many requests for features like this and generally to create a more flexible way of manipulating pages.

**Comment by rubyFeedback** [comment]
I work around this a bit via a ruby helper script but it may be nice if qpdf itself has some more flexibility here (+ examples ideally, as people may forget about things or be unaware of the usage). That could also be useful on windows if there is a qpdf.exe in the PATH.

**Comment by jberkenbilt** [comment]
I'm going to implement the syntax suggested in #564.

**Comment by jberkenbilt** [comment]
Implemented for 11.7.1 -- see #564 for discussion
