### ISSUE TITLE
std::bad_alloc - Visual Studio 2022

### ISSUE THREAD

**Issue by DreamEspacial** [qpdf/qpdf#801]
Hi I'm new to C++, I copied the code from https://github.com/qpdf/qpdf/blob/main/examples/pdf-npages.cc and tried using it but it returns the error std::bad_alloc, any idea what Can be?

![screenshoot](https://user-images.githubusercontent.com/111513887/194079252-5e7bf08a-f6a7-4ad9-bb20-4e73766a3f49.png)

**Comment by jberkenbilt** [comment]
The code looks correct to me. If the PDF file were invalid, it's possible that something with throw an exception, but I don't think you'd get a bad_alloc under that condition. So I don't have any specific ideas.

**Comment by DreamEspacial** [comment]
After lots and lots of research I found that the problem was the visual studio debug mode, I switched from debug to release and it worked normally. Thanks!

**Comment by chenbingbcb** [comment]
Me too. Only with release mode...
