### ISSUE TITLE
Can't build qpdf with OpenSSL on macOS

### ISSUE THREAD

**Issue by mario-grgic** [qpdf/qpdf#803]
I'm trying to build qpdf 11.1.1 on macOS. I have OpenSSL installed in default location at ```/usr/local/ssl```

```
$ type openssl
openssl is aliased to `/usr/local/ssl/bin/openssl'
$ openssl version
OpenSSL 1.1.1q  5 Jul 2022
$ pkg-config --libs openssl
-L/usr/local/ssl/lib -lssl -lcrypto
$ pkg-config --cflags openssl
-I/usr/local/ssl/include
```

So, I'm trying:

```
$ pwd
/Volumes/ramdisk/qpdf-11.1.1/build
$ cmake -DCMAKE_BUILD_TYPE=Release -DUSE_IMPLICIT_CRYPTO=OFF -DREQUIRE_CRYPTO_OPENSSL=ON ..
```

and I get 

```
- Checking for module 'openssl>=1.1.0'
--   Requested 'openssl >= 1.1.0' but version of OpenSSL is 1.0.2h
CMake Error at libqpdf/CMakeLists.txt:224 (message):
  openssl not found


CMake Error at libqpdf/CMakeLists.txt:272 (message):
  no crypto provider is available


CMake Error at libqpdf/CMakeLists.txt:276 (message):
  Missing dependencies; unable to continue


-- Configuring incomplete, errors occurred!
```

Not sure where it is getting OpenSSL 1.0.2h (I don't have such thing installed on my system, and the built in OpenSSL is LibreSSL 2.8.3).

Is there a way to specify to cmake what OpenSSL to use?

**Comment by jberkenbilt** [comment]
This is a general question about cmake, not a question specifically about qpdf. From a quick perusal of the cmake documentation, it looks like you should be able to set the environment variable `CMAKE_PREFIX_PATH` to `/usr/local/ssl`. It may also work to run with `-DCMAKE_PREFIX_PATH=/usr/local/ssl` or to set this from the Advanced section of cmake-gui or one of the other cmake front-ends but I haven't personally tried this. Does this help?

**Comment by mario-grgic** [comment]
Yes, setting `-DCMAKE_PREFIX_PATH=/usr/local/ssl` does it. Thank you.

**Comment by jberkenbilt** [comment]
Great, thanks for the follow-up.
