### ISSUE TITLE
libqpdf is not consumable by msvc caused by incompatible #warning macro in PointerHolder.hh (potentiall also QPDFObject.hh)

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [qpdf/qpdf#804]
I am currently developing a conan package recipe for qpdf:
https://github.com/conan-io/conan-center-index/pull/13113#issuecomment-1271912751

The last blocking part is a compile error from msvc when the libqpdf is used. Exactly when `PointerHolder.hh` is included, since this brings the `# warning` macro, which is not compatible with msvc compiler. It fails with:

```
----Running------
> cmake --build C:\J\w\prod\BuildSingleReference@2\conan-center-index\recipes\qpdf\all\test_v1_package\build\a1f410b7f918b45b1ec298bbba1d330c7bc32c54 --config Release -- /m:8 /verbosity:minimal
-----------------
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/J/w/prod/BuildSingleReference@2/conan-center-index/recipes/qpdf/all/test_v1_package/CMakeLists.txt
  test_package.cpp
C:\J\w\prod\BuildSingleReference@2\.conan\data\qpdf\11.1.1\_\_\package\26bafdc4ba785a8a3a974d957f1b04f467f69663\include\qpdf/PointerHolder.hh(31): fatal error C1021: invalid preprocessor command 'warning' [C:\J\w\prod\BuildSingleReference@2\conan-center-index\recipes\qpdf\all\test_v1_package\build\a1f410b7f918b45b1ec298bbba1d330c7bc32c54\test_package.vcxproj]
```

**Comment by jberkenbilt** [comment]
Yeah, see #775 . I don't have a good fix for this. What you'll need to do is `#define POINTERHOLDER_TRANSITION` to some value or add that symbol to your build. The value of 0 is full backward compatibility, and the value of 4 is fully transitioned. See https://qpdf.readthedocs.io/en/stable/design.html#smart-pointers for a full discussion.

**Comment by jberkenbilt** [comment]
For just building libqpdf itself, a value of 4 is appropriate.

**Comment by cguentherTUChemnitz** [comment]
Thanks for the fast reply. I try to fix my tests there with such a compile definition.

**Comment by cguentherTUChemnitz** [comment]
Thanks again for the very fast clarifications. This enabled to bring the package through under quite time-pressure, but preserving all major pattforms. Since your note really did solve the problems here, i will close this ticket accordingly as solved, since the msvc does not hit the warning pragma, when the define is present as specified

**Comment by jberkenbilt** [comment]
Thanks for the follow-up!
