### ISSUE TITLE
Large PDF loading issue

### ISSUE THREAD

**Issue by sz5000** [qpdf/qpdf#808]
Large PDF file is this:
https://drive.google.com/file/d/1i-kW6iyJg8QkzCG9RhjS5rfIkLDWT-oI/view?usp=sharing

Performed action is --decrypt --password=test

QPDF does not finish in a timely manner and consumes about 3 Gigs of RAM. Can this be improved?

**Comment by jberkenbilt** [comment]
I am seeing other viewers also struggle with this file. I'll have to study it, but I suspect that there is just something very complex about the PDF structure. The file has 907,094 objects in it, which accounts for the very large amount of RAM. A quick perusal of the file (looking at the raw PDF, not in a viewer) shows lots and lots of link annotations. There are also pages with complex drawings on them. The file also has 3,613 pages, which means qpdf is using about 1 MB per page. All in all, I think it's not likely that there's much that can be done to make qpdf handle the file more efficiently. It's just a big, complex file.
