### ISSUE TITLE
E-book collection

### ISSUE THREAD

**Issue by fturco** [qpdf/qpdf#81]
This is a question from a qpdf user, not a bug report.

I have a large e-book collection in PDF format, and I'm evaluating the possibility of using qpdf to check/fix/compress e-books. All e-books can be opened with the Evince PDF viewer without apparent problems, but `qpdf --check` returns errors for many of them (exit status 2). Should I try fixing them all with `qpdf broken.pdf fixed.pdf`? Does running this command on unbroken files make sense too? My only need is to preserve all content without loss of informations, in other terms I need the conversion process to be lossless. I accept the idea of having a few corrupted PDFs that cannot be repaired and the need to replace/discard them. I also tried the `--linearize` option but that seems to make PDFs slightly bigger than the original version. I read my e-books offline on the same machine where they are stored, so perhaps I don't need to linearize them. Still not sure. As far as compression is concerned a better idea may be to use btrfs filesystem compression or xz compression instead of qpdf.

What do you think?

**Comment by jberkenbilt** [comment]
`qpdf broken.pdf fixed.pdf` will generally work but it may or may not always preserve all the data depending on the nature of the problem. PDF files generally mostly contain data that is already compressed, so compression tools like xz won't compress them very much unless your original files are compressed very inefficiently. I'm not sure what sort of compression btrfs uses, but it's not likely going to result in anything better than something like xz. You may get the best compression by using qpdf to uncompress all the data in the PDF file and then use xz on the result, but that would be sort of an odd thing to do unless space were at an extreme premium. If qpdf is making the files smaller and also repairing them, I'd worry a little about whether you were losing data. Unfortunately I can't give you a reliable way to know for sure whether you're losing data, though converting both fixed.pdf and broken.pdf to images using something like convert from ImageMagick or using ghostscript and then comparing the images could at least tell you whether lost any data that affects the rendering. But this is all kind of overkill. I'm not sure if this addresses your question, but if not, feel free to clarify what you're looking for.

**Comment by fturco** [comment]
Thanks for the answer. I guess the best thing to do in my case is probably to preserve the original PDF files as they are.

**Comment by jberkenbilt** [comment]
Yes, I think preserving the originals would be your best bet.

**Comment by necros2k7** [comment]
So it`s still not known if qpdf lossless?
