### ISSUE TITLE
[Half-baked idea, quarter-suggestion] qpdf providing "meta-information" about .pdf files

### ISSUE THREAD

**Issue by rubyFeedback** [qpdf/qpdf#812]
Heya,

This is mostly a bit of a question, half-idea, quarter suggestion. It builds a tiny bit on earlier ad-hoc suggestions or so, e. g. encrypting or decrypting .pdf files, or analysing problems of .pdf files or discovering evilness in .pdf files (e. g. .pdf files that are malicious). See other suggestions such as "qpdf --check", so I think some users may have similar use cases and the like. Kind of like ffmpeg "swiss-toolkit for multimedia", with qpdf being the toolkit for pdf files. :D

Note: I am NOT saying ALL use cases should be covered by qpdf here! That would probably require too much time and go off from the primary use case that qpdf wants to support.

What do I mean with "meta-information"?

Well - any information that qpdf can provide that may not be instantly obvious. For instance, "tell me how many pages are in this .pdf file". This is an instantly obvious question-answer to me. So I don't mean that.

I mean something like "this .pdf file has a unique identifier embedded into location XYZ". Or something like that.

So, one possible use case I have had was this.

I obtained a .pdf file from a university recently. I suspect that all students get the same, but I was wondering whether identifiers were embedded into them (is that even possible?) to identify a student, so if you then upload the .pdf, you can be tracked bad, and perhaps may be expelled from a university. This is somewhat hypothetical, but I was here wondering whether qpdf could kind of let me know what meta-tracking information a .pdf file could be used.

Or, alternatively, since these are SIMPLE .pdf files, it's not a big deal because I can just re-create them easily really. The text is just text, and the images, well - I can extract the images from a .pdf file, or I can do the lazy man approach and just do a screenshot, and then embed that and generate a new .pdf file. So it is not a really very important use case. It's fine that qpdf would not support that since it is too special.

Nonetheless, though, I was wondering about this, e. g. use cases for malicious pdf files or .pdf files that track people.

Anyway - this is mostly just an ad-hoc suggestion so please feel free to ignore it and close it. I just wanted to give some semi-random thoughts where some possible use cases may overlap with what people could need or want (e. g. some "higher" abstraction level of a .pdf file analyser or perhaps even "meta-arranger". I use qpdf a lot to re-arrange individual pages. qpdf also seems to be faster compared to ~2 years ago, but I don't know whether that is just my perception or whether things changed code-wise, it just feels "snappier" and faster suddenly).

**Comment by jberkenbilt** [comment]
I know that people have used qpdf to analyze PDF files for malicious content. That's quite a large undertaking and is a project in itself. It's not something I would build into qpdf. It would be possible with some work to use qpdf to identify places in the file that are ignored by the PDF parser and could potentially contain hidden data. I haven't ever written that, but I added file offset information to parser callbacks for the purpose of being able to know that information. Anyway, it's an interesting suggestion, but not something that qpdf itself will do. If there are specific use cases or issues that come up for someone trying to do that, I am definitely open to adding stuff to the qpdf API to help. The file location stuff was an example of that.

A great deal of work was put into improving qpdf's performance recently, so you are not imaging it. qpdf is probably almost twice as fast as it was two years ago. Most of the work was done by people other than me -- you can get details in the release notes.

**Comment by jberkenbilt** [comment]
I'm going to close this since I'm not likely to do anything with it, and you said it was okay to close. I appreciate that you take the time to share your ideas, even when only fractionally baked. :-)
