### ISSUE TITLE
Feature: Detect strings shifted in ASCII value by X

### ISSUE THREAD

**Issue by Atrate** [qpdf/qpdf#820]
Today I've come across a PDF with a string encoded in a very interesting way: It was encoded as a normal pdf hex-string but with the ASCII values shifted down by X (and separated by `NUL`s), in this case `29` in decimal or `1D` in hex, so e.g.
```
<002b0048004F004F0052>
 Tj
```
would render as `Hello`.

It seems that `qpdf` does not decode it into normal ASCII text, even with the following options: `--decrypt --stream-data=uncompress --qdf --decode-level=specialized` (`pdftotext` does, though). Would it be possible for `qpdf` to include an "intensive mode" switch, where it would try all the possible shifts (at least in the ASCII space) for strings it did not decode in a "standard" way?

**Comment by jberkenbilt** [comment]
This is just UTF-16 encoding without the leading FEFF. I'm not sure exactly what the right solution is, but text like this within a context stream is definitely out of spec. I wonder whether pdf2text really handles it or whether it is outputting the nulls. I'd try piping its output through cat -v. Do you have a sample file?

**Comment by jberkenbilt** [comment]
This was probably written by PDF generation software that was sloppy about string encoding. I'm a little surprised that any reader would handle it unless there are special cases. I don't think trying all possible shifts would be necessary. Anyway, I doubt I would handle this in qpdf in any systematic way, but I'd have to see what other viewers do.

**Comment by Atrate** [comment]
> This was probably written by PDF generation software that was sloppy about string encoding. I'm a little surprised that any reader would handle it unless there are special cases. I don't think trying all possible shifts would be necessary. Anyway, I doubt I would handle this in qpdf in any systematic way, but I'd have to see what other viewers do.

For context: this was done on a watermark string, so the sloppy handling may be purposeful to make watermark removal harder.

> Do you have a sample file?

Not one that could be distributed, unfortunately.
