### ISSUE TITLE
Split and add a pdf to the end of output

### ISSUE THREAD

**Issue by chrisrex** [qpdf/qpdf#821]
Hi,
with this I split an infile to and outfile including a cover to each

qpdf.exe --linearize infile.pdf --pages cover.pdf infile.pdf 43-85 -- output1.pdf

Now, I want to add to the end an other file called appendix.pdf

I try this with no success.
qpdf.exe --linearize infile.pdf --pages cover.pdf infile.pdf 43-85 -- appendix.pdf -- output1.pdf

Thank you for help
Christoph

**Comment by jberkenbilt** [comment]
I haven't tried it, but I think you want this instead:
```
qpdf.exe --linearize infile.pdf --pages cover.pdf infile.pdf 43-85 appendix.pdf -- output1.pdf
```

The `--` goes at the end of all the `--pages` options.

**Comment by chrisrex** [comment]
Thank you very much, this works fine.
