### ISSUE TITLE
How to delete bookmarks in output pdf

### ISSUE THREAD

**Issue by chrisrex** [qpdf/qpdf#823]
Hi,
with this command line i split a pdf to several little pdfs

qpdf.exe --linearize infile.pdf --pages cover.pdf infile.pdf 43-85 -- output1.pdf

How can I remove all bookmarks in the output1.pdf ?

Because I know, qpfd cannot remove unused bookmarks. 
Is it possible to delete all bookmarks instead?

Christoph

**Comment by jberkenbilt** [comment]
Try `qpdf --empty --linearize --pages cover.pdf infile.pdf 43-85 -- output1.pdf` and see if that works for you.

**Comment by chrisrex** [comment]
Thank you again, this works also fine.

**Comment by chrisrex** [comment]
Hi,
if i use `qpdf --empty --linearize --pages cover.pdf infile.pdf 43-85 -- output1.pdf` all Metatags are gone.
The title, author and the document language
How can I keep this information? I have to delete the bookmarks without deleting metatags.
Best regards
Christoph
