### ISSUE TITLE
table of contents TOC

### ISSUE THREAD

**Issue by femifrak** [qpdf/qpdf#831]
There is hardly any feature missing in qpdf. I like and use it very much! Thanks for maintaining and developing!

Is it possible to add a TOC to an existing pdf?  
I searched a bit already and understood that qpdf uses the first command line parameter (a pdf file) to assign certain properties to the output pdf. I have a pdf containing a TOC which I want to assign to the output:
`qpdf pdf_with_TOC.pdf --pages pdfs_without_TOC*.pdf -- out.pdf`
The merged ones have the same and consecutive number of pages as the TOC one.

out.pdf shows the TOC but the TOC page labels are missing so that the entries in the TOC are not selectable. Is there a way to overcome this?

**Comment by jberkenbilt** [comment]
This is a known issue and is related to a larger issue, which is that PDF files internally store certain information about the file, including link destinations, at the document level, and qpdf only preserves document-level information from the first file when using `--pages`.  This is a major thing to fix, but it is "next up" on my work list. I'm not sure exactly when it will get done. All the github issues with the `pages` tag are in some way related to this issue.

**Comment by jberkenbilt** [comment]
Reading this more closely, I'm not sure I understand exactly what the feature request is. If you are looking to create a TOC completely separately, merge it in, and then have links work, that's not going to be possible without additional coding. If my pages work is successful, it would be possible to make certain types of changes to PDF files with qpdf while more intelligently preserving the destination of existing links, but I don't have any plans at this time for adding new links. This is about more than just page labels -- links in PDF are separated from page content and basically say that a particular region of a page links to some destination, which might be an external URL or a region of a page in this or some other PDF. So I think I'll have to backtrack and say this is not something qpdf will support, but if you do it with some other tool, qpdf should preserve it now in some cases and, in a future release, it a few additional cases.

Sorry for the confusion. I'm going to close this, but please reopen if I have misunderstood your request.
