### ISSUE TITLE
Option --no-warn don't suppress all warnings checking a PDF

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#851]
### Discussed in https://github.com/qpdf/qpdf/discussions/850

<div type='discussions-op-text'>

<sup>Originally posted by **vf1962** December 21, 2022</sup>
Maybe I'm using parameters in a wrong way but executing this qpdf
**QPDF.EXE** **--no-warn**  **--check** **"C:\temp\Outlook.Dump\2022.11.23 pulizia - redmine #31190 ESEGUITA.pdf"**

The result is
checking C:\temp\Outlook.Dump\2022.11.23 pulizia - redmine #31190 ESEGUITA.pdf
PDF Version: 1.4
File is not encrypted
File is linearized
WARNING: shared object 0 length mismatch: hint table = 65536; computed = 187
WARNING: shared object 1 length mismatch: hint table = 65536; computed = 13879
WARNING: shared object 2 length mismatch: hint table = 65536; computed = 21
                                                  _[OMISSIS]_
WARNING: shared object 239 length mismatch: hint table = 65536; computed = 35
WARNING: shared object 240 length mismatch: hint table = 65536; computed = 33
WARNING: shared object 241 length mismatch: hint table = 65536; computed = 924
WARNING: object count mismatch for page 0: hint table = 0; computed = 242

The PDF file is a Chrome print-out from Redmine web application.
Tank you</div>

**Comment by jberkenbilt** [comment]
Specifically, --no-warn is not suppressing linearization warnings.

**Comment by jberkenbilt** [comment]
@vf962 See here for the issue you previously reported.

**Comment by jberkenbilt** [comment]
@vf1962 See here for the issue you previously reported.

**Comment by vf1962** [comment]
Thank you.
For completeness, I'm using last qpdf version (11.2.0) on Windows 10 & 11
