### ISSUE TITLE
merging two pages into one

### ISSUE THREAD

**Issue by prelop** [qpdf/qpdf#86]
Please, is there some way in QPDF to merge two pages into one output page? I have two musical scores, each of them occupies approximately half of the page and I would like copy their contents subsequently to one page. I have compiled QPDF 5.1.2 in MS VS 2008.
Thank you very much, Filip

**Comment by jberkenbilt** [comment]
Interestingly, someone else also asked almost this exact question. Please see my response in #87. Also feel free to reopen this issue or comment on that one if you have further questions.
