### ISSUE TITLE
documentation lacking on merging pdf files on top of each other

### ISSUE THREAD

**Issue by kxra** [qpdf/qpdf#87]
Simple operation presumably supported but can't find in documentation. Combining two pages and merging them into a single flattened page (not side by side, but layered)

**Comment by jberkenbilt** [comment]
I wish it were just a documentation issue, but it's not something qpdf can do out of the box. It would be possible to write code using qpdf to do this, but it's not just a simple structural operation. You would actually have to combine the contents of the pages. Using qpdf to do this would require a decent level of knowledge about PDF content streams. There may be other tools that can do it as there are tools designed to edit PDF files. Maybe Open Office (or similar) could do it. It wouldn't be too hard to write qpdf code that would just concatenate the content streams. That would work okay in some cases but not in the general case. Sorry I don't have a better answer for you.

Please feel free to reopen if you have any further questions.
