### ISSUE TITLE
Set image /Interpolate flag

### ISSUE THREAD

**Issue by benbro** [qpdf/qpdf#884]
Is it possible to set or change image interpolate flag with the qpdf cli?
Similar to this simplified command:
```bash
sed -i 's/\/Interpolate false/\/Interpolate true/g' in.pdf
```

**Comment by jberkenbilt** [comment]
You can use [qpdf JSON](https://qpdf.readthedocs.io/en/stable/json.html) to do this kind of manipulation. It will be more complicated than sed, but you probably need to change this flag in some context, and you will have to take that into consideration.

**Comment by jberkenbilt** [comment]
Alternatively, you could use [QDF mode](https://qpdf.readthedocs.io/en/stable/qdf.html). I plan to blog about how to use qpdf JSON to do manipulations in PDF like this. I have made a note to remember this issue if/when I get around to writing that blog post.

**Comment by benbro** [comment]
I'll look into qpdf JSON. Thanks.
