### ISSUE TITLE
Support command line option --password-file for encrypting in addition to decrypting

### ISSUE THREAD

**Issue by qpanda** [qpdf/qpdf#885]
Could you please support command line option  **--password-file** (or similar) when encrypting PDF files?

Currently there seems to be no way to prevent passwords from leaking into the process table when encrypting PDFs. This allows everyone able to list / inspect the process table (with command such as **ps**) to obtain the password used to encrypt PDFs.

The **--password-file** command line option (introduced in 10.2.0) can be used with **--decrypt** to avoid leaking the password into the process table. Unfortunately this option doesn't seem to work with **--encrypt**. Given the syntax **--encrypt** and the fact that both a user and owner password can be specified it may be necessary to introduce a new set of command line options.

**Comment by qpanda** [comment]
Instead of introducing more command line parameters, another option could be to introduce environment variables that QPDF reads the password from (when set).

**Comment by jberkenbilt** [comment]
You can already do this using the `@file` syntax. Example:
```
echo user-password > /tmp/u
echo owner-password > /tmp/o
qpdf --encrypt @/tmp/u @/tmp/o 256 -- in.pdf out.pdf
```
For details, see https://qpdf.readthedocs.io/en/stable/cli.html#basic-invocation

**Comment by qpanda** [comment]
Thanks, didn't realize this is already supported. I read the last paragraph in section Basic Invocation, the section "can’t appear in the middle of an argument" lead me to believe that it isn't supported for --encrypt.
