### ISSUE TITLE
libqpdf.so.28: "File is too short" Error 

### ISSUE THREAD

**Issue by m7md7sien** [qpdf/qpdf#895]
Hi,

When I try to run qpdf on linux I get this error" error while loading shared libraries: ~/qpdf-10.6.3-bin-linux-x86_64/bin/../lib/libqpdf.so.28: file too short

I opened libqpdf.so.28 itself and found that itdoesn;t contain any binaries, just the text string "libqpdf.so.28.6.3". Which in turn contains regular binaries. When I replaced libqpdf.so.28 by libqpdf.so.28.6.3 it worked fine.

Can you please help me figure out how does this work? Is libqpdf.so.28 pointing to other .so somehow?

I am running v10.6.3 but I could reproduce the error on latest version too.

**Comment by jberkenbilt** [comment]
libqpdf.so.28 is supposed to be a symbolic link to libqpdf.so.28.6.3. Something must have gone wrong with your installation, but it's hard to imagine how something like that could happen without some odd process of installation or setup of the distribution. If you tried to install onto a VFAT or FAT file system, maybe it would be possible.

**Comment by m7md7sien** [comment]
This make sense, I just downloaded the release .zip file and extracted on my windows machine, then tested it using wsl Linux environment in Windows. So this must corrupted the symbolic link.

Thanks.
