### ISSUE TITLE
configure file is missing

### ISSUE THREAD

**Issue by Derek-Jones** [qpdf/qpdf#90]
The configure file is missing.

Using an very old configure (after commenting out the path to qpdf-config.h), then running make results in qpdf-config.h not being found (no surprise there; but no file of this name exists in the source tree).

**Comment by jberkenbilt** [comment]
You have to run ./autogen.sh if you are starting from a git checkout. Please see the section "Building from a pristine checkout" in the top-level README.

**Comment by Derek-Jones** [comment]
Thanks, that worked.

You might want to add this point to the INSTALL file.
