### ISSUE TITLE
Error while loading shared libraries: libqpdf.so.17

### ISSUE THREAD

**Issue by nathandrew** [qpdf/qpdf#91]
I just installed the latest qpdf on Amazon Linux (CentOS):
1. `yum -y install pcre-devel`
2. `wget http://downloads.sourceforge.net/project/qpdf/qpdf/6.0.0/qpdf-6.0.0.tar.gz`
3. `tar -xvf qpdf-6.0.0.tar.gz`
4. `./configure`
5. `make`
6. `sudo make install`

When I run `qpdf` I get this error:

> qpdf: error while loading shared libraries: libqpdf.so.17: cannot open shared object file: No such file or directory

Here are some printouts:

> ls /usr/local/lib
> libqpdf.a  libqpdf.la  libqpdf.so  libqpdf.so.17  libqpdf.so.17.0.0  pkgconfig  python2.7
> 
> ls /usr/local/bin/
> fix-qdf  qpdf  redis-cli  zlib-flate

I tried copying the shared library as directed [here](http://www.pc-freak.net/blog/extracting-pages-page-ranges-protect-password-remove-password-pdf-gnu-linux-qpdf/) but no luck.

Is there a flag I need to set to link the library correctly?

**Comment by jberkenbilt** [comment]
Maybe /usr/local/lib isn't in your library path. You could try

export LD_LIBRARY_PATH=/usr/local/lib

or checking /etc/ld.so.conf to see whether that file or something it includes adds /usr/local/lib to the library path. If not, you could add it and run ldconfig.

**Comment by nathandrew** [comment]
👍

**Comment by eesheesh** [comment]
I encountered `qpdf: error while loading shared libraries: libqpdf.so.18: cannot open shared object file: No such file or directory` after `sudo make install`ing qpdf 7.0.0 (built from the release). I needed to run ldconfig - maybe `make install` should run ldconfig?

**Comment by justasflash** [comment]
I happen to have the same error after building qpdf 8.0. but after reading @jberkenbilt comment. I used export LD_LIBRARY_PATH=/usr/local/lib command and run sudo ldconfig. works better now
