### ISSUE TITLE
Dynamic linking of qpdf library on Mac OS X

### ISSUE THREAD

**Issue by rakeshthp** [qpdf/qpdf#92]
Hi,

I have compiled QPDF on one of my MAC system. The configuration was done using following command:

./autogen.sh
CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --prefix=/Users/rakesh/Desktop/QPDF
sudo make install

I am getting following four files:
1. libqpdf.17.dylib
2. libqpdf.a
3. libqpdf.dylib (alias)
4. libqpdf.la

I need to use these libraries to build my Qt based project. So I move these libraries in my application folder and I user relative path to link it with my project. My application builds properly without any errors. But when I run the application, it crashes showing the following error:

> dyld: Library not loaded: /Users/rakesh/Desktop/QPDF/lib/libqpdf.17.dylib
>   Referenced from: /Users/mahesh/Documents/PDF_Import/Bin/Mac/Debug/MyApp.app/Contents/MacOS/MyApp
>   Reason: image not found
> The program has unexpectedly finished.

I want to keep these libraries separately along with the source code, so that it can be easily taken to another system and without doing any changes in the code or without manually copying files into /usr/local directory, it should build and run successfully. Now when I take this project to another system, it shows me above error. If observed properly, the path is shown of the folder existing in the compiled system, and not where project is built.

Is there anything I am missing? Please guide me as I am new with dynamic libraries in MAC.

Thanks & Regards
Rakesh P.

**Comment by jberkenbilt** [comment]
Sorry for lack of reply on this. Up to now, I have had no access to any mac systems, but soon my work laptop will be replaced with a mac. Maybe at that time I can learn something about this.

**Comment by mtoftdal** [comment]
@rakeshthp , you'll need to read about the install names of dylibs on Mac. The dylibs have an install name which is the path where the file should be found at runtime. If the install name is not correct, the environment variable `DYLD_LIBRARY_PATH` can be used, but that's not the way to go for release builds for instance.
The install name is set at build time (with a linker option) but can be changed later with `install_name_tool`. You can view the current install name with `otool -L`. Finally, the install name can be relative to various runtime variables, see for instance:
https://wincent.com/wiki/@executable_path,_@load_path_and_@rpath

**Comment by jberkenbilt** [comment]
I'm closing this issue -- since qpdf's build was replaced with cmake, I think issues like this are no longer present.
