### ISSUE TITLE
Is removing the meta data from PDF permanent?

### ISSUE THREAD

**Issue by bertalanimre** [qpdf/qpdf#93]
Hi there,

I have a question if the meta data deletion is reversible or not like with ExifTool. This is very important, please answer if possible.

I use the following command to erase metadata from PDF files:
`qpdf --empty --pages input.pdf 1-z -- output.pdf`

Regards:
Bert

**Comment by bertalanimre** [comment]
Still waiting for an aswer...

**Comment by jberkenbilt** [comment]
I'm not sure how I overlooked this. I'm going through and cleaning up old issues. If it's still relevant, yes, it's permanent.
