### ISSUE TITLE
Can qpdf crop most pages while ignoring some?

### ISSUE THREAD

**Issue by Shohreh** [qpdf/qpdf#955]
Hello,

Before trying to turn it into an EPUB, I need to crop the bottom of all pages, and the top of most pages of a PDF while ignoring the first page of each chapter.

Can qpdf do this?

Thank you.

PS: What's the difference between mediabox, cropbox, bleedbox, trimbox, and artbox?

![image](https://github.com/qpdf/qpdf/assets/1541861/9f9492fe-4c8c-4098-83b6-ee04a2c6df07)

**Comment by jberkenbilt** [comment]
qpdf does not have awareness of the meaning of the page and is not able to do the kind of edits that you are suggesting. This is not something qpdf is likely to be able to do -- it falls outside of the structural changes that qpdf is intended for. If the PDF file is tagged and has structural elements, it might be possible to use qpdf to assist with writing a tool that could do this, but it would require detailed knowledge of the PDF spec.

The different boxes are unrelated to this, but here's a basic summary:

* Media Box -- boundaries of physical page
* Crop Box -- clipping region of what is displayed
* Bleed Box -- clipping region for production environments
* Trim Box -- dimensions of final printed page after trimming
* Art Box -- extent of meaningful content including margins

Of these, only MediaBox is required. If they are absent, crop box defaults to media box, and the rest default to crop box.

**Comment by Shohreh** [comment]
Thanks much
