### ISSUE TITLE
Bug when trying this test method

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#965]
Hi,

When running this test scenario from my wrapper I would expect it to output at least something but nothing gets returned.

All my other methods just return data but not this one. When switching back to a qpdf version from a year ago I get output so I wonder if this is a bug or if something else has been changed in qpdf so that this does not return anything anymore.

![image](https://github.com/qpdf/qpdf/assets/6692947/8f99d444-1ada-4e77-85ba-c21509f8ab12)

**Comment by Sicos1977** [comment]
![image](https://github.com/qpdf/qpdf/assets/6692947/7920e828-40b9-449a-9eb6-27a2d58d39ec)

**Comment by Sicos1977** [comment]
When doing it like this

![image](https://github.com/qpdf/qpdf/assets/6692947/5dfb176c-4186-4344-878c-888d786b3171)

It will dump the data ... but here I'm using the internal name... so did I use it wrong in the first post in this issue?

**Comment by jberkenbilt** [comment]
The internal name, as you call it, is the only correct way to do it. If it worked before, I'm not sure why. Perhaps it picked up 20 and parsed it less strictly and was dumping the output of object 20.

**Comment by Sicos1977** [comment]
Ok I understand that this is the way it works.

**Comment by Sicos1977** [comment]
Since all my tests now worked as expected I released a new C# wrapper with the latest version in it --> https://www.nuget.org/packages/QPdfNet

**Comment by jberkenbilt** [comment]
Thanks. I assume you're subscribed to qpdf-announce so you'll know when I release 11.4.

**Comment by Sicos1977** [comment]
> pdf-

Uh no... where do I do that?

**Comment by jberkenbilt** [comment]
Visit https://qpdf.sourceforge.io/ -- there is a button to join the mailing list. Let me know if you have any trouble. I set it up millions of years ago using sourceforge's antiquated mailman-based distribution list stuff.
