### ISSUE TITLE
Offline installation for Mac OS X

### ISSUE THREAD

**Issue by bertalanimre** [qpdf/qpdf#97]
Hey Forum,

I have to install qpdf on an offline MacMini Server. My question is, how else can I sintall is besides the source? The reason behind this question is, that I can't really build it from source, since the server doesn't have all the necesarry applications to install anything from source and I'm not in position to do that.

Do you have any suggestions? Maybe you know how can I copy the application from an online Mac to the server via pendrive?

Cheers!

Bert

**Comment by jberkenbilt** [comment]
Unfortunately, I don't have a mac and don't know anything about the mac ecosystem, so I am unable to comment on this. Maybe someone else can help you.

**Comment by bertalanimre** [comment]
I've figured out and going to test it tomorrow.

Just brew fetch qpdf --deps and there you'Ll have all the binary. If I'm thkingin right, then all you have to do is set a Path to it and there you go. 

If this works tomorrow I'll close the ticket and marked solved.

**Comment by bertalanimre** [comment]
If you would have homebrew already installed, then it could work. For me it didn't since I had no homebrew and there is no offline installation for it.

So I've just installed the application from source.... Closing the ticket.
