### ISSUE TITLE
split damaged PDF after qpdf 9.1.1 get pages with ASCII85 stream problems

### ISSUE THREAD

**Issue by alvaro-canepa** [qpdf/qpdf#973]
[ORIGINAL.pdf](https://github.com/qpdf/qpdf/files/11554663/ORIGINAL.pdf)

**Attached PDF has error on page 2.** 
After split pages, I use `cpdf -add-text ...` command, and, for page 2, get message `Error decoding ASCII85 stream`
Using `qpdf 9.1.1` (current version on apt install) split pages without error. But after update to latest 11.4.0, couldn't use `cpdf` or any library to edit content. 

### Output of 11.40
`qpdf --split-pages "ORIGINAL.pdf" "p_%d.pdf"`
```bash
WARNING: ORIGINAL.pdf (offset 5894): error decoding stream data for object 15 0: broken end-of-data sequence in base 85 data
WARNING: ORIGINAL.pdf (offset 5894): stream will be re-processed without filtering to avoid data loss
```

### Output with 9.1.1
`qpdf-911 --split-pages "${DIR}ORIGINAL.pdf" "${DIR}p_%d.pdf"`
```bash
WARNING: ORIGINAL.pdf (offset 5894): error decoding stream data for object 15 0: broken end-of-data sequence in base 85 data
WARNING: ORIGINAL.pdf, object 14 0 at offset 5576: Unable to parse content stream: content stream (content stream object 15 0): errors while decoding content stream; not attempting to remove unreferenced objects from this page
WARNING: ORIGINAL.pdf (offset 5894): error decoding stream data for object 15 0: broken end-of-data sequence in base 85 data
qpdf: operation succeeded with warnings; resulting file may have some problems
```

Is there any extra option or library to fix the stream issued on page 2?

> BTW: pdf's are uploaded by users on a web app, I don't have control of that. After upload, the app split, crop and edit each page, based on settings.

**Comment by jberkenbilt** [comment]
Though I can say without looking at the file that, if the file is actually damaged in the way qpdf reports, then there won't be anything qpdf can do about it. However I will check the file and see whether the warning is accurate and whether the error is something I could teach qpdf to tolerate.

**Comment by alvaro-canepa** [comment]
Thanks @jberkenbilt for your answer

Actually if split the pages with v 9.1.1, qpdf report warnings, but another libraries (like cpdf) can process the pages without problem. With the same PDF and newest qpdf version, after split pages, the damaged page (page 2 in this case) can't be processed.

**Comment by jberkenbilt** [comment]
Very likely that qpdf is being overly strict about some aspect of the ASCII85 encoder. I can probably make the encoder more forgiving. I will definitely give it a good look. Thanks for reporting.

**Comment by johnwhitington** [comment]
It appears to have a newline character in the middle of the ~> EOD sequence:

```
[`pE`jRJH6aG^W)A>_d9=27ph9OT\g&uB9_M.1o'OHZM93ZYD"%$23`6Y1hcV,$/QZIB6mIK'Q(VVJQ~
>
```

The spec says

"The ASCII base-85 encoding shall use the ASCII characters ! through u ((21h) - (75h)) and the character z (7Ah), with the 2-character sequence ~> (7Eh)(3Eh) as its EOD marker. The ASCII85Decode filter shall ignore all white-space characters (see 7.2, "Lexical conventions")"

which is confusing. Can we have a newline between the `~` and the `>` or does that mean it's no longer a 2-character sequence?

Well, we have an example file, so probably.
