### ISSUE TITLE
Restrictions on mobile

### ISSUE THREAD

**Issue by Ash0ur** [qpdf/qpdf#977]
Setting restrictions for copy and print works on desktop but it doesn't work on mobile, by entering user password on mobile, I can copy and print the PDF file,  Is that normal?

The command:

` qpdf -encrypt pass passowner 256 --extract=n --print=none --modify=none -- source.pdf -- result.pdf`

**Comment by jberkenbilt** [comment]
You haven't specified what mobile app you're using. This wouldn't be about qpdf though; it would be about the mobile app. It's up to each individual PDF reading app to decide whether/how to enforce PDF security restrictions. PDF security restrictions are just indicators to the application. They won't work in any application that ignores them.

So, to answer your question about whether it's normal, I'd say that it completely depends on the app.
