### ISSUE TITLE
New version of qpdf produces a different version of PDF than previous versions of qpdf.

### ISSUE THREAD

**Issue by a1346054** [qpdf/qpdf#993]
Input PDF is `%PDF-1.6`

When using qpdf version 10.1.0 from debian bullseye:
```
qpdf --deterministic-id --recompress-flate --compression-level=9 --empty --pages "in.pdf" 1-z -- "out.pdf"
```
produces a PDF that is `%PDF-1.3`

When using appimage qpdf version 11.4.0:
```
qpdf --deterministic-id --recompress-flate --compression-level=9 --empty --pages "in.pdf" 1-z -- "out.pdf"
```
produces a PDF that is `%PDF-1.6`

The rest of the file is bit-for-bit identical (except for a different /ID in the files).

Why is PDF 1.6 generated, instead of the lowest compatible version?

**Comment by jberkenbilt** [comment]
What version is `in.pdf`? A bug was fixed prior to the release of 10.6.0 that took the highest version from all the input files when copying pages. Prior to 10.6, the version was copied from the initial input file, which in the case of `--empty`, is 1.3. S most likely `in.pdf` has version 1.6.

**Comment by jberkenbilt** [comment]
qpdf can't determine the lowest compatible version. It trusts the file headers.

**Comment by a1346054** [comment]
> What version is `in.pdf`?

Input PDF is %PDF-1.6

So the old behavior was a bug, and new behavior is the correct behavior? If that's the case, then all is good and the issue can be closed.
