### ISSUE TITLE
how to use compress-level by c api

### ISSUE THREAD

**Issue by wingjson** [qpdf/qpdf#994]
hello,i want to know how to compress pdf by using c++ api or c api,thanks

**Comment by jberkenbilt** [comment]
Please see comments in `include/qpdf/qpdf-c.h` and examples in the examples directory. I won't be able to help with very broad questions like this in the issue tracker, but feel free to request assistance if you have a more specific problem. That said, there are a lot of comments and examples in the qpdf source repository.
